extern __imp_AddMRUStringW:qword 
AddMRUStringW TEXTEQU <__imp_AddMRUStringW> 
extern __imp_CreateMRUListW:qword 
CreateMRUListW TEXTEQU <__imp_CreateMRUListW> 
extern __imp_CreateMappedBitmap:qword 
CreateMappedBitmap TEXTEQU <__imp_CreateMappedBitmap> 
extern __imp_CreatePropertySheetPage:qword 
CreatePropertySheetPage TEXTEQU <__imp_CreatePropertySheetPage> 
extern __imp_CreatePropertySheetPageA:qword 
CreatePropertySheetPage TEXTEQU <__imp_CreatePropertySheetPageA> 
extern __imp_CreatePropertySheetPageW:qword 
CreatePropertySheetPageW TEXTEQU <__imp_CreatePropertySheetPageW> 
extern __imp_CreateStatusWindow:qword 
CreateStatusWindow TEXTEQU <__imp_CreateStatusWindow> 
extern __imp_CreateStatusWindowA:qword 
CreateStatusWindow TEXTEQU <__imp_CreateStatusWindowA> 
extern __imp_CreateStatusWindowW:qword 
CreateStatusWindowW TEXTEQU <__imp_CreateStatusWindowW> 
extern __imp_CreateToolbar:qword 
CreateToolbar TEXTEQU <__imp_CreateToolbar> 
extern __imp_CreateToolbarEx:qword 
CreateToolbarEx TEXTEQU <__imp_CreateToolbarEx> 
extern __imp_CreateUpDownControl:qword 
CreateUpDownControl TEXTEQU <__imp_CreateUpDownControl> 
extern __imp_DPA_Clone:qword 
DPA_Clone TEXTEQU <__imp_DPA_Clone> 
extern __imp_DPA_Create:qword 
DPA_Create TEXTEQU <__imp_DPA_Create> 
extern __imp_DPA_CreateEx:qword 
DPA_CreateEx TEXTEQU <__imp_DPA_CreateEx> 
extern __imp_DPA_DeleteAllPtrs:qword 
DPA_DeleteAllPtrs TEXTEQU <__imp_DPA_DeleteAllPtrs> 
extern __imp_DPA_DeletePtr:qword 
DPA_DeletePtr TEXTEQU <__imp_DPA_DeletePtr> 
extern __imp_DPA_Destroy:qword 
DPA_Destroy TEXTEQU <__imp_DPA_Destroy> 
extern __imp_DPA_DestroyCallback:qword 
DPA_DestroyCallback TEXTEQU <__imp_DPA_DestroyCallback> 
extern __imp_DPA_EnumCallback:qword 
DPA_EnumCallback TEXTEQU <__imp_DPA_EnumCallback> 
extern __imp_DPA_GetPtr:qword 
DPA_GetPtr TEXTEQU <__imp_DPA_GetPtr> 
extern __imp_DPA_GetPtrIndex:qword 
DPA_GetPtrIndex TEXTEQU <__imp_DPA_GetPtrIndex> 
extern __imp_DPA_Grow:qword 
DPA_Grow TEXTEQU <__imp_DPA_Grow> 
extern __imp_DPA_InsertPtr:qword 
DPA_InsertPtr TEXTEQU <__imp_DPA_InsertPtr> 
extern __imp_DPA_LoadStream:qword 
DPA_LoadStream TEXTEQU <__imp_DPA_LoadStream> 
extern __imp_DPA_Merge:qword 
DPA_Merge TEXTEQU <__imp_DPA_Merge> 
extern __imp_DPA_SaveStream:qword 
DPA_SaveStream TEXTEQU <__imp_DPA_SaveStream> 
extern __imp_DPA_Search:qword 
DPA_Search TEXTEQU <__imp_DPA_Search> 
extern __imp_DPA_SetPtr:qword 
DPA_SetPtr TEXTEQU <__imp_DPA_SetPtr> 
extern __imp_DPA_Sort:qword 
DPA_Sort TEXTEQU <__imp_DPA_Sort> 
extern __imp_DSA_Create:qword 
DSA_Create TEXTEQU <__imp_DSA_Create> 
extern __imp_DSA_DeleteAllItems:qword 
DSA_DeleteAllItems TEXTEQU <__imp_DSA_DeleteAllItems> 
extern __imp_DSA_DeleteItem:qword 
DSA_DeleteItem TEXTEQU <__imp_DSA_DeleteItem> 
extern __imp_DSA_Destroy:qword 
DSA_Destroy TEXTEQU <__imp_DSA_Destroy> 
extern __imp_DSA_DestroyCallback:qword 
DSA_DestroyCallback TEXTEQU <__imp_DSA_DestroyCallback> 
extern __imp_DSA_EnumCallback:qword 
DSA_EnumCallback TEXTEQU <__imp_DSA_EnumCallback> 
extern __imp_DSA_GetItem:qword 
DSA_GetItem TEXTEQU <__imp_DSA_GetItem> 
extern __imp_DSA_GetItemPtr:qword 
DSA_GetItemPtr TEXTEQU <__imp_DSA_GetItemPtr> 
extern __imp_DSA_InsertItem:qword 
DSA_InsertItem TEXTEQU <__imp_DSA_InsertItem> 
extern __imp_DSA_SetItem:qword 
DSA_SetItem TEXTEQU <__imp_DSA_SetItem> 
extern __imp_DefSubclassProc:qword 
DefSubclassProc TEXTEQU <__imp_DefSubclassProc> 
extern __imp_DestroyPropertySheetPage:qword 
DestroyPropertySheetPage TEXTEQU <__imp_DestroyPropertySheetPage> 
extern __imp_DllGetVersion:qword 
DllGetVersion TEXTEQU <__imp_DllGetVersion> 
extern __imp_DrawInsert:qword 
DrawInsert TEXTEQU <__imp_DrawInsert> 
extern __imp_DrawStatusText:qword 
DrawStatusText TEXTEQU <__imp_DrawStatusText> 
extern __imp_DrawStatusTextA:qword 
DrawStatusText TEXTEQU <__imp_DrawStatusTextA> 
extern __imp_DrawStatusTextW:qword 
DrawStatusTextW TEXTEQU <__imp_DrawStatusTextW> 
extern __imp_EnumMRUListW:qword 
EnumMRUListW TEXTEQU <__imp_EnumMRUListW> 
extern __imp_FlatSB_EnableScrollBar:qword 
FlatSB_EnableScrollBar TEXTEQU <__imp_FlatSB_EnableScrollBar> 
extern __imp_FlatSB_GetScrollInfo:qword 
FlatSB_GetScrollInfo TEXTEQU <__imp_FlatSB_GetScrollInfo> 
extern __imp_FlatSB_GetScrollPos:qword 
FlatSB_GetScrollPos TEXTEQU <__imp_FlatSB_GetScrollPos> 
extern __imp_FlatSB_GetScrollProp:qword 
FlatSB_GetScrollProp TEXTEQU <__imp_FlatSB_GetScrollProp> 
extern __imp_FlatSB_GetScrollPropPtr:qword 
FlatSB_GetScrollPropPtr TEXTEQU <__imp_FlatSB_GetScrollPropPtr> 
extern __imp_FlatSB_GetScrollRange:qword 
FlatSB_GetScrollRange TEXTEQU <__imp_FlatSB_GetScrollRange> 
extern __imp_FlatSB_SetScrollInfo:qword 
FlatSB_SetScrollInfo TEXTEQU <__imp_FlatSB_SetScrollInfo> 
extern __imp_FlatSB_SetScrollPos:qword 
FlatSB_SetScrollPos TEXTEQU <__imp_FlatSB_SetScrollPos> 
extern __imp_FlatSB_SetScrollProp:qword 
FlatSB_SetScrollProp TEXTEQU <__imp_FlatSB_SetScrollProp> 
extern __imp_FlatSB_SetScrollRange:qword 
FlatSB_SetScrollRange TEXTEQU <__imp_FlatSB_SetScrollRange> 
extern __imp_FlatSB_ShowScrollBar:qword 
FlatSB_ShowScrollBar TEXTEQU <__imp_FlatSB_ShowScrollBar> 
extern __imp_FreeMRUList:qword 
FreeMRUList TEXTEQU <__imp_FreeMRUList> 
extern __imp_GetEffectiveClientRect:qword 
GetEffectiveClientRect TEXTEQU <__imp_GetEffectiveClientRect> 
extern __imp_GetMUILanguage:qword 
GetMUILanguage TEXTEQU <__imp_GetMUILanguage> 
extern __imp_ImageList_Add:qword 
ImageList_Add TEXTEQU <__imp_ImageList_Add> 
extern __imp_ImageList_AddIcon:qword 
ImageList_AddIcon TEXTEQU <__imp_ImageList_AddIcon> 
extern __imp_ImageList_AddMasked:qword 
ImageList_AddMasked TEXTEQU <__imp_ImageList_AddMasked> 
extern __imp_ImageList_BeginDrag:qword 
ImageList_BeginDrag TEXTEQU <__imp_ImageList_BeginDrag> 
extern __imp_ImageList_Copy:qword 
ImageList_Copy TEXTEQU <__imp_ImageList_Copy> 
extern __imp_ImageList_Create:qword 
ImageList_Create TEXTEQU <__imp_ImageList_Create> 
extern __imp_ImageList_Destroy:qword 
ImageList_Destroy TEXTEQU <__imp_ImageList_Destroy> 
extern __imp_ImageList_DragEnter:qword 
ImageList_DragEnter TEXTEQU <__imp_ImageList_DragEnter> 
extern __imp_ImageList_DragLeave:qword 
ImageList_DragLeave TEXTEQU <__imp_ImageList_DragLeave> 
extern __imp_ImageList_DragMove:qword 
ImageList_DragMove TEXTEQU <__imp_ImageList_DragMove> 
extern __imp_ImageList_DragShowNolock:qword 
ImageList_DragShowNolock TEXTEQU <__imp_ImageList_DragShowNolock> 
extern __imp_ImageList_Draw:qword 
ImageList_Draw TEXTEQU <__imp_ImageList_Draw> 
extern __imp_ImageList_DrawEx:qword 
ImageList_DrawEx TEXTEQU <__imp_ImageList_DrawEx> 
extern __imp_ImageList_DrawIndirect:qword 
ImageList_DrawIndirect TEXTEQU <__imp_ImageList_DrawIndirect> 
extern __imp_ImageList_Duplicate:qword 
ImageList_Duplicate TEXTEQU <__imp_ImageList_Duplicate> 
extern __imp_ImageList_EndDrag:qword 
ImageList_EndDrag TEXTEQU <__imp_ImageList_EndDrag> 
extern __imp_ImageList_GetBkColor:qword 
ImageList_GetBkColor TEXTEQU <__imp_ImageList_GetBkColor> 
extern __imp_ImageList_GetDragImage:qword 
ImageList_GetDragImage TEXTEQU <__imp_ImageList_GetDragImage> 
extern __imp_ImageList_GetFlags:qword 
ImageList_GetFlags TEXTEQU <__imp_ImageList_GetFlags> 
extern __imp_ImageList_GetIcon:qword 
ImageList_GetIcon TEXTEQU <__imp_ImageList_GetIcon> 
extern __imp_ImageList_GetIconSize:qword 
ImageList_GetIconSize TEXTEQU <__imp_ImageList_GetIconSize> 
extern __imp_ImageList_GetImageCount:qword 
ImageList_GetImageCount TEXTEQU <__imp_ImageList_GetImageCount> 
extern __imp_ImageList_GetImageInfo:qword 
ImageList_GetImageInfo TEXTEQU <__imp_ImageList_GetImageInfo> 
extern __imp_ImageList_GetImageRect:qword 
ImageList_GetImageRect TEXTEQU <__imp_ImageList_GetImageRect> 
extern __imp_ImageList_LoadImage:qword 
ImageList_LoadImage TEXTEQU <__imp_ImageList_LoadImage> 
extern __imp_ImageList_LoadImageA:qword 
ImageList_LoadImage TEXTEQU <__imp_ImageList_LoadImageA> 
extern __imp_ImageList_LoadImageW:qword 
ImageList_LoadImageW TEXTEQU <__imp_ImageList_LoadImageW> 
extern __imp_ImageList_Merge:qword 
ImageList_Merge TEXTEQU <__imp_ImageList_Merge> 
extern __imp_ImageList_Read:qword 
ImageList_Read TEXTEQU <__imp_ImageList_Read> 
extern __imp_ImageList_Remove:qword 
ImageList_Remove TEXTEQU <__imp_ImageList_Remove> 
extern __imp_ImageList_Replace:qword 
ImageList_Replace TEXTEQU <__imp_ImageList_Replace> 
extern __imp_ImageList_ReplaceIcon:qword 
ImageList_ReplaceIcon TEXTEQU <__imp_ImageList_ReplaceIcon> 
extern __imp_ImageList_SetBkColor:qword 
ImageList_SetBkColor TEXTEQU <__imp_ImageList_SetBkColor> 
extern __imp_ImageList_SetDragCursorImage:qword 
ImageList_SetDragCursorImage TEXTEQU <__imp_ImageList_SetDragCursorImage> 
extern __imp_ImageList_SetFilter:qword 
ImageList_SetFilter TEXTEQU <__imp_ImageList_SetFilter> 
extern __imp_ImageList_SetFlags:qword 
ImageList_SetFlags TEXTEQU <__imp_ImageList_SetFlags> 
extern __imp_ImageList_SetIconSize:qword 
ImageList_SetIconSize TEXTEQU <__imp_ImageList_SetIconSize> 
extern __imp_ImageList_SetImageCount:qword 
ImageList_SetImageCount TEXTEQU <__imp_ImageList_SetImageCount> 
extern __imp_ImageList_SetOverlayImage:qword 
ImageList_SetOverlayImage TEXTEQU <__imp_ImageList_SetOverlayImage> 
extern __imp_ImageList_Write:qword 
ImageList_Write TEXTEQU <__imp_ImageList_Write> 
extern __imp_InitCommonControls:qword 
InitCommonControls TEXTEQU <__imp_InitCommonControls> 
extern __imp_InitCommonControlsEx:qword 
InitCommonControlsEx TEXTEQU <__imp_InitCommonControlsEx> 
extern __imp_InitMUILanguage:qword 
InitMUILanguage TEXTEQU <__imp_InitMUILanguage> 
extern __imp_InitializeFlatSB:qword 
InitializeFlatSB TEXTEQU <__imp_InitializeFlatSB> 
extern __imp_LBItemFromPt:qword 
LBItemFromPt TEXTEQU <__imp_LBItemFromPt> 
extern __imp_MakeDragList:qword 
MakeDragList TEXTEQU <__imp_MakeDragList> 
extern __imp_MenuHelp:qword 
MenuHelp TEXTEQU <__imp_MenuHelp> 
extern __imp_PropertySheet:qword 
PropertySheet TEXTEQU <__imp_PropertySheet> 
extern __imp_PropertySheetA:qword 
PropertySheet TEXTEQU <__imp_PropertySheetA> 
extern __imp_PropertySheetW:qword 
PropertySheetW TEXTEQU <__imp_PropertySheetW> 
extern __imp_RegisterClassNameW:qword 
RegisterClassNameW TEXTEQU <__imp_RegisterClassNameW> 
extern __imp_RemoveWindowSubclass:qword 
RemoveWindowSubclass TEXTEQU <__imp_RemoveWindowSubclass> 
extern __imp_SetWindowSubclass:qword 
SetWindowSubclass TEXTEQU <__imp_SetWindowSubclass> 
extern __imp_ShowHideMenuCtl:qword 
ShowHideMenuCtl TEXTEQU <__imp_ShowHideMenuCtl> 
extern __imp_Str_SetPtrW:qword 
Str_SetPtrW TEXTEQU <__imp_Str_SetPtrW> 
extern __imp_UninitializeFlatSB:qword 
UninitializeFlatSB TEXTEQU <__imp_UninitializeFlatSB> 
extern __imp__TrackMouseEvent:qword 
_TrackMouseEvent TEXTEQU <__imp__TrackMouseEvent> 
extern __imp_comctl32_ordinal71:qword 
comctl32_ordinal71 TEXTEQU <__imp_comctl32_ordinal71> 
extern __imp_comctl32_ordinal72:qword 
comctl32_ordinal72 TEXTEQU <__imp_comctl32_ordinal72> 
extern __imp_comctl32_ordinal73:qword 
comctl32_ordinal73 TEXTEQU <__imp_comctl32_ordinal73> 
extern __imp_comctl32_ordinal74:qword 
comctl32_ordinal74 TEXTEQU <__imp_comctl32_ordinal74> 
extern __imp_comctl32_ordinal151:qword 
comctl32_ordinal151 TEXTEQU <__imp_comctl32_ordinal151> 
extern __imp_comctl32_ordinal153:qword 
comctl32_ordinal153 TEXTEQU <__imp_comctl32_ordinal153> 
extern __imp_comctl32_ordinal154:qword 
comctl32_ordinal154 TEXTEQU <__imp_comctl32_ordinal154> 
extern __imp_comctl32_ordinal155:qword 
comctl32_ordinal155 TEXTEQU <__imp_comctl32_ordinal155> 
extern __imp_comctl32_ordinal156:qword 
comctl32_ordinal156 TEXTEQU <__imp_comctl32_ordinal156> 
extern __imp_comctl32_ordinal157:qword 
comctl32_ordinal157 TEXTEQU <__imp_comctl32_ordinal157> 
extern __imp_comctl32_ordinal163:qword 
comctl32_ordinal163 TEXTEQU <__imp_comctl32_ordinal163> 
extern __imp_comctl32_ordinal164:qword 
comctl32_ordinal164 TEXTEQU <__imp_comctl32_ordinal164> 
extern __imp_comctl32_ordinal167:qword 
comctl32_ordinal167 TEXTEQU <__imp_comctl32_ordinal167> 
extern __imp_comctl32_ordinal169:qword 
comctl32_ordinal169 TEXTEQU <__imp_comctl32_ordinal169> 
extern __imp_comctl32_ordinal233:qword 
comctl32_ordinal233 TEXTEQU <__imp_comctl32_ordinal233> 
extern __imp_comctl32_ordinal234:qword 
comctl32_ordinal234 TEXTEQU <__imp_comctl32_ordinal234> 
extern __imp_comctl32_ordinal235:qword 
comctl32_ordinal235 TEXTEQU <__imp_comctl32_ordinal235> 
extern __imp_comctl32_ordinal341:qword 
comctl32_ordinal341 TEXTEQU <__imp_comctl32_ordinal341> 
extern __imp_comctl32_ordinal342:qword 
comctl32_ordinal342 TEXTEQU <__imp_comctl32_ordinal342> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_comctl32_ordinal382:qword 
comctl32_ordinal382 TEXTEQU <__imp_comctl32_ordinal382> 
extern __imp_comctl32_ordinal383:qword 
comctl32_ordinal383 TEXTEQU <__imp_comctl32_ordinal383> 
extern __imp_comctl32_ordinal384:qword 
comctl32_ordinal384 TEXTEQU <__imp_comctl32_ordinal384> 
extern __imp_comctl32_ordinal389:qword 
comctl32_ordinal389 TEXTEQU <__imp_comctl32_ordinal389> 
extern __imp_comctl32_ordinal390:qword 
comctl32_ordinal390 TEXTEQU <__imp_comctl32_ordinal390> 
extern __imp_comctl32_ordinal402:qword 
comctl32_ordinal402 TEXTEQU <__imp_comctl32_ordinal402> 
extern __imp_comctl32_ordinal404:qword 
comctl32_ordinal404 TEXTEQU <__imp_comctl32_ordinal404> 
extern __imp_comctl32_ordinal411:qword 
comctl32_ordinal411 TEXTEQU <__imp_comctl32_ordinal411> 
extern __imp_comctl32_ordinal414:qword 
comctl32_ordinal414 TEXTEQU <__imp_comctl32_ordinal414> 
extern __imp_comctl32_ordinal415:qword 
comctl32_ordinal415 TEXTEQU <__imp_comctl32_ordinal415> 
extern __imp_comctl32_ordinal416:qword 
comctl32_ordinal416 TEXTEQU <__imp_comctl32_ordinal416> 
extern __imp_comctl32_ordinal417:qword 
comctl32_ordinal417 TEXTEQU <__imp_comctl32_ordinal417> 
extern __imp_comctl32_ordinal418:qword 
comctl32_ordinal418 TEXTEQU <__imp_comctl32_ordinal418> 
extern __imp_comctl32_ordinal419:qword 
comctl32_ordinal419 TEXTEQU <__imp_comctl32_ordinal419> 
extern __imp_comctl32_ordinal420:qword 
comctl32_ordinal420 TEXTEQU <__imp_comctl32_ordinal420> 
extern __imp_comctl32_ordinal421:qword 
comctl32_ordinal421 TEXTEQU <__imp_comctl32_ordinal421> 
;------------------------------
TCITEMA STRUCT
       imask DWORD ?
       dwState DWORD ?
       dwStateMask DWORD ?,?
       pszText QWORD ?
       cchTextMax DWORD ?
       iImage DWORD ?
       lParam QWORD ?
TCITEMA ENDS
; Tab control messages

TCM_GETIMAGELIST   = TCM_FIRST + 2
TCM_SETIMAGELIST   = TCM_FIRST + 3
TCM_GETITEMCOUNT   = TCM_FIRST + 4
TCM_GETITEMA	   = TCM_FIRST + 5
TCM_SETITEMA	   = TCM_FIRST + 6
TCM_INSERTITEMA    = TCM_FIRST + 7
TCM_DELETEITEM	   = TCM_FIRST + 8
TCM_DELETEALLITEMS = TCM_FIRST + 9
TCM_GETITEMRECT    = TCM_FIRST + 10
TCM_GETCURSEL	   = TCM_FIRST + 11
TCM_SETCURSEL	   = TCM_FIRST + 12
TCM_HITTEST	   = TCM_FIRST + 13
TCM_SETITEMEXTRA   = TCM_FIRST + 14
TCM_ADJUSTRECT	   = TCM_FIRST + 40
TCM_SETITEMSIZE    = TCM_FIRST + 41
TCM_REMOVEIMAGE    = TCM_FIRST + 42
TCM_SETPADDING	   = TCM_FIRST + 43
TCM_GETROWCOUNT    = TCM_FIRST + 44
TCM_GETTOOLTIPS    = TCM_FIRST + 45
TCM_SETTOOLTIPS    = TCM_FIRST + 46
TCM_GETCURFOCUS    = TCM_FIRST + 47
TCM_SETCURFOCUS    = TCM_FIRST + 48
TCM_GETITEMW	   = TCM_FIRST + 60
TCM_SETITEMW	   = TCM_FIRST + 61
TCM_INSERTITEMW    = TCM_FIRST + 62
TCM_GETITEM	   = TCM_GETITEMA
TCM_SETITEM	   = TCM_SETITEMA
TCM_INSERTITEM	   = TCM_INSERTITEMA
; Tab control item structure flags

TCIF_TEXT	= 1
TCIF_IMAGE	= 2
TCIF_RTLREADING = 4
TCIF_PARAM	= 8

TCN_FIRST        equ 0-550
TCN_LAST         equ 0-580 
TCN_KEYDOWN      equ TCN_FIRST - 0
TCN_SELCHANGE    equ TCN_FIRST - 1
TCN_SELCHANGING  equ TCN_FIRST - 2
TCN_FOCUSCHANGE        equ TCN_FIRST - 4
; Toolbar messages

TB_ENABLEBUTTON 	 = WM_USER + 1
TB_CHECKBUTTON		 = WM_USER + 2
TB_PRESSBUTTON		 = WM_USER + 3
TB_HIDEBUTTON		 = WM_USER + 4
TB_INDETERMINATE	 = WM_USER + 5
TB_ISBUTTONENABLED	 = WM_USER + 9
TB_ISBUTTONCHECKED	 = WM_USER + 10
TB_ISBUTTONPRESSED	 = WM_USER + 11
TB_ISBUTTONHIDDEN	 = WM_USER + 12
TB_ISBUTTONINDETERMINATE = WM_USER + 13
TB_SETSTATE		 = WM_USER + 17
TB_GETSTATE		 = WM_USER + 18
TB_ADDBITMAP		 = WM_USER + 19
TB_ADDBUTTONS		 = WM_USER + 20
TB_INSERTBUTTON 	 = WM_USER + 21
TB_DELETEBUTTON 	 = WM_USER + 22
TB_GETBUTTON		 = WM_USER + 23
TB_BUTTONCOUNT		 = WM_USER + 24
TB_COMMANDTOINDEX	 = WM_USER + 25
TB_SAVERESTOREA 	 = WM_USER + 26
TB_ADDSTRINGA		 = WM_USER + 28
TB_CUSTOMIZE		 = WM_USER + 27
TB_GETITEMRECT		 = WM_USER + 29
TB_BUTTONSTRUCTSIZE	 = WM_USER + 30
TB_SETBUTTONSIZE	 = WM_USER + 31
TB_SETBITMAPSIZE	 = WM_USER + 32
TB_AUTOSIZE		 = WM_USER + 33
TB_GETTOOLTIPS		 = WM_USER + 35
TB_SETTOOLTIPS		 = WM_USER + 36
TB_SETPARENT		 = WM_USER + 37
TB_SETROWS		 = WM_USER + 39
TB_GETROWS		 = WM_USER + 40
TB_GETBITMAPFLAGS	 = WM_USER + 41
TB_SETCMDID		 = WM_USER + 42
TB_CHANGEBITMAP 	 = WM_USER + 43
TB_GETBITMAP		 = WM_USER + 44
TB_GETBUTTONTEXTA	 = WM_USER + 45
TB_REPLACEBITMAP	 = WM_USER + 46
TB_SETINDENT		 = WM_USER + 47
TB_SETIMAGELIST 	 = WM_USER + 48
TB_GETIMAGELIST 	 = WM_USER + 49
TB_LOADIMAGES		 = WM_USER + 50
TB_GETRECT		 = WM_USER + 51
TB_SETHOTIMAGELIST	 = WM_USER + 52
TB_GETHOTIMAGELIST	 = WM_USER + 53
TB_SETDISABLEDIMAGELIST  = WM_USER + 54
TB_GETDISABLEDIMAGELIST  = WM_USER + 55
TB_SETSTYLE		 = WM_USER + 56
TB_GETSTYLE		 = WM_USER + 57
TB_GETBUTTONSIZE	 = WM_USER + 58
TB_SETBUTTONWIDTH	 = WM_USER + 59
TB_SETMAXTEXTROWS	 = WM_USER + 60
TB_GETTEXTROWS		 = WM_USER + 61
TB_GETBUTTONTEXTW	 = WM_USER + 75
TB_SAVERESTOREW 	 = WM_USER + 76
TB_ADDSTRINGW		 = WM_USER + 77
TB_SETEXTENDEDSTYLE	 = WM_USER + 84
TB_GETEXTENDEDSTYLE	 = WM_USER + 85
TB_GETBUTTONTEXT	 = TB_GETBUTTONTEXTA
TB_SAVERESTORE		 = TB_SAVERESTOREA
TB_ADDSTRING		 = TB_ADDSTRINGA

TBBUTTON STRUCT
  iBitmap   DWORD ?
  idCommand DWORD ?
  fsState   BYTE ?
  fsStyle   BYTE 7 dup (?)
  dwData    DWORD ?
  iString   QWORD ?
TBBUTTON ENDS

TOOLTIPTEXT STRUCT
  hdr	   NMHDR <>
  lpszText QWORD ?
           DWORD ?
  szText   BYTE 80 dup (?)
  hinst    QWORD ?
  uFlags   DWORD ?
TOOLTIPTEXT ENDS

; Icon indexes for standard bitmap

STD_CUT        = 0
STD_COPY       = 1
STD_PASTE      = 2
STD_UNDO       = 3
STD_REDOW      = 4
STD_DELETE     = 5
STD_FILENEW    = 6
STD_FILEOPEN   = 7
STD_FILESAVE   = 8
STD_PRINTPRE   = 9
STD_PROPERTIES = 10
STD_HELP       = 11
STD_FIND       = 12
STD_REPLACE    = 13
STD_PRINT      = 14

; Progress bar messages

PBM_SETRANGE   = WM_USER + 1
PBM_SETPOS     = WM_USER + 2
PBM_DELTAPOS   = WM_USER + 3
PBM_SETSTEP    = WM_USER + 4
PBM_STEPIT     = WM_USER + 5
PBM_SETRANGE32 = WM_USER + 6
PBM_GETRANGE   = WM_USER + 7
PBM_GETPOS     = WM_USER + 8

PBS_SMOOTH	 equ 1
PBS_VERTICAL	 equ 4
;---------------------------------
TVN_FIRST  = -400

TV_ITEM STRUCT
  imask		 DWORD ?,?
  hItem 	 QWORD ?
  state 	 DWORD ?
  stateMask	 DWORD ?
  pszText	 QWORD ?
  cchTextMax	 DWORD ?
  iImage	 DWORD ?
  iSelectedImage DWORD ?
  cChildren	 DWORD ?
  lParam	 DWORD ?
TV_ITEM ENDS

NM_TREEVIEW STRUCT
  hdr	  NMHDR <>
	DWORD ?
  action  DWORD ?
  itemOld TV_ITEM <>
  itemNew TV_ITEM <>
  ptDrag  POINT <>
NM_TREEVIEW ENDS
; Tree view messages

TVM_INSERTITEMA       = TV_FIRST + 0
TVM_DELETEITEM	      = TV_FIRST + 1
TVM_EXPAND	      = TV_FIRST + 2
TVM_GETITEMRECT       = TV_FIRST + 4
TVM_GETCOUNT	      = TV_FIRST + 5
TVM_GETINDENT	      = TV_FIRST + 6
TVM_SETINDENT	      = TV_FIRST + 7
TVM_GETIMAGELIST      = TV_FIRST + 8
TVM_SETIMAGELIST      = TV_FIRST + 9
TVM_GETNEXTITEM       = TV_FIRST + 10
TVM_SELECTITEM	      = TV_FIRST + 11
TVM_GETITEMA	      = TV_FIRST + 12
TVM_SETITEMA	      = TV_FIRST + 13
TVM_EDITLABELA	      = TV_FIRST + 14
TVM_GETEDITCONTROL    = TV_FIRST + 15
TVM_GETVISIBLECOUNT   = TV_FIRST + 16
TVM_HITTEST	      = TV_FIRST + 17
TVM_CREATEDRAGIMAGE   = TV_FIRST + 18
TVM_SORTCHILDREN      = TV_FIRST + 19
TVM_ENSUREVISIBLE     = TV_FIRST + 20
TVM_SORTCHILDRENCB    = TV_FIRST + 21
TVM_ENDEDITLABELNOW   = TV_FIRST + 22
TVM_GETISEARCHSTRINGA = TV_FIRST + 23
TVM_INSERTITEMW       = TV_FIRST + 50
TVM_GETITEMW	      = TV_FIRST + 62
TVM_SETITEMW	      = TV_FIRST + 63
TVM_GETISEARCHSTRINGW = TV_FIRST + 64
TVM_EDITLABELW	      = TV_FIRST + 65
TVM_INSERTITEM	      = TVM_INSERTITEMA
TVM_GETITEM	      = TVM_GETITEMA
TVM_SETITEM	      = TVM_SETITEMA
TVM_GETISEARCHSTRING  = TVM_GETISEARCHSTRINGA
TVM_EDITLABEL	      = TVM_EDITLABELA

; Tree view notifications

TVN_SELCHANGINGA    = TVN_FIRST - 1
TVN_SELCHANGEDA     = TVN_FIRST - 2
TVN_GETDISPINFOA    = TVN_FIRST - 3
TVN_SETDISPINFOA    = TVN_FIRST - 4
TVN_ITEMEXPANDINGA  = TVN_FIRST - 5
TVN_ITEMEXPANDEDA   = TVN_FIRST - 6
TVN_BEGINDRAGA	    = TVN_FIRST - 7
TVN_BEGINRDRAGA     = TVN_FIRST - 8
TVN_DELETEITEMA     = TVN_FIRST - 9
TVN_BEGINLABELEDITA = TVN_FIRST - 10
TVN_ENDLABELEDITA   = TVN_FIRST - 11
TVN_KEYDOWN	    = TVN_FIRST - 12
TVN_SELCHANGINGW    = TVN_FIRST - 50
TVN_SELCHANGEDW     = TVN_FIRST - 51
TVN_GETDISPINFOW    = TVN_FIRST - 52
TVN_SETDISPINFOW    = TVN_FIRST - 53
TVN_ITEMEXPANDINGW  = TVN_FIRST - 54
TVN_ITEMEXPANDEDW   = TVN_FIRST - 55
TVN_BEGINDRAGW	    = TVN_FIRST - 56
TVN_BEGINRDRAGW     = TVN_FIRST - 57
TVN_DELETEITEMW     = TVN_FIRST - 58
TVN_BEGINLABELEDITW = TVN_FIRST - 59
TVN_ENDLABELEDITW   = TVN_FIRST - 60
TVN_SELCHANGING     = TVN_SELCHANGINGA
TVN_SELCHANGED	    = TVN_SELCHANGEDA
TVN_GETDISPINFO     = TVN_GETDISPINFOA
TVN_SETDISPINFO     = TVN_SETDISPINFOA
TVN_ITEMEXPANDING   = TVN_ITEMEXPANDINGA
TVN_ITEMEXPANDED    = TVN_ITEMEXPANDEDA
TVN_BEGINDRAG	    = TVN_BEGINDRAGA
TVN_BEGINRDRAG	    = TVN_BEGINRDRAGA
TVN_DELETEITEM	    = TVN_DELETEITEMA
TVN_BEGINLABELEDIT  = TVN_BEGINLABELEDITA
TVN_ENDLABELEDIT    = TVN_ENDLABELEDITA

; Tree view next item types

TVGN_ROOT	     = 0
TVGN_NEXT	     = 1
TVGN_PREVIOUS	     = 2
TVGN_PARENT	     = 3
TVGN_CHILD	     = 4
TVGN_FIRSTVISIBLE    = 5
TVGN_NEXTVISIBLE     = 6
TVGN_PREVIOUSVISIBLE = 7
TVGN_DROPHILITE      = 8
TVGN_CARET	     = 9

; Tree view styles

TVS_HASBUTTONS	    = 0001h
TVS_HASLINES	    = 0002h
TVS_LINESATROOT     = 0004h
TVS_EDITLABELS	    = 0008h
TVS_DISABLEDRAGDROP = 0010h
TVS_SHOWSELALWAYS   = 0020h
TVS_RTLREADING	    = 0040h
TVS_NOTOOLTIPS	    = 0080h
TVS_CHECKBOXES	    = 0100h
TVS_TRACKSELECT     = 0200h
TVS_SINGLEEXPAND    = 0400h
TVS_INFOTIP	    = 0800h
TVS_FULLROWSELECT   = 1000h
TVS_NOSCROLL	    = 2000h
TVS_NONEVENHEIGHT   = 4000h

TV_INSERTSTRUCT STRUCT
  hParent      QWORD ?
  hInsertAfter QWORD ?
  item	       TV_ITEM <>
TV_INSERTSTRUCT ENDS

; Tree view predefined item values

TVI_ROOT  = 0FFFF0000h
TVI_FIRST = 0FFFF0001h
TVI_LAST  = 0FFFF0002h
TVI_SORT  = 0FFFF0003h
TV_HITTESTINFO STRUCT
  pt	POINT <>
  flags DWORD ?,?
  hItem QWORD ?
TV_HITTESTINFO ENDS

; Tree view item structure flags

TVIF_TEXT	   = 0001h
TVIF_IMAGE	   = 0002h
TVIF_PARAM	   = 0004h
TVIF_STATE	   = 0008h
TVIF_HANDLE	   = 0010h
TVIF_SELECTEDIMAGE = 0020h
TVIF_CHILDREN	   = 0040h
TVIF_DI_SETITEM    = 1000h

; Tree view action flags

TVE_COLLAPSE	  = 0001h
TVE_EXPAND	  = 0002h
TVE_TOGGLE	  = 0003h
TVE_EXPANDPARTIAL = 4000h
TVE_COLLAPSERESET = 8000h

TVM_SETBKCOLOR         equ  TV_FIRST + 29
TVM_SETTEXTCOLOR       equ  TV_FIRST + 30
TVM_SETLINECOLOR       equ  TV_FIRST + 40
TVM_SETINSERTMARKCOLOR equ  TV_FIRST + 37

TOOLINFO STRUCT
  cbSize   DWORD ?
  uFlags   DWORD ?
  hwnd	   QWORD ?
  uId	   QWORD ?
  Rect	   RECT <>
           ;DWORD ?
  hInst    QWORD ?
  lpszText QWORD ?
TOOLINFO ENDS

LV_COLUMN STRUCT
  imask	     DWORD ?
  fmt	     DWORD ?
  lx	     DWORD ?,?
  pszText    QWORD ?
  cchTextMax DWORD ?
  iSubItem   DWORD ?
LV_COLUMN ENDS

LV_ITEM STRUCT
  imask	     DWORD ?
  iItem      DWORD ?
  iSubItem   DWORD ?
  state      DWORD ?
  stateMask  DWORD ?,?
  pszText    QWORD ?
  cchTextMax DWORD ?
  iImage     DWORD ?
  lParam     DWORD ?
  iIndent    DWORD ?
LV_ITEM ENDS

; List view messages

LVM_GETBKCOLOR		     = LVM_FIRST + 0
LVM_SETBKCOLOR		     = LVM_FIRST + 1
LVM_GETIMAGELIST	     = LVM_FIRST + 2
LVM_SETIMAGELIST	     = LVM_FIRST + 3
LVM_GETITEMCOUNT	     = LVM_FIRST + 4
LVM_GETITEMA		     = LVM_FIRST + 5
LVM_SETITEMA		     = LVM_FIRST + 6
LVM_INSERTITEMA 	     = LVM_FIRST + 7
LVM_DELETEITEM		     = LVM_FIRST + 8
LVM_DELETEALLITEMS	     = LVM_FIRST + 9
LVM_GETCALLBACKMASK	     = LVM_FIRST + 10
LVM_SETCALLBACKMASK	     = LVM_FIRST + 11
LVM_GETNEXTITEM 	     = LVM_FIRST + 12
LVM_FINDITEMA		     = LVM_FIRST + 13
LVM_GETITEMRECT 	     = LVM_FIRST + 14
LVM_SETITEMPOSITION	     = LVM_FIRST + 15
LVM_GETITEMPOSITION	     = LVM_FIRST + 16
LVM_GETSTRINGWIDTHA	     = LVM_FIRST + 17
LVM_HITTEST		     = LVM_FIRST + 18
LVM_ENSUREVISIBLE	     = LVM_FIRST + 19
LVM_SCROLL		     = LVM_FIRST + 20
LVM_REDRAWITEMS 	     = LVM_FIRST + 21
LVM_ARRANGE		     = LVM_FIRST + 22
LVM_EDITLABELA		     = LVM_FIRST + 23
LVM_GETEDITCONTROL	     = LVM_FIRST + 24
LVM_GETCOLUMNA		     = LVM_FIRST + 25
LVM_SETCOLUMNA		     = LVM_FIRST + 26
LVM_INSERTCOLUMNA	     = LVM_FIRST + 27
LVM_DELETECOLUMN	     = LVM_FIRST + 28
LVM_GETCOLUMNWIDTH	     = LVM_FIRST + 29
LVM_SETCOLUMNWIDTH	     = LVM_FIRST + 30
LVM_CREATEDRAGIMAGE	     = LVM_FIRST + 33
LVM_GETVIEWRECT 	     = LVM_FIRST + 34
LVM_GETTEXTCOLOR	     = LVM_FIRST + 35
LVM_SETTEXTCOLOR	     = LVM_FIRST + 36
LVM_GETTEXTBKCOLOR	     = LVM_FIRST + 37
LVM_SETTEXTBKCOLOR	     = LVM_FIRST + 38
LVM_GETTOPINDEX 	     = LVM_FIRST + 39
LVM_GETCOUNTPERPAGE	     = LVM_FIRST + 40
LVM_GETORIGIN		     = LVM_FIRST + 41
LVM_UPDATE		     = LVM_FIRST + 42
LVM_SETITEMSTATE	     = LVM_FIRST + 43
LVM_GETITEMSTATE	     = LVM_FIRST + 44
LVM_GETITEMTEXTA	     = LVM_FIRST + 45
LVM_SETITEMTEXTA	     = LVM_FIRST + 46
LVM_SETITEMCOUNT	     = LVM_FIRST + 47
LVM_SORTITEMS		     = LVM_FIRST + 48
LVM_SETITEMPOSITION32	     = LVM_FIRST + 49
LVM_GETSELECTEDCOUNT	     = LVM_FIRST + 50
LVM_GETITEMSPACING	     = LVM_FIRST + 51
LVM_GETISEARCHSTRINGA	     = LVM_FIRST + 52
LVM_SETICONSPACING	     = LVM_FIRST + 53
LVM_SETEXTENDEDLISTVIEWSTYLE = LVM_FIRST + 54
LVM_GETEXTENDEDLISTVIEWSTYLE = LVM_FIRST + 55
LVM_GETSUBITEMRECT	     = LVM_FIRST + 56
LVM_SUBITEMHITTEST	     = LVM_FIRST + 57
LVM_SETCOLUMNORDERARRAY      = LVM_FIRST + 58
LVM_GETCOLUMNORDERARRAY      = LVM_FIRST + 59
LVM_SETHOTITEM		     = LVM_FIRST + 60
LVM_GETHOTITEM		     = LVM_FIRST + 61
LVM_SETHOTCURSOR	     = LVM_FIRST + 62
LVM_GETHOTCURSOR	     = LVM_FIRST + 63
LVM_APPROXIMATEVIEWRECT      = LVM_FIRST + 64
LVM_SETWORKAREA 	     = LVM_FIRST + 65
LVM_GETITEMW		     = LVM_FIRST + 75
LVM_SETITEMW		     = LVM_FIRST + 76
LVM_INSERTITEMW 	     = LVM_FIRST + 77
LVM_FINDITEMW		     = LVM_FIRST + 83
LVM_GETSTRINGWIDTHW	     = LVM_FIRST + 87
LVM_GETCOLUMNW		     = LVM_FIRST + 95
LVM_SETCOLUMNW		     = LVM_FIRST + 96
LVM_INSERTCOLUMNW	     = LVM_FIRST + 97
LVM_GETITEMTEXTW	     = LVM_FIRST + 115
LVM_SETITEMTEXTW	     = LVM_FIRST + 116
LVM_GETISEARCHSTRINGW	     = LVM_FIRST + 117
LVM_EDITLABELW		     = LVM_FIRST + 118
LVM_GETITEM		     = LVM_GETITEMA
LVM_SETITEM		     = LVM_SETITEMA
LVM_INSERTITEM		     = LVM_INSERTITEMA
LVM_FINDITEM		     = LVM_FINDITEMA
LVM_GETSTRINGWIDTH	     = LVM_GETSTRINGWIDTHA
LVM_GETCOLUMN		     = LVM_GETCOLUMNA
LVM_SETCOLUMN		     = LVM_SETCOLUMNA
LVM_INSERTCOLUMN	     = LVM_INSERTCOLUMNA
LVM_GETITEMTEXT 	     = LVM_GETITEMTEXTA
LVM_SETITEMTEXT 	     = LVM_SETITEMTEXTA
LVM_GETISEARCHSTRING	     = LVM_GETISEARCHSTRINGA
LVM_EDITLABEL		     = LVM_EDITLABELA

; List view next item relations

LVNI_ALL	 = 000h
LVNI_FOCUSED	 = 001h
LVNI_SELECTED	 = 002h
LVNI_CUT	 = 004h
LVNI_DROPHILITED = 008h
LVNI_ABOVE	 = 100h
LVNI_BELOW	 = 200h
LVNI_TOLEFT	 = 400h
LVNI_TORIGHT	 = 800h

NM_LISTVIEW  STRUCT
  hdr	    NMHDR <>
  iItem     DWORD ?
            DWORD ?
  iSubItem  DWORD ?
  uNewState DWORD ?
  uOldState DWORD ?
  uChanged  DWORD ?
  ptAction  POINT <>
	    DWORD ?
  lParam    QWORD ?
NM_LISTVIEW  ENDS

LV_HITTESTINFO STRUCT
  pt        POINT <>
  flags     DWORD ?
  iItem     DWORD ?
  iSubItem  DWORD ?
LV_HITTESTINFO ENDS

; List view hit test flags

LVHT_NOWHERE	    = 1
LVHT_ONITEMICON     = 2
LVHT_ONITEMLABEL    = 4
LVHT_ONITEMSTATEICON= 8
LVHT_ONITEM	    = LVHT_ONITEMICON or LVHT_ONITEMLABEL or LVHT_ONITEMSTATEICON
LVHT_ABOVE	    = 8
LVHT_BELOW	    = 10h
LVHT_TORIGHT	    = 20h
LVHT_TOLEFT	    = 40h

; List view alignment values

LVA_DEFAULT	   = 0
LVA_ALIGNLEFT	   = 1
LVA_ALIGNTOP	   = 2
LVA_ALIGNRIGHT	   = 3
LVA_ALIGNBOTTOM    = 4
LVA_SNAPTOGRID	   = 5
LVA_SORTASCENDING  = 100h
LVA_SORTDESCENDING = 200h