extern __imp_AbortDoc:qword 
AbortDoc TEXTEQU <__imp_AbortDoc> 
extern __imp_AbortPath:qword 
AbortPath TEXTEQU <__imp_AbortPath> 
extern __imp_AddFontMemResourceEx:qword 
AddFontMemResourceEx TEXTEQU <__imp_AddFontMemResourceEx> 
extern __imp_AddFontResourceA:qword 
AddFontResource TEXTEQU <__imp_AddFontResourceA> 
extern __imp_AddFontResourceExA:qword 
AddFontResourceEx TEXTEQU <__imp_AddFontResourceExA> 
extern __imp_AddFontResourceExW:qword 
AddFontResourceExW TEXTEQU <__imp_AddFontResourceExW> 
extern __imp_AddFontResourceTracking:qword 
AddFontResourceTracking TEXTEQU <__imp_AddFontResourceTracking> 
extern __imp_AddFontResourceW:qword 
AddFontResourceW TEXTEQU <__imp_AddFontResourceW> 
extern __imp_AngleArc:qword 
AngleArc TEXTEQU <__imp_AngleArc> 
extern __imp_AnimatePalette:qword 
AnimatePalette TEXTEQU <__imp_AnimatePalette> 
extern __imp_AnyLinkedFonts:qword 
AnyLinkedFonts TEXTEQU <__imp_AnyLinkedFonts> 
extern __imp_Arc:qword 
Arc TEXTEQU <__imp_Arc> 
extern __imp_ArcTo:qword 
ArcTo TEXTEQU <__imp_ArcTo> 
extern __imp_BRUSHOBJ_hGetColorTransform:qword 
BRUSHOBJ_hGetColorTransform TEXTEQU <__imp_BRUSHOBJ_hGetColorTransform> 
extern __imp_BRUSHOBJ_pvAllocRbrush:qword 
BRUSHOBJ_pvAllocRbrush TEXTEQU <__imp_BRUSHOBJ_pvAllocRbrush> 
extern __imp_BRUSHOBJ_pvGetRbrush:qword 
BRUSHOBJ_pvGetRbrush TEXTEQU <__imp_BRUSHOBJ_pvGetRbrush> 
extern __imp_BRUSHOBJ_ulGetBrushColor:qword 
BRUSHOBJ_ulGetBrushColor TEXTEQU <__imp_BRUSHOBJ_ulGetBrushColor> 
extern __imp_BeginGdiRendering:qword 
BeginGdiRendering TEXTEQU <__imp_BeginGdiRendering> 
extern __imp_BeginPath:qword 
BeginPath TEXTEQU <__imp_BeginPath> 
extern __imp_BitBlt:qword 
BitBlt TEXTEQU <__imp_BitBlt> 
extern __imp_CLIPOBJ_bEnum:qword 
CLIPOBJ_bEnum TEXTEQU <__imp_CLIPOBJ_bEnum> 
extern __imp_CLIPOBJ_cEnumStart:qword 
CLIPOBJ_cEnumStart TEXTEQU <__imp_CLIPOBJ_cEnumStart> 
extern __imp_CLIPOBJ_ppoGetPath:qword 
CLIPOBJ_ppoGetPath TEXTEQU <__imp_CLIPOBJ_ppoGetPath> 
extern __imp_CancelDC:qword 
CancelDC TEXTEQU <__imp_CancelDC> 
extern __imp_CheckColorsInGamut:qword 
CheckColorsInGamut TEXTEQU <__imp_CheckColorsInGamut> 
extern __imp_ChoosePixelFormat:qword 
ChoosePixelFormat TEXTEQU <__imp_ChoosePixelFormat> 
extern __imp_Chord:qword 
Chord TEXTEQU <__imp_Chord> 
extern __imp_ClearBitmapAttributes:qword 
ClearBitmapAttributes TEXTEQU <__imp_ClearBitmapAttributes> 
extern __imp_ClearBrushAttributes:qword 
ClearBrushAttributes TEXTEQU <__imp_ClearBrushAttributes> 
extern __imp_CloseEnhMetaFile:qword 
CloseEnhMetaFile TEXTEQU <__imp_CloseEnhMetaFile> 
extern __imp_CloseFigure:qword 
CloseFigure TEXTEQU <__imp_CloseFigure> 
extern __imp_CloseMetaFile:qword 
CloseMetaFile TEXTEQU <__imp_CloseMetaFile> 
extern __imp_ColorCorrectPalette:qword 
ColorCorrectPalette TEXTEQU <__imp_ColorCorrectPalette> 
extern __imp_ColorMatchToTarget:qword 
ColorMatchToTarget TEXTEQU <__imp_ColorMatchToTarget> 
extern __imp_CombineRgn:qword 
CombineRgn TEXTEQU <__imp_CombineRgn> 
extern __imp_CombineTransform:qword 
CombineTransform TEXTEQU <__imp_CombineTransform> 
extern __imp_ConfigureOPMProtectedOutput:qword 
ConfigureOPMProtectedOutput TEXTEQU <__imp_ConfigureOPMProtectedOutput> 
extern __imp_CopyEnhMetaFileA:qword 
CopyEnhMetaFile TEXTEQU <__imp_CopyEnhMetaFileA> 
extern __imp_CopyEnhMetaFileW:qword 
CopyEnhMetaFileW TEXTEQU <__imp_CopyEnhMetaFileW> 
extern __imp_CopyMetaFileA:qword 
CopyMetaFile TEXTEQU <__imp_CopyMetaFileA> 
extern __imp_CopyMetaFileW:qword 
CopyMetaFileW TEXTEQU <__imp_CopyMetaFileW> 
extern __imp_CreateBitmap:qword 
CreateBitmap TEXTEQU <__imp_CreateBitmap> 
extern __imp_CreateBitmapFromDxSurface:qword 
CreateBitmapFromDxSurface TEXTEQU <__imp_CreateBitmapFromDxSurface> 
extern __imp_CreateBitmapIndirect:qword 
CreateBitmapIndirect TEXTEQU <__imp_CreateBitmapIndirect> 
extern __imp_CreateBrushIndirect:qword 
CreateBrushIndirect TEXTEQU <__imp_CreateBrushIndirect> 
extern __imp_CreateColorSpaceA:qword 
CreateColorSpace TEXTEQU <__imp_CreateColorSpaceA> 
extern __imp_CreateColorSpaceW:qword 
CreateColorSpaceW TEXTEQU <__imp_CreateColorSpaceW> 
extern __imp_CreateCompatibleBitmap:qword 
CreateCompatibleBitmap TEXTEQU <__imp_CreateCompatibleBitmap> 
extern __imp_CreateCompatibleDC:qword 
CreateCompatibleDC TEXTEQU <__imp_CreateCompatibleDC> 
extern __imp_CreateDCA:qword 
CreateDC TEXTEQU <__imp_CreateDCA> 
extern __imp_CreateDCW:qword 
CreateDCW TEXTEQU <__imp_CreateDCW> 
extern __imp_CreateDIBPatternBrush:qword 
CreateDIBPatternBrush TEXTEQU <__imp_CreateDIBPatternBrush> 
extern __imp_CreateDIBPatternBrushPt:qword 
CreateDIBPatternBrushPt TEXTEQU <__imp_CreateDIBPatternBrushPt> 
extern __imp_CreateDIBSection:qword 
CreateDIBSection TEXTEQU <__imp_CreateDIBSection> 
extern __imp_CreateDIBitmap:qword 
CreateDIBitmap TEXTEQU <__imp_CreateDIBitmap> 
extern __imp_CreateDiscardableBitmap:qword 
CreateDiscardableBitmap TEXTEQU <__imp_CreateDiscardableBitmap> 
extern __imp_CreateEllipticRgn:qword 
CreateEllipticRgn TEXTEQU <__imp_CreateEllipticRgn> 
extern __imp_CreateEllipticRgnIndirect:qword 
CreateEllipticRgnIndirect TEXTEQU <__imp_CreateEllipticRgnIndirect> 
extern __imp_CreateEnhMetaFileA:qword 
CreateEnhMetaFile TEXTEQU <__imp_CreateEnhMetaFileA> 
extern __imp_CreateEnhMetaFileW:qword 
CreateEnhMetaFileW TEXTEQU <__imp_CreateEnhMetaFileW> 
extern __imp_CreateFontA:qword 
CreateFont TEXTEQU <__imp_CreateFontA> 
extern __imp_CreateFontIndirectA:qword 
CreateFontIndirect TEXTEQU <__imp_CreateFontIndirectA> 
extern __imp_CreateFontIndirectExA:qword 
CreateFontIndirectEx TEXTEQU <__imp_CreateFontIndirectExA> 
extern __imp_CreateFontIndirectExW:qword 
CreateFontIndirectExW TEXTEQU <__imp_CreateFontIndirectExW> 
extern __imp_CreateFontIndirectW:qword 
CreateFontIndirectW TEXTEQU <__imp_CreateFontIndirectW> 
extern __imp_CreateFontW:qword 
CreateFontW TEXTEQU <__imp_CreateFontW> 
extern __imp_CreateHalftonePalette:qword 
CreateHalftonePalette TEXTEQU <__imp_CreateHalftonePalette> 
extern __imp_CreateHatchBrush:qword 
CreateHatchBrush TEXTEQU <__imp_CreateHatchBrush> 
extern __imp_CreateICA:qword 
CreateIC TEXTEQU <__imp_CreateICA> 
extern __imp_CreateICW:qword 
CreateICW TEXTEQU <__imp_CreateICW> 
extern __imp_CreateMetaFileA:qword 
CreateMetaFile TEXTEQU <__imp_CreateMetaFileA> 
extern __imp_CreateMetaFileW:qword 
CreateMetaFileW TEXTEQU <__imp_CreateMetaFileW> 
extern __imp_CreateOPMProtectedOutputs:qword 
CreateOPMProtectedOutputs TEXTEQU <__imp_CreateOPMProtectedOutputs> 
extern __imp_CreatePalette:qword 
CreatePalette TEXTEQU <__imp_CreatePalette> 
extern __imp_CreatePatternBrush:qword 
CreatePatternBrush TEXTEQU <__imp_CreatePatternBrush> 
extern __imp_CreatePen:qword 
CreatePen TEXTEQU <__imp_CreatePen> 
extern __imp_CreatePenIndirect:qword 
CreatePenIndirect TEXTEQU <__imp_CreatePenIndirect> 
extern __imp_CreatePolyPolygonRgn:qword 
CreatePolyPolygonRgn TEXTEQU <__imp_CreatePolyPolygonRgn> 
extern __imp_CreatePolygonRgn:qword 
CreatePolygonRgn TEXTEQU <__imp_CreatePolygonRgn> 
extern __imp_CreateRectRgn:qword 
CreateRectRgn TEXTEQU <__imp_CreateRectRgn> 
extern __imp_CreateRectRgnIndirect:qword 
CreateRectRgnIndirect TEXTEQU <__imp_CreateRectRgnIndirect> 
extern __imp_CreateRoundRectRgn:qword 
CreateRoundRectRgn TEXTEQU <__imp_CreateRoundRectRgn> 
extern __imp_CreateScalableFontResourceA:qword 
CreateScalableFontResource TEXTEQU <__imp_CreateScalableFontResourceA> 
extern __imp_CreateScalableFontResourceW:qword 
CreateScalableFontResourceW TEXTEQU <__imp_CreateScalableFontResourceW> 
extern __imp_CreateSolidBrush:qword 
CreateSolidBrush TEXTEQU <__imp_CreateSolidBrush> 
extern __imp_D3DKMTAcquireKeyedMutex:qword 
D3DKMTAcquireKeyedMutex TEXTEQU <__imp_D3DKMTAcquireKeyedMutex> 
extern __imp_D3DKMTCheckExclusiveOwnership:qword 
D3DKMTCheckExclusiveOwnership TEXTEQU <__imp_D3DKMTCheckExclusiveOwnership> 
extern __imp_D3DKMTCheckMonitorPowerState:qword 
D3DKMTCheckMonitorPowerState TEXTEQU <__imp_D3DKMTCheckMonitorPowerState> 
extern __imp_D3DKMTCheckOcclusion:qword 
D3DKMTCheckOcclusion TEXTEQU <__imp_D3DKMTCheckOcclusion> 
extern __imp_D3DKMTCheckSharedResourceAccess:qword 
D3DKMTCheckSharedResourceAccess TEXTEQU <__imp_D3DKMTCheckSharedResourceAccess> 
extern __imp_D3DKMTCheckVidPnExclusiveOwnership:qword 
D3DKMTCheckVidPnExclusiveOwnership TEXTEQU <__imp_D3DKMTCheckVidPnExclusiveOwnership> 
extern __imp_D3DKMTCloseAdapter:qword 
D3DKMTCloseAdapter TEXTEQU <__imp_D3DKMTCloseAdapter> 
extern __imp_D3DKMTConfigureSharedResource:qword 
D3DKMTConfigureSharedResource TEXTEQU <__imp_D3DKMTConfigureSharedResource> 
extern __imp_D3DKMTCreateAllocation:qword 
D3DKMTCreateAllocation TEXTEQU <__imp_D3DKMTCreateAllocation> 
extern __imp_D3DKMTCreateAllocation2:qword 
D3DKMTCreateAllocation2 TEXTEQU <__imp_D3DKMTCreateAllocation2> 
extern __imp_D3DKMTCreateContext:qword 
D3DKMTCreateContext TEXTEQU <__imp_D3DKMTCreateContext> 
extern __imp_D3DKMTCreateDCFromMemory:qword 
D3DKMTCreateDCFromMemory TEXTEQU <__imp_D3DKMTCreateDCFromMemory> 
extern __imp_D3DKMTCreateDevice:qword 
D3DKMTCreateDevice TEXTEQU <__imp_D3DKMTCreateDevice> 
extern __imp_D3DKMTCreateKeyedMutex:qword 
D3DKMTCreateKeyedMutex TEXTEQU <__imp_D3DKMTCreateKeyedMutex> 
extern __imp_D3DKMTCreateOverlay:qword 
D3DKMTCreateOverlay TEXTEQU <__imp_D3DKMTCreateOverlay> 
extern __imp_D3DKMTCreateSynchronizationObject:qword 
D3DKMTCreateSynchronizationObject TEXTEQU <__imp_D3DKMTCreateSynchronizationObject> 
extern __imp_D3DKMTCreateSynchronizationObject2:qword 
D3DKMTCreateSynchronizationObject2 TEXTEQU <__imp_D3DKMTCreateSynchronizationObject2> 
extern __imp_D3DKMTDestroyAllocation:qword 
D3DKMTDestroyAllocation TEXTEQU <__imp_D3DKMTDestroyAllocation> 
extern __imp_D3DKMTDestroyContext:qword 
D3DKMTDestroyContext TEXTEQU <__imp_D3DKMTDestroyContext> 
extern __imp_D3DKMTDestroyDCFromMemory:qword 
D3DKMTDestroyDCFromMemory TEXTEQU <__imp_D3DKMTDestroyDCFromMemory> 
extern __imp_D3DKMTDestroyDevice:qword 
D3DKMTDestroyDevice TEXTEQU <__imp_D3DKMTDestroyDevice> 
extern __imp_D3DKMTDestroyKeyedMutex:qword 
D3DKMTDestroyKeyedMutex TEXTEQU <__imp_D3DKMTDestroyKeyedMutex> 
extern __imp_D3DKMTDestroyOverlay:qword 
D3DKMTDestroyOverlay TEXTEQU <__imp_D3DKMTDestroyOverlay> 
extern __imp_D3DKMTDestroySynchronizationObject:qword 
D3DKMTDestroySynchronizationObject TEXTEQU <__imp_D3DKMTDestroySynchronizationObject> 
extern __imp_D3DKMTEscape:qword 
D3DKMTEscape TEXTEQU <__imp_D3DKMTEscape> 
extern __imp_D3DKMTFlipOverlay:qword 
D3DKMTFlipOverlay TEXTEQU <__imp_D3DKMTFlipOverlay> 
extern __imp_D3DKMTGetContextSchedulingPriority:qword 
D3DKMTGetContextSchedulingPriority TEXTEQU <__imp_D3DKMTGetContextSchedulingPriority> 
extern __imp_D3DKMTGetDeviceState:qword 
D3DKMTGetDeviceState TEXTEQU <__imp_D3DKMTGetDeviceState> 
extern __imp_D3DKMTGetDisplayModeList:qword 
D3DKMTGetDisplayModeList TEXTEQU <__imp_D3DKMTGetDisplayModeList> 
extern __imp_D3DKMTGetMultisampleMethodList:qword 
D3DKMTGetMultisampleMethodList TEXTEQU <__imp_D3DKMTGetMultisampleMethodList> 
extern __imp_D3DKMTGetOverlayState:qword 
D3DKMTGetOverlayState TEXTEQU <__imp_D3DKMTGetOverlayState> 
extern __imp_D3DKMTGetPresentHistory:qword 
D3DKMTGetPresentHistory TEXTEQU <__imp_D3DKMTGetPresentHistory> 
extern __imp_D3DKMTGetPresentQueueEvent:qword 
D3DKMTGetPresentQueueEvent TEXTEQU <__imp_D3DKMTGetPresentQueueEvent> 
extern __imp_D3DKMTGetProcessSchedulingPriorityClass:qword 
D3DKMTGetProcessSchedulingPriorityClass TEXTEQU <__imp_D3DKMTGetProcessSchedulingPriorityClass> 
extern __imp_D3DKMTGetRuntimeData:qword 
D3DKMTGetRuntimeDat TEXTEQU <__imp_D3DKMTGetRuntimeData> 
extern __imp_D3DKMTGetScanLine:qword 
D3DKMTGetScanLine TEXTEQU <__imp_D3DKMTGetScanLine> 
extern __imp_D3DKMTGetSharedPrimaryHandle:qword 
D3DKMTGetSharedPrimaryHandle TEXTEQU <__imp_D3DKMTGetSharedPrimaryHandle> 
extern __imp_D3DKMTInvalidateActiveVidPn:qword 
D3DKMTInvalidateActiveVidPn TEXTEQU <__imp_D3DKMTInvalidateActiveVidPn> 
extern __imp_D3DKMTLock:qword 
D3DKMTLock TEXTEQU <__imp_D3DKMTLock> 
extern __imp_D3DKMTOpenAdapterFromDeviceName:qword 
D3DKMTOpenAdapterFromDeviceName TEXTEQU <__imp_D3DKMTOpenAdapterFromDeviceName> 
extern __imp_D3DKMTOpenAdapterFromGdiDisplayName:qword 
D3DKMTOpenAdapterFromGdiDisplayName TEXTEQU <__imp_D3DKMTOpenAdapterFromGdiDisplayName> 
extern __imp_D3DKMTOpenAdapterFromHdc:qword 
D3DKMTOpenAdapterFromHdc TEXTEQU <__imp_D3DKMTOpenAdapterFromHdc> 
extern __imp_D3DKMTOpenKeyedMutex:qword 
D3DKMTOpenKeyedMutex TEXTEQU <__imp_D3DKMTOpenKeyedMutex> 
extern __imp_D3DKMTOpenResource:qword 
D3DKMTOpenResource TEXTEQU <__imp_D3DKMTOpenResource> 
extern __imp_D3DKMTOpenResource2:qword 
D3DKMTOpenResource2 TEXTEQU <__imp_D3DKMTOpenResource2> 
extern __imp_D3DKMTOpenSynchronizationObject:qword 
D3DKMTOpenSynchronizationObject TEXTEQU <__imp_D3DKMTOpenSynchronizationObject> 
extern __imp_D3DKMTPollDisplayChildren:qword 
D3DKMTPollDisplayChildren TEXTEQU <__imp_D3DKMTPollDisplayChildren> 
extern __imp_D3DKMTPresent:qword 
D3DKMTPresent TEXTEQU <__imp_D3DKMTPresent> 
extern __imp_D3DKMTQueryAdapterInfo:qword 
D3DKMTQueryAdapterInfo TEXTEQU <__imp_D3DKMTQueryAdapterInfo> 
extern __imp_D3DKMTQueryAllocationResidency:qword 
D3DKMTQueryAllocationResidency TEXTEQU <__imp_D3DKMTQueryAllocationResidency> 
extern __imp_D3DKMTQueryResourceInfo:qword 
D3DKMTQueryResourceInfo TEXTEQU <__imp_D3DKMTQueryResourceInfo> 
extern __imp_D3DKMTQueryStatistics:qword 
D3DKMTQueryStatistics TEXTEQU <__imp_D3DKMTQueryStatistics> 
extern __imp_D3DKMTReleaseKeyedMutex:qword 
D3DKMTReleaseKeyedMutex TEXTEQU <__imp_D3DKMTReleaseKeyedMutex> 
extern __imp_D3DKMTReleaseProcessVidPnSourceOwners:qword 
D3DKMTReleaseProcessVidPnSourceOwners TEXTEQU <__imp_D3DKMTReleaseProcessVidPnSourceOwners> 
extern __imp_D3DKMTRender:qword 
D3DKMTRender TEXTEQU <__imp_D3DKMTRender> 
extern __imp_D3DKMTSetAllocationPriority:qword 
D3DKMTSetAllocationPriority TEXTEQU <__imp_D3DKMTSetAllocationPriority> 
extern __imp_D3DKMTSetContextSchedulingPriority:qword 
D3DKMTSetContextSchedulingPriority TEXTEQU <__imp_D3DKMTSetContextSchedulingPriority> 
extern __imp_D3DKMTSetDisplayMode:qword 
D3DKMTSetDisplayMode TEXTEQU <__imp_D3DKMTSetDisplayMode> 
extern __imp_D3DKMTSetDisplayPrivateDriverFormat:qword 
D3DKMTSetDisplayPrivateDriverFormat TEXTEQU <__imp_D3DKMTSetDisplayPrivateDriverFormat> 
extern __imp_D3DKMTSetGammaRamp:qword 
D3DKMTSetGammaRamp TEXTEQU <__imp_D3DKMTSetGammaRamp> 
extern __imp_D3DKMTSetProcessSchedulingPriorityClass:qword 
D3DKMTSetProcessSchedulingPriorityClass TEXTEQU <__imp_D3DKMTSetProcessSchedulingPriorityClass> 
extern __imp_D3DKMTSetQueuedLimit:qword 
D3DKMTSetQueuedLimit TEXTEQU <__imp_D3DKMTSetQueuedLimit> 
extern __imp_D3DKMTSetVidPnSourceOwner:qword 
D3DKMTSetVidPnSourceOwner TEXTEQU <__imp_D3DKMTSetVidPnSourceOwner> 
extern __imp_D3DKMTSharedPrimaryLockNotification:qword 
D3DKMTSharedPrimaryLockNotification TEXTEQU <__imp_D3DKMTSharedPrimaryLockNotification> 
extern __imp_D3DKMTSharedPrimaryUnLockNotification:qword 
D3DKMTSharedPrimaryUnLockNotification TEXTEQU <__imp_D3DKMTSharedPrimaryUnLockNotification> 
extern __imp_D3DKMTSignalSynchronizationObject:qword 
D3DKMTSignalSynchronizationObject TEXTEQU <__imp_D3DKMTSignalSynchronizationObject> 
extern __imp_D3DKMTSignalSynchronizationObject2:qword 
D3DKMTSignalSynchronizationObject2 TEXTEQU <__imp_D3DKMTSignalSynchronizationObject2> 
extern __imp_D3DKMTUnlock:qword 
D3DKMTUnlock TEXTEQU <__imp_D3DKMTUnlock> 
extern __imp_D3DKMTUpdateOverlay:qword 
D3DKMTUpdateOverlay TEXTEQU <__imp_D3DKMTUpdateOverlay> 
extern __imp_D3DKMTWaitForIdle:qword 
D3DKMTWaitForIdle TEXTEQU <__imp_D3DKMTWaitForIdle> 
extern __imp_D3DKMTWaitForSynchronizationObject:qword 
D3DKMTWaitForSynchronizationObject TEXTEQU <__imp_D3DKMTWaitForSynchronizationObject> 
extern __imp_D3DKMTWaitForSynchronizationObject2:qword 
D3DKMTWaitForSynchronizationObject2 TEXTEQU <__imp_D3DKMTWaitForSynchronizationObject2> 
extern __imp_D3DKMTWaitForVerticalBlankEvent:qword 
D3DKMTWaitForVerticalBlankEvent TEXTEQU <__imp_D3DKMTWaitForVerticalBlankEvent> 
extern __imp_DDCCIGetCapabilitiesString:qword 
DDCCIGetCapabilitiesString TEXTEQU <__imp_DDCCIGetCapabilitiesString> 
extern __imp_DDCCIGetCapabilitiesStringLength:qword 
DDCCIGetCapabilitiesStringLength TEXTEQU <__imp_DDCCIGetCapabilitiesStringLength> 
extern __imp_DDCCIGetTimingReport:qword 
DDCCIGetTimingReport TEXTEQU <__imp_DDCCIGetTimingReport> 
extern __imp_DDCCIGetVCPFeature:qword 
DDCCIGetVCPFeature TEXTEQU <__imp_DDCCIGetVCPFeature> 
extern __imp_DDCCISaveCurrentSettings:qword 
DDCCISaveCurrentSettings TEXTEQU <__imp_DDCCISaveCurrentSettings> 
extern __imp_DDCCISetVCPFeature:qword 
DDCCISetVCPFeature TEXTEQU <__imp_DDCCISetVCPFeature> 
extern __imp_DPtoLP:qword 
DPtoLP TEXTEQU <__imp_DPtoLP> 
extern __imp_DdCreateFullscreenSprite:qword 
DdCreateFullscreenSprite TEXTEQU <__imp_DdCreateFullscreenSprite> 
extern __imp_DdDestroyFullscreenSprite:qword 
DdDestroyFullscreenSprite TEXTEQU <__imp_DdDestroyFullscreenSprite> 
extern __imp_DdEntry0:qword 
DdEntry0 TEXTEQU <__imp_DdEntry0> 
extern __imp_DdEntry1:qword 
DdEntry1 TEXTEQU <__imp_DdEntry1> 
extern __imp_DdEntry10:qword 
DdEntry10 TEXTEQU <__imp_DdEntry10> 
extern __imp_DdEntry11:qword 
DdEntry11 TEXTEQU <__imp_DdEntry11> 
extern __imp_DdEntry12:qword 
DdEntry12 TEXTEQU <__imp_DdEntry12> 
extern __imp_DdEntry13:qword 
DdEntry13 TEXTEQU <__imp_DdEntry13> 
extern __imp_DdEntry14:qword 
DdEntry14 TEXTEQU <__imp_DdEntry14> 
extern __imp_DdEntry15:qword 
DdEntry15 TEXTEQU <__imp_DdEntry15> 
extern __imp_DdEntry16:qword 
DdEntry16 TEXTEQU <__imp_DdEntry16> 
extern __imp_DdEntry17:qword 
DdEntry17 TEXTEQU <__imp_DdEntry17> 
extern __imp_DdEntry18:qword 
DdEntry18 TEXTEQU <__imp_DdEntry18> 
extern __imp_DdEntry19:qword 
DdEntry19 TEXTEQU <__imp_DdEntry19> 
extern __imp_DdEntry2:qword 
DdEntry2 TEXTEQU <__imp_DdEntry2> 
extern __imp_DdEntry20:qword 
DdEntry20 TEXTEQU <__imp_DdEntry20> 
extern __imp_DdEntry21:qword 
DdEntry21 TEXTEQU <__imp_DdEntry21> 
extern __imp_DdEntry22:qword 
DdEntry22 TEXTEQU <__imp_DdEntry22> 
extern __imp_DdEntry23:qword 
DdEntry23 TEXTEQU <__imp_DdEntry23> 
extern __imp_DdEntry24:qword 
DdEntry24 TEXTEQU <__imp_DdEntry24> 
extern __imp_DdEntry25:qword 
DdEntry25 TEXTEQU <__imp_DdEntry25> 
extern __imp_DdEntry26:qword 
DdEntry26 TEXTEQU <__imp_DdEntry26> 
extern __imp_DdEntry27:qword 
DdEntry27 TEXTEQU <__imp_DdEntry27> 
extern __imp_DdEntry28:qword 
DdEntry28 TEXTEQU <__imp_DdEntry28> 
extern __imp_DdEntry29:qword 
DdEntry29 TEXTEQU <__imp_DdEntry29> 
extern __imp_DdEntry3:qword 
DdEntry3 TEXTEQU <__imp_DdEntry3> 
extern __imp_DdEntry30:qword 
DdEntry30 TEXTEQU <__imp_DdEntry30> 
extern __imp_DdEntry31:qword 
DdEntry31 TEXTEQU <__imp_DdEntry31> 
extern __imp_DdEntry32:qword 
DdEntry32 TEXTEQU <__imp_DdEntry32> 
extern __imp_DdEntry33:qword 
DdEntry33 TEXTEQU <__imp_DdEntry33> 
extern __imp_DdEntry34:qword 
DdEntry34 TEXTEQU <__imp_DdEntry34> 
extern __imp_DdEntry35:qword 
DdEntry35 TEXTEQU <__imp_DdEntry35> 
extern __imp_DdEntry36:qword 
DdEntry36 TEXTEQU <__imp_DdEntry36> 
extern __imp_DdEntry37:qword 
DdEntry37 TEXTEQU <__imp_DdEntry37> 
extern __imp_DdEntry38:qword 
DdEntry38 TEXTEQU <__imp_DdEntry38> 
extern __imp_DdEntry39:qword 
DdEntry39 TEXTEQU <__imp_DdEntry39> 
extern __imp_DdEntry4:qword 
DdEntry4 TEXTEQU <__imp_DdEntry4> 
extern __imp_DdEntry40:qword 
DdEntry40 TEXTEQU <__imp_DdEntry40> 
extern __imp_DdEntry41:qword 
DdEntry41 TEXTEQU <__imp_DdEntry41> 
extern __imp_DdEntry42:qword 
DdEntry42 TEXTEQU <__imp_DdEntry42> 
extern __imp_DdEntry43:qword 
DdEntry43 TEXTEQU <__imp_DdEntry43> 
extern __imp_DdEntry44:qword 
DdEntry44 TEXTEQU <__imp_DdEntry44> 
extern __imp_DdEntry45:qword 
DdEntry45 TEXTEQU <__imp_DdEntry45> 
extern __imp_DdEntry46:qword 
DdEntry46 TEXTEQU <__imp_DdEntry46> 
extern __imp_DdEntry47:qword 
DdEntry47 TEXTEQU <__imp_DdEntry47> 
extern __imp_DdEntry48:qword 
DdEntry48 TEXTEQU <__imp_DdEntry48> 
extern __imp_DdEntry49:qword 
DdEntry49 TEXTEQU <__imp_DdEntry49> 
extern __imp_DdEntry5:qword 
DdEntry5 TEXTEQU <__imp_DdEntry5> 
extern __imp_DdEntry50:qword 
DdEntry50 TEXTEQU <__imp_DdEntry50> 
extern __imp_DdEntry51:qword 
DdEntry51 TEXTEQU <__imp_DdEntry51> 
extern __imp_DdEntry52:qword 
DdEntry52 TEXTEQU <__imp_DdEntry52> 
extern __imp_DdEntry53:qword 
DdEntry53 TEXTEQU <__imp_DdEntry53> 
extern __imp_DdEntry54:qword 
DdEntry54 TEXTEQU <__imp_DdEntry54> 
extern __imp_DdEntry55:qword 
DdEntry55 TEXTEQU <__imp_DdEntry55> 
extern __imp_DdEntry56:qword 
DdEntry56 TEXTEQU <__imp_DdEntry56> 
extern __imp_DdEntry6:qword 
DdEntry6 TEXTEQU <__imp_DdEntry6> 
extern __imp_DdEntry7:qword 
DdEntry7 TEXTEQU <__imp_DdEntry7> 
extern __imp_DdEntry8:qword 
DdEntry8 TEXTEQU <__imp_DdEntry8> 
extern __imp_DdEntry9:qword 
DdEntry9 TEXTEQU <__imp_DdEntry9> 
extern __imp_DdNotifyFullscreenSpriteUpdate:qword 
DdNotifyFullscreenSpriteUpdate TEXTEQU <__imp_DdNotifyFullscreenSpriteUpdate> 
extern __imp_DdQueryVisRgnUniqueness:qword 
DdQueryVisRgnUniqueness TEXTEQU <__imp_DdQueryVisRgnUniqueness> 
extern __imp_DeleteColorSpace:qword 
DeleteColorSpace TEXTEQU <__imp_DeleteColorSpace> 
extern __imp_DeleteDC:qword 
DeleteDC TEXTEQU <__imp_DeleteDC> 
extern __imp_DeleteEnhMetaFile:qword 
DeleteEnhMetaFile TEXTEQU <__imp_DeleteEnhMetaFile> 
extern __imp_DeleteMetaFile:qword 
DeleteMetaFile TEXTEQU <__imp_DeleteMetaFile> 
extern __imp_DeleteObject:qword 
DeleteObject TEXTEQU <__imp_DeleteObject> 
extern __imp_DescribePixelFormat:qword 
DescribePixelFormat TEXTEQU <__imp_DescribePixelFormat> 
extern __imp_DestroyOPMProtectedOutput:qword 
DestroyOPMProtectedOutput TEXTEQU <__imp_DestroyOPMProtectedOutput> 
extern __imp_DestroyPhysicalMonitorInternal:qword 
DestroyPhysicalMonitorInternal TEXTEQU <__imp_DestroyPhysicalMonitorInternal> 
extern __imp_DeviceCapabilitiesExA:qword 
DeviceCapabilitiesEx TEXTEQU <__imp_DeviceCapabilitiesExA> 
extern __imp_DeviceCapabilitiesExW:qword 
DeviceCapabilitiesExW TEXTEQU <__imp_DeviceCapabilitiesExW> 
extern __imp_DrawEscape:qword 
DrawEscape TEXTEQU <__imp_DrawEscape> 
extern __imp_Ellipse:qword 
Ellipse TEXTEQU <__imp_Ellipse> 
extern __imp_EnableEUDC:qword 
EnableEUDC TEXTEQU <__imp_EnableEUDC> 
extern __imp_EndDoc:qword 
EndDoc TEXTEQU <__imp_EndDoc> 
extern __imp_EndFormPage:qword 
EndFormPage TEXTEQU <__imp_EndFormPage> 
extern __imp_EndGdiRendering:qword 
EndGdiRendering TEXTEQU <__imp_EndGdiRendering> 
extern __imp_EndPage:qword 
EndPage TEXTEQU <__imp_EndPage> 
extern __imp_EndPath:qword 
EndPath TEXTEQU <__imp_EndPath> 
extern __imp_EngAcquireSemaphore:qword 
EngAcquireSemaphore TEXTEQU <__imp_EngAcquireSemaphore> 
extern __imp_EngAlphaBlend:qword 
EngAlphaBlend TEXTEQU <__imp_EngAlphaBlend> 
extern __imp_EngAssociateSurface:qword 
EngAssociateSurface TEXTEQU <__imp_EngAssociateSurface> 
extern __imp_EngBitBlt:qword 
EngBitBlt TEXTEQU <__imp_EngBitBlt> 
extern __imp_EngCheckAbort:qword 
EngCheckAbort TEXTEQU <__imp_EngCheckAbort> 
extern __imp_EngComputeGlyphSet:qword 
EngComputeGlyphSet TEXTEQU <__imp_EngComputeGlyphSet> 
extern __imp_EngCopyBits:qword 
EngCopyBits TEXTEQU <__imp_EngCopyBits> 
extern __imp_EngCreateBitmap:qword 
EngCreateBitmap TEXTEQU <__imp_EngCreateBitmap> 
extern __imp_EngCreateClip:qword 
EngCreateClip TEXTEQU <__imp_EngCreateClip> 
extern __imp_EngCreateDeviceBitmap:qword 
EngCreateDeviceBitmap TEXTEQU <__imp_EngCreateDeviceBitmap> 
extern __imp_EngCreateDeviceSurface:qword 
EngCreateDeviceSurface TEXTEQU <__imp_EngCreateDeviceSurface> 
extern __imp_EngCreatePalette:qword 
EngCreatePalette TEXTEQU <__imp_EngCreatePalette> 
extern __imp_EngCreateSemaphore:qword 
EngCreateSemaphore TEXTEQU <__imp_EngCreateSemaphore> 
extern __imp_EngDeleteClip:qword 
EngDeleteClip TEXTEQU <__imp_EngDeleteClip> 
extern __imp_EngDeletePalette:qword 
EngDeletePalette TEXTEQU <__imp_EngDeletePalette> 
extern __imp_EngDeletePath:qword 
EngDeletePath TEXTEQU <__imp_EngDeletePath> 
extern __imp_EngDeleteSemaphore:qword 
EngDeleteSemaphore TEXTEQU <__imp_EngDeleteSemaphore> 
extern __imp_EngDeleteSurface:qword 
EngDeleteSurface TEXTEQU <__imp_EngDeleteSurface> 
extern __imp_EngEraseSurface:qword 
EngEraseSurface TEXTEQU <__imp_EngEraseSurface> 
extern __imp_EngFillPath:qword 
EngFillPath TEXTEQU <__imp_EngFillPath> 
extern __imp_EngFindResource:qword 
EngFindResource TEXTEQU <__imp_EngFindResource> 
extern __imp_EngFreeModule:qword 
EngFreeModule TEXTEQU <__imp_EngFreeModule> 
extern __imp_EngGetCurrentCodePage:qword 
EngGetCurrentCodePage TEXTEQU <__imp_EngGetCurrentCodePage> 
extern __imp_EngGetDriverName:qword 
EngGetDriverName TEXTEQU <__imp_EngGetDriverName> 
extern __imp_EngGetPrinterDataFileName:qword 
EngGetPrinterDataFileName TEXTEQU <__imp_EngGetPrinterDataFileName> 
extern __imp_EngGradientFill:qword 
EngGradientFill TEXTEQU <__imp_EngGradientFill> 
extern __imp_EngLineTo:qword 
EngLineTo TEXTEQU <__imp_EngLineTo> 
extern __imp_EngLoadModule:qword 
EngLoadModule TEXTEQU <__imp_EngLoadModule> 
extern __imp_EngLockSurface:qword 
EngLockSurface TEXTEQU <__imp_EngLockSurface> 
extern __imp_EngMarkBandingSurface:qword 
EngMarkBandingSurface TEXTEQU <__imp_EngMarkBandingSurface> 
extern __imp_EngMultiByteToUnicodeN:qword 
EngMultiByteToUnicodeN TEXTEQU <__imp_EngMultiByteToUnicodeN> 
extern __imp_EngMultiByteToWideChar:qword 
EngMultiByteToWideChar TEXTEQU <__imp_EngMultiByteToWideChar> 
extern __imp_EngPaint:qword 
EngPaint TEXTEQU <__imp_EngPaint> 
extern __imp_EngPlgBlt:qword 
EngPlgBlt TEXTEQU <__imp_EngPlgBlt> 
extern __imp_EngQueryEMFInfo:qword 
EngQueryEMFInfo TEXTEQU <__imp_EngQueryEMFInfo> 
extern __imp_EngQueryLocalTime:qword 
EngQueryLocalTime TEXTEQU <__imp_EngQueryLocalTime> 
extern __imp_EngReleaseSemaphore:qword 
EngReleaseSemaphore TEXTEQU <__imp_EngReleaseSemaphore> 
extern __imp_EngStretchBlt:qword 
EngStretchBlt TEXTEQU <__imp_EngStretchBlt> 
extern __imp_EngStretchBltROP:qword 
EngStretchBltROP TEXTEQU <__imp_EngStretchBltROP> 
extern __imp_EngStrokeAndFillPath:qword 
EngStrokeAndFillPath TEXTEQU <__imp_EngStrokeAndFillPath> 
extern __imp_EngStrokePath:qword 
EngStrokePath TEXTEQU <__imp_EngStrokePath> 
extern __imp_EngTextOut:qword 
EngTextOut TEXTEQU <__imp_EngTextOut> 
extern __imp_EngTransparentBlt:qword 
EngTransparentBlt TEXTEQU <__imp_EngTransparentBlt> 
extern __imp_EngUnicodeToMultiByteN:qword 
EngUnicodeToMultiByteN TEXTEQU <__imp_EngUnicodeToMultiByteN> 
extern __imp_EngUnlockSurface:qword 
EngUnlockSurface TEXTEQU <__imp_EngUnlockSurface> 
extern __imp_EngWideCharToMultiByte:qword 
EngWideCharToMultiByte TEXTEQU <__imp_EngWideCharToMultiByte> 
extern __imp_EnumEnhMetaFile:qword 
EnumEnhMetaFile TEXTEQU <__imp_EnumEnhMetaFile> 
extern __imp_EnumFontFamiliesA:qword 
EnumFontFamilies TEXTEQU <__imp_EnumFontFamiliesA> 
extern __imp_EnumFontFamiliesExA:qword 
EnumFontFamiliesEx TEXTEQU <__imp_EnumFontFamiliesExA> 
extern __imp_EnumFontFamiliesExW:qword 
EnumFontFamiliesExW TEXTEQU <__imp_EnumFontFamiliesExW> 
extern __imp_EnumFontFamiliesW:qword 
EnumFontFamiliesW TEXTEQU <__imp_EnumFontFamiliesW> 
extern __imp_EnumFontsA:qword 
EnumFonts TEXTEQU <__imp_EnumFontsA> 
extern __imp_EnumFontsW:qword 
EnumFontsW TEXTEQU <__imp_EnumFontsW> 
extern __imp_EnumICMProfilesA:qword 
EnumICMProfiles TEXTEQU <__imp_EnumICMProfilesA> 
extern __imp_EnumICMProfilesW:qword 
EnumICMProfilesW TEXTEQU <__imp_EnumICMProfilesW> 
extern __imp_EnumMetaFile:qword 
EnumMetaFile TEXTEQU <__imp_EnumMetaFile> 
extern __imp_EnumObjects:qword 
EnumObjects TEXTEQU <__imp_EnumObjects> 
extern __imp_EqualRgn:qword 
EqualRgn TEXTEQU <__imp_EqualRgn> 
extern __imp_Escape:qword 
Escape TEXTEQU <__imp_Escape> 
extern __imp_EudcLoadLinkW:qword 
EudcLoadLinkW TEXTEQU <__imp_EudcLoadLinkW> 
extern __imp_EudcUnloadLinkW:qword 
EudcUnloadLinkW TEXTEQU <__imp_EudcUnloadLinkW> 
extern __imp_ExcludeClipRect:qword 
ExcludeClipRect TEXTEQU <__imp_ExcludeClipRect> 
extern __imp_ExtCreatePen:qword 
ExtCreatePen TEXTEQU <__imp_ExtCreatePen> 
extern __imp_ExtCreateRegion:qword 
ExtCreateRegion TEXTEQU <__imp_ExtCreateRegion> 
extern __imp_ExtEscape:qword 
ExtEscape TEXTEQU <__imp_ExtEscape> 
extern __imp_ExtFloodFill:qword 
ExtFloodFill TEXTEQU <__imp_ExtFloodFill> 
extern __imp_ExtSelectClipRgn:qword 
ExtSelectClipRgn TEXTEQU <__imp_ExtSelectClipRgn> 
extern __imp_ExtTextOutA:qword 
ExtTextOut TEXTEQU <__imp_ExtTextOutA> 
extern __imp_ExtTextOutW:qword 
ExtTextOutW TEXTEQU <__imp_ExtTextOutW> 
extern __imp_FONTOBJ_cGetAllGlyphHandles:qword 
FONTOBJ_cGetAllGlyphHandles TEXTEQU <__imp_FONTOBJ_cGetAllGlyphHandles> 
extern __imp_FONTOBJ_cGetGlyphs:qword 
FONTOBJ_cGetGlyphs TEXTEQU <__imp_FONTOBJ_cGetGlyphs> 
extern __imp_FONTOBJ_pQueryGlyphAttrs:qword 
FONTOBJ_pQueryGlyphAttrs TEXTEQU <__imp_FONTOBJ_pQueryGlyphAttrs> 
extern __imp_FONTOBJ_pfdg:qword 
FONTOBJ_pfdg TEXTEQU <__imp_FONTOBJ_pfdg> 
extern __imp_FONTOBJ_pifi:qword 
FONTOBJ_pifi TEXTEQU <__imp_FONTOBJ_pifi> 
extern __imp_FONTOBJ_pvTrueTypeFontFile:qword 
FONTOBJ_pvTrueTypeFontFile TEXTEQU <__imp_FONTOBJ_pvTrueTypeFontFile> 
extern __imp_FONTOBJ_pxoGetXform:qword 
FONTOBJ_pxoGetXform TEXTEQU <__imp_FONTOBJ_pxoGetXform> 
extern __imp_FONTOBJ_vGetInfo:qword 
FONTOBJ_vGetInfo TEXTEQU <__imp_FONTOBJ_vGetInfo> 
extern __imp_FillPath:qword 
FillPath TEXTEQU <__imp_FillPath> 
extern __imp_FillRgn:qword 
FillRgn TEXTEQU <__imp_FillRgn> 
extern __imp_FixBrushOrgEx:qword 
FixBrushOrgEx TEXTEQU <__imp_FixBrushOrgEx> 
extern __imp_FlattenPath:qword 
FlattenPath TEXTEQU <__imp_FlattenPath> 
extern __imp_FloodFill:qword 
FloodFill TEXTEQU <__imp_FloodFill> 
extern __imp_FontIsLinked:qword 
FontIsLinked TEXTEQU <__imp_FontIsLinked> 
extern __imp_FrameRgn:qword 
FrameRgn TEXTEQU <__imp_FrameRgn> 
extern __imp_GdiAddFontResourceW:qword 
GdiAddFontResourceW TEXTEQU <__imp_GdiAddFontResourceW> 
extern __imp_GdiAddGlsBounds:qword 
GdiAddGlsBounds TEXTEQU <__imp_GdiAddGlsBounds> 
extern __imp_GdiAddGlsRecord:qword 
GdiAddGlsRecord TEXTEQU <__imp_GdiAddGlsRecord> 
extern __imp_GdiAlphaBlend:qword 
GdiAlphaBlend TEXTEQU <__imp_GdiAlphaBlend> 
extern __imp_GdiArtificialDecrementDriver:qword 
GdiArtificialDecrementDriver TEXTEQU <__imp_GdiArtificialDecrementDriver> 
extern __imp_GdiCleanCacheDC:qword 
GdiCleanCacheDC TEXTEQU <__imp_GdiCleanCacheDC> 
extern __imp_GdiComment:qword 
GdiComment TEXTEQU <__imp_GdiComment> 
extern __imp_GdiConsoleTextOut:qword 
GdiConsoleTextOut TEXTEQU <__imp_GdiConsoleTextOut> 
extern __imp_GdiConvertAndCheckDC:qword 
GdiConvertAndCheckDC TEXTEQU <__imp_GdiConvertAndCheckDC> 
extern __imp_GdiConvertBitmap:qword 
GdiConvertBitmap TEXTEQU <__imp_GdiConvertBitmap> 
extern __imp_GdiConvertBitmapV5:qword 
GdiConvertBitmapV5 TEXTEQU <__imp_GdiConvertBitmapV5> 
extern __imp_GdiConvertBrush:qword 
GdiConvertBrush TEXTEQU <__imp_GdiConvertBrush> 
extern __imp_GdiConvertDC:qword 
GdiConvertDC TEXTEQU <__imp_GdiConvertDC> 
extern __imp_GdiConvertEnhMetaFile:qword 
GdiConvertEnhMetaFile TEXTEQU <__imp_GdiConvertEnhMetaFile> 
extern __imp_GdiConvertFont:qword 
GdiConvertFont TEXTEQU <__imp_GdiConvertFont> 
extern __imp_GdiConvertMetaFilePict:qword 
GdiConvertMetaFilePict TEXTEQU <__imp_GdiConvertMetaFilePict> 
extern __imp_GdiConvertPalette:qword 
GdiConvertPalette TEXTEQU <__imp_GdiConvertPalette> 
extern __imp_GdiConvertRegion:qword 
GdiConvertRegion TEXTEQU <__imp_GdiConvertRegion> 
extern __imp_GdiConvertToDevmodeW:qword 
GdiConvertToDevmodeW TEXTEQU <__imp_GdiConvertToDevmodeW> 
extern __imp_GdiCreateLocalEnhMetaFile:qword 
GdiCreateLocalEnhMetaFile TEXTEQU <__imp_GdiCreateLocalEnhMetaFile> 
extern __imp_GdiCreateLocalMetaFilePict:qword 
GdiCreateLocalMetaFilePict TEXTEQU <__imp_GdiCreateLocalMetaFilePict> 
extern __imp_GdiDeleteLocalDC:qword 
GdiDeleteLocalDC TEXTEQU <__imp_GdiDeleteLocalDC> 
extern __imp_GdiDeleteSpoolFileHandle:qword 
GdiDeleteSpoolFileHandle TEXTEQU <__imp_GdiDeleteSpoolFileHandle> 
extern __imp_GdiDescribePixelFormat:qword 
GdiDescribePixelFormat TEXTEQU <__imp_GdiDescribePixelFormat> 
extern __imp_GdiDllInitialize:qword 
GdiDllInitialize TEXTEQU <__imp_GdiDllInitialize> 
extern __imp_GdiDrawStream:qword 
GdiDrawStream TEXTEQU <__imp_GdiDrawStream> 
extern __imp_GdiEndDocEMF:qword 
GdiEndDocEMF TEXTEQU <__imp_GdiEndDocEMF> 
extern __imp_GdiEndPageEMF:qword 
GdiEndPageEMF TEXTEQU <__imp_GdiEndPageEMF> 
extern __imp_GdiEntry1:qword 
GdiEntry1 TEXTEQU <__imp_GdiEntry1> 
extern __imp_GdiEntry10:qword 
GdiEntry10 TEXTEQU <__imp_GdiEntry10> 
extern __imp_GdiEntry11:qword 
GdiEntry11 TEXTEQU <__imp_GdiEntry11> 
extern __imp_GdiEntry12:qword 
GdiEntry12 TEXTEQU <__imp_GdiEntry12> 
extern __imp_GdiEntry13:qword 
GdiEntry13 TEXTEQU <__imp_GdiEntry13> 
extern __imp_GdiEntry14:qword 
GdiEntry14 TEXTEQU <__imp_GdiEntry14> 
extern __imp_GdiEntry15:qword 
GdiEntry15 TEXTEQU <__imp_GdiEntry15> 
extern __imp_GdiEntry16:qword 
GdiEntry16 TEXTEQU <__imp_GdiEntry16> 
extern __imp_GdiEntry2:qword 
GdiEntry2 TEXTEQU <__imp_GdiEntry2> 
extern __imp_GdiEntry3:qword 
GdiEntry3 TEXTEQU <__imp_GdiEntry3> 
extern __imp_GdiEntry4:qword 
GdiEntry4 TEXTEQU <__imp_GdiEntry4> 
extern __imp_GdiEntry5:qword 
GdiEntry5 TEXTEQU <__imp_GdiEntry5> 
extern __imp_GdiEntry6:qword 
GdiEntry6 TEXTEQU <__imp_GdiEntry6> 
extern __imp_GdiEntry7:qword 
GdiEntry7 TEXTEQU <__imp_GdiEntry7> 
extern __imp_GdiEntry8:qword 
GdiEntry8 TEXTEQU <__imp_GdiEntry8> 
extern __imp_GdiEntry9:qword 
GdiEntry9 TEXTEQU <__imp_GdiEntry9> 
extern __imp_GdiFixUpHandle:qword 
GdiFixUpHandle TEXTEQU <__imp_GdiFixUpHandle> 
extern __imp_GdiFlush:qword 
GdiFlush TEXTEQU <__imp_GdiFlush> 
extern __imp_GdiFullscreenControl:qword 
GdiFullscreenControl TEXTEQU <__imp_GdiFullscreenControl> 
extern __imp_GdiGetBatchLimit:qword 
GdiGetBatchLimit TEXTEQU <__imp_GdiGetBatchLimit> 
extern __imp_GdiGetBitmapBitsSize:qword 
GdiGetBitmapBitsSize TEXTEQU <__imp_GdiGetBitmapBitsSize> 
extern __imp_GdiGetCharDimensions:qword 
GdiGetCharDimensions TEXTEQU <__imp_GdiGetCharDimensions> 
extern __imp_GdiGetCodePage:qword 
GdiGetCodePage TEXTEQU <__imp_GdiGetCodePage> 
extern __imp_GdiGetDC:qword 
GdiGetDC TEXTEQU <__imp_GdiGetDC> 
extern __imp_GdiGetDevmodeForPage:qword 
GdiGetDevmodeForPage TEXTEQU <__imp_GdiGetDevmodeForPage> 
extern __imp_GdiGetLocalBrush:qword 
GdiGetLocalBrush TEXTEQU <__imp_GdiGetLocalBrush> 
extern __imp_GdiGetLocalDC:qword 
GdiGetLocalDC TEXTEQU <__imp_GdiGetLocalDC> 
extern __imp_GdiGetLocalFont:qword 
GdiGetLocalFont TEXTEQU <__imp_GdiGetLocalFont> 
extern __imp_GdiGetPageCount:qword 
GdiGetPageCount TEXTEQU <__imp_GdiGetPageCount> 
extern __imp_GdiGetPageHandle:qword 
GdiGetPageHandle TEXTEQU <__imp_GdiGetPageHandle> 
extern __imp_GdiGetSpoolFileHandle:qword 
GdiGetSpoolFileHandle TEXTEQU <__imp_GdiGetSpoolFileHandle> 
extern __imp_GdiGetSpoolMessage:qword 
GdiGetSpoolMessage TEXTEQU <__imp_GdiGetSpoolMessage> 
extern __imp_GdiGradientFill:qword 
GdiGradientFill TEXTEQU <__imp_GdiGradientFill> 
extern __imp_GdiInitSpool:qword 
GdiInitSpool TEXTEQU <__imp_GdiInitSpool> 
extern __imp_GdiInitializeLanguagePack:qword 
GdiInitializeLanguagePack TEXTEQU <__imp_GdiInitializeLanguagePack> 
extern __imp_GdiIsMetaFileDC:qword 
GdiIsMetaFileDC TEXTEQU <__imp_GdiIsMetaFileDC> 
extern __imp_GdiIsMetaPrintDC:qword 
GdiIsMetaPrintDC TEXTEQU <__imp_GdiIsMetaPrintDC> 
extern __imp_GdiIsPlayMetafileDC:qword 
GdiIsPlayMetafileDC TEXTEQU <__imp_GdiIsPlayMetafileDC> 
extern __imp_GdiIsScreenDC:qword 
GdiIsScreenDC TEXTEQU <__imp_GdiIsScreenDC> 
extern __imp_GdiLoadType1Fonts:qword 
GdiLoadType1Fonts TEXTEQU <__imp_GdiLoadType1Fonts> 
extern __imp_GdiPlayDCScript:qword 
GdiPlayDCScript TEXTEQU <__imp_GdiPlayDCScript> 
extern __imp_GdiPlayEMF:qword 
GdiPlayEMF TEXTEQU <__imp_GdiPlayEMF> 
extern __imp_GdiPlayJournal:qword 
GdiPlayJournal TEXTEQU <__imp_GdiPlayJournal> 
extern __imp_GdiPlayPageEMF:qword 
GdiPlayPageEMF TEXTEQU <__imp_GdiPlayPageEMF> 
extern __imp_GdiPlayPrivatePageEMF:qword 
GdiPlayPrivatePageEMF TEXTEQU <__imp_GdiPlayPrivatePageEMF> 
extern __imp_GdiPlayScript:qword 
GdiPlayScript TEXTEQU <__imp_GdiPlayScript> 
extern __imp_GdiPrinterThunk:qword 
GdiPrinterThunk TEXTEQU <__imp_GdiPrinterThunk> 
extern __imp_GdiProcessSetup:qword 
GdiProcessSetup TEXTEQU <__imp_GdiProcessSetup> 
extern __imp_GdiQueryFonts:qword 
GdiQueryFonts TEXTEQU <__imp_GdiQueryFonts> 
extern __imp_GdiQueryTable:qword 
GdiQueryTable TEXTEQU <__imp_GdiQueryTable> 
extern __imp_GdiRealizationInfo:qword 
GdiRealizationInfo TEXTEQU <__imp_GdiRealizationInfo> 
extern __imp_GdiReleaseDC:qword 
GdiReleaseDC TEXTEQU <__imp_GdiReleaseDC> 
extern __imp_GdiReleaseLocalDC:qword 
GdiReleaseLocalDC TEXTEQU <__imp_GdiReleaseLocalDC> 
extern __imp_GdiResetDCEMF:qword 
GdiResetDCEMF TEXTEQU <__imp_GdiResetDCEMF> 
extern __imp_GdiSetAttrs:qword 
GdiSetAttrs TEXTEQU <__imp_GdiSetAttrs> 
extern __imp_GdiSetBatchLimit:qword 
GdiSetBatchLimit TEXTEQU <__imp_GdiSetBatchLimit> 
extern __imp_GdiSetLastError:qword 
GdiSetLastError TEXTEQU <__imp_GdiSetLastError> 
extern __imp_GdiSetPixelFormat:qword 
GdiSetPixelFormat TEXTEQU <__imp_GdiSetPixelFormat> 
extern __imp_GdiSetServerAttr:qword 
GdiSetServerAttr TEXTEQU <__imp_GdiSetServerAttr> 
extern __imp_GdiStartDocEMF:qword 
GdiStartDocEMF TEXTEQU <__imp_GdiStartDocEMF> 
extern __imp_GdiStartPageEMF:qword 
GdiStartPageEMF TEXTEQU <__imp_GdiStartPageEMF> 
extern __imp_GdiSwapBuffers:qword 
GdiSwapBuffers TEXTEQU <__imp_GdiSwapBuffers> 
extern __imp_GdiTransparentBlt:qword 
GdiTransparentBlt TEXTEQU <__imp_GdiTransparentBlt> 
extern __imp_GdiValidateHandle:qword 
GdiValidateHandle TEXTEQU <__imp_GdiValidateHandle> 
extern __imp_GetArcDirection:qword 
GetArcDirection TEXTEQU <__imp_GetArcDirection> 
extern __imp_GetAspectRatioFilterEx:qword 
GetAspectRatioFilterEx TEXTEQU <__imp_GetAspectRatioFilterEx> 
extern __imp_GetBitmapAttributes:qword 
GetBitmapAttributes TEXTEQU <__imp_GetBitmapAttributes> 
extern __imp_GetBitmapBits:qword 
GetBitmapBits TEXTEQU <__imp_GetBitmapBits> 
extern __imp_GetBitmapDimensionEx:qword 
GetBitmapDimensionEx TEXTEQU <__imp_GetBitmapDimensionEx> 
extern __imp_GetBkColor:qword 
GetBkColor TEXTEQU <__imp_GetBkColor> 
extern __imp_GetBkMode:qword 
GetBkMode TEXTEQU <__imp_GetBkMode> 
extern __imp_GetBoundsRect:qword 
GetBoundsRect TEXTEQU <__imp_GetBoundsRect> 
extern __imp_GetBrushAttributes:qword 
GetBrushAttributes TEXTEQU <__imp_GetBrushAttributes> 
extern __imp_GetBrushOrgEx:qword 
GetBrushOrgEx TEXTEQU <__imp_GetBrushOrgEx> 
extern __imp_GetCOPPCompatibleOPMInformation:qword 
GetCOPPCompatibleOPMInformation TEXTEQU <__imp_GetCOPPCompatibleOPMInformation> 
extern __imp_GetCertificate:qword 
GetCertificate TEXTEQU <__imp_GetCertificate> 
extern __imp_GetCertificateSize:qword 
GetCertificateSize TEXTEQU <__imp_GetCertificateSize> 
extern __imp_GetCharABCWidthsA:qword 
GetCharABCWidths TEXTEQU <__imp_GetCharABCWidthsA> 
extern __imp_GetCharABCWidthsFloatA:qword 
GetCharABCWidthsFloat TEXTEQU <__imp_GetCharABCWidthsFloatA> 
extern __imp_GetCharABCWidthsFloatW:qword 
GetCharABCWidthsFloatW TEXTEQU <__imp_GetCharABCWidthsFloatW> 
extern __imp_GetCharABCWidthsI:qword 
GetCharABCWidthsI TEXTEQU <__imp_GetCharABCWidthsI> 
extern __imp_GetCharABCWidthsW:qword 
GetCharABCWidthsW TEXTEQU <__imp_GetCharABCWidthsW> 
extern __imp_GetCharWidth32A:qword 
GetCharWidth32 TEXTEQU <__imp_GetCharWidth32A> 
extern __imp_GetCharWidth32W:qword 
GetCharWidth32W TEXTEQU <__imp_GetCharWidth32W> 
extern __imp_GetCharWidthA:qword 
GetCharWidth TEXTEQU <__imp_GetCharWidthA> 
extern __imp_GetCharWidthFloatA:qword 
GetCharWidthFloat TEXTEQU <__imp_GetCharWidthFloatA> 
extern __imp_GetCharWidthFloatW:qword 
GetCharWidthFloatW TEXTEQU <__imp_GetCharWidthFloatW> 
extern __imp_GetCharWidthI:qword 
GetCharWidthI TEXTEQU <__imp_GetCharWidthI> 
extern __imp_GetCharWidthInfo:qword 
GetCharWidthInfo TEXTEQU <__imp_GetCharWidthInfo> 
extern __imp_GetCharWidthW:qword 
GetCharWidthW TEXTEQU <__imp_GetCharWidthW> 
extern __imp_GetCharacterPlacementA:qword 
GetCharacterPlacement TEXTEQU <__imp_GetCharacterPlacementA> 
extern __imp_GetCharacterPlacementW:qword 
GetCharacterPlacementW TEXTEQU <__imp_GetCharacterPlacementW> 
extern __imp_GetClipBox:qword 
GetClipBox TEXTEQU <__imp_GetClipBox> 
extern __imp_GetClipRgn:qword 
GetClipRgn TEXTEQU <__imp_GetClipRgn> 
extern __imp_GetColorAdjustment:qword 
GetColorAdjustment TEXTEQU <__imp_GetColorAdjustment> 
extern __imp_GetColorSpace:qword 
GetColorSpace TEXTEQU <__imp_GetColorSpace> 
extern __imp_GetCurrentObject:qword 
GetCurrentObject TEXTEQU <__imp_GetCurrentObject> 
extern __imp_GetCurrentPositionEx:qword 
GetCurrentPositionEx TEXTEQU <__imp_GetCurrentPositionEx> 
extern __imp_GetDCBrushColor:qword 
GetDCBrushColor TEXTEQU <__imp_GetDCBrushColor> 
extern __imp_GetDCOrgEx:qword 
GetDCOrgEx TEXTEQU <__imp_GetDCOrgEx> 
extern __imp_GetDCPenColor:qword 
GetDCPenColor TEXTEQU <__imp_GetDCPenColor> 
extern __imp_GetDIBColorTable:qword 
GetDIBColorTable TEXTEQU <__imp_GetDIBColorTable> 
extern __imp_GetDIBits:qword 
GetDIBits TEXTEQU <__imp_GetDIBits> 
extern __imp_GetDeviceCaps:qword 
GetDeviceCaps TEXTEQU <__imp_GetDeviceCaps> 
extern __imp_GetDeviceGammaRamp:qword 
GetDeviceGammaRamp TEXTEQU <__imp_GetDeviceGammaRamp> 
extern __imp_GetETM:qword 
GetETM TEXTEQU <__imp_GetETM> 
extern __imp_GetEUDCTimeStamp:qword 
GetEUDCTimeStamp TEXTEQU <__imp_GetEUDCTimeStamp> 
extern __imp_GetEUDCTimeStampExW:qword 
GetEUDCTimeStampExW TEXTEQU <__imp_GetEUDCTimeStampExW> 
extern __imp_GetEnhMetaFileA:qword 
GetEnhMetaFile TEXTEQU <__imp_GetEnhMetaFileA> 
extern __imp_GetEnhMetaFileBits:qword 
GetEnhMetaFileBits TEXTEQU <__imp_GetEnhMetaFileBits> 
extern __imp_GetEnhMetaFileDescriptionA:qword 
GetEnhMetaFileDescription TEXTEQU <__imp_GetEnhMetaFileDescriptionA> 
extern __imp_GetEnhMetaFileDescriptionW:qword 
GetEnhMetaFileDescriptionW TEXTEQU <__imp_GetEnhMetaFileDescriptionW> 
extern __imp_GetEnhMetaFileHeader:qword 
GetEnhMetaFileHeader TEXTEQU <__imp_GetEnhMetaFileHeader> 
extern __imp_GetEnhMetaFilePaletteEntries:qword 
GetEnhMetaFilePaletteEntries TEXTEQU <__imp_GetEnhMetaFilePaletteEntries> 
extern __imp_GetEnhMetaFilePixelFormat:qword 
GetEnhMetaFilePixelFormat TEXTEQU <__imp_GetEnhMetaFilePixelFormat> 
extern __imp_GetEnhMetaFileW:qword 
GetEnhMetaFileW TEXTEQU <__imp_GetEnhMetaFileW> 
extern __imp_GetFontAssocStatus:qword 
GetFontAssocStatus TEXTEQU <__imp_GetFontAssocStatus> 
extern __imp_GetFontData:qword 
GetFontDat TEXTEQU <__imp_GetFontData> 
extern __imp_GetFontFileData:qword 
GetFontFileDat TEXTEQU <__imp_GetFontFileData> 
extern __imp_GetFontFileInfo:qword 
GetFontFileInfo TEXTEQU <__imp_GetFontFileInfo> 
extern __imp_GetFontLanguageInfo:qword 
GetFontLanguageInfo TEXTEQU <__imp_GetFontLanguageInfo> 
extern __imp_GetFontRealizationInfo:qword 
GetFontRealizationInfo TEXTEQU <__imp_GetFontRealizationInfo> 
extern __imp_GetFontResourceInfoW:qword 
GetFontResourceInfoW TEXTEQU <__imp_GetFontResourceInfoW> 
extern __imp_GetFontUnicodeRanges:qword 
GetFontUnicodeRanges TEXTEQU <__imp_GetFontUnicodeRanges> 
extern __imp_GetGlyphIndicesA:qword 
GetGlyphIndices TEXTEQU <__imp_GetGlyphIndicesA> 
extern __imp_GetGlyphIndicesW:qword 
GetGlyphIndicesW TEXTEQU <__imp_GetGlyphIndicesW> 
extern __imp_GetGlyphOutline:qword 
GetGlyphOutline TEXTEQU <__imp_GetGlyphOutline> 
extern __imp_GetGlyphOutlineA:qword 
GetGlyphOutline TEXTEQU <__imp_GetGlyphOutlineA> 
extern __imp_GetGlyphOutlineW:qword 
GetGlyphOutlineW TEXTEQU <__imp_GetGlyphOutlineW> 
extern __imp_GetGlyphOutlineWow:qword 
GetGlyphOutlineWow TEXTEQU <__imp_GetGlyphOutlineWow> 
extern __imp_GetGraphicsMode:qword 
GetGraphicsMode TEXTEQU <__imp_GetGraphicsMode> 
extern __imp_GetHFONT:qword 
GetHFONT TEXTEQU <__imp_GetHFONT> 
extern __imp_GetICMProfileA:qword 
GetICMProfile TEXTEQU <__imp_GetICMProfileA> 
extern __imp_GetICMProfileW:qword 
GetICMProfileW TEXTEQU <__imp_GetICMProfileW> 
extern __imp_GetKerningPairs:qword 
GetKerningPairs TEXTEQU <__imp_GetKerningPairs> 
extern __imp_GetKerningPairsA:qword 
GetKerningPairs TEXTEQU <__imp_GetKerningPairsA> 
extern __imp_GetKerningPairsW:qword 
GetKerningPairsW TEXTEQU <__imp_GetKerningPairsW> 
extern __imp_GetLayout:qword 
GetLayout TEXTEQU <__imp_GetLayout> 
extern __imp_GetLogColorSpaceA:qword 
GetLogColorSpace TEXTEQU <__imp_GetLogColorSpaceA> 
extern __imp_GetLogColorSpaceW:qword 
GetLogColorSpaceW TEXTEQU <__imp_GetLogColorSpaceW> 
extern __imp_GetMapMode:qword 
GetMapMode TEXTEQU <__imp_GetMapMode> 
extern __imp_GetMetaFileA:qword 
GetMetaFile TEXTEQU <__imp_GetMetaFileA> 
extern __imp_GetMetaFileBitsEx:qword 
GetMetaFileBitsEx TEXTEQU <__imp_GetMetaFileBitsEx> 
extern __imp_GetMetaFileW:qword 
GetMetaFileW TEXTEQU <__imp_GetMetaFileW> 
extern __imp_GetMetaRgn:qword 
GetMetaRgn TEXTEQU <__imp_GetMetaRgn> 
extern __imp_GetMiterLimit:qword 
GetMiterLimit TEXTEQU <__imp_GetMiterLimit> 
extern __imp_GetNearestColor:qword 
GetNearestColor TEXTEQU <__imp_GetNearestColor> 
extern __imp_GetNearestPaletteIndex:qword 
GetNearestPaletteIndex TEXTEQU <__imp_GetNearestPaletteIndex> 
extern __imp_GetNumberOfPhysicalMonitors:qword 
GetNumberOfPhysicalMonitors TEXTEQU <__imp_GetNumberOfPhysicalMonitors> 
extern __imp_GetOPMInformation:qword 
GetOPMInformation TEXTEQU <__imp_GetOPMInformation> 
extern __imp_GetOPMRandomNumber:qword 
GetOPMRandomNumber TEXTEQU <__imp_GetOPMRandomNumber> 
extern __imp_GetObjectA:qword 
GetObject TEXTEQU <__imp_GetObjectA> 
extern __imp_GetObjectType:qword 
GetObjectType TEXTEQU <__imp_GetObjectType> 
extern __imp_GetObjectW:qword 
GetObjectW TEXTEQU <__imp_GetObjectW> 
extern __imp_GetOutlineTextMetricsA:qword 
GetOutlineTextMetrics TEXTEQU <__imp_GetOutlineTextMetricsA> 
extern __imp_GetOutlineTextMetricsW:qword 
GetOutlineTextMetricsW TEXTEQU <__imp_GetOutlineTextMetricsW> 
extern __imp_GetPaletteEntries:qword 
GetPaletteEntries TEXTEQU <__imp_GetPaletteEntries> 
extern __imp_GetPath:qword 
GetPath TEXTEQU <__imp_GetPath> 
extern __imp_GetPhysicalMonitorDescription:qword 
GetPhysicalMonitorDescription TEXTEQU <__imp_GetPhysicalMonitorDescription> 
extern __imp_GetPhysicalMonitors:qword 
GetPhysicalMonitors TEXTEQU <__imp_GetPhysicalMonitors> 
extern __imp_GetPixel:qword 
GetPixel TEXTEQU <__imp_GetPixel> 
extern __imp_GetPixelFormat:qword 
GetPixelFormat TEXTEQU <__imp_GetPixelFormat> 
extern __imp_GetPolyFillMode:qword 
GetPolyFillMode TEXTEQU <__imp_GetPolyFillMode> 
extern __imp_GetROP2:qword 
GetROP2 TEXTEQU <__imp_GetROP2> 
extern __imp_GetRandomRgn:qword 
GetRandomRgn TEXTEQU <__imp_GetRandomRgn> 
extern __imp_GetRasterizerCaps:qword 
GetRasterizerCaps TEXTEQU <__imp_GetRasterizerCaps> 
extern __imp_GetRegionData:qword 
GetRegionDat TEXTEQU <__imp_GetRegionData> 
extern __imp_GetRelAbs:qword 
GetRelAbs TEXTEQU <__imp_GetRelAbs> 
extern __imp_GetRgnBox:qword 
GetRgnBox TEXTEQU <__imp_GetRgnBox> 
extern __imp_GetStockObject:qword 
GetStockObject TEXTEQU <__imp_GetStockObject> 
extern __imp_GetStretchBltMode:qword 
GetStretchBltMode TEXTEQU <__imp_GetStretchBltMode> 
extern __imp_GetStringBitmapA:qword 
GetStringBitmap TEXTEQU <__imp_GetStringBitmapA> 
extern __imp_GetStringBitmapW:qword 
GetStringBitmapW TEXTEQU <__imp_GetStringBitmapW> 
extern __imp_GetSuggestedOPMProtectedOutputArraySize:qword 
GetSuggestedOPMProtectedOutputArraySize TEXTEQU <__imp_GetSuggestedOPMProtectedOutputArraySize> 
extern __imp_GetSystemPaletteEntries:qword 
GetSystemPaletteEntries TEXTEQU <__imp_GetSystemPaletteEntries> 
extern __imp_GetSystemPaletteUse:qword 
GetSystemPaletteUse TEXTEQU <__imp_GetSystemPaletteUse> 
extern __imp_GetTextAlign:qword 
GetTextAlign TEXTEQU <__imp_GetTextAlign> 
extern __imp_GetTextCharacterExtra:qword 
GetTextCharacterExtr TEXTEQU <__imp_GetTextCharacterExtra> 
extern __imp_GetTextCharset:qword 
GetTextCharset TEXTEQU <__imp_GetTextCharset> 
extern __imp_GetTextCharsetInfo:qword 
GetTextCharsetInfo TEXTEQU <__imp_GetTextCharsetInfo> 
extern __imp_GetTextColor:qword 
GetTextColor TEXTEQU <__imp_GetTextColor> 
extern __imp_GetTextExtentExPointA:qword 
GetTextExtentExPoint TEXTEQU <__imp_GetTextExtentExPointA> 
extern __imp_GetTextExtentExPointI:qword 
GetTextExtentExPointI TEXTEQU <__imp_GetTextExtentExPointI> 
extern __imp_GetTextExtentExPointW:qword 
GetTextExtentExPointW TEXTEQU <__imp_GetTextExtentExPointW> 
extern __imp_GetTextExtentExPointWPri:qword 
GetTextExtentExPointWPri TEXTEQU <__imp_GetTextExtentExPointWPri> 
extern __imp_GetTextExtentPoint32A:qword 
GetTextExtentPoint32 TEXTEQU <__imp_GetTextExtentPoint32A> 
extern __imp_GetTextExtentPoint32W:qword 
GetTextExtentPoint32W TEXTEQU <__imp_GetTextExtentPoint32W> 
extern __imp_GetTextExtentPointA:qword 
GetTextExtentPoint TEXTEQU <__imp_GetTextExtentPointA> 
extern __imp_GetTextExtentPointI:qword 
GetTextExtentPointI TEXTEQU <__imp_GetTextExtentPointI> 
extern __imp_GetTextExtentPointW:qword 
GetTextExtentPointW TEXTEQU <__imp_GetTextExtentPointW> 
extern __imp_GetTextFaceA:qword 
GetTextFace TEXTEQU <__imp_GetTextFaceA> 
extern __imp_GetTextFaceAliasW:qword 
GetTextFaceAliasW TEXTEQU <__imp_GetTextFaceAliasW> 
extern __imp_GetTextFaceW:qword 
GetTextFaceW TEXTEQU <__imp_GetTextFaceW> 
extern __imp_GetTextMetricsA:qword 
GetTextMetrics TEXTEQU <__imp_GetTextMetricsA> 
extern __imp_GetTextMetricsW:qword 
GetTextMetricsW TEXTEQU <__imp_GetTextMetricsW> 
extern __imp_GetTransform:qword 
GetTransform TEXTEQU <__imp_GetTransform> 
extern __imp_GetViewportExtEx:qword 
GetViewportExtEx TEXTEQU <__imp_GetViewportExtEx> 
extern __imp_GetViewportOrgEx:qword 
GetViewportOrgEx TEXTEQU <__imp_GetViewportOrgEx> 
extern __imp_GetWinMetaFileBits:qword 
GetWinMetaFileBits TEXTEQU <__imp_GetWinMetaFileBits> 
extern __imp_GetWindowExtEx:qword 
GetWindowExtEx TEXTEQU <__imp_GetWindowExtEx> 
extern __imp_GetWindowOrgEx:qword 
GetWindowOrgEx TEXTEQU <__imp_GetWindowOrgEx> 
extern __imp_GetWorldTransform:qword 
GetWorldTransform TEXTEQU <__imp_GetWorldTransform> 
extern __imp_HT_Get8BPPFormatPalette:qword 
HT_Get8BPPFormatPalette TEXTEQU <__imp_HT_Get8BPPFormatPalette> 
extern __imp_HT_Get8BPPMaskPalette:qword 
HT_Get8BPPMaskPalette TEXTEQU <__imp_HT_Get8BPPMaskPalette> 
extern __imp_IntersectClipRect:qword 
IntersectClipRect TEXTEQU <__imp_IntersectClipRect> 
extern __imp_InvertRgn:qword 
InvertRgn TEXTEQU <__imp_InvertRgn> 
extern __imp_IsValidEnhMetaRecord:qword 
IsValidEnhMetaRecord TEXTEQU <__imp_IsValidEnhMetaRecord> 
extern __imp_IsValidEnhMetaRecordOffExt:qword 
IsValidEnhMetaRecordOffExt TEXTEQU <__imp_IsValidEnhMetaRecordOffExt> 
extern __imp_LPtoDP:qword 
LPtoDP TEXTEQU <__imp_LPtoDP> 
extern __imp_LineDDA:qword 
LineDD TEXTEQU <__imp_LineDDA> 
extern __imp_LineTo:qword 
LineTo TEXTEQU <__imp_LineTo> 
extern __imp_MaskBlt:qword 
MaskBlt TEXTEQU <__imp_MaskBlt> 
extern __imp_MirrorRgn:qword 
MirrorRgn TEXTEQU <__imp_MirrorRgn> 
extern __imp_ModifyWorldTransform:qword 
ModifyWorldTransform TEXTEQU <__imp_ModifyWorldTransform> 
extern __imp_MoveToEx:qword 
MoveToEx TEXTEQU <__imp_MoveToEx> 
extern __imp_NamedEscape:qword 
NamedEscape TEXTEQU <__imp_NamedEscape> 
extern __imp_OffsetClipRgn:qword 
OffsetClipRgn TEXTEQU <__imp_OffsetClipRgn> 
extern __imp_OffsetRgn:qword 
OffsetRgn TEXTEQU <__imp_OffsetRgn> 
extern __imp_OffsetViewportOrgEx:qword 
OffsetViewportOrgEx TEXTEQU <__imp_OffsetViewportOrgEx> 
extern __imp_OffsetWindowOrgEx:qword 
OffsetWindowOrgEx TEXTEQU <__imp_OffsetWindowOrgEx> 
extern __imp_PATHOBJ_bEnum:qword 
PATHOBJ_bEnum TEXTEQU <__imp_PATHOBJ_bEnum> 
extern __imp_PATHOBJ_bEnumClipLines:qword 
PATHOBJ_bEnumClipLines TEXTEQU <__imp_PATHOBJ_bEnumClipLines> 
extern __imp_PATHOBJ_vEnumStart:qword 
PATHOBJ_vEnumStart TEXTEQU <__imp_PATHOBJ_vEnumStart> 
extern __imp_PATHOBJ_vEnumStartClipLines:qword 
PATHOBJ_vEnumStartClipLines TEXTEQU <__imp_PATHOBJ_vEnumStartClipLines> 
extern __imp_PATHOBJ_vGetBounds:qword 
PATHOBJ_vGetBounds TEXTEQU <__imp_PATHOBJ_vGetBounds> 
extern __imp_PaintRgn:qword 
PaintRgn TEXTEQU <__imp_PaintRgn> 
extern __imp_PatBlt:qword 
PatBlt TEXTEQU <__imp_PatBlt> 
extern __imp_PathToRegion:qword 
PathToRegion TEXTEQU <__imp_PathToRegion> 
extern __imp_Pie:qword 
Pie TEXTEQU <__imp_Pie> 
extern __imp_PlayEnhMetaFile:qword 
PlayEnhMetaFile TEXTEQU <__imp_PlayEnhMetaFile> 
extern __imp_PlayEnhMetaFileRecord:qword 
PlayEnhMetaFileRecord TEXTEQU <__imp_PlayEnhMetaFileRecord> 
extern __imp_PlayMetaFile:qword 
PlayMetaFile TEXTEQU <__imp_PlayMetaFile> 
extern __imp_PlayMetaFileRecord:qword 
PlayMetaFileRecord TEXTEQU <__imp_PlayMetaFileRecord> 
extern __imp_PlgBlt:qword 
PlgBlt TEXTEQU <__imp_PlgBlt> 
extern __imp_PolyBezier:qword 
PolyBezier TEXTEQU <__imp_PolyBezier> 
extern __imp_PolyBezierTo:qword 
PolyBezierTo TEXTEQU <__imp_PolyBezierTo> 
extern __imp_PolyDraw:qword 
PolyDraw TEXTEQU <__imp_PolyDraw> 
extern __imp_PolyPatBlt:qword 
PolyPatBlt TEXTEQU <__imp_PolyPatBlt> 
extern __imp_PolyPolygon:qword 
PolyPolygon TEXTEQU <__imp_PolyPolygon> 
extern __imp_PolyPolyline:qword 
PolyPolyline TEXTEQU <__imp_PolyPolyline> 
extern __imp_PolyTextOutA:qword 
PolyTextOut TEXTEQU <__imp_PolyTextOutA> 
extern __imp_PolyTextOutW:qword 
PolyTextOutW TEXTEQU <__imp_PolyTextOutW> 
extern __imp_Polygon:qword 
Polygon TEXTEQU <__imp_Polygon> 
extern __imp_Polyline:qword 
Polyline TEXTEQU <__imp_Polyline> 
extern __imp_PolylineTo:qword 
PolylineTo TEXTEQU <__imp_PolylineTo> 
extern __imp_PtInRegion:qword 
PtInRegion TEXTEQU <__imp_PtInRegion> 
extern __imp_PtVisible:qword 
PtVisible TEXTEQU <__imp_PtVisible> 
extern __imp_QueryFontAssocStatus:qword 
QueryFontAssocStatus TEXTEQU <__imp_QueryFontAssocStatus> 
extern __imp_RealizePalette:qword 
RealizePalette TEXTEQU <__imp_RealizePalette> 
extern __imp_RectInRegion:qword 
RectInRegion TEXTEQU <__imp_RectInRegion> 
extern __imp_RectVisible:qword 
RectVisible TEXTEQU <__imp_RectVisible> 
extern __imp_Rectangle:qword 
Rectangle TEXTEQU <__imp_Rectangle> 
extern __imp_RemoveFontMemResourceEx:qword 
RemoveFontMemResourceEx TEXTEQU <__imp_RemoveFontMemResourceEx> 
extern __imp_RemoveFontResourceA:qword 
RemoveFontResource TEXTEQU <__imp_RemoveFontResourceA> 
extern __imp_RemoveFontResourceExA:qword 
RemoveFontResourceEx TEXTEQU <__imp_RemoveFontResourceExA> 
extern __imp_RemoveFontResourceExW:qword 
RemoveFontResourceExW TEXTEQU <__imp_RemoveFontResourceExW> 
extern __imp_RemoveFontResourceTracking:qword 
RemoveFontResourceTracking TEXTEQU <__imp_RemoveFontResourceTracking> 
extern __imp_RemoveFontResourceW:qword 
RemoveFontResourceW TEXTEQU <__imp_RemoveFontResourceW> 
extern __imp_ResetDCA:qword 
ResetDC TEXTEQU <__imp_ResetDCA> 
extern __imp_ResetDCW:qword 
ResetDCW TEXTEQU <__imp_ResetDCW> 
extern __imp_ResizePalette:qword 
ResizePalette TEXTEQU <__imp_ResizePalette> 
extern __imp_RestoreDC:qword 
RestoreDC TEXTEQU <__imp_RestoreDC> 
extern __imp_RoundRect:qword 
RoundRect TEXTEQU <__imp_RoundRect> 
extern __imp_STROBJ_bEnum:qword 
STROBJ_bEnum TEXTEQU <__imp_STROBJ_bEnum> 
extern __imp_STROBJ_bEnumPositionsOnly:qword 
STROBJ_bEnumPositionsOnly TEXTEQU <__imp_STROBJ_bEnumPositionsOnly> 
extern __imp_STROBJ_bGetAdvanceWidths:qword 
STROBJ_bGetAdvanceWidths TEXTEQU <__imp_STROBJ_bGetAdvanceWidths> 
extern __imp_STROBJ_dwGetCodePage:qword 
STROBJ_dwGetCodePage TEXTEQU <__imp_STROBJ_dwGetCodePage> 
extern __imp_STROBJ_vEnumStart:qword 
STROBJ_vEnumStart TEXTEQU <__imp_STROBJ_vEnumStart> 
extern __imp_SaveDC:qword 
SaveDC TEXTEQU <__imp_SaveDC> 
extern __imp_ScaleViewportExtEx:qword 
ScaleViewportExtEx TEXTEQU <__imp_ScaleViewportExtEx> 
extern __imp_ScaleWindowExtEx:qword 
ScaleWindowExtEx TEXTEQU <__imp_ScaleWindowExtEx> 
extern __imp_SelectBrushLocal:qword 
SelectBrushLocal TEXTEQU <__imp_SelectBrushLocal> 
extern __imp_SelectClipPath:qword 
SelectClipPath TEXTEQU <__imp_SelectClipPath> 
extern __imp_SelectClipRgn:qword 
SelectClipRgn TEXTEQU <__imp_SelectClipRgn> 
extern __imp_SelectFontLocal:qword 
SelectFontLocal TEXTEQU <__imp_SelectFontLocal> 
extern __imp_SelectObject:qword 
SelectObject TEXTEQU <__imp_SelectObject> 
extern __imp_SelectPalette:qword 
SelectPalette TEXTEQU <__imp_SelectPalette> 
extern __imp_SetAbortProc:qword 
SetAbortProc TEXTEQU <__imp_SetAbortProc> 
extern __imp_SetArcDirection:qword 
SetArcDirection TEXTEQU <__imp_SetArcDirection> 
extern __imp_SetBitmapAttributes:qword 
SetBitmapAttributes TEXTEQU <__imp_SetBitmapAttributes> 
extern __imp_SetBitmapBits:qword 
SetBitmapBits TEXTEQU <__imp_SetBitmapBits> 
extern __imp_SetBitmapDimensionEx:qword 
SetBitmapDimensionEx TEXTEQU <__imp_SetBitmapDimensionEx> 
extern __imp_SetBkColor:qword 
SetBkColor TEXTEQU <__imp_SetBkColor> 
extern __imp_SetBkMode:qword 
SetBkMode TEXTEQU <__imp_SetBkMode> 
extern __imp_SetBoundsRect:qword 
SetBoundsRect TEXTEQU <__imp_SetBoundsRect> 
extern __imp_SetBrushAttributes:qword 
SetBrushAttributes TEXTEQU <__imp_SetBrushAttributes> 
extern __imp_SetBrushOrgEx:qword 
SetBrushOrgEx TEXTEQU <__imp_SetBrushOrgEx> 
extern __imp_SetColorAdjustment:qword 
SetColorAdjustment TEXTEQU <__imp_SetColorAdjustment> 
extern __imp_SetColorSpace:qword 
SetColorSpace TEXTEQU <__imp_SetColorSpace> 
extern __imp_SetDCBrushColor:qword 
SetDCBrushColor TEXTEQU <__imp_SetDCBrushColor> 
extern __imp_SetDCPenColor:qword 
SetDCPenColor TEXTEQU <__imp_SetDCPenColor> 
extern __imp_SetDIBColorTable:qword 
SetDIBColorTable TEXTEQU <__imp_SetDIBColorTable> 
extern __imp_SetDIBits:qword 
SetDIBits TEXTEQU <__imp_SetDIBits> 
extern __imp_SetDIBitsToDevice:qword 
SetDIBitsToDevice TEXTEQU <__imp_SetDIBitsToDevice> 
extern __imp_SetDeviceGammaRamp:qword 
SetDeviceGammaRamp TEXTEQU <__imp_SetDeviceGammaRamp> 
extern __imp_SetEnhMetaFileBits:qword 
SetEnhMetaFileBits TEXTEQU <__imp_SetEnhMetaFileBits> 
extern __imp_SetFontEnumeration:qword 
SetFontEnumeration TEXTEQU <__imp_SetFontEnumeration> 
extern __imp_SetGraphicsMode:qword 
SetGraphicsMode TEXTEQU <__imp_SetGraphicsMode> 
extern __imp_SetICMMode:qword 
SetICMMode TEXTEQU <__imp_SetICMMode> 
extern __imp_SetICMProfileA:qword 
SetICMProfile TEXTEQU <__imp_SetICMProfileA> 
extern __imp_SetICMProfileW:qword 
SetICMProfileW TEXTEQU <__imp_SetICMProfileW> 
extern __imp_SetLayout:qword 
SetLayout TEXTEQU <__imp_SetLayout> 
extern __imp_SetLayoutWidth:qword 
SetLayoutWidth TEXTEQU <__imp_SetLayoutWidth> 
extern __imp_SetMagicColors:qword 
SetMagicColors TEXTEQU <__imp_SetMagicColors> 
extern __imp_SetMapMode:qword 
SetMapMode TEXTEQU <__imp_SetMapMode> 
extern __imp_SetMapperFlags:qword 
SetMapperFlags TEXTEQU <__imp_SetMapperFlags> 
extern __imp_SetMetaFileBitsEx:qword 
SetMetaFileBitsEx TEXTEQU <__imp_SetMetaFileBitsEx> 
extern __imp_SetMetaRgn:qword 
SetMetaRgn TEXTEQU <__imp_SetMetaRgn> 
extern __imp_SetMiterLimit:qword 
SetMiterLimit TEXTEQU <__imp_SetMiterLimit> 
extern __imp_SetOPMSigningKeyAndSequenceNumbers:qword 
SetOPMSigningKeyAndSequenceNumbers TEXTEQU <__imp_SetOPMSigningKeyAndSequenceNumbers> 
extern __imp_SetPaletteEntries:qword 
SetPaletteEntries TEXTEQU <__imp_SetPaletteEntries> 
extern __imp_SetPixel:qword 
SetPixel TEXTEQU <__imp_SetPixel> 
extern __imp_SetPixelFormat:qword 
SetPixelFormat TEXTEQU <__imp_SetPixelFormat> 
extern __imp_SetPixelV:qword 
SetPixelV TEXTEQU <__imp_SetPixelV> 
extern __imp_SetPolyFillMode:qword 
SetPolyFillMode TEXTEQU <__imp_SetPolyFillMode> 
extern __imp_SetROP2:qword 
SetROP2 TEXTEQU <__imp_SetROP2> 
extern __imp_SetRectRgn:qword 
SetRectRgn TEXTEQU <__imp_SetRectRgn> 
extern __imp_SetRelAbs:qword 
SetRelAbs TEXTEQU <__imp_SetRelAbs> 
extern __imp_SetStretchBltMode:qword 
SetStretchBltMode TEXTEQU <__imp_SetStretchBltMode> 
extern __imp_SetSystemPaletteUse:qword 
SetSystemPaletteUse TEXTEQU <__imp_SetSystemPaletteUse> 
extern __imp_SetTextAlign:qword 
SetTextAlign TEXTEQU <__imp_SetTextAlign> 
extern __imp_SetTextCharacterExtra:qword 
SetTextCharacterExtr TEXTEQU <__imp_SetTextCharacterExtra> 
extern __imp_SetTextColor:qword 
SetTextColor TEXTEQU <__imp_SetTextColor> 
extern __imp_SetTextJustification:qword 
SetTextJustification TEXTEQU <__imp_SetTextJustification> 
extern __imp_SetViewportExtEx:qword 
SetViewportExtEx TEXTEQU <__imp_SetViewportExtEx> 
extern __imp_SetViewportOrgEx:qword 
SetViewportOrgEx TEXTEQU <__imp_SetViewportOrgEx> 
extern __imp_SetVirtualResolution:qword 
SetVirtualResolution TEXTEQU <__imp_SetVirtualResolution> 
extern __imp_SetWinMetaFileBits:qword 
SetWinMetaFileBits TEXTEQU <__imp_SetWinMetaFileBits> 
extern __imp_SetWindowExtEx:qword 
SetWindowExtEx TEXTEQU <__imp_SetWindowExtEx> 
extern __imp_SetWindowOrgEx:qword 
SetWindowOrgEx TEXTEQU <__imp_SetWindowOrgEx> 
extern __imp_SetWorldTransform:qword 
SetWorldTransform TEXTEQU <__imp_SetWorldTransform> 
extern __imp_StartDocA:qword 
StartDoc TEXTEQU <__imp_StartDocA> 
extern __imp_StartDocW:qword 
StartDocW TEXTEQU <__imp_StartDocW> 
extern __imp_StartFormPage:qword 
StartFormPage TEXTEQU <__imp_StartFormPage> 
extern __imp_StartPage:qword 
StartPage TEXTEQU <__imp_StartPage> 
extern __imp_StretchBlt:qword 
StretchBlt TEXTEQU <__imp_StretchBlt> 
extern __imp_StretchDIBits:qword 
StretchDIBits TEXTEQU <__imp_StretchDIBits> 
extern __imp_StrokeAndFillPath:qword 
StrokeAndFillPath TEXTEQU <__imp_StrokeAndFillPath> 
extern __imp_StrokePath:qword 
StrokePath TEXTEQU <__imp_StrokePath> 
extern __imp_SwapBuffers:qword 
SwapBuffers TEXTEQU <__imp_SwapBuffers> 
extern __imp_TextOutA:qword 
TextOut TEXTEQU <__imp_TextOutA> 
extern __imp_TextOutW:qword 
TextOutW TEXTEQU <__imp_TextOutW> 
extern __imp_TranslateCharsetInfo:qword 
TranslateCharsetInfo TEXTEQU <__imp_TranslateCharsetInfo> 
extern __imp_UnloadNetworkFonts:qword 
UnloadNetworkFonts TEXTEQU <__imp_UnloadNetworkFonts> 
extern __imp_UnrealizeObject:qword 
UnrealizeObject TEXTEQU <__imp_UnrealizeObject> 
extern __imp_UpdateColors:qword 
UpdateColors TEXTEQU <__imp_UpdateColors> 
extern __imp_UpdateICMRegKeyA:qword 
UpdateICMRegKey TEXTEQU <__imp_UpdateICMRegKeyA> 
extern __imp_UpdateICMRegKeyW:qword 
UpdateICMRegKeyW TEXTEQU <__imp_UpdateICMRegKeyW> 
extern __imp_WidenPath:qword 
WidenPath TEXTEQU <__imp_WidenPath> 
extern __imp_XFORMOBJ_bApplyXform:qword 
XFORMOBJ_bApplyXform TEXTEQU <__imp_XFORMOBJ_bApplyXform> 
extern __imp_XFORMOBJ_iGetXform:qword 
XFORMOBJ_iGetXform TEXTEQU <__imp_XFORMOBJ_iGetXform> 
extern __imp_XLATEOBJ_cGetPalette:qword 
XLATEOBJ_cGetPalette TEXTEQU <__imp_XLATEOBJ_cGetPalette> 
extern __imp_XLATEOBJ_hGetColorTransform:qword 
XLATEOBJ_hGetColorTransform TEXTEQU <__imp_XLATEOBJ_hGetColorTransform> 
extern __imp_XLATEOBJ_iXlate:qword 
XLATEOBJ_iXlate TEXTEQU <__imp_XLATEOBJ_iXlate> 
extern __imp_XLATEOBJ_piVector:qword 
XLATEOBJ_piVector TEXTEQU <__imp_XLATEOBJ_piVector> 
extern __imp_bInitSystemAndFontsDirectoriesW:qword 
bInitSystemAndFontsDirectoriesW TEXTEQU <__imp_bInitSystemAndFontsDirectoriesW> 
extern __imp_bMakePathNameW:qword 
bMakePathNameW TEXTEQU <__imp_bMakePathNameW> 
extern __imp_cGetTTFFromFOT:qword 
cGetTTFFromFOT TEXTEQU <__imp_cGetTTFFromFOT> 
extern __imp_gdiPlaySpoolStream:qword 
gdiPlaySpoolStream TEXTEQU <__imp_gdiPlaySpoolStream> 
extern __imp_gdi32_ordinal1000:qword 
gdi32_ordinal1000 TEXTEQU <__imp_gdi32_ordinal1000> 
extern __imp_gdi32_ordinal1001:qword 
gdi32_ordinal1001 TEXTEQU <__imp_gdi32_ordinal1001> 
extern __imp_gdi32_ordinal1002:qword 
gdi32_ordinal1002 TEXTEQU <__imp_gdi32_ordinal1002> 
extern __imp_gdi32_ordinal1003:qword 
gdi32_ordinal1003 TEXTEQU <__imp_gdi32_ordinal1003> 
extern __imp_gdi32_ordinal1004:qword 
gdi32_ordinal1004 TEXTEQU <__imp_gdi32_ordinal1004> 
extern __imp_gdi32_ordinal1005:qword 
gdi32_ordinal1005 TEXTEQU <__imp_gdi32_ordinal1005> 
extern __imp_gdi32_ordinal1006:qword 
gdi32_ordinal1006 TEXTEQU <__imp_gdi32_ordinal1006> 
extern __imp_gdi32_ordinal1007:qword 
gdi32_ordinal1007 TEXTEQU <__imp_gdi32_ordinal1007> 
extern __imp_gdi32_ordinal1008:qword 
gdi32_ordinal1008 TEXTEQU <__imp_gdi32_ordinal1008> 
extern __imp_gdi32_ordinal1009:qword 
gdi32_ordinal1009 TEXTEQU <__imp_gdi32_ordinal1009> 
extern __imp_gdi32_ordinal1010:qword 
gdi32_ordinal1010 TEXTEQU <__imp_gdi32_ordinal1010> 
extern __imp_gdi32_ordinal1011:qword 
gdi32_ordinal1011 TEXTEQU <__imp_gdi32_ordinal1011> 
;-----------------------------
TEXTMETRICA STRUCT
  tmHeight              DWORD      ?
  tmAscent              DWORD      ?
  tmDescent             DWORD      ?
  tmInternalLeading     DWORD      ?
  tmExternalLeading     DWORD      ?
  tmAveCharWidth        DWORD      ?
  tmMaxCharWidth        DWORD      ?
  tmWeight              DWORD      ?
  tmOverhang            DWORD      ?
  tmDigitizedAspectX    DWORD      ?
  tmDigitizedAspectY    DWORD      ?
  tmFirstChar           BYTE      ?
  tmLastChar            BYTE      ?
  tmDefaultChar         BYTE      ?
  tmBreakChar           BYTE      ?
  tmItalic              BYTE      ?
  tmUnderlined          BYTE      ?
  tmStruckOut           BYTE      ?
  tmPitchAndFamily      BYTE      ?
  tmCharSet             BYTE      ?
TEXTMETRICA ENDS

POLYTEXT STRUCT
  x         DWORD       ?
  y         DWORD       ?
  n         QWORD       ?
  lpStr     QWORD       ?
  uiFlags   QWORD       ?
  icl       RECT        <>
  pdx       QWORD       ?
POLYTEXT ENDS