extern __imp_ActivateActCtx:qword 
ActivateActCtx TEXTEQU <__imp_ActivateActCtx> 
extern __imp_AddAtomA:qword 
AddAtom TEXTEQU <__imp_AddAtomA> 
extern __imp_AddAtomW:qword 
AddAtomW TEXTEQU <__imp_AddAtomW> 
extern __imp_AddConsoleAliasA:qword 
AddConsoleAlias TEXTEQU <__imp_AddConsoleAliasA> 
extern __imp_AddConsoleAliasW:qword 
AddConsoleAliasW TEXTEQU <__imp_AddConsoleAliasW> 
extern __imp_AddIntegrityLabelToBoundaryDescriptor:qword 
AddIntegrityLabelToBoundaryDescriptor TEXTEQU <__imp_AddIntegrityLabelToBoundaryDescriptor> 
extern __imp_AddLocalAlternateComputerNameA:qword 
AddLocalAlternateComputerName TEXTEQU <__imp_AddLocalAlternateComputerNameA> 
extern __imp_AddLocalAlternateComputerNameW:qword 
AddLocalAlternateComputerNameW TEXTEQU <__imp_AddLocalAlternateComputerNameW> 
extern __imp_AddRefActCtx:qword 
AddRefActCtx TEXTEQU <__imp_AddRefActCtx> 
extern __imp_AddSIDToBoundaryDescriptor:qword 
AddSIDToBoundaryDescriptor TEXTEQU <__imp_AddSIDToBoundaryDescriptor> 
extern __imp_AddSecureMemoryCacheCallback:qword 
AddSecureMemoryCacheCallback TEXTEQU <__imp_AddSecureMemoryCacheCallback> 
extern __imp_AdjustCalendarDate:qword 
AdjustCalendarDate TEXTEQU <__imp_AdjustCalendarDate> 
extern __imp_AllocConsole:qword 
AllocConsole TEXTEQU <__imp_AllocConsole> 
extern __imp_AllocateUserPhysicalPages:qword 
AllocateUserPhysicalPages TEXTEQU <__imp_AllocateUserPhysicalPages> 
extern __imp_AllocateUserPhysicalPagesNuma:qword 
AllocateUserPhysicalPagesNum TEXTEQU <__imp_AllocateUserPhysicalPagesNuma> 
extern __imp_ApplicationRecoveryFinished:qword 
ApplicationRecoveryFinished TEXTEQU <__imp_ApplicationRecoveryFinished> 
extern __imp_ApplicationRecoveryInProgress:qword 
ApplicationRecoveryInProgress TEXTEQU <__imp_ApplicationRecoveryInProgress> 
extern __imp_AreFileApisANSI:qword 
AreFileApisANSI TEXTEQU <__imp_AreFileApisANSI> 
extern __imp_AssignProcessToJobObject:qword 
AssignProcessToJobObject TEXTEQU <__imp_AssignProcessToJobObject> 
extern __imp_AttachConsole:qword 
AttachConsole TEXTEQU <__imp_AttachConsole> 
extern __imp_BackupRead:qword 
BackupRead TEXTEQU <__imp_BackupRead> 
extern __imp_BackupSeek:qword 
BackupSeek TEXTEQU <__imp_BackupSeek> 
extern __imp_BackupWrite:qword 
BackupWrite TEXTEQU <__imp_BackupWrite> 
extern __imp_BaseCheckAppcompatCache:qword 
BaseCheckAppcompatCache TEXTEQU <__imp_BaseCheckAppcompatCache> 
extern __imp_BaseCheckAppcompatCacheEx:qword 
BaseCheckAppcompatCacheEx TEXTEQU <__imp_BaseCheckAppcompatCacheEx> 
extern __imp_BaseCheckRunApp:qword 
BaseCheckRunApp TEXTEQU <__imp_BaseCheckRunApp> 
extern __imp_BaseCleanupAppcompatCacheSupport:qword 
BaseCleanupAppcompatCacheSupport TEXTEQU <__imp_BaseCleanupAppcompatCacheSupport> 
extern __imp_BaseDllReadWriteIniFile:qword 
BaseDllReadWriteIniFile TEXTEQU <__imp_BaseDllReadWriteIniFile> 
extern __imp_BaseDumpAppcompatCache:qword 
BaseDumpAppcompatCache TEXTEQU <__imp_BaseDumpAppcompatCache> 
extern __imp_BaseFlushAppcompatCache:qword 
BaseFlushAppcompatCache TEXTEQU <__imp_BaseFlushAppcompatCache> 
extern __imp_BaseFormatObjectAttributes:qword 
BaseFormatObjectAttributes TEXTEQU <__imp_BaseFormatObjectAttributes> 
extern __imp_BaseFormatTimeOut:qword 
BaseFormatTimeOut TEXTEQU <__imp_BaseFormatTimeOut> 
extern __imp_BaseGenerateAppCompatData:qword 
BaseGenerateAppCompatDat TEXTEQU <__imp_BaseGenerateAppCompatData> 
extern __imp_BaseGetNamedObjectDirectory:qword 
BaseGetNamedObjectDirectory TEXTEQU <__imp_BaseGetNamedObjectDirectory> 
extern __imp_BaseInitAppcompatCacheSupport:qword 
BaseInitAppcompatCacheSupport TEXTEQU <__imp_BaseInitAppcompatCacheSupport> 
extern __imp_BaseIsAppcompatInfrastructureDisabled:qword 
BaseIsAppcompatInfrastructureDisabled TEXTEQU <__imp_BaseIsAppcompatInfrastructureDisabled> 
extern __imp_BaseQueryModuleData:qword 
BaseQueryModuleDat TEXTEQU <__imp_BaseQueryModuleData> 
extern __imp_BaseSetLastNTError:qword 
BaseSetLastNTError TEXTEQU <__imp_BaseSetLastNTError> 
extern __imp_BaseThreadInitThunk:qword 
BaseThreadInitThunk TEXTEQU <__imp_BaseThreadInitThunk> 
extern __imp_BaseUpdateAppcompatCache:qword 
BaseUpdateAppcompatCache TEXTEQU <__imp_BaseUpdateAppcompatCache> 
extern __imp_BaseVerifyUnicodeString:qword 
BaseVerifyUnicodeString TEXTEQU <__imp_BaseVerifyUnicodeString> 
extern __imp_Basep8BitStringToDynamicUnicodeString:qword 
Basep8BitStringToDynamicUnicodeString TEXTEQU <__imp_Basep8BitStringToDynamicUnicodeString> 
extern __imp_BasepAllocateActivationContextActivationBlock:qword 
BasepAllocateActivationContextActivationBlock TEXTEQU <__imp_BasepAllocateActivationContextActivationBlock> 
extern __imp_BasepAnsiStringToDynamicUnicodeString:qword 
BasepAnsiStringToDynamicUnicodeString TEXTEQU <__imp_BasepAnsiStringToDynamicUnicodeString> 
extern __imp_BasepCheckAppCompat:qword 
BasepCheckAppCompat TEXTEQU <__imp_BasepCheckAppCompat> 
extern __imp_BasepCheckBadapp:qword 
BasepCheckBadapp TEXTEQU <__imp_BasepCheckBadapp> 
extern __imp_BasepCheckWinSaferRestrictions:qword 
BasepCheckWinSaferRestrictions TEXTEQU <__imp_BasepCheckWinSaferRestrictions> 
extern __imp_BasepFreeActivationContextActivationBlock:qword 
BasepFreeActivationContextActivationBlock TEXTEQU <__imp_BasepFreeActivationContextActivationBlock> 
extern __imp_BasepFreeAppCompatData:qword 
BasepFreeAppCompatDat TEXTEQU <__imp_BasepFreeAppCompatData> 
extern __imp_BasepMapModuleHandle:qword 
BasepMapModuleHandle TEXTEQU <__imp_BasepMapModuleHandle> 
extern __imp_Beep:qword 
Beep TEXTEQU <__imp_Beep> 
extern __imp_BeginUpdateResourceA:qword 
BeginUpdateResource TEXTEQU <__imp_BeginUpdateResourceA> 
extern __imp_BeginUpdateResourceW:qword 
BeginUpdateResourceW TEXTEQU <__imp_BeginUpdateResourceW> 
extern __imp_BindIoCompletionCallback:qword 
BindIoCompletionCallback TEXTEQU <__imp_BindIoCompletionCallback> 
extern __imp_BuildCommDCBA:qword 
BuildCommDCB TEXTEQU <__imp_BuildCommDCBA> 
extern __imp_BuildCommDCBAndTimeoutsA:qword 
BuildCommDCBAndTimeouts TEXTEQU <__imp_BuildCommDCBAndTimeoutsA> 
extern __imp_BuildCommDCBAndTimeoutsW:qword 
BuildCommDCBAndTimeoutsW TEXTEQU <__imp_BuildCommDCBAndTimeoutsW> 
extern __imp_BuildCommDCBW:qword 
BuildCommDCBW TEXTEQU <__imp_BuildCommDCBW> 
extern __imp_CallNamedPipeA:qword 
CallNamedPipe TEXTEQU <__imp_CallNamedPipeA> 
extern __imp_CallNamedPipeW:qword 
CallNamedPipeW TEXTEQU <__imp_CallNamedPipeW> 
extern __imp_CallbackMayRunLong:qword 
CallbackMayRunLong TEXTEQU <__imp_CallbackMayRunLong> 
extern __imp_CancelDeviceWakeupRequest:qword 
CancelDeviceWakeupRequest TEXTEQU <__imp_CancelDeviceWakeupRequest> 
extern __imp_CancelIo:qword 
CancelIo TEXTEQU <__imp_CancelIo> 
extern __imp_CancelIoEx:qword 
CancelIoEx TEXTEQU <__imp_CancelIoEx> 
extern __imp_CancelSynchronousIo:qword 
CancelSynchronousIo TEXTEQU <__imp_CancelSynchronousIo> 
extern __imp_CancelTimerQueueTimer:qword 
CancelTimerQueueTimer TEXTEQU <__imp_CancelTimerQueueTimer> 
extern __imp_CancelWaitableTimer:qword 
CancelWaitableTimer TEXTEQU <__imp_CancelWaitableTimer> 
extern __imp_ChangeTimerQueueTimer:qword 
ChangeTimerQueueTimer TEXTEQU <__imp_ChangeTimerQueueTimer> 
extern __imp_CheckElevation:qword 
CheckElevation TEXTEQU <__imp_CheckElevation> 
extern __imp_CheckElevationEnabled:qword 
CheckElevationEnabled TEXTEQU <__imp_CheckElevationEnabled> 
extern __imp_CheckForReadOnlyResource:qword 
CheckForReadOnlyResource TEXTEQU <__imp_CheckForReadOnlyResource> 
extern __imp_CheckNameLegalDOS8Dot3A:qword 
CheckNameLegalDOS8Dot3 TEXTEQU <__imp_CheckNameLegalDOS8Dot3A> 
extern __imp_CheckNameLegalDOS8Dot3W:qword 
CheckNameLegalDOS8Dot3W TEXTEQU <__imp_CheckNameLegalDOS8Dot3W> 
extern __imp_CheckRemoteDebuggerPresent:qword 
CheckRemoteDebuggerPresent TEXTEQU <__imp_CheckRemoteDebuggerPresent> 
extern __imp_ClearCommBreak:qword 
ClearCommBreak TEXTEQU <__imp_ClearCommBreak> 
extern __imp_ClearCommError:qword 
ClearCommError TEXTEQU <__imp_ClearCommError> 
extern __imp_CloseConsoleHandle:qword 
CloseConsoleHandle TEXTEQU <__imp_CloseConsoleHandle> 
extern __imp_CloseHandle:qword 
CloseHandle TEXTEQU <__imp_CloseHandle> 
extern __imp_ClosePrivateNamespace:qword 
ClosePrivateNamespace TEXTEQU <__imp_ClosePrivateNamespace> 
extern __imp_CloseProfileUserMapping:qword 
CloseProfileUserMapping TEXTEQU <__imp_CloseProfileUserMapping> 
extern __imp_CmdBatNotification:qword 
CmdBatNotification TEXTEQU <__imp_CmdBatNotification> 
extern __imp_CommConfigDialogA:qword 
CommConfigDialog TEXTEQU <__imp_CommConfigDialogA> 
extern __imp_CommConfigDialogW:qword 
CommConfigDialogW TEXTEQU <__imp_CommConfigDialogW> 
extern __imp_CompareCalendarDates:qword 
CompareCalendarDates TEXTEQU <__imp_CompareCalendarDates> 
extern __imp_CompareFileTime:qword 
CompareFileTime TEXTEQU <__imp_CompareFileTime> 
extern __imp_CompareStringA:qword 
CompareString TEXTEQU <__imp_CompareStringA> 
extern __imp_CompareStringEx:qword 
CompareStringEx TEXTEQU <__imp_CompareStringEx> 
extern __imp_CompareStringOrdinal:qword 
CompareStringOrdinal TEXTEQU <__imp_CompareStringOrdinal> 
extern __imp_CompareStringW:qword 
CompareStringW TEXTEQU <__imp_CompareStringW> 
extern __imp_ConnectNamedPipe:qword 
ConnectNamedPipe TEXTEQU <__imp_ConnectNamedPipe> 
extern __imp_ConsoleMenuControl:qword 
ConsoleMenuControl TEXTEQU <__imp_ConsoleMenuControl> 
extern __imp_ContinueDebugEvent:qword 
ContinueDebugEvent TEXTEQU <__imp_ContinueDebugEvent> 
extern __imp_ConvertCalDateTimeToSystemTime:qword 
ConvertCalDateTimeToSystemTime TEXTEQU <__imp_ConvertCalDateTimeToSystemTime> 
extern __imp_ConvertDefaultLocale:qword 
ConvertDefaultLocale TEXTEQU <__imp_ConvertDefaultLocale> 
extern __imp_ConvertFiberToThread:qword 
ConvertFiberToThread TEXTEQU <__imp_ConvertFiberToThread> 
extern __imp_ConvertNLSDayOfWeekToWin32DayOfWeek:qword 
ConvertNLSDayOfWeekToWin32DayOfWeek TEXTEQU <__imp_ConvertNLSDayOfWeekToWin32DayOfWeek> 
extern __imp_ConvertSystemTimeToCalDateTime:qword 
ConvertSystemTimeToCalDateTime TEXTEQU <__imp_ConvertSystemTimeToCalDateTime> 
extern __imp_ConvertThreadToFiber:qword 
ConvertThreadToFiber TEXTEQU <__imp_ConvertThreadToFiber> 
extern __imp_ConvertThreadToFiberEx:qword 
ConvertThreadToFiberEx TEXTEQU <__imp_ConvertThreadToFiberEx> 
extern __imp_CopyContext:qword 
CopyContext TEXTEQU <__imp_CopyContext> 
extern __imp_CopyFileA:qword 
CopyFile TEXTEQU <__imp_CopyFileA> 
extern __imp_CopyFileExA:qword 
CopyFileEx TEXTEQU <__imp_CopyFileExA> 
extern __imp_CopyFileExW:qword 
CopyFileExW TEXTEQU <__imp_CopyFileExW> 
extern __imp_CopyFileTransactedA:qword 
CopyFileTransacted TEXTEQU <__imp_CopyFileTransactedA> 
extern __imp_CopyFileTransactedW:qword 
CopyFileTransactedW TEXTEQU <__imp_CopyFileTransactedW> 
extern __imp_CopyFileW:qword 
CopyFileW TEXTEQU <__imp_CopyFileW> 
extern __imp_CopyLZFile:qword 
CopyLZFile TEXTEQU <__imp_CopyLZFile> 
extern __imp_CreateActCtxA:qword 
CreateActCtx TEXTEQU <__imp_CreateActCtxA> 
extern __imp_CreateActCtxW:qword 
CreateActCtxW TEXTEQU <__imp_CreateActCtxW> 
extern __imp_CreateBoundaryDescriptorA:qword 
CreateBoundaryDescriptor TEXTEQU <__imp_CreateBoundaryDescriptorA> 
extern __imp_CreateBoundaryDescriptorW:qword 
CreateBoundaryDescriptorW TEXTEQU <__imp_CreateBoundaryDescriptorW> 
extern __imp_CreateConsoleScreenBuffer:qword 
CreateConsoleScreenBuffer TEXTEQU <__imp_CreateConsoleScreenBuffer> 
extern __imp_CreateDirectoryA:qword 
CreateDirectory TEXTEQU <__imp_CreateDirectoryA> 
extern __imp_CreateDirectoryExA:qword 
CreateDirectoryEx TEXTEQU <__imp_CreateDirectoryExA> 
extern __imp_CreateDirectoryExW:qword 
CreateDirectoryExW TEXTEQU <__imp_CreateDirectoryExW> 
extern __imp_CreateDirectoryTransactedA:qword 
CreateDirectoryTransacted TEXTEQU <__imp_CreateDirectoryTransactedA> 
extern __imp_CreateDirectoryTransactedW:qword 
CreateDirectoryTransactedW TEXTEQU <__imp_CreateDirectoryTransactedW> 
extern __imp_CreateDirectoryW:qword 
CreateDirectoryW TEXTEQU <__imp_CreateDirectoryW> 
extern __imp_CreateEventA:qword 
CreateEvent TEXTEQU <__imp_CreateEventA> 
extern __imp_CreateEventExA:qword 
CreateEventEx TEXTEQU <__imp_CreateEventExA> 
extern __imp_CreateEventExW:qword 
CreateEventExW TEXTEQU <__imp_CreateEventExW> 
extern __imp_CreateEventW:qword 
CreateEventW TEXTEQU <__imp_CreateEventW> 
extern __imp_CreateFiber:qword 
CreateFiber TEXTEQU <__imp_CreateFiber> 
extern __imp_CreateFiberEx:qword 
CreateFiberEx TEXTEQU <__imp_CreateFiberEx> 
extern __imp_CreateFileA:qword 
CreateFile TEXTEQU <__imp_CreateFileA> 
extern __imp_CreateFileMappingA:qword 
CreateFileMapping TEXTEQU <__imp_CreateFileMappingA> 
extern __imp_CreateFileMappingNumaA:qword 
CreateFileMappingNuma TEXTEQU <__imp_CreateFileMappingNumaA> 
extern __imp_CreateFileMappingNumaW:qword 
CreateFileMappingNumaW TEXTEQU <__imp_CreateFileMappingNumaW> 
extern __imp_CreateFileMappingW:qword 
CreateFileMappingW TEXTEQU <__imp_CreateFileMappingW> 
extern __imp_CreateFileTransactedA:qword 
CreateFileTransacted TEXTEQU <__imp_CreateFileTransactedA> 
extern __imp_CreateFileTransactedW:qword 
CreateFileTransactedW TEXTEQU <__imp_CreateFileTransactedW> 
extern __imp_CreateFileW:qword 
CreateFileW TEXTEQU <__imp_CreateFileW> 
extern __imp_CreateHardLinkA:qword 
CreateHardLink TEXTEQU <__imp_CreateHardLinkA> 
extern __imp_CreateHardLinkTransactedA:qword 
CreateHardLinkTransacted TEXTEQU <__imp_CreateHardLinkTransactedA> 
extern __imp_CreateHardLinkTransactedW:qword 
CreateHardLinkTransactedW TEXTEQU <__imp_CreateHardLinkTransactedW> 
extern __imp_CreateHardLinkW:qword 
CreateHardLinkW TEXTEQU <__imp_CreateHardLinkW> 
extern __imp_CreateIoCompletionPort:qword 
CreateIoCompletionPort TEXTEQU <__imp_CreateIoCompletionPort> 
extern __imp_CreateJobObjectA:qword 
CreateJobObject TEXTEQU <__imp_CreateJobObjectA> 
extern __imp_CreateJobObjectW:qword 
CreateJobObjectW TEXTEQU <__imp_CreateJobObjectW> 
extern __imp_CreateJobSet:qword 
CreateJobSet TEXTEQU <__imp_CreateJobSet> 
extern __imp_CreateMailslotA:qword 
CreateMailslot TEXTEQU <__imp_CreateMailslotA> 
extern __imp_CreateMailslotW:qword 
CreateMailslotW TEXTEQU <__imp_CreateMailslotW> 
extern __imp_CreateMemoryResourceNotification:qword 
CreateMemoryResourceNotification TEXTEQU <__imp_CreateMemoryResourceNotification> 
extern __imp_CreateMutexA:qword 
CreateMutex TEXTEQU <__imp_CreateMutexA> 
extern __imp_CreateMutexExA:qword 
CreateMutexEx TEXTEQU <__imp_CreateMutexExA> 
extern __imp_CreateMutexExW:qword 
CreateMutexExW TEXTEQU <__imp_CreateMutexExW> 
extern __imp_CreateMutexW:qword 
CreateMutexW TEXTEQU <__imp_CreateMutexW> 
extern __imp_CreateNamedPipeA:qword 
CreateNamedPipe TEXTEQU <__imp_CreateNamedPipeA> 
extern __imp_CreateNamedPipeW:qword 
CreateNamedPipeW TEXTEQU <__imp_CreateNamedPipeW> 
extern __imp_CreatePipe:qword 
CreatePipe TEXTEQU <__imp_CreatePipe> 
extern __imp_CreatePrivateNamespaceA:qword 
CreatePrivateNamespace TEXTEQU <__imp_CreatePrivateNamespaceA> 
extern __imp_CreatePrivateNamespaceW:qword 
CreatePrivateNamespaceW TEXTEQU <__imp_CreatePrivateNamespaceW> 
extern __imp_CreateProcessA:qword 
CreateProcess TEXTEQU <__imp_CreateProcessA> 
extern __imp_CreateProcessAsUserW:qword 
CreateProcessAsUserW TEXTEQU <__imp_CreateProcessAsUserW> 
extern __imp_CreateProcessInternalA:qword 
CreateProcessInternal TEXTEQU <__imp_CreateProcessInternalA> 
extern __imp_CreateProcessInternalW:qword 
CreateProcessInternalW TEXTEQU <__imp_CreateProcessInternalW> 
extern __imp_CreateProcessW:qword 
CreateProcessW TEXTEQU <__imp_CreateProcessW> 
extern __imp_CreateRemoteThread:qword 
CreateRemoteThread TEXTEQU <__imp_CreateRemoteThread> 
extern __imp_CreateSemaphoreA:qword 
CreateSemaphore TEXTEQU <__imp_CreateSemaphoreA> 
extern __imp_CreateSemaphoreExA:qword 
CreateSemaphoreEx TEXTEQU <__imp_CreateSemaphoreExA> 
extern __imp_CreateSemaphoreExW:qword 
CreateSemaphoreExW TEXTEQU <__imp_CreateSemaphoreExW> 
extern __imp_CreateSemaphoreW:qword 
CreateSemaphoreW TEXTEQU <__imp_CreateSemaphoreW> 
extern __imp_CreateSymbolicLinkA:qword 
CreateSymbolicLink TEXTEQU <__imp_CreateSymbolicLinkA> 
extern __imp_CreateSymbolicLinkTransactedA:qword 
CreateSymbolicLinkTransacted TEXTEQU <__imp_CreateSymbolicLinkTransactedA> 
extern __imp_CreateSymbolicLinkTransactedW:qword 
CreateSymbolicLinkTransactedW TEXTEQU <__imp_CreateSymbolicLinkTransactedW> 
extern __imp_CreateSymbolicLinkW:qword 
CreateSymbolicLinkW TEXTEQU <__imp_CreateSymbolicLinkW> 
extern __imp_CreateTapePartition:qword 
CreateTapePartition TEXTEQU <__imp_CreateTapePartition> 
extern __imp_CreateThread:qword 
CreateThread TEXTEQU <__imp_CreateThread> 
extern __imp_CreateThreadpool:qword 
CreateThreadpool TEXTEQU <__imp_CreateThreadpool> 
extern __imp_CreateThreadpoolCleanupGroup:qword 
CreateThreadpoolCleanupGroup TEXTEQU <__imp_CreateThreadpoolCleanupGroup> 
extern __imp_CreateThreadpoolIo:qword 
CreateThreadpoolIo TEXTEQU <__imp_CreateThreadpoolIo> 
extern __imp_CreateThreadpoolTimer:qword 
CreateThreadpoolTimer TEXTEQU <__imp_CreateThreadpoolTimer> 
extern __imp_CreateThreadpoolWait:qword 
CreateThreadpoolWait TEXTEQU <__imp_CreateThreadpoolWait> 
extern __imp_CreateThreadpoolWork:qword 
CreateThreadpoolWork TEXTEQU <__imp_CreateThreadpoolWork> 
extern __imp_CreateTimerQueue:qword 
CreateTimerQueue TEXTEQU <__imp_CreateTimerQueue> 
extern __imp_CreateTimerQueueTimer:qword 
CreateTimerQueueTimer TEXTEQU <__imp_CreateTimerQueueTimer> 
extern __imp_CreateToolhelp32Snapshot:qword 
CreateToolhelp32Snapshot TEXTEQU <__imp_CreateToolhelp32Snapshot> 
extern __imp_CreateUmsCompletionList:qword 
CreateUmsCompletionList TEXTEQU <__imp_CreateUmsCompletionList> 
extern __imp_CreateUmsThreadContext:qword 
CreateUmsThreadContext TEXTEQU <__imp_CreateUmsThreadContext> 
extern __imp_CreateWaitableTimerA:qword 
CreateWaitableTimer TEXTEQU <__imp_CreateWaitableTimerA> 
extern __imp_CreateWaitableTimerExA:qword 
CreateWaitableTimerEx TEXTEQU <__imp_CreateWaitableTimerExA> 
extern __imp_CreateWaitableTimerExW:qword 
CreateWaitableTimerExW TEXTEQU <__imp_CreateWaitableTimerExW> 
extern __imp_CreateWaitableTimerW:qword 
CreateWaitableTimerW TEXTEQU <__imp_CreateWaitableTimerW> 
extern __imp_CtrlRoutine:qword 
CtrlRoutine TEXTEQU <__imp_CtrlRoutine> 
extern __imp_DeactivateActCtx:qword 
DeactivateActCtx TEXTEQU <__imp_DeactivateActCtx> 
extern __imp_DebugActiveProcess:qword 
DebugActiveProcess TEXTEQU <__imp_DebugActiveProcess> 
extern __imp_DebugActiveProcessStop:qword 
DebugActiveProcessStop TEXTEQU <__imp_DebugActiveProcessStop> 
extern __imp_DebugBreak:qword 
DebugBreak TEXTEQU <__imp_DebugBreak> 
extern __imp_DebugBreakProcess:qword 
DebugBreakProcess TEXTEQU <__imp_DebugBreakProcess> 
extern __imp_DebugSetProcessKillOnExit:qword 
DebugSetProcessKillOnExit TEXTEQU <__imp_DebugSetProcessKillOnExit> 
extern __imp_DefineDosDeviceA:qword 
DefineDosDevice TEXTEQU <__imp_DefineDosDeviceA> 
extern __imp_DefineDosDeviceW:qword 
DefineDosDeviceW TEXTEQU <__imp_DefineDosDeviceW> 
extern __imp_DelayLoadFailureHook:qword 
DelayLoadFailureHook TEXTEQU <__imp_DelayLoadFailureHook> 
extern __imp_DeleteAtom:qword 
DeleteAtom TEXTEQU <__imp_DeleteAtom> 
extern __imp_DeleteFiber:qword 
DeleteFiber TEXTEQU <__imp_DeleteFiber> 
extern __imp_DeleteFileA:qword 
DeleteFile TEXTEQU <__imp_DeleteFileA> 
extern __imp_DeleteFileTransactedA:qword 
DeleteFileTransacted TEXTEQU <__imp_DeleteFileTransactedA> 
extern __imp_DeleteFileTransactedW:qword 
DeleteFileTransactedW TEXTEQU <__imp_DeleteFileTransactedW> 
extern __imp_DeleteFileW:qword 
DeleteFileW TEXTEQU <__imp_DeleteFileW> 
extern __imp_DeleteTimerQueue:qword 
DeleteTimerQueue TEXTEQU <__imp_DeleteTimerQueue> 
extern __imp_DeleteTimerQueueEx:qword 
DeleteTimerQueueEx TEXTEQU <__imp_DeleteTimerQueueEx> 
extern __imp_DeleteTimerQueueTimer:qword 
DeleteTimerQueueTimer TEXTEQU <__imp_DeleteTimerQueueTimer> 
extern __imp_DeleteUmsCompletionList:qword 
DeleteUmsCompletionList TEXTEQU <__imp_DeleteUmsCompletionList> 
extern __imp_DeleteUmsThreadContext:qword 
DeleteUmsThreadContext TEXTEQU <__imp_DeleteUmsThreadContext> 
extern __imp_DeleteVolumeMountPointA:qword 
DeleteVolumeMountPoint TEXTEQU <__imp_DeleteVolumeMountPointA> 
extern __imp_DeleteVolumeMountPointW:qword 
DeleteVolumeMountPointW TEXTEQU <__imp_DeleteVolumeMountPointW> 
extern __imp_DequeueUmsCompletionListItems:qword 
DequeueUmsCompletionListItems TEXTEQU <__imp_DequeueUmsCompletionListItems> 
extern __imp_DeviceIoControl:qword 
DeviceIoControl TEXTEQU <__imp_DeviceIoControl> 
extern __imp_DisableThreadLibraryCalls:qword 
DisableThreadLibraryCalls TEXTEQU <__imp_DisableThreadLibraryCalls> 
extern __imp_DisableThreadProfiling:qword 
DisableThreadProfiling TEXTEQU <__imp_DisableThreadProfiling> 
extern __imp_DisconnectNamedPipe:qword 
DisconnectNamedPipe TEXTEQU <__imp_DisconnectNamedPipe> 
extern __imp_DnsHostnameToComputerNameA:qword 
DnsHostnameToComputerName TEXTEQU <__imp_DnsHostnameToComputerNameA> 
extern __imp_DnsHostnameToComputerNameW:qword 
DnsHostnameToComputerNameW TEXTEQU <__imp_DnsHostnameToComputerNameW> 
extern __imp_DosDateTimeToFileTime:qword 
DosDateTimeToFileTime TEXTEQU <__imp_DosDateTimeToFileTime> 
extern __imp_DosPathToSessionPathA:qword 
DosPathToSessionPath TEXTEQU <__imp_DosPathToSessionPathA> 
extern __imp_DosPathToSessionPathW:qword 
DosPathToSessionPathW TEXTEQU <__imp_DosPathToSessionPathW> 
extern __imp_DuplicateConsoleHandle:qword 
DuplicateConsoleHandle TEXTEQU <__imp_DuplicateConsoleHandle> 
extern __imp_DuplicateHandle:qword 
DuplicateHandle TEXTEQU <__imp_DuplicateHandle> 
extern __imp_EnableThreadProfiling:qword 
EnableThreadProfiling TEXTEQU <__imp_EnableThreadProfiling> 
extern __imp_EndUpdateResourceA:qword 
EndUpdateResource TEXTEQU <__imp_EndUpdateResourceA> 
extern __imp_EndUpdateResourceW:qword 
EndUpdateResourceW TEXTEQU <__imp_EndUpdateResourceW> 
extern __imp_EnterUmsSchedulingMode:qword 
EnterUmsSchedulingMode TEXTEQU <__imp_EnterUmsSchedulingMode> 
extern __imp_EnumCalendarInfoA:qword 
EnumCalendarInfo TEXTEQU <__imp_EnumCalendarInfoA> 
extern __imp_EnumCalendarInfoExA:qword 
EnumCalendarInfoEx TEXTEQU <__imp_EnumCalendarInfoExA> 
extern __imp_EnumCalendarInfoExEx:qword 
EnumCalendarInfoExEx TEXTEQU <__imp_EnumCalendarInfoExEx> 
extern __imp_EnumCalendarInfoExW:qword 
EnumCalendarInfoExW TEXTEQU <__imp_EnumCalendarInfoExW> 
extern __imp_EnumCalendarInfoW:qword 
EnumCalendarInfoW TEXTEQU <__imp_EnumCalendarInfoW> 
extern __imp_EnumDateFormatsA:qword 
EnumDateFormats TEXTEQU <__imp_EnumDateFormatsA> 
extern __imp_EnumDateFormatsExA:qword 
EnumDateFormatsEx TEXTEQU <__imp_EnumDateFormatsExA> 
extern __imp_EnumDateFormatsExEx:qword 
EnumDateFormatsExEx TEXTEQU <__imp_EnumDateFormatsExEx> 
extern __imp_EnumDateFormatsExW:qword 
EnumDateFormatsExW TEXTEQU <__imp_EnumDateFormatsExW> 
extern __imp_EnumDateFormatsW:qword 
EnumDateFormatsW TEXTEQU <__imp_EnumDateFormatsW> 
extern __imp_EnumLanguageGroupLocalesA:qword 
EnumLanguageGroupLocales TEXTEQU <__imp_EnumLanguageGroupLocalesA> 
extern __imp_EnumLanguageGroupLocalesW:qword 
EnumLanguageGroupLocalesW TEXTEQU <__imp_EnumLanguageGroupLocalesW> 
extern __imp_EnumResourceLanguagesA:qword 
EnumResourceLanguages TEXTEQU <__imp_EnumResourceLanguagesA> 
extern __imp_EnumResourceLanguagesExA:qword 
EnumResourceLanguagesEx TEXTEQU <__imp_EnumResourceLanguagesExA> 
extern __imp_EnumResourceLanguagesExW:qword 
EnumResourceLanguagesExW TEXTEQU <__imp_EnumResourceLanguagesExW> 
extern __imp_EnumResourceLanguagesW:qword 
EnumResourceLanguagesW TEXTEQU <__imp_EnumResourceLanguagesW> 
extern __imp_EnumResourceNamesA:qword 
EnumResourceNames TEXTEQU <__imp_EnumResourceNamesA> 
extern __imp_EnumResourceNamesExA:qword 
EnumResourceNamesEx TEXTEQU <__imp_EnumResourceNamesExA> 
extern __imp_EnumResourceNamesExW:qword 
EnumResourceNamesExW TEXTEQU <__imp_EnumResourceNamesExW> 
extern __imp_EnumResourceNamesW:qword 
EnumResourceNamesW TEXTEQU <__imp_EnumResourceNamesW> 
extern __imp_EnumResourceTypesA:qword 
EnumResourceTypes TEXTEQU <__imp_EnumResourceTypesA> 
extern __imp_EnumResourceTypesExA:qword 
EnumResourceTypesEx TEXTEQU <__imp_EnumResourceTypesExA> 
extern __imp_EnumResourceTypesExW:qword 
EnumResourceTypesExW TEXTEQU <__imp_EnumResourceTypesExW> 
extern __imp_EnumResourceTypesW:qword 
EnumResourceTypesW TEXTEQU <__imp_EnumResourceTypesW> 
extern __imp_EnumSystemCodePagesA:qword 
EnumSystemCodePages TEXTEQU <__imp_EnumSystemCodePagesA> 
extern __imp_EnumSystemCodePagesW:qword 
EnumSystemCodePagesW TEXTEQU <__imp_EnumSystemCodePagesW> 
extern __imp_EnumSystemFirmwareTables:qword 
EnumSystemFirmwareTables TEXTEQU <__imp_EnumSystemFirmwareTables> 
extern __imp_EnumSystemGeoID:qword 
EnumSystemGeoID TEXTEQU <__imp_EnumSystemGeoID> 
extern __imp_EnumSystemLanguageGroupsA:qword 
EnumSystemLanguageGroups TEXTEQU <__imp_EnumSystemLanguageGroupsA> 
extern __imp_EnumSystemLanguageGroupsW:qword 
EnumSystemLanguageGroupsW TEXTEQU <__imp_EnumSystemLanguageGroupsW> 
extern __imp_EnumSystemLocalesA:qword 
EnumSystemLocales TEXTEQU <__imp_EnumSystemLocalesA> 
extern __imp_EnumSystemLocalesEx:qword 
EnumSystemLocalesEx TEXTEQU <__imp_EnumSystemLocalesEx> 
extern __imp_EnumSystemLocalesW:qword 
EnumSystemLocalesW TEXTEQU <__imp_EnumSystemLocalesW> 
extern __imp_EnumTimeFormatsA:qword 
EnumTimeFormats TEXTEQU <__imp_EnumTimeFormatsA> 
extern __imp_EnumTimeFormatsEx:qword 
EnumTimeFormatsEx TEXTEQU <__imp_EnumTimeFormatsEx> 
extern __imp_EnumTimeFormatsW:qword 
EnumTimeFormatsW TEXTEQU <__imp_EnumTimeFormatsW> 
extern __imp_EnumUILanguagesA:qword 
EnumUILanguages TEXTEQU <__imp_EnumUILanguagesA> 
extern __imp_EnumUILanguagesW:qword 
EnumUILanguagesW TEXTEQU <__imp_EnumUILanguagesW> 
extern __imp_EnumerateLocalComputerNamesA:qword 
EnumerateLocalComputerNames TEXTEQU <__imp_EnumerateLocalComputerNamesA> 
extern __imp_EnumerateLocalComputerNamesW:qword 
EnumerateLocalComputerNamesW TEXTEQU <__imp_EnumerateLocalComputerNamesW> 
extern __imp_EraseTape:qword 
EraseTape TEXTEQU <__imp_EraseTape> 
extern __imp_EscapeCommFunction:qword 
EscapeCommFunction TEXTEQU <__imp_EscapeCommFunction> 
extern __imp_ExecuteUmsThread:qword 
ExecuteUmsThread TEXTEQU <__imp_ExecuteUmsThread> 
extern __imp_ExitVDM:qword 
ExitVDM TEXTEQU <__imp_ExitVDM> 
extern __imp_ExpandEnvironmentStringsA:qword 
ExpandEnvironmentStrings TEXTEQU <__imp_ExpandEnvironmentStringsA> 
extern __imp_ExpandEnvironmentStringsW:qword 
ExpandEnvironmentStringsW TEXTEQU <__imp_ExpandEnvironmentStringsW> 
extern __imp_ExpungeConsoleCommandHistoryA:qword 
ExpungeConsoleCommandHistory TEXTEQU <__imp_ExpungeConsoleCommandHistoryA> 
extern __imp_ExpungeConsoleCommandHistoryW:qword 
ExpungeConsoleCommandHistoryW TEXTEQU <__imp_ExpungeConsoleCommandHistoryW> 
extern __imp_FatalAppExitA:qword 
FatalAppExit TEXTEQU <__imp_FatalAppExitA> 
extern __imp_FatalAppExitW:qword 
FatalAppExitW TEXTEQU <__imp_FatalAppExitW> 
extern __imp_FatalExit:qword 
FatalExit TEXTEQU <__imp_FatalExit> 
extern __imp_FileTimeToDosDateTime:qword 
FileTimeToDosDateTime TEXTEQU <__imp_FileTimeToDosDateTime> 
extern __imp_FileTimeToLocalFileTime:qword 
FileTimeToLocalFileTime TEXTEQU <__imp_FileTimeToLocalFileTime> 
extern __imp_FileTimeToSystemTime:qword 
FileTimeToSystemTime TEXTEQU <__imp_FileTimeToSystemTime> 
extern __imp_FillConsoleOutputAttribute:qword 
FillConsoleOutputAttribute TEXTEQU <__imp_FillConsoleOutputAttribute> 
extern __imp_FillConsoleOutputCharacterA:qword 
FillConsoleOutputCharacter TEXTEQU <__imp_FillConsoleOutputCharacterA> 
extern __imp_FillConsoleOutputCharacterW:qword 
FillConsoleOutputCharacterW TEXTEQU <__imp_FillConsoleOutputCharacterW> 
extern __imp_FindActCtxSectionGuid:qword 
FindActCtxSectionGuid TEXTEQU <__imp_FindActCtxSectionGuid> 
extern __imp_FindActCtxSectionStringA:qword 
FindActCtxSectionString TEXTEQU <__imp_FindActCtxSectionStringA> 
extern __imp_FindActCtxSectionStringW:qword 
FindActCtxSectionStringW TEXTEQU <__imp_FindActCtxSectionStringW> 
extern __imp_FindAtomA:qword 
FindAtom TEXTEQU <__imp_FindAtomA> 
extern __imp_FindAtomW:qword 
FindAtomW TEXTEQU <__imp_FindAtomW> 
extern __imp_FindClose:qword 
FindClose TEXTEQU <__imp_FindClose> 
extern __imp_FindCloseChangeNotification:qword 
FindCloseChangeNotification TEXTEQU <__imp_FindCloseChangeNotification> 
extern __imp_FindFirstChangeNotificationA:qword 
FindFirstChangeNotification TEXTEQU <__imp_FindFirstChangeNotificationA> 
extern __imp_FindFirstChangeNotificationW:qword 
FindFirstChangeNotificationW TEXTEQU <__imp_FindFirstChangeNotificationW> 
extern __imp_FindFirstFileA:qword 
FindFirstFile TEXTEQU <__imp_FindFirstFileA> 
extern __imp_FindFirstFileExA:qword 
FindFirstFileEx TEXTEQU <__imp_FindFirstFileExA> 
extern __imp_FindFirstFileExW:qword 
FindFirstFileExW TEXTEQU <__imp_FindFirstFileExW> 
extern __imp_FindFirstFileNameTransactedW:qword 
FindFirstFileNameTransactedW TEXTEQU <__imp_FindFirstFileNameTransactedW> 
extern __imp_FindFirstFileNameW:qword 
FindFirstFileNameW TEXTEQU <__imp_FindFirstFileNameW> 
extern __imp_FindFirstFileTransactedA:qword 
FindFirstFileTransacted TEXTEQU <__imp_FindFirstFileTransactedA> 
extern __imp_FindFirstFileTransactedW:qword 
FindFirstFileTransactedW TEXTEQU <__imp_FindFirstFileTransactedW> 
extern __imp_FindFirstFileW:qword 
FindFirstFileW TEXTEQU <__imp_FindFirstFileW> 
extern __imp_FindFirstStreamTransactedW:qword 
FindFirstStreamTransactedW TEXTEQU <__imp_FindFirstStreamTransactedW> 
extern __imp_FindFirstStreamW:qword 
FindFirstStreamW TEXTEQU <__imp_FindFirstStreamW> 
extern __imp_FindFirstVolumeA:qword 
FindFirstVolume TEXTEQU <__imp_FindFirstVolumeA> 
extern __imp_FindFirstVolumeMountPointA:qword 
FindFirstVolumeMountPoint TEXTEQU <__imp_FindFirstVolumeMountPointA> 
extern __imp_FindFirstVolumeMountPointW:qword 
FindFirstVolumeMountPointW TEXTEQU <__imp_FindFirstVolumeMountPointW> 
extern __imp_FindFirstVolumeW:qword 
FindFirstVolumeW TEXTEQU <__imp_FindFirstVolumeW> 
extern __imp_FindNLSString:qword 
FindNLSString TEXTEQU <__imp_FindNLSString> 
extern __imp_FindNLSStringEx:qword 
FindNLSStringEx TEXTEQU <__imp_FindNLSStringEx> 
extern __imp_FindNextChangeNotification:qword 
FindNextChangeNotification TEXTEQU <__imp_FindNextChangeNotification> 
extern __imp_FindNextFileA:qword 
FindNextFile TEXTEQU <__imp_FindNextFileA> 
extern __imp_FindNextFileNameW:qword 
FindNextFileNameW TEXTEQU <__imp_FindNextFileNameW> 
extern __imp_FindNextFileW:qword 
FindNextFileW TEXTEQU <__imp_FindNextFileW> 
extern __imp_FindNextStreamW:qword 
FindNextStreamW TEXTEQU <__imp_FindNextStreamW> 
extern __imp_FindNextVolumeA:qword 
FindNextVolume TEXTEQU <__imp_FindNextVolumeA> 
extern __imp_FindNextVolumeMountPointA:qword 
FindNextVolumeMountPoint TEXTEQU <__imp_FindNextVolumeMountPointA> 
extern __imp_FindNextVolumeMountPointW:qword 
FindNextVolumeMountPointW TEXTEQU <__imp_FindNextVolumeMountPointW> 
extern __imp_FindNextVolumeW:qword 
FindNextVolumeW TEXTEQU <__imp_FindNextVolumeW> 
extern __imp_FindResourceA:qword 
FindResource TEXTEQU <__imp_FindResourceA> 
extern __imp_FindResourceExA:qword 
FindResourceEx TEXTEQU <__imp_FindResourceExA> 
extern __imp_FindResourceExW:qword 
FindResourceExW TEXTEQU <__imp_FindResourceExW> 
extern __imp_FindResourceW:qword 
FindResourceW TEXTEQU <__imp_FindResourceW> 
extern __imp_FindStringOrdinal:qword 
FindStringOrdinal TEXTEQU <__imp_FindStringOrdinal> 
extern __imp_FindVolumeClose:qword 
FindVolumeClose TEXTEQU <__imp_FindVolumeClose> 
extern __imp_FindVolumeMountPointClose:qword 
FindVolumeMountPointClose TEXTEQU <__imp_FindVolumeMountPointClose> 
extern __imp_FlsAlloc:qword 
FlsAlloc TEXTEQU <__imp_FlsAlloc> 
extern __imp_FlsFree:qword 
FlsFree TEXTEQU <__imp_FlsFree> 
extern __imp_FlsGetValue:qword 
FlsGetValue TEXTEQU <__imp_FlsGetValue> 
extern __imp_FlsSetValue:qword 
FlsSetValue TEXTEQU <__imp_FlsSetValue> 
extern __imp_FlushConsoleInputBuffer:qword 
FlushConsoleInputBuffer TEXTEQU <__imp_FlushConsoleInputBuffer> 
extern __imp_FlushFileBuffers:qword 
FlushFileBuffers TEXTEQU <__imp_FlushFileBuffers> 
extern __imp_FlushInstructionCache:qword 
FlushInstructionCache TEXTEQU <__imp_FlushInstructionCache> 
extern __imp_FlushViewOfFile:qword 
FlushViewOfFile TEXTEQU <__imp_FlushViewOfFile> 
extern __imp_FoldStringA:qword 
FoldString TEXTEQU <__imp_FoldStringA> 
extern __imp_FoldStringW:qword 
FoldStringW TEXTEQU <__imp_FoldStringW> 
extern __imp_FormatMessageA:qword 
FormatMessage TEXTEQU <__imp_FormatMessageA> 
extern __imp_FormatMessageW:qword 
FormatMessageW TEXTEQU <__imp_FormatMessageW> 
extern __imp_FreeConsole:qword 
FreeConsole TEXTEQU <__imp_FreeConsole> 
extern __imp_FreeEnvironmentStringsA:qword 
FreeEnvironmentStrings TEXTEQU <__imp_FreeEnvironmentStringsA> 
extern __imp_FreeEnvironmentStringsW:qword 
FreeEnvironmentStringsW TEXTEQU <__imp_FreeEnvironmentStringsW> 
extern __imp_FreeLibrary:qword 
FreeLibrary TEXTEQU <__imp_FreeLibrary> 
extern __imp_FreeLibraryAndExitThread:qword 
FreeLibraryAndExitThread TEXTEQU <__imp_FreeLibraryAndExitThread> 
extern __imp_FreeResource:qword 
FreeResource TEXTEQU <__imp_FreeResource> 
extern __imp_FreeUserPhysicalPages:qword 
FreeUserPhysicalPages TEXTEQU <__imp_FreeUserPhysicalPages> 
extern __imp_GenerateConsoleCtrlEvent:qword 
GenerateConsoleCtrlEvent TEXTEQU <__imp_GenerateConsoleCtrlEvent> 
extern __imp_GetACP:qword 
GetACP TEXTEQU <__imp_GetACP> 
extern __imp_GetActiveProcessorCount:qword 
GetActiveProcessorCount TEXTEQU <__imp_GetActiveProcessorCount> 
extern __imp_GetActiveProcessorGroupCount:qword 
GetActiveProcessorGroupCount TEXTEQU <__imp_GetActiveProcessorGroupCount> 
extern __imp_GetApplicationRecoveryCallback:qword 
GetApplicationRecoveryCallback TEXTEQU <__imp_GetApplicationRecoveryCallback> 
extern __imp_GetApplicationRestartSettings:qword 
GetApplicationRestartSettings TEXTEQU <__imp_GetApplicationRestartSettings> 
extern __imp_GetAtomNameA:qword 
GetAtomName TEXTEQU <__imp_GetAtomNameA> 
extern __imp_GetAtomNameW:qword 
GetAtomNameW TEXTEQU <__imp_GetAtomNameW> 
extern __imp_GetBinaryType:qword 
GetBinaryType TEXTEQU <__imp_GetBinaryType> 
extern __imp_GetBinaryTypeA:qword 
GetBinaryType TEXTEQU <__imp_GetBinaryTypeA> 
extern __imp_GetBinaryTypeW:qword 
GetBinaryTypeW TEXTEQU <__imp_GetBinaryTypeW> 
extern __imp_GetCPInfo:qword 
GetCPInfo TEXTEQU <__imp_GetCPInfo> 
extern __imp_GetCPInfoExA:qword 
GetCPInfoEx TEXTEQU <__imp_GetCPInfoExA> 
extern __imp_GetCPInfoExW:qword 
GetCPInfoExW TEXTEQU <__imp_GetCPInfoExW> 
extern __imp_GetCalendarDateFormat:qword 
GetCalendarDateFormat TEXTEQU <__imp_GetCalendarDateFormat> 
extern __imp_GetCalendarDateFormatEx:qword 
GetCalendarDateFormatEx TEXTEQU <__imp_GetCalendarDateFormatEx> 
extern __imp_GetCalendarDaysInMonth:qword 
GetCalendarDaysInMonth TEXTEQU <__imp_GetCalendarDaysInMonth> 
extern __imp_GetCalendarDifferenceInDays:qword 
GetCalendarDifferenceInDays TEXTEQU <__imp_GetCalendarDifferenceInDays> 
extern __imp_GetCalendarInfoA:qword 
GetCalendarInfo TEXTEQU <__imp_GetCalendarInfoA> 
extern __imp_GetCalendarInfoEx:qword 
GetCalendarInfoEx TEXTEQU <__imp_GetCalendarInfoEx> 
extern __imp_GetCalendarInfoW:qword 
GetCalendarInfoW TEXTEQU <__imp_GetCalendarInfoW> 
extern __imp_GetCalendarMonthsInYear:qword 
GetCalendarMonthsInYear TEXTEQU <__imp_GetCalendarMonthsInYear> 
extern __imp_GetCalendarSupportedDateRange:qword 
GetCalendarSupportedDateRange TEXTEQU <__imp_GetCalendarSupportedDateRange> 
extern __imp_GetCalendarWeekNumber:qword 
GetCalendarWeekNumber TEXTEQU <__imp_GetCalendarWeekNumber> 
extern __imp_GetComPlusPackageInstallStatus:qword 
GetComPlusPackageInstallStatus TEXTEQU <__imp_GetComPlusPackageInstallStatus> 
extern __imp_GetCommConfig:qword 
GetCommConfig TEXTEQU <__imp_GetCommConfig> 
extern __imp_GetCommMask:qword 
GetCommMask TEXTEQU <__imp_GetCommMask> 
extern __imp_GetCommModemStatus:qword 
GetCommModemStatus TEXTEQU <__imp_GetCommModemStatus> 
extern __imp_GetCommProperties:qword 
GetCommProperties TEXTEQU <__imp_GetCommProperties> 
extern __imp_GetCommState:qword 
GetCommState TEXTEQU <__imp_GetCommState> 
extern __imp_GetCommTimeouts:qword 
GetCommTimeouts TEXTEQU <__imp_GetCommTimeouts> 
extern __imp_GetCommandLineA:qword 
GetCommandLine TEXTEQU <__imp_GetCommandLineA> 
extern __imp_GetCommandLineW:qword 
GetCommandLineW TEXTEQU <__imp_GetCommandLineW> 
extern __imp_GetCompressedFileSizeA:qword 
GetCompressedFileSize TEXTEQU <__imp_GetCompressedFileSizeA> 
extern __imp_GetCompressedFileSizeTransactedA:qword 
GetCompressedFileSizeTransacted TEXTEQU <__imp_GetCompressedFileSizeTransactedA> 
extern __imp_GetCompressedFileSizeTransactedW:qword 
GetCompressedFileSizeTransactedW TEXTEQU <__imp_GetCompressedFileSizeTransactedW> 
extern __imp_GetCompressedFileSizeW:qword 
GetCompressedFileSizeW TEXTEQU <__imp_GetCompressedFileSizeW> 
extern __imp_GetComputerNameA:qword 
GetComputerName TEXTEQU <__imp_GetComputerNameA> 
extern __imp_GetComputerNameExA:qword 
GetComputerNameEx TEXTEQU <__imp_GetComputerNameExA> 
extern __imp_GetComputerNameExW:qword 
GetComputerNameExW TEXTEQU <__imp_GetComputerNameExW> 
extern __imp_GetComputerNameW:qword 
GetComputerNameW TEXTEQU <__imp_GetComputerNameW> 
extern __imp_GetConsoleAliasA:qword 
GetConsoleAlias TEXTEQU <__imp_GetConsoleAliasA> 
extern __imp_GetConsoleAliasExesA:qword 
GetConsoleAliasExes TEXTEQU <__imp_GetConsoleAliasExesA> 
extern __imp_GetConsoleAliasExesLengthA:qword 
GetConsoleAliasExesLength TEXTEQU <__imp_GetConsoleAliasExesLengthA> 
extern __imp_GetConsoleAliasExesLengthW:qword 
GetConsoleAliasExesLengthW TEXTEQU <__imp_GetConsoleAliasExesLengthW> 
extern __imp_GetConsoleAliasExesW:qword 
GetConsoleAliasExesW TEXTEQU <__imp_GetConsoleAliasExesW> 
extern __imp_GetConsoleAliasW:qword 
GetConsoleAliasW TEXTEQU <__imp_GetConsoleAliasW> 
extern __imp_GetConsoleAliasesA:qword 
GetConsoleAliases TEXTEQU <__imp_GetConsoleAliasesA> 
extern __imp_GetConsoleAliasesLengthA:qword 
GetConsoleAliasesLength TEXTEQU <__imp_GetConsoleAliasesLengthA> 
extern __imp_GetConsoleAliasesLengthW:qword 
GetConsoleAliasesLengthW TEXTEQU <__imp_GetConsoleAliasesLengthW> 
extern __imp_GetConsoleAliasesW:qword 
GetConsoleAliasesW TEXTEQU <__imp_GetConsoleAliasesW> 
extern __imp_GetConsoleCP:qword 
GetConsoleCP TEXTEQU <__imp_GetConsoleCP> 
extern __imp_GetConsoleCharType:qword 
GetConsoleCharType TEXTEQU <__imp_GetConsoleCharType> 
extern __imp_GetConsoleCommandHistoryA:qword 
GetConsoleCommandHistory TEXTEQU <__imp_GetConsoleCommandHistoryA> 
extern __imp_GetConsoleCommandHistoryLengthA:qword 
GetConsoleCommandHistoryLength TEXTEQU <__imp_GetConsoleCommandHistoryLengthA> 
extern __imp_GetConsoleCommandHistoryLengthW:qword 
GetConsoleCommandHistoryLengthW TEXTEQU <__imp_GetConsoleCommandHistoryLengthW> 
extern __imp_GetConsoleCommandHistoryW:qword 
GetConsoleCommandHistoryW TEXTEQU <__imp_GetConsoleCommandHistoryW> 
extern __imp_GetConsoleCursorInfo:qword 
GetConsoleCursorInfo TEXTEQU <__imp_GetConsoleCursorInfo> 
extern __imp_GetConsoleCursorMode:qword 
GetConsoleCursorMode TEXTEQU <__imp_GetConsoleCursorMode> 
extern __imp_GetConsoleDisplayMode:qword 
GetConsoleDisplayMode TEXTEQU <__imp_GetConsoleDisplayMode> 
extern __imp_GetConsoleFontInfo:qword 
GetConsoleFontInfo TEXTEQU <__imp_GetConsoleFontInfo> 
extern __imp_GetConsoleFontSize:qword 
GetConsoleFontSize TEXTEQU <__imp_GetConsoleFontSize> 
extern __imp_GetConsoleHardwareState:qword 
GetConsoleHardwareState TEXTEQU <__imp_GetConsoleHardwareState> 
extern __imp_GetConsoleHistoryInfo:qword 
GetConsoleHistoryInfo TEXTEQU <__imp_GetConsoleHistoryInfo> 
extern __imp_GetConsoleInputExeNameA:qword 
GetConsoleInputExeName TEXTEQU <__imp_GetConsoleInputExeNameA> 
extern __imp_GetConsoleInputExeNameW:qword 
GetConsoleInputExeNameW TEXTEQU <__imp_GetConsoleInputExeNameW> 
extern __imp_GetConsoleInputWaitHandle:qword 
GetConsoleInputWaitHandle TEXTEQU <__imp_GetConsoleInputWaitHandle> 
extern __imp_GetConsoleKeyboardLayoutNameA:qword 
GetConsoleKeyboardLayoutName TEXTEQU <__imp_GetConsoleKeyboardLayoutNameA> 
extern __imp_GetConsoleKeyboardLayoutNameW:qword 
GetConsoleKeyboardLayoutNameW TEXTEQU <__imp_GetConsoleKeyboardLayoutNameW> 
extern __imp_GetConsoleMode:qword 
GetConsoleMode TEXTEQU <__imp_GetConsoleMode> 
extern __imp_GetConsoleNlsMode:qword 
GetConsoleNlsMode TEXTEQU <__imp_GetConsoleNlsMode> 
extern __imp_GetConsoleOriginalTitleA:qword 
GetConsoleOriginalTitle TEXTEQU <__imp_GetConsoleOriginalTitleA> 
extern __imp_GetConsoleOriginalTitleW:qword 
GetConsoleOriginalTitleW TEXTEQU <__imp_GetConsoleOriginalTitleW> 
extern __imp_GetConsoleOutputCP:qword 
GetConsoleOutputCP TEXTEQU <__imp_GetConsoleOutputCP> 
extern __imp_GetConsoleProcessList:qword 
GetConsoleProcessList TEXTEQU <__imp_GetConsoleProcessList> 
extern __imp_GetConsoleScreenBufferInfo:qword 
GetConsoleScreenBufferInfo TEXTEQU <__imp_GetConsoleScreenBufferInfo> 
extern __imp_GetConsoleScreenBufferInfoEx:qword 
GetConsoleScreenBufferInfoEx TEXTEQU <__imp_GetConsoleScreenBufferInfoEx> 
extern __imp_GetConsoleSelectionInfo:qword 
GetConsoleSelectionInfo TEXTEQU <__imp_GetConsoleSelectionInfo> 
extern __imp_GetConsoleTitleA:qword 
GetConsoleTitle TEXTEQU <__imp_GetConsoleTitleA> 
extern __imp_GetConsoleTitleW:qword 
GetConsoleTitleW TEXTEQU <__imp_GetConsoleTitleW> 
extern __imp_GetConsoleWindow:qword 
GetConsoleWindow TEXTEQU <__imp_GetConsoleWindow> 
extern __imp_GetCurrencyFormatA:qword 
GetCurrencyFormat TEXTEQU <__imp_GetCurrencyFormatA> 
extern __imp_GetCurrencyFormatEx:qword 
GetCurrencyFormatEx TEXTEQU <__imp_GetCurrencyFormatEx> 
extern __imp_GetCurrencyFormatW:qword 
GetCurrencyFormatW TEXTEQU <__imp_GetCurrencyFormatW> 
extern __imp_GetCurrentActCtx:qword 
GetCurrentActCtx TEXTEQU <__imp_GetCurrentActCtx> 
extern __imp_GetCurrentConsoleFont:qword 
GetCurrentConsoleFont TEXTEQU <__imp_GetCurrentConsoleFont> 
extern __imp_GetCurrentConsoleFontEx:qword 
GetCurrentConsoleFontEx TEXTEQU <__imp_GetCurrentConsoleFontEx> 
extern __imp_GetCurrentDirectoryA:qword 
GetCurrentDirectory TEXTEQU <__imp_GetCurrentDirectoryA> 
extern __imp_GetCurrentDirectoryW:qword 
GetCurrentDirectoryW TEXTEQU <__imp_GetCurrentDirectoryW> 
extern __imp_GetCurrentProcess:qword 
GetCurrentProcess TEXTEQU <__imp_GetCurrentProcess> 
extern __imp_GetCurrentProcessId:qword 
GetCurrentProcessId TEXTEQU <__imp_GetCurrentProcessId> 
extern __imp_GetCurrentThread:qword 
GetCurrentThread TEXTEQU <__imp_GetCurrentThread> 
extern __imp_GetCurrentThreadId:qword 
GetCurrentThreadId TEXTEQU <__imp_GetCurrentThreadId> 
extern __imp_GetCurrentUmsThread:qword 
GetCurrentUmsThread TEXTEQU <__imp_GetCurrentUmsThread> 
extern __imp_GetDateFormatA:qword 
GetDateFormat TEXTEQU <__imp_GetDateFormatA> 
extern __imp_GetDateFormatEx:qword 
GetDateFormatEx TEXTEQU <__imp_GetDateFormatEx> 
extern __imp_GetDateFormatW:qword 
GetDateFormatW TEXTEQU <__imp_GetDateFormatW> 
extern __imp_GetDefaultCommConfigA:qword 
GetDefaultCommConfig TEXTEQU <__imp_GetDefaultCommConfigA> 
extern __imp_GetDefaultCommConfigW:qword 
GetDefaultCommConfigW TEXTEQU <__imp_GetDefaultCommConfigW> 
extern __imp_GetDevicePowerState:qword 
GetDevicePowerState TEXTEQU <__imp_GetDevicePowerState> 
extern __imp_GetDiskFreeSpaceA:qword 
GetDiskFreeSpace TEXTEQU <__imp_GetDiskFreeSpaceA> 
extern __imp_GetDiskFreeSpaceExA:qword 
GetDiskFreeSpaceEx TEXTEQU <__imp_GetDiskFreeSpaceExA> 
extern __imp_GetDiskFreeSpaceExW:qword 
GetDiskFreeSpaceExW TEXTEQU <__imp_GetDiskFreeSpaceExW> 
extern __imp_GetDiskFreeSpaceW:qword 
GetDiskFreeSpaceW TEXTEQU <__imp_GetDiskFreeSpaceW> 
extern __imp_GetDllDirectoryA:qword 
GetDllDirectory TEXTEQU <__imp_GetDllDirectoryA> 
extern __imp_GetDllDirectoryW:qword 
GetDllDirectoryW TEXTEQU <__imp_GetDllDirectoryW> 
extern __imp_GetDriveTypeA:qword 
GetDriveType TEXTEQU <__imp_GetDriveTypeA> 
extern __imp_GetDriveTypeW:qword 
GetDriveTypeW TEXTEQU <__imp_GetDriveTypeW> 
extern __imp_GetDurationFormat:qword 
GetDurationFormat TEXTEQU <__imp_GetDurationFormat> 
extern __imp_GetDurationFormatEx:qword 
GetDurationFormatEx TEXTEQU <__imp_GetDurationFormatEx> 
extern __imp_GetDynamicTimeZoneInformation:qword 
GetDynamicTimeZoneInformation TEXTEQU <__imp_GetDynamicTimeZoneInformation> 
extern __imp_GetEnabledXStateFeatures:qword 
GetEnabledXStateFeatures TEXTEQU <__imp_GetEnabledXStateFeatures> 
extern __imp_GetEnvironmentStrings:qword 
GetEnvironmentStrings TEXTEQU <__imp_GetEnvironmentStrings> 
extern __imp_GetEnvironmentStringsA:qword 
GetEnvironmentStrings TEXTEQU <__imp_GetEnvironmentStringsA> 
extern __imp_GetEnvironmentStringsW:qword 
GetEnvironmentStringsW TEXTEQU <__imp_GetEnvironmentStringsW> 
extern __imp_GetEnvironmentVariableA:qword 
GetEnvironmentVariable TEXTEQU <__imp_GetEnvironmentVariableA> 
extern __imp_GetEnvironmentVariableW:qword 
GetEnvironmentVariableW TEXTEQU <__imp_GetEnvironmentVariableW> 
extern __imp_GetEraNameCountedString:qword 
GetEraNameCountedString TEXTEQU <__imp_GetEraNameCountedString> 
extern __imp_GetErrorMode:qword 
GetErrorMode TEXTEQU <__imp_GetErrorMode> 
extern __imp_GetExitCodeProcess:qword 
GetExitCodeProcess TEXTEQU <__imp_GetExitCodeProcess> 
extern __imp_GetExitCodeThread:qword 
GetExitCodeThread TEXTEQU <__imp_GetExitCodeThread> 
extern __imp_GetExpandedNameA:qword 
GetExpandedName TEXTEQU <__imp_GetExpandedNameA> 
extern __imp_GetExpandedNameW:qword 
GetExpandedNameW TEXTEQU <__imp_GetExpandedNameW> 
extern __imp_GetFileAttributesA:qword 
GetFileAttributes TEXTEQU <__imp_GetFileAttributesA> 
extern __imp_GetFileAttributesExA:qword 
GetFileAttributesEx TEXTEQU <__imp_GetFileAttributesExA> 
extern __imp_GetFileAttributesExW:qword 
GetFileAttributesExW TEXTEQU <__imp_GetFileAttributesExW> 
extern __imp_GetFileAttributesTransactedA:qword 
GetFileAttributesTransacted TEXTEQU <__imp_GetFileAttributesTransactedA> 
extern __imp_GetFileAttributesTransactedW:qword 
GetFileAttributesTransactedW TEXTEQU <__imp_GetFileAttributesTransactedW> 
extern __imp_GetFileAttributesW:qword 
GetFileAttributesW TEXTEQU <__imp_GetFileAttributesW> 
extern __imp_GetFileBandwidthReservation:qword 
GetFileBandwidthReservation TEXTEQU <__imp_GetFileBandwidthReservation> 
extern __imp_GetFileInformationByHandle:qword 
GetFileInformationByHandle TEXTEQU <__imp_GetFileInformationByHandle> 
extern __imp_GetFileInformationByHandleEx:qword 
GetFileInformationByHandleEx TEXTEQU <__imp_GetFileInformationByHandleEx> 
extern __imp_GetFileMUIInfo:qword 
GetFileMUIInfo TEXTEQU <__imp_GetFileMUIInfo> 
extern __imp_GetFileMUIPath:qword 
GetFileMUIPath TEXTEQU <__imp_GetFileMUIPath> 
extern __imp_GetFileSize:qword 
GetFileSize TEXTEQU <__imp_GetFileSize> 
extern __imp_GetFileSizeEx:qword 
GetFileSizeEx TEXTEQU <__imp_GetFileSizeEx> 
extern __imp_GetFileTime:qword 
GetFileTime TEXTEQU <__imp_GetFileTime> 
extern __imp_GetFileType:qword 
GetFileType TEXTEQU <__imp_GetFileType> 
extern __imp_GetFinalPathNameByHandleA:qword 
GetFinalPathNameByHandle TEXTEQU <__imp_GetFinalPathNameByHandleA> 
extern __imp_GetFinalPathNameByHandleW:qword 
GetFinalPathNameByHandleW TEXTEQU <__imp_GetFinalPathNameByHandleW> 
extern __imp_GetFirmwareEnvironmentVariableA:qword 
GetFirmwareEnvironmentVariable TEXTEQU <__imp_GetFirmwareEnvironmentVariableA> 
extern __imp_GetFirmwareEnvironmentVariableW:qword 
GetFirmwareEnvironmentVariableW TEXTEQU <__imp_GetFirmwareEnvironmentVariableW> 
extern __imp_GetFullPathNameA:qword 
GetFullPathName TEXTEQU <__imp_GetFullPathNameA> 
extern __imp_GetFullPathNameTransactedA:qword 
GetFullPathNameTransacted TEXTEQU <__imp_GetFullPathNameTransactedA> 
extern __imp_GetFullPathNameTransactedW:qword 
GetFullPathNameTransactedW TEXTEQU <__imp_GetFullPathNameTransactedW> 
extern __imp_GetFullPathNameW:qword 
GetFullPathNameW TEXTEQU <__imp_GetFullPathNameW> 
extern __imp_GetGeoInfoA:qword 
GetGeoInfo TEXTEQU <__imp_GetGeoInfoA> 
extern __imp_GetGeoInfoW:qword 
GetGeoInfoW TEXTEQU <__imp_GetGeoInfoW> 
extern __imp_GetHandleInformation:qword 
GetHandleInformation TEXTEQU <__imp_GetHandleInformation> 
extern __imp_GetLargePageMinimum:qword 
GetLargePageMinimum TEXTEQU <__imp_GetLargePageMinimum> 
extern __imp_GetLargestConsoleWindowSize:qword 
GetLargestConsoleWindowSize TEXTEQU <__imp_GetLargestConsoleWindowSize> 
extern __imp_GetLastError:qword 
GetLastError TEXTEQU <__imp_GetLastError> 
extern __imp_GetLocalTime:qword 
GetLocalTime TEXTEQU <__imp_GetLocalTime> 
extern __imp_GetLocaleInfoA:qword 
GetLocaleInfo TEXTEQU <__imp_GetLocaleInfoA> 
extern __imp_GetLocaleInfoEx:qword 
GetLocaleInfoEx TEXTEQU <__imp_GetLocaleInfoEx> 
extern __imp_GetLocaleInfoW:qword 
GetLocaleInfoW TEXTEQU <__imp_GetLocaleInfoW> 
extern __imp_GetLogicalDriveStringsA:qword 
GetLogicalDriveStrings TEXTEQU <__imp_GetLogicalDriveStringsA> 
extern __imp_GetLogicalDriveStringsW:qword 
GetLogicalDriveStringsW TEXTEQU <__imp_GetLogicalDriveStringsW> 
extern __imp_GetLogicalDrives:qword 
GetLogicalDrives TEXTEQU <__imp_GetLogicalDrives> 
extern __imp_GetLogicalProcessorInformation:qword 
GetLogicalProcessorInformation TEXTEQU <__imp_GetLogicalProcessorInformation> 
extern __imp_GetLongPathNameA:qword 
GetLongPathName TEXTEQU <__imp_GetLongPathNameA> 
extern __imp_GetLongPathNameTransactedA:qword 
GetLongPathNameTransacted TEXTEQU <__imp_GetLongPathNameTransactedA> 
extern __imp_GetLongPathNameTransactedW:qword 
GetLongPathNameTransactedW TEXTEQU <__imp_GetLongPathNameTransactedW> 
extern __imp_GetLongPathNameW:qword 
GetLongPathNameW TEXTEQU <__imp_GetLongPathNameW> 
extern __imp_GetMailslotInfo:qword 
GetMailslotInfo TEXTEQU <__imp_GetMailslotInfo> 
extern __imp_GetMaximumProcessorCount:qword 
GetMaximumProcessorCount TEXTEQU <__imp_GetMaximumProcessorCount> 
extern __imp_GetMaximumProcessorGroupCount:qword 
GetMaximumProcessorGroupCount TEXTEQU <__imp_GetMaximumProcessorGroupCount> 
extern __imp_GetModuleFileNameA:qword 
GetModuleFileName TEXTEQU <__imp_GetModuleFileNameA> 
extern __imp_GetModuleFileNameW:qword 
GetModuleFileNameW TEXTEQU <__imp_GetModuleFileNameW> 
extern __imp_GetModuleHandleA:qword 
GetModuleHandle TEXTEQU <__imp_GetModuleHandleA> 
extern __imp_GetModuleHandleExA:qword 
GetModuleHandleEx TEXTEQU <__imp_GetModuleHandleExA> 
extern __imp_GetModuleHandleExW:qword 
GetModuleHandleExW TEXTEQU <__imp_GetModuleHandleExW> 
extern __imp_GetModuleHandleW:qword 
GetModuleHandleW TEXTEQU <__imp_GetModuleHandleW> 
extern __imp_GetNLSVersion:qword 
GetNLSVersion TEXTEQU <__imp_GetNLSVersion> 
extern __imp_GetNLSVersionEx:qword 
GetNLSVersionEx TEXTEQU <__imp_GetNLSVersionEx> 
extern __imp_GetNamedPipeAttribute:qword 
GetNamedPipeAttribute TEXTEQU <__imp_GetNamedPipeAttribute> 
extern __imp_GetNamedPipeClientComputerNameA:qword 
GetNamedPipeClientComputerName TEXTEQU <__imp_GetNamedPipeClientComputerNameA> 
extern __imp_GetNamedPipeClientComputerNameW:qword 
GetNamedPipeClientComputerNameW TEXTEQU <__imp_GetNamedPipeClientComputerNameW> 
extern __imp_GetNamedPipeClientProcessId:qword 
GetNamedPipeClientProcessId TEXTEQU <__imp_GetNamedPipeClientProcessId> 
extern __imp_GetNamedPipeClientSessionId:qword 
GetNamedPipeClientSessionId TEXTEQU <__imp_GetNamedPipeClientSessionId> 
extern __imp_GetNamedPipeHandleStateA:qword 
GetNamedPipeHandleState TEXTEQU <__imp_GetNamedPipeHandleStateA> 
extern __imp_GetNamedPipeHandleStateW:qword 
GetNamedPipeHandleStateW TEXTEQU <__imp_GetNamedPipeHandleStateW> 
extern __imp_GetNamedPipeInfo:qword 
GetNamedPipeInfo TEXTEQU <__imp_GetNamedPipeInfo> 
extern __imp_GetNamedPipeServerProcessId:qword 
GetNamedPipeServerProcessId TEXTEQU <__imp_GetNamedPipeServerProcessId> 
extern __imp_GetNamedPipeServerSessionId:qword 
GetNamedPipeServerSessionId TEXTEQU <__imp_GetNamedPipeServerSessionId> 
extern __imp_GetNativeSystemInfo:qword 
GetNativeSystemInfo TEXTEQU <__imp_GetNativeSystemInfo> 
extern __imp_GetNextUmsListItem:qword 
GetNextUmsListItem TEXTEQU <__imp_GetNextUmsListItem> 
extern __imp_GetNextVDMCommand:qword 
GetNextVDMCommand TEXTEQU <__imp_GetNextVDMCommand> 
extern __imp_GetNumaAvailableMemoryNode:qword 
GetNumaAvailableMemoryNode TEXTEQU <__imp_GetNumaAvailableMemoryNode> 
extern __imp_GetNumaAvailableMemoryNodeEx:qword 
GetNumaAvailableMemoryNodeEx TEXTEQU <__imp_GetNumaAvailableMemoryNodeEx> 
extern __imp_GetNumaHighestNodeNumber:qword 
GetNumaHighestNodeNumber TEXTEQU <__imp_GetNumaHighestNodeNumber> 
extern __imp_GetNumaNodeNumberFromHandle:qword 
GetNumaNodeNumberFromHandle TEXTEQU <__imp_GetNumaNodeNumberFromHandle> 
extern __imp_GetNumaNodeProcessorMask:qword 
GetNumaNodeProcessorMask TEXTEQU <__imp_GetNumaNodeProcessorMask> 
extern __imp_GetNumaNodeProcessorMaskEx:qword 
GetNumaNodeProcessorMaskEx TEXTEQU <__imp_GetNumaNodeProcessorMaskEx> 
extern __imp_GetNumaProcessorNode:qword 
GetNumaProcessorNode TEXTEQU <__imp_GetNumaProcessorNode> 
extern __imp_GetNumaProcessorNodeEx:qword 
GetNumaProcessorNodeEx TEXTEQU <__imp_GetNumaProcessorNodeEx> 
extern __imp_GetNumaProximityNode:qword 
GetNumaProximityNode TEXTEQU <__imp_GetNumaProximityNode> 
extern __imp_GetNumaProximityNodeEx:qword 
GetNumaProximityNodeEx TEXTEQU <__imp_GetNumaProximityNodeEx> 
extern __imp_GetNumberFormatA:qword 
GetNumberFormat TEXTEQU <__imp_GetNumberFormatA> 
extern __imp_GetNumberFormatEx:qword 
GetNumberFormatEx TEXTEQU <__imp_GetNumberFormatEx> 
extern __imp_GetNumberFormatW:qword 
GetNumberFormatW TEXTEQU <__imp_GetNumberFormatW> 
extern __imp_GetNumberOfConsoleFonts:qword 
GetNumberOfConsoleFonts TEXTEQU <__imp_GetNumberOfConsoleFonts> 
extern __imp_GetNumberOfConsoleInputEvents:qword 
GetNumberOfConsoleInputEvents TEXTEQU <__imp_GetNumberOfConsoleInputEvents> 
extern __imp_GetNumberOfConsoleMouseButtons:qword 
GetNumberOfConsoleMouseButtons TEXTEQU <__imp_GetNumberOfConsoleMouseButtons> 
extern __imp_GetOEMCP:qword 
GetOEMCP TEXTEQU <__imp_GetOEMCP> 
extern __imp_GetOverlappedResult:qword 
GetOverlappedResult TEXTEQU <__imp_GetOverlappedResult> 
extern __imp_GetPhysicallyInstalledSystemMemory:qword 
GetPhysicallyInstalledSystemMemory TEXTEQU <__imp_GetPhysicallyInstalledSystemMemory> 
extern __imp_GetPriorityClass:qword 
GetPriorityClass TEXTEQU <__imp_GetPriorityClass> 
extern __imp_GetPrivateProfileIntA:qword 
GetPrivateProfileInt TEXTEQU <__imp_GetPrivateProfileIntA> 
extern __imp_GetPrivateProfileIntW:qword 
GetPrivateProfileIntW TEXTEQU <__imp_GetPrivateProfileIntW> 
extern __imp_GetPrivateProfileSectionA:qword 
GetPrivateProfileSection TEXTEQU <__imp_GetPrivateProfileSectionA> 
extern __imp_GetPrivateProfileSectionNamesA:qword 
GetPrivateProfileSectionNames TEXTEQU <__imp_GetPrivateProfileSectionNamesA> 
extern __imp_GetPrivateProfileSectionNamesW:qword 
GetPrivateProfileSectionNamesW TEXTEQU <__imp_GetPrivateProfileSectionNamesW> 
extern __imp_GetPrivateProfileSectionW:qword 
GetPrivateProfileSectionW TEXTEQU <__imp_GetPrivateProfileSectionW> 
extern __imp_GetPrivateProfileStringA:qword 
GetPrivateProfileString TEXTEQU <__imp_GetPrivateProfileStringA> 
extern __imp_GetPrivateProfileStringW:qword 
GetPrivateProfileStringW TEXTEQU <__imp_GetPrivateProfileStringW> 
extern __imp_GetPrivateProfileStructA:qword 
GetPrivateProfileStruct TEXTEQU <__imp_GetPrivateProfileStructA> 
extern __imp_GetPrivateProfileStructW:qword 
GetPrivateProfileStructW TEXTEQU <__imp_GetPrivateProfileStructW> 
extern __imp_GetProcAddress:qword 
GetProcAddress TEXTEQU <__imp_GetProcAddress> 
extern __imp_GetProcessAffinityMask:qword 
GetProcessAffinityMask TEXTEQU <__imp_GetProcessAffinityMask> 
extern __imp_GetProcessDEPPolicy:qword 
GetProcessDEPPolicy TEXTEQU <__imp_GetProcessDEPPolicy> 
extern __imp_GetProcessGroupAffinity:qword 
GetProcessGroupAffinity TEXTEQU <__imp_GetProcessGroupAffinity> 
extern __imp_GetProcessHandleCount:qword 
GetProcessHandleCount TEXTEQU <__imp_GetProcessHandleCount> 
extern __imp_GetProcessHeap:qword 
GetProcessHeap TEXTEQU <__imp_GetProcessHeap> 
extern __imp_GetProcessHeaps:qword 
GetProcessHeaps TEXTEQU <__imp_GetProcessHeaps> 
extern __imp_GetProcessId:qword 
GetProcessId TEXTEQU <__imp_GetProcessId> 
extern __imp_GetProcessIdOfThread:qword 
GetProcessIdOfThread TEXTEQU <__imp_GetProcessIdOfThread> 
extern __imp_GetProcessIoCounters:qword 
GetProcessIoCounters TEXTEQU <__imp_GetProcessIoCounters> 
extern __imp_GetProcessPreferredUILanguages:qword 
GetProcessPreferredUILanguages TEXTEQU <__imp_GetProcessPreferredUILanguages> 
extern __imp_GetProcessPriorityBoost:qword 
GetProcessPriorityBoost TEXTEQU <__imp_GetProcessPriorityBoost> 
extern __imp_GetProcessShutdownParameters:qword 
GetProcessShutdownParameters TEXTEQU <__imp_GetProcessShutdownParameters> 
extern __imp_GetProcessTimes:qword 
GetProcessTimes TEXTEQU <__imp_GetProcessTimes> 
extern __imp_GetProcessUserModeExceptionPolicy:qword 
GetProcessUserModeExceptionPolicy TEXTEQU <__imp_GetProcessUserModeExceptionPolicy> 
extern __imp_GetProcessVersion:qword 
GetProcessVersion TEXTEQU <__imp_GetProcessVersion> 
extern __imp_GetProcessWorkingSetSize:qword 
GetProcessWorkingSetSize TEXTEQU <__imp_GetProcessWorkingSetSize> 
extern __imp_GetProcessWorkingSetSizeEx:qword 
GetProcessWorkingSetSizeEx TEXTEQU <__imp_GetProcessWorkingSetSizeEx> 
extern __imp_GetProcessorSystemCycleTime:qword 
GetProcessorSystemCycleTime TEXTEQU <__imp_GetProcessorSystemCycleTime> 
extern __imp_GetProductInfo:qword 
GetProductInfo TEXTEQU <__imp_GetProductInfo> 
extern __imp_GetProfileIntA:qword 
GetProfileInt TEXTEQU <__imp_GetProfileIntA> 
extern __imp_GetProfileIntW:qword 
GetProfileIntW TEXTEQU <__imp_GetProfileIntW> 
extern __imp_GetProfileSectionA:qword 
GetProfileSection TEXTEQU <__imp_GetProfileSectionA> 
extern __imp_GetProfileSectionW:qword 
GetProfileSectionW TEXTEQU <__imp_GetProfileSectionW> 
extern __imp_GetProfileStringA:qword 
GetProfileString TEXTEQU <__imp_GetProfileStringA> 
extern __imp_GetProfileStringW:qword 
GetProfileStringW TEXTEQU <__imp_GetProfileStringW> 
extern __imp_GetQueuedCompletionStatus:qword 
GetQueuedCompletionStatus TEXTEQU <__imp_GetQueuedCompletionStatus> 
extern __imp_GetQueuedCompletionStatusEx:qword 
GetQueuedCompletionStatusEx TEXTEQU <__imp_GetQueuedCompletionStatusEx> 
extern __imp_GetShortPathNameA:qword 
GetShortPathName TEXTEQU <__imp_GetShortPathNameA> 
extern __imp_GetShortPathNameW:qword 
GetShortPathNameW TEXTEQU <__imp_GetShortPathNameW> 
extern __imp_GetStartupInfoA:qword 
GetStartupInfo TEXTEQU <__imp_GetStartupInfoA> 
extern __imp_GetStartupInfoW:qword 
GetStartupInfoW TEXTEQU <__imp_GetStartupInfoW> 
extern __imp_GetStdHandle:qword 
GetStdHandle TEXTEQU <__imp_GetStdHandle> 
extern __imp_GetStringScripts:qword 
GetStringScripts TEXTEQU <__imp_GetStringScripts> 
extern __imp_GetStringTypeA:qword 
GetStringType TEXTEQU <__imp_GetStringTypeA> 
extern __imp_GetStringTypeExA:qword 
GetStringTypeEx TEXTEQU <__imp_GetStringTypeExA> 
extern __imp_GetStringTypeExW:qword 
GetStringTypeExW TEXTEQU <__imp_GetStringTypeExW> 
extern __imp_GetStringTypeW:qword 
GetStringTypeW TEXTEQU <__imp_GetStringTypeW> 
extern __imp_GetSystemDEPPolicy:qword 
GetSystemDEPPolicy TEXTEQU <__imp_GetSystemDEPPolicy> 
extern __imp_GetSystemDefaultLCID:qword 
GetSystemDefaultLCID TEXTEQU <__imp_GetSystemDefaultLCID> 
extern __imp_GetSystemDefaultLangID:qword 
GetSystemDefaultLangID TEXTEQU <__imp_GetSystemDefaultLangID> 
extern __imp_GetSystemDefaultLocaleName:qword 
GetSystemDefaultLocaleName TEXTEQU <__imp_GetSystemDefaultLocaleName> 
extern __imp_GetSystemDefaultUILanguage:qword 
GetSystemDefaultUILanguage TEXTEQU <__imp_GetSystemDefaultUILanguage> 
extern __imp_GetSystemDirectoryA:qword 
GetSystemDirectory TEXTEQU <__imp_GetSystemDirectoryA> 
extern __imp_GetSystemDirectoryW:qword 
GetSystemDirectoryW TEXTEQU <__imp_GetSystemDirectoryW> 
extern __imp_GetSystemFileCacheSize:qword 
GetSystemFileCacheSize TEXTEQU <__imp_GetSystemFileCacheSize> 
extern __imp_GetSystemFirmwareTable:qword 
GetSystemFirmwareTable TEXTEQU <__imp_GetSystemFirmwareTable> 
extern __imp_GetSystemInfo:qword 
GetSystemInfo TEXTEQU <__imp_GetSystemInfo> 
extern __imp_GetSystemPowerStatus:qword 
GetSystemPowerStatus TEXTEQU <__imp_GetSystemPowerStatus> 
extern __imp_GetSystemPreferredUILanguages:qword 
GetSystemPreferredUILanguages TEXTEQU <__imp_GetSystemPreferredUILanguages> 
extern __imp_GetSystemRegistryQuota:qword 
GetSystemRegistryQuot TEXTEQU <__imp_GetSystemRegistryQuota> 
extern __imp_GetSystemTime:qword 
GetSystemTime TEXTEQU <__imp_GetSystemTime> 
extern __imp_GetSystemTimeAdjustment:qword 
GetSystemTimeAdjustment TEXTEQU <__imp_GetSystemTimeAdjustment> 
extern __imp_GetSystemTimeAsFileTime:qword 
GetSystemTimeAsFileTime TEXTEQU <__imp_GetSystemTimeAsFileTime> 
extern __imp_GetSystemTimes:qword 
GetSystemTimes TEXTEQU <__imp_GetSystemTimes> 
extern __imp_GetSystemWindowsDirectoryA:qword 
GetSystemWindowsDirectory TEXTEQU <__imp_GetSystemWindowsDirectoryA> 
extern __imp_GetSystemWindowsDirectoryW:qword 
GetSystemWindowsDirectoryW TEXTEQU <__imp_GetSystemWindowsDirectoryW> 
extern __imp_GetSystemWow64DirectoryA:qword 
GetSystemWow64Directory TEXTEQU <__imp_GetSystemWow64DirectoryA> 
extern __imp_GetSystemWow64DirectoryW:qword 
GetSystemWow64DirectoryW TEXTEQU <__imp_GetSystemWow64DirectoryW> 
extern __imp_GetTapeParameters:qword 
GetTapeParameters TEXTEQU <__imp_GetTapeParameters> 
extern __imp_GetTapePosition:qword 
GetTapePosition TEXTEQU <__imp_GetTapePosition> 
extern __imp_GetTapeStatus:qword 
GetTapeStatus TEXTEQU <__imp_GetTapeStatus> 
extern __imp_GetTempFileNameA:qword 
GetTempFileName TEXTEQU <__imp_GetTempFileNameA> 
extern __imp_GetTempFileNameW:qword 
GetTempFileNameW TEXTEQU <__imp_GetTempFileNameW> 
extern __imp_GetTempPathA:qword 
GetTempPath TEXTEQU <__imp_GetTempPathA> 
extern __imp_GetTempPathW:qword 
GetTempPathW TEXTEQU <__imp_GetTempPathW> 
extern __imp_GetThreadContext:qword 
GetThreadContext TEXTEQU <__imp_GetThreadContext> 
extern __imp_GetThreadErrorMode:qword 
GetThreadErrorMode TEXTEQU <__imp_GetThreadErrorMode> 
extern __imp_GetThreadGroupAffinity:qword 
GetThreadGroupAffinity TEXTEQU <__imp_GetThreadGroupAffinity> 
extern __imp_GetThreadIOPendingFlag:qword 
GetThreadIOPendingFlag TEXTEQU <__imp_GetThreadIOPendingFlag> 
extern __imp_GetThreadId:qword 
GetThreadId TEXTEQU <__imp_GetThreadId> 
extern __imp_GetThreadIdealProcessorEx:qword 
GetThreadIdealProcessorEx TEXTEQU <__imp_GetThreadIdealProcessorEx> 
extern __imp_GetThreadLocale:qword 
GetThreadLocale TEXTEQU <__imp_GetThreadLocale> 
extern __imp_GetThreadPreferredUILanguages:qword 
GetThreadPreferredUILanguages TEXTEQU <__imp_GetThreadPreferredUILanguages> 
extern __imp_GetThreadPriority:qword 
GetThreadPriority TEXTEQU <__imp_GetThreadPriority> 
extern __imp_GetThreadPriorityBoost:qword 
GetThreadPriorityBoost TEXTEQU <__imp_GetThreadPriorityBoost> 
extern __imp_GetThreadSelectorEntry:qword 
GetThreadSelectorEntry TEXTEQU <__imp_GetThreadSelectorEntry> 
extern __imp_GetThreadTimes:qword 
GetThreadTimes TEXTEQU <__imp_GetThreadTimes> 
extern __imp_GetThreadUILanguage:qword 
GetThreadUILanguage TEXTEQU <__imp_GetThreadUILanguage> 
extern __imp_GetTickCount:qword 
GetTickCount TEXTEQU <__imp_GetTickCount> 
extern __imp_GetTickCount64:qword 
GetTickCount64 TEXTEQU <__imp_GetTickCount64> 
extern __imp_GetTimeFormatA:qword 
GetTimeFormat TEXTEQU <__imp_GetTimeFormatA> 
extern __imp_GetTimeFormatEx:qword 
GetTimeFormatEx TEXTEQU <__imp_GetTimeFormatEx> 
extern __imp_GetTimeFormatW:qword 
GetTimeFormatW TEXTEQU <__imp_GetTimeFormatW> 
extern __imp_GetTimeZoneInformation:qword 
GetTimeZoneInformation TEXTEQU <__imp_GetTimeZoneInformation> 
extern __imp_GetTimeZoneInformationForYear:qword 
GetTimeZoneInformationForYear TEXTEQU <__imp_GetTimeZoneInformationForYear> 
extern __imp_GetUILanguageInfo:qword 
GetUILanguageInfo TEXTEQU <__imp_GetUILanguageInfo> 
extern __imp_GetUmsCompletionListEvent:qword 
GetUmsCompletionListEvent TEXTEQU <__imp_GetUmsCompletionListEvent> 
extern __imp_GetUmsSystemThreadInformation:qword 
GetUmsSystemThreadInformation TEXTEQU <__imp_GetUmsSystemThreadInformation> 
extern __imp_GetUserDefaultLCID:qword 
GetUserDefaultLCID TEXTEQU <__imp_GetUserDefaultLCID> 
extern __imp_GetUserDefaultLangID:qword 
GetUserDefaultLangID TEXTEQU <__imp_GetUserDefaultLangID> 
extern __imp_GetUserDefaultLocaleName:qword 
GetUserDefaultLocaleName TEXTEQU <__imp_GetUserDefaultLocaleName> 
extern __imp_GetUserDefaultUILanguage:qword 
GetUserDefaultUILanguage TEXTEQU <__imp_GetUserDefaultUILanguage> 
extern __imp_GetUserGeoID:qword 
GetUserGeoID TEXTEQU <__imp_GetUserGeoID> 
extern __imp_GetUserPreferredUILanguages:qword 
GetUserPreferredUILanguages TEXTEQU <__imp_GetUserPreferredUILanguages> 
extern __imp_GetVDMCurrentDirectories:qword 
GetVDMCurrentDirectories TEXTEQU <__imp_GetVDMCurrentDirectories> 
extern __imp_GetVersion:qword 
GetVersion TEXTEQU <__imp_GetVersion> 
extern __imp_GetVersionExA:qword 
GetVersionEx TEXTEQU <__imp_GetVersionExA> 
extern __imp_GetVersionExW:qword 
GetVersionExW TEXTEQU <__imp_GetVersionExW> 
extern __imp_GetVolumeInformationA:qword 
GetVolumeInformation TEXTEQU <__imp_GetVolumeInformationA> 
extern __imp_GetVolumeInformationByHandleW:qword 
GetVolumeInformationByHandleW TEXTEQU <__imp_GetVolumeInformationByHandleW> 
extern __imp_GetVolumeInformationW:qword 
GetVolumeInformationW TEXTEQU <__imp_GetVolumeInformationW> 
extern __imp_GetVolumeNameForVolumeMountPointA:qword 
GetVolumeNameForVolumeMountPoint TEXTEQU <__imp_GetVolumeNameForVolumeMountPointA> 
extern __imp_GetVolumeNameForVolumeMountPointW:qword 
GetVolumeNameForVolumeMountPointW TEXTEQU <__imp_GetVolumeNameForVolumeMountPointW> 
extern __imp_GetVolumePathNameA:qword 
GetVolumePathName TEXTEQU <__imp_GetVolumePathNameA> 
extern __imp_GetVolumePathNameW:qword 
GetVolumePathNameW TEXTEQU <__imp_GetVolumePathNameW> 
extern __imp_GetVolumePathNamesForVolumeNameA:qword 
GetVolumePathNamesForVolumeName TEXTEQU <__imp_GetVolumePathNamesForVolumeNameA> 
extern __imp_GetVolumePathNamesForVolumeNameW:qword 
GetVolumePathNamesForVolumeNameW TEXTEQU <__imp_GetVolumePathNamesForVolumeNameW> 
extern __imp_GetWindowsDirectoryA:qword 
GetWindowsDirectory TEXTEQU <__imp_GetWindowsDirectoryA> 
extern __imp_GetWindowsDirectoryW:qword 
GetWindowsDirectoryW TEXTEQU <__imp_GetWindowsDirectoryW> 
extern __imp_GetWriteWatch:qword 
GetWriteWatch TEXTEQU <__imp_GetWriteWatch> 
extern __imp_GetXStateFeaturesMask:qword 
GetXStateFeaturesMask TEXTEQU <__imp_GetXStateFeaturesMask> 
extern __imp_GlobalAddAtomA:qword 
GlobalAddAtom TEXTEQU <__imp_GlobalAddAtomA> 
extern __imp_GlobalAddAtomW:qword 
GlobalAddAtomW TEXTEQU <__imp_GlobalAddAtomW> 
extern __imp_GlobalAlloc:qword 
GlobalAlloc TEXTEQU <__imp_GlobalAlloc> 
extern __imp_GlobalCompact:qword 
GlobalCompact TEXTEQU <__imp_GlobalCompact> 
extern __imp_GlobalDeleteAtom:qword 
GlobalDeleteAtom TEXTEQU <__imp_GlobalDeleteAtom> 
extern __imp_GlobalFindAtomA:qword 
GlobalFindAtom TEXTEQU <__imp_GlobalFindAtomA> 
extern __imp_GlobalFindAtomW:qword 
GlobalFindAtomW TEXTEQU <__imp_GlobalFindAtomW> 
extern __imp_GlobalFix:qword 
GlobalFix TEXTEQU <__imp_GlobalFix> 
extern __imp_GlobalFlags:qword 
GlobalFlags TEXTEQU <__imp_GlobalFlags> 
extern __imp_GlobalFree:qword 
GlobalFree TEXTEQU <__imp_GlobalFree> 
extern __imp_GlobalGetAtomNameA:qword 
GlobalGetAtomName TEXTEQU <__imp_GlobalGetAtomNameA> 
extern __imp_GlobalGetAtomNameW:qword 
GlobalGetAtomNameW TEXTEQU <__imp_GlobalGetAtomNameW> 
extern __imp_GlobalHandle:qword 
GlobalHandle TEXTEQU <__imp_GlobalHandle> 
extern __imp_GlobalLock:qword 
GlobalLock TEXTEQU <__imp_GlobalLock> 
extern __imp_GlobalMemoryStatus:qword 
GlobalMemoryStatus TEXTEQU <__imp_GlobalMemoryStatus> 
extern __imp_GlobalMemoryStatusEx:qword 
GlobalMemoryStatusEx TEXTEQU <__imp_GlobalMemoryStatusEx> 
extern __imp_GlobalReAlloc:qword 
GlobalReAlloc TEXTEQU <__imp_GlobalReAlloc> 
extern __imp_GlobalSize:qword 
GlobalSize TEXTEQU <__imp_GlobalSize> 
extern __imp_GlobalUnWire:qword 
GlobalUnWire TEXTEQU <__imp_GlobalUnWire> 
extern __imp_GlobalUnfix:qword 
GlobalUnfix TEXTEQU <__imp_GlobalUnfix> 
extern __imp_GlobalUnlock:qword 
GlobalUnlock TEXTEQU <__imp_GlobalUnlock> 
extern __imp_GlobalWire:qword 
GlobalWire TEXTEQU <__imp_GlobalWire> 
extern __imp_Heap32First:qword 
Heap32First TEXTEQU <__imp_Heap32First> 
extern __imp_Heap32ListFirst:qword 
Heap32ListFirst TEXTEQU <__imp_Heap32ListFirst> 
extern __imp_Heap32ListNext:qword 
Heap32ListNext TEXTEQU <__imp_Heap32ListNext> 
extern __imp_Heap32Next:qword 
Heap32Next TEXTEQU <__imp_Heap32Next> 
extern __imp_HeapCompact:qword 
HeapCompact TEXTEQU <__imp_HeapCompact> 
extern __imp_HeapCreate:qword 
HeapCreate TEXTEQU <__imp_HeapCreate> 
extern __imp_HeapDestroy:qword 
HeapDestroy TEXTEQU <__imp_HeapDestroy> 
extern __imp_HeapFree:qword 
HeapFree TEXTEQU <__imp_HeapFree> 
extern __imp_HeapLock:qword 
HeapLock TEXTEQU <__imp_HeapLock> 
extern __imp_HeapQueryInformation:qword 
HeapQueryInformation TEXTEQU <__imp_HeapQueryInformation> 
extern __imp_HeapSetInformation:qword 
HeapSetInformation TEXTEQU <__imp_HeapSetInformation> 
extern __imp_HeapSummary:qword 
HeapSummary TEXTEQU <__imp_HeapSummary> 
extern __imp_HeapUnlock:qword 
HeapUnlock TEXTEQU <__imp_HeapUnlock> 
extern __imp_HeapValidate:qword 
HeapValidate TEXTEQU <__imp_HeapValidate> 
extern __imp_HeapWalk:qword 
HeapWalk TEXTEQU <__imp_HeapWalk> 
extern __imp_IdnToAscii:qword 
IdnToAscii TEXTEQU <__imp_IdnToAscii> 
extern __imp_IdnToNameprepUnicode:qword 
IdnToNameprepUnicode TEXTEQU <__imp_IdnToNameprepUnicode> 
extern __imp_IdnToUnicode:qword 
IdnToUnicode TEXTEQU <__imp_IdnToUnicode> 
extern __imp_InitAtomTable:qword 
InitAtomTable TEXTEQU <__imp_InitAtomTable> 
extern __imp_InitOnceBeginInitialize:qword 
InitOnceBeginInitialize TEXTEQU <__imp_InitOnceBeginInitialize> 
extern __imp_InitOnceComplete:qword 
InitOnceComplete TEXTEQU <__imp_InitOnceComplete> 
extern __imp_InitOnceExecuteOnce:qword 
InitOnceExecuteOnce TEXTEQU <__imp_InitOnceExecuteOnce> 
extern __imp_InitializeContext:qword 
InitializeContext TEXTEQU <__imp_InitializeContext> 
extern __imp_InitializeCriticalSectionAndSpinCount:qword 
InitializeCriticalSectionAndSpinCount TEXTEQU <__imp_InitializeCriticalSectionAndSpinCount> 
extern __imp_InitializeCriticalSectionEx:qword 
InitializeCriticalSectionEx TEXTEQU <__imp_InitializeCriticalSectionEx> 
extern __imp_InvalidateConsoleDIBits:qword 
InvalidateConsoleDIBits TEXTEQU <__imp_InvalidateConsoleDIBits> 
extern __imp_IsBadCodePtr:qword 
IsBadCodePtr TEXTEQU <__imp_IsBadCodePtr> 
extern __imp_IsBadHugeReadPtr:qword 
IsBadHugeReadPtr TEXTEQU <__imp_IsBadHugeReadPtr> 
extern __imp_IsBadHugeWritePtr:qword 
IsBadHugeWritePtr TEXTEQU <__imp_IsBadHugeWritePtr> 
extern __imp_IsBadReadPtr:qword 
IsBadReadPtr TEXTEQU <__imp_IsBadReadPtr> 
extern __imp_IsBadStringPtrA:qword 
IsBadStringPtr TEXTEQU <__imp_IsBadStringPtrA> 
extern __imp_IsBadStringPtrW:qword 
IsBadStringPtrW TEXTEQU <__imp_IsBadStringPtrW> 
extern __imp_IsBadWritePtr:qword 
IsBadWritePtr TEXTEQU <__imp_IsBadWritePtr> 
extern __imp_IsCalendarLeapDay:qword 
IsCalendarLeapDay TEXTEQU <__imp_IsCalendarLeapDay> 
extern __imp_IsCalendarLeapMonth:qword 
IsCalendarLeapMonth TEXTEQU <__imp_IsCalendarLeapMonth> 
extern __imp_IsCalendarLeapYear:qword 
IsCalendarLeapYear TEXTEQU <__imp_IsCalendarLeapYear> 
extern __imp_IsDBCSLeadByte:qword 
IsDBCSLeadByte TEXTEQU <__imp_IsDBCSLeadByte> 
extern __imp_IsDBCSLeadByteEx:qword 
IsDBCSLeadByteEx TEXTEQU <__imp_IsDBCSLeadByteEx> 
extern __imp_IsDebuggerPresent:qword 
IsDebuggerPresent TEXTEQU <__imp_IsDebuggerPresent> 
extern __imp_IsNLSDefinedString:qword 
IsNLSDefinedString TEXTEQU <__imp_IsNLSDefinedString> 
extern __imp_IsNormalizedString:qword 
IsNormalizedString TEXTEQU <__imp_IsNormalizedString> 
extern __imp_IsProcessInJob:qword 
IsProcessInJob TEXTEQU <__imp_IsProcessInJob> 
extern __imp_IsProcessorFeaturePresent:qword 
IsProcessorFeaturePresent TEXTEQU <__imp_IsProcessorFeaturePresent> 
extern __imp_IsSystemResumeAutomatic:qword 
IsSystemResumeAutomatic TEXTEQU <__imp_IsSystemResumeAutomatic> 
extern __imp_IsThreadAFiber:qword 
IsThreadAFiber TEXTEQU <__imp_IsThreadAFiber> 
extern __imp_IsTimeZoneRedirectionEnabled:qword 
IsTimeZoneRedirectionEnabled TEXTEQU <__imp_IsTimeZoneRedirectionEnabled> 
extern __imp_IsValidCalDateTime:qword 
IsValidCalDateTime TEXTEQU <__imp_IsValidCalDateTime> 
extern __imp_IsValidCodePage:qword 
IsValidCodePage TEXTEQU <__imp_IsValidCodePage> 
extern __imp_IsValidLanguageGroup:qword 
IsValidLanguageGroup TEXTEQU <__imp_IsValidLanguageGroup> 
extern __imp_IsValidLocale:qword 
IsValidLocale TEXTEQU <__imp_IsValidLocale> 
extern __imp_IsValidLocaleName:qword 
IsValidLocaleName TEXTEQU <__imp_IsValidLocaleName> 
extern __imp_IsWow64Process:qword 
IsWow64Process TEXTEQU <__imp_IsWow64Process> 
extern __imp_K32EmptyWorkingSet:qword 
K32EmptyWorkingSet TEXTEQU <__imp_K32EmptyWorkingSet> 
extern __imp_K32EnumDeviceDrivers:qword 
K32EnumDeviceDrivers TEXTEQU <__imp_K32EnumDeviceDrivers> 
extern __imp_K32EnumPageFilesA:qword 
K32EnumPageFiles TEXTEQU <__imp_K32EnumPageFilesA> 
extern __imp_K32EnumPageFilesW:qword 
K32EnumPageFilesW TEXTEQU <__imp_K32EnumPageFilesW> 
extern __imp_K32EnumProcessModules:qword 
K32EnumProcessModules TEXTEQU <__imp_K32EnumProcessModules> 
extern __imp_K32EnumProcessModulesEx:qword 
K32EnumProcessModulesEx TEXTEQU <__imp_K32EnumProcessModulesEx> 
extern __imp_K32EnumProcesses:qword 
K32EnumProcesses TEXTEQU <__imp_K32EnumProcesses> 
extern __imp_K32GetDeviceDriverBaseNameA:qword 
K32GetDeviceDriverBaseName TEXTEQU <__imp_K32GetDeviceDriverBaseNameA> 
extern __imp_K32GetDeviceDriverBaseNameW:qword 
K32GetDeviceDriverBaseNameW TEXTEQU <__imp_K32GetDeviceDriverBaseNameW> 
extern __imp_K32GetDeviceDriverFileNameA:qword 
K32GetDeviceDriverFileName TEXTEQU <__imp_K32GetDeviceDriverFileNameA> 
extern __imp_K32GetDeviceDriverFileNameW:qword 
K32GetDeviceDriverFileNameW TEXTEQU <__imp_K32GetDeviceDriverFileNameW> 
extern __imp_K32GetMappedFileNameA:qword 
K32GetMappedFileName TEXTEQU <__imp_K32GetMappedFileNameA> 
extern __imp_K32GetMappedFileNameW:qword 
K32GetMappedFileNameW TEXTEQU <__imp_K32GetMappedFileNameW> 
extern __imp_K32GetModuleBaseNameA:qword 
K32GetModuleBaseName TEXTEQU <__imp_K32GetModuleBaseNameA> 
extern __imp_K32GetModuleBaseNameW:qword 
K32GetModuleBaseNameW TEXTEQU <__imp_K32GetModuleBaseNameW> 
extern __imp_K32GetModuleFileNameExA:qword 
K32GetModuleFileNameEx TEXTEQU <__imp_K32GetModuleFileNameExA> 
extern __imp_K32GetModuleFileNameExW:qword 
K32GetModuleFileNameExW TEXTEQU <__imp_K32GetModuleFileNameExW> 
extern __imp_K32GetModuleInformation:qword 
K32GetModuleInformation TEXTEQU <__imp_K32GetModuleInformation> 
extern __imp_K32GetPerformanceInfo:qword 
K32GetPerformanceInfo TEXTEQU <__imp_K32GetPerformanceInfo> 
extern __imp_K32GetProcessImageFileNameA:qword 
K32GetProcessImageFileName TEXTEQU <__imp_K32GetProcessImageFileNameA> 
extern __imp_K32GetProcessImageFileNameW:qword 
K32GetProcessImageFileNameW TEXTEQU <__imp_K32GetProcessImageFileNameW> 
extern __imp_K32GetProcessMemoryInfo:qword 
K32GetProcessMemoryInfo TEXTEQU <__imp_K32GetProcessMemoryInfo> 
extern __imp_K32GetWsChanges:qword 
K32GetWsChanges TEXTEQU <__imp_K32GetWsChanges> 
extern __imp_K32GetWsChangesEx:qword 
K32GetWsChangesEx TEXTEQU <__imp_K32GetWsChangesEx> 
extern __imp_K32InitializeProcessForWsWatch:qword 
K32InitializeProcessForWsWatch TEXTEQU <__imp_K32InitializeProcessForWsWatch> 
extern __imp_K32QueryWorkingSet:qword 
K32QueryWorkingSet TEXTEQU <__imp_K32QueryWorkingSet> 
extern __imp_K32QueryWorkingSetEx:qword 
K32QueryWorkingSetEx TEXTEQU <__imp_K32QueryWorkingSetEx> 
extern __imp_LCIDToLocaleName:qword 
LCIDToLocaleName TEXTEQU <__imp_LCIDToLocaleName> 
extern __imp_LCMapStringA:qword 
LCMapString TEXTEQU <__imp_LCMapStringA> 
extern __imp_LCMapStringEx:qword 
LCMapStringEx TEXTEQU <__imp_LCMapStringEx> 
extern __imp_LCMapStringW:qword 
LCMapStringW TEXTEQU <__imp_LCMapStringW> 
extern __imp_LZClose:qword 
LZClose TEXTEQU <__imp_LZClose> 
extern __imp_LZCloseFile:qword 
LZCloseFile TEXTEQU <__imp_LZCloseFile> 
extern __imp_LZCopy:qword 
LZCopy TEXTEQU <__imp_LZCopy> 
extern __imp_LZCreateFileW:qword 
LZCreateFileW TEXTEQU <__imp_LZCreateFileW> 
extern __imp_LZDone:qword 
LZDone TEXTEQU <__imp_LZDone> 
extern __imp_LZInit:qword 
LZInit TEXTEQU <__imp_LZInit> 
extern __imp_LZOpenFileA:qword 
LZOpenFile TEXTEQU <__imp_LZOpenFileA> 
extern __imp_LZOpenFileW:qword 
LZOpenFileW TEXTEQU <__imp_LZOpenFileW> 
extern __imp_LZRead:qword 
LZRead TEXTEQU <__imp_LZRead> 
extern __imp_LZSeek:qword 
LZSeek TEXTEQU <__imp_LZSeek> 
extern __imp_LZStart:qword 
LZStart TEXTEQU <__imp_LZStart> 
extern __imp_LoadAppInitDlls:qword 
LoadAppInitDlls TEXTEQU <__imp_LoadAppInitDlls> 
extern __imp_LoadLibraryA:qword 
LoadLibrary TEXTEQU <__imp_LoadLibraryA> 
extern __imp_LoadLibraryExA:qword 
LoadLibraryEx TEXTEQU <__imp_LoadLibraryExA> 
extern __imp_LoadLibraryExW:qword 
LoadLibraryExW TEXTEQU <__imp_LoadLibraryExW> 
extern __imp_LoadLibraryW:qword 
LoadLibraryW TEXTEQU <__imp_LoadLibraryW> 
extern __imp_LoadModule:qword 
LoadModule TEXTEQU <__imp_LoadModule> 
extern __imp_LoadResource:qword 
LoadResource TEXTEQU <__imp_LoadResource> 
extern __imp_LoadStringBaseExW:qword 
LoadStringBaseExW TEXTEQU <__imp_LoadStringBaseExW> 
extern __imp_LoadStringBaseW:qword 
LoadStringBaseW TEXTEQU <__imp_LoadStringBaseW> 
extern __imp_LocalAlloc:qword 
LocalAlloc TEXTEQU <__imp_LocalAlloc> 
extern __imp_LocalCompact:qword 
LocalCompact TEXTEQU <__imp_LocalCompact> 
extern __imp_LocalFileTimeToFileTime:qword 
LocalFileTimeToFileTime TEXTEQU <__imp_LocalFileTimeToFileTime> 
extern __imp_LocalFlags:qword 
LocalFlags TEXTEQU <__imp_LocalFlags> 
extern __imp_LocalFree:qword 
LocalFree TEXTEQU <__imp_LocalFree> 
extern __imp_LocalHandle:qword 
LocalHandle TEXTEQU <__imp_LocalHandle> 
extern __imp_LocalLock:qword 
LocalLock TEXTEQU <__imp_LocalLock> 
extern __imp_LocalReAlloc:qword 
LocalReAlloc TEXTEQU <__imp_LocalReAlloc> 
extern __imp_LocalShrink:qword 
LocalShrink TEXTEQU <__imp_LocalShrink> 
extern __imp_LocalSize:qword 
LocalSize TEXTEQU <__imp_LocalSize> 
extern __imp_LocalUnlock:qword 
LocalUnlock TEXTEQU <__imp_LocalUnlock> 
extern __imp_LocaleNameToLCID:qword 
LocaleNameToLCID TEXTEQU <__imp_LocaleNameToLCID> 
extern __imp_LocateXStateFeature:qword 
LocateXStateFeature TEXTEQU <__imp_LocateXStateFeature> 
extern __imp_LockFile:qword 
LockFile TEXTEQU <__imp_LockFile> 
extern __imp_LockFileEx:qword 
LockFileEx TEXTEQU <__imp_LockFileEx> 
extern __imp_LockResource:qword 
LockResource TEXTEQU <__imp_LockResource> 
extern __imp_MapUserPhysicalPages:qword 
MapUserPhysicalPages TEXTEQU <__imp_MapUserPhysicalPages> 
extern __imp_MapUserPhysicalPagesScatter:qword 
MapUserPhysicalPagesScatter TEXTEQU <__imp_MapUserPhysicalPagesScatter> 
extern __imp_MapViewOfFile:qword 
MapViewOfFile TEXTEQU <__imp_MapViewOfFile> 
extern __imp_MapViewOfFileEx:qword 
MapViewOfFileEx TEXTEQU <__imp_MapViewOfFileEx> 
extern __imp_MapViewOfFileExNuma:qword 
MapViewOfFileExNum TEXTEQU <__imp_MapViewOfFileExNuma> 
extern __imp_Module32First:qword 
Module32First TEXTEQU <__imp_Module32First> 
extern __imp_Module32FirstW:qword 
Module32FirstW TEXTEQU <__imp_Module32FirstW> 
extern __imp_Module32Next:qword 
Module32Next TEXTEQU <__imp_Module32Next> 
extern __imp_Module32NextW:qword 
Module32NextW TEXTEQU <__imp_Module32NextW> 
extern __imp_MoveFileA:qword 
MoveFile TEXTEQU <__imp_MoveFileA> 
extern __imp_MoveFileExA:qword 
MoveFileEx TEXTEQU <__imp_MoveFileExA> 
extern __imp_MoveFileExW:qword 
MoveFileExW TEXTEQU <__imp_MoveFileExW> 
extern __imp_MoveFileTransactedA:qword 
MoveFileTransacted TEXTEQU <__imp_MoveFileTransactedA> 
extern __imp_MoveFileTransactedW:qword 
MoveFileTransactedW TEXTEQU <__imp_MoveFileTransactedW> 
extern __imp_MoveFileW:qword 
MoveFileW TEXTEQU <__imp_MoveFileW> 
extern __imp_MoveFileWithProgressA:qword 
MoveFileWithProgress TEXTEQU <__imp_MoveFileWithProgressA> 
extern __imp_MoveFileWithProgressW:qword 
MoveFileWithProgressW TEXTEQU <__imp_MoveFileWithProgressW> 
extern __imp_MulDiv:qword 
MulDiv TEXTEQU <__imp_MulDiv> 
extern __imp_MultiByteToWideChar:qword 
MultiByteToWideChar TEXTEQU <__imp_MultiByteToWideChar> 
extern __imp_NeedCurrentDirectoryForExePathA:qword 
NeedCurrentDirectoryForExePath TEXTEQU <__imp_NeedCurrentDirectoryForExePathA> 
extern __imp_NeedCurrentDirectoryForExePathW:qword 
NeedCurrentDirectoryForExePathW TEXTEQU <__imp_NeedCurrentDirectoryForExePathW> 
extern __imp_NlsCheckPolicy:qword 
NlsCheckPolicy TEXTEQU <__imp_NlsCheckPolicy> 
extern __imp_NlsEventDataDescCreate:qword 
NlsEventDataDescCreate TEXTEQU <__imp_NlsEventDataDescCreate> 
extern __imp_NlsGetCacheUpdateCount:qword 
NlsGetCacheUpdateCount TEXTEQU <__imp_NlsGetCacheUpdateCount> 
extern __imp_NlsUpdateLocale:qword 
NlsUpdateLocale TEXTEQU <__imp_NlsUpdateLocale> 
extern __imp_NlsUpdateSystemLocale:qword 
NlsUpdateSystemLocale TEXTEQU <__imp_NlsUpdateSystemLocale> 
extern __imp_NlsWriteEtwEvent:qword 
NlsWriteEtwEvent TEXTEQU <__imp_NlsWriteEtwEvent> 
extern __imp_NormalizeString:qword 
NormalizeString TEXTEQU <__imp_NormalizeString> 
extern __imp_NotifyMountMgr:qword 
NotifyMountMgr TEXTEQU <__imp_NotifyMountMgr> 
extern __imp_NotifyUILanguageChange:qword 
NotifyUILanguageChange TEXTEQU <__imp_NotifyUILanguageChange> 
extern __imp_OpenConsoleW:qword 
OpenConsoleW TEXTEQU <__imp_OpenConsoleW> 
extern __imp_OpenEventA:qword 
OpenEvent TEXTEQU <__imp_OpenEventA> 
extern __imp_OpenEventW:qword 
OpenEventW TEXTEQU <__imp_OpenEventW> 
extern __imp_OpenFile:qword 
OpenFile TEXTEQU <__imp_OpenFile> 
extern __imp_OpenFileById:qword 
OpenFileById TEXTEQU <__imp_OpenFileById> 
extern __imp_OpenFileMappingA:qword 
OpenFileMapping TEXTEQU <__imp_OpenFileMappingA> 
extern __imp_OpenFileMappingW:qword 
OpenFileMappingW TEXTEQU <__imp_OpenFileMappingW> 
extern __imp_OpenJobObjectA:qword 
OpenJobObject TEXTEQU <__imp_OpenJobObjectA> 
extern __imp_OpenJobObjectW:qword 
OpenJobObjectW TEXTEQU <__imp_OpenJobObjectW> 
extern __imp_OpenMutexA:qword 
OpenMutex TEXTEQU <__imp_OpenMutexA> 
extern __imp_OpenMutexW:qword 
OpenMutexW TEXTEQU <__imp_OpenMutexW> 
extern __imp_OpenPrivateNamespaceA:qword 
OpenPrivateNamespace TEXTEQU <__imp_OpenPrivateNamespaceA> 
extern __imp_OpenPrivateNamespaceW:qword 
OpenPrivateNamespaceW TEXTEQU <__imp_OpenPrivateNamespaceW> 
extern __imp_OpenProcess:qword 
OpenProcess TEXTEQU <__imp_OpenProcess> 
extern __imp_OpenProfileUserMapping:qword 
OpenProfileUserMapping TEXTEQU <__imp_OpenProfileUserMapping> 
extern __imp_OpenSemaphoreA:qword 
OpenSemaphore TEXTEQU <__imp_OpenSemaphoreA> 
extern __imp_OpenSemaphoreW:qword 
OpenSemaphoreW TEXTEQU <__imp_OpenSemaphoreW> 
extern __imp_OpenThread:qword 
OpenThread TEXTEQU <__imp_OpenThread> 
extern __imp_OpenWaitableTimerA:qword 
OpenWaitableTimer TEXTEQU <__imp_OpenWaitableTimerA> 
extern __imp_OpenWaitableTimerW:qword 
OpenWaitableTimerW TEXTEQU <__imp_OpenWaitableTimerW> 
extern __imp_OutputDebugStringA:qword 
OutputDebugString TEXTEQU <__imp_OutputDebugStringA> 
extern __imp_OutputDebugStringW:qword 
OutputDebugStringW TEXTEQU <__imp_OutputDebugStringW> 
extern __imp_PeekConsoleInputA:qword 
PeekConsoleInput TEXTEQU <__imp_PeekConsoleInputA> 
extern __imp_PeekConsoleInputW:qword 
PeekConsoleInputW TEXTEQU <__imp_PeekConsoleInputW> 
extern __imp_PeekNamedPipe:qword 
PeekNamedPipe TEXTEQU <__imp_PeekNamedPipe> 
extern __imp_PostQueuedCompletionStatus:qword 
PostQueuedCompletionStatus TEXTEQU <__imp_PostQueuedCompletionStatus> 
extern __imp_PowerClearRequest:qword 
PowerClearRequest TEXTEQU <__imp_PowerClearRequest> 
extern __imp_PowerCreateRequest:qword 
PowerCreateRequest TEXTEQU <__imp_PowerCreateRequest> 
extern __imp_PowerSetRequest:qword 
PowerSetRequest TEXTEQU <__imp_PowerSetRequest> 
extern __imp_PrepareTape:qword 
PrepareTape TEXTEQU <__imp_PrepareTape> 
extern __imp_PrivCopyFileExW:qword 
PrivCopyFileExW TEXTEQU <__imp_PrivCopyFileExW> 
extern __imp_PrivMoveFileIdentityW:qword 
PrivMoveFileIdentityW TEXTEQU <__imp_PrivMoveFileIdentityW> 
extern __imp_Process32First:qword 
Process32First TEXTEQU <__imp_Process32First> 
extern __imp_Process32FirstW:qword 
Process32FirstW TEXTEQU <__imp_Process32FirstW> 
extern __imp_Process32Next:qword 
Process32Next TEXTEQU <__imp_Process32Next> 
extern __imp_Process32NextW:qword 
Process32NextW TEXTEQU <__imp_Process32NextW> 
extern __imp_ProcessIdToSessionId:qword 
ProcessIdToSessionId TEXTEQU <__imp_ProcessIdToSessionId> 
extern __imp_PulseEvent:qword 
PulseEvent TEXTEQU <__imp_PulseEvent> 
extern __imp_PurgeComm:qword 
PurgeComm TEXTEQU <__imp_PurgeComm> 
extern __imp_QueryActCtxSettingsW:qword 
QueryActCtxSettingsW TEXTEQU <__imp_QueryActCtxSettingsW> 
extern __imp_QueryActCtxW:qword 
QueryActCtxW TEXTEQU <__imp_QueryActCtxW> 
extern __imp_QueryDosDeviceA:qword 
QueryDosDevice TEXTEQU <__imp_QueryDosDeviceA> 
extern __imp_QueryDosDeviceW:qword 
QueryDosDeviceW TEXTEQU <__imp_QueryDosDeviceW> 
extern __imp_QueryFullProcessImageNameA:qword 
QueryFullProcessImageName TEXTEQU <__imp_QueryFullProcessImageNameA> 
extern __imp_QueryFullProcessImageNameW:qword 
QueryFullProcessImageNameW TEXTEQU <__imp_QueryFullProcessImageNameW> 
extern __imp_QueryIdleProcessorCycleTime:qword 
QueryIdleProcessorCycleTime TEXTEQU <__imp_QueryIdleProcessorCycleTime> 
extern __imp_QueryIdleProcessorCycleTimeEx:qword 
QueryIdleProcessorCycleTimeEx TEXTEQU <__imp_QueryIdleProcessorCycleTimeEx> 
extern __imp_QueryInformationJobObject:qword 
QueryInformationJobObject TEXTEQU <__imp_QueryInformationJobObject> 
extern __imp_QueryMemoryResourceNotification:qword 
QueryMemoryResourceNotification TEXTEQU <__imp_QueryMemoryResourceNotification> 
extern __imp_QueryPerformanceCounter:qword 
QueryPerformanceCounter TEXTEQU <__imp_QueryPerformanceCounter> 
extern __imp_QueryPerformanceFrequency:qword 
QueryPerformanceFrequency TEXTEQU <__imp_QueryPerformanceFrequency> 
extern __imp_QueryProcessAffinityUpdateMode:qword 
QueryProcessAffinityUpdateMode TEXTEQU <__imp_QueryProcessAffinityUpdateMode> 
extern __imp_QueryProcessCycleTime:qword 
QueryProcessCycleTime TEXTEQU <__imp_QueryProcessCycleTime> 
extern __imp_QueryThreadCycleTime:qword 
QueryThreadCycleTime TEXTEQU <__imp_QueryThreadCycleTime> 
extern __imp_QueryThreadProfiling:qword 
QueryThreadProfiling TEXTEQU <__imp_QueryThreadProfiling> 
extern __imp_QueryThreadpoolStackInformation:qword 
QueryThreadpoolStackInformation TEXTEQU <__imp_QueryThreadpoolStackInformation> 
extern __imp_QueryUmsThreadInformation:qword 
QueryUmsThreadInformation TEXTEQU <__imp_QueryUmsThreadInformation> 
extern __imp_QueryUnbiasedInterruptTime:qword 
QueryUnbiasedInterruptTime TEXTEQU <__imp_QueryUnbiasedInterruptTime> 
extern __imp_QueueUserAPC:qword 
QueueUserAPC TEXTEQU <__imp_QueueUserAPC> 
extern __imp_QueueUserWorkItem:qword 
QueueUserWorkItem TEXTEQU <__imp_QueueUserWorkItem> 
extern __imp_RaiseException:qword 
RaiseException TEXTEQU <__imp_RaiseException> 
extern __imp_RaiseFailFastException:qword 
RaiseFailFastException TEXTEQU <__imp_RaiseFailFastException> 
extern __imp_ReOpenFile:qword 
ReOpenFile TEXTEQU <__imp_ReOpenFile> 
extern __imp_ReadConsoleA:qword 
ReadConsole TEXTEQU <__imp_ReadConsoleA> 
extern __imp_ReadConsoleInputA:qword 
ReadConsoleInput TEXTEQU <__imp_ReadConsoleInputA> 
extern __imp_ReadConsoleInputExA:qword 
ReadConsoleInputEx TEXTEQU <__imp_ReadConsoleInputExA> 
extern __imp_ReadConsoleInputExW:qword 
ReadConsoleInputExW TEXTEQU <__imp_ReadConsoleInputExW> 
extern __imp_ReadConsoleInputW:qword 
ReadConsoleInputW TEXTEQU <__imp_ReadConsoleInputW> 
extern __imp_ReadConsoleOutputA:qword 
ReadConsoleOutput TEXTEQU <__imp_ReadConsoleOutputA> 
extern __imp_ReadConsoleOutputAttribute:qword 
ReadConsoleOutputAttribute TEXTEQU <__imp_ReadConsoleOutputAttribute> 
extern __imp_ReadConsoleOutputCharacterA:qword 
ReadConsoleOutputCharacter TEXTEQU <__imp_ReadConsoleOutputCharacterA> 
extern __imp_ReadConsoleOutputCharacterW:qword 
ReadConsoleOutputCharacterW TEXTEQU <__imp_ReadConsoleOutputCharacterW> 
extern __imp_ReadConsoleOutputW:qword 
ReadConsoleOutputW TEXTEQU <__imp_ReadConsoleOutputW> 
extern __imp_ReadConsoleW:qword 
ReadConsoleW TEXTEQU <__imp_ReadConsoleW> 
extern __imp_ReadDirectoryChangesW:qword 
ReadDirectoryChangesW TEXTEQU <__imp_ReadDirectoryChangesW> 
extern __imp_ReadFile:qword 
ReadFile TEXTEQU <__imp_ReadFile> 
extern __imp_ReadFileEx:qword 
ReadFileEx TEXTEQU <__imp_ReadFileEx> 
extern __imp_ReadFileScatter:qword 
ReadFileScatter TEXTEQU <__imp_ReadFileScatter> 
extern __imp_ReadProcessMemory:qword 
ReadProcessMemory TEXTEQU <__imp_ReadProcessMemory> 
extern __imp_ReadThreadProfilingData:qword 
ReadThreadProfilingDat TEXTEQU <__imp_ReadThreadProfilingData> 
extern __imp_RegCloseKey:qword 
RegCloseKey TEXTEQU <__imp_RegCloseKey> 
extern __imp_RegCreateKeyExA:qword 
RegCreateKeyEx TEXTEQU <__imp_RegCreateKeyExA> 
extern __imp_RegCreateKeyExW:qword 
RegCreateKeyExW TEXTEQU <__imp_RegCreateKeyExW> 
extern __imp_RegDeleteKeyExA:qword 
RegDeleteKeyEx TEXTEQU <__imp_RegDeleteKeyExA> 
extern __imp_RegDeleteKeyExW:qword 
RegDeleteKeyExW TEXTEQU <__imp_RegDeleteKeyExW> 
extern __imp_RegDeleteTreeA:qword 
RegDeleteTree TEXTEQU <__imp_RegDeleteTreeA> 
extern __imp_RegDeleteTreeW:qword 
RegDeleteTreeW TEXTEQU <__imp_RegDeleteTreeW> 
extern __imp_RegDeleteValueA:qword 
RegDeleteValue TEXTEQU <__imp_RegDeleteValueA> 
extern __imp_RegDeleteValueW:qword 
RegDeleteValueW TEXTEQU <__imp_RegDeleteValueW> 
extern __imp_RegDisablePredefinedCacheEx:qword 
RegDisablePredefinedCacheEx TEXTEQU <__imp_RegDisablePredefinedCacheEx> 
extern __imp_RegEnumKeyExA:qword 
RegEnumKeyEx TEXTEQU <__imp_RegEnumKeyExA> 
extern __imp_RegEnumKeyExW:qword 
RegEnumKeyExW TEXTEQU <__imp_RegEnumKeyExW> 
extern __imp_RegEnumValueA:qword 
RegEnumValue TEXTEQU <__imp_RegEnumValueA> 
extern __imp_RegEnumValueW:qword 
RegEnumValueW TEXTEQU <__imp_RegEnumValueW> 
extern __imp_RegFlushKey:qword 
RegFlushKey TEXTEQU <__imp_RegFlushKey> 
extern __imp_RegGetKeySecurity:qword 
RegGetKeySecurity TEXTEQU <__imp_RegGetKeySecurity> 
extern __imp_RegGetValueA:qword 
RegGetValue TEXTEQU <__imp_RegGetValueA> 
extern __imp_RegGetValueW:qword 
RegGetValueW TEXTEQU <__imp_RegGetValueW> 
extern __imp_RegKrnGetGlobalState:qword 
RegKrnGetGlobalState TEXTEQU <__imp_RegKrnGetGlobalState> 
extern __imp_RegKrnInitialize:qword 
RegKrnInitialize TEXTEQU <__imp_RegKrnInitialize> 
extern __imp_RegLoadKeyA:qword 
RegLoadKey TEXTEQU <__imp_RegLoadKeyA> 
extern __imp_RegLoadKeyW:qword 
RegLoadKeyW TEXTEQU <__imp_RegLoadKeyW> 
extern __imp_RegLoadMUIStringA:qword 
RegLoadMUIString TEXTEQU <__imp_RegLoadMUIStringA> 
extern __imp_RegLoadMUIStringW:qword 
RegLoadMUIStringW TEXTEQU <__imp_RegLoadMUIStringW> 
extern __imp_RegNotifyChangeKeyValue:qword 
RegNotifyChangeKeyValue TEXTEQU <__imp_RegNotifyChangeKeyValue> 
extern __imp_RegOpenCurrentUser:qword 
RegOpenCurrentUser TEXTEQU <__imp_RegOpenCurrentUser> 
extern __imp_RegOpenKeyExA:qword 
RegOpenKeyEx TEXTEQU <__imp_RegOpenKeyExA> 
extern __imp_RegOpenKeyExW:qword 
RegOpenKeyExW TEXTEQU <__imp_RegOpenKeyExW> 
extern __imp_RegOpenUserClassesRoot:qword 
RegOpenUserClassesRoot TEXTEQU <__imp_RegOpenUserClassesRoot> 
extern __imp_RegQueryInfoKeyA:qword 
RegQueryInfoKey TEXTEQU <__imp_RegQueryInfoKeyA> 
extern __imp_RegQueryInfoKeyW:qword 
RegQueryInfoKeyW TEXTEQU <__imp_RegQueryInfoKeyW> 
extern __imp_RegQueryValueExA:qword 
RegQueryValueEx TEXTEQU <__imp_RegQueryValueExA> 
extern __imp_RegQueryValueExW:qword 
RegQueryValueExW TEXTEQU <__imp_RegQueryValueExW> 
extern __imp_RegRestoreKeyA:qword 
RegRestoreKey TEXTEQU <__imp_RegRestoreKeyA> 
extern __imp_RegRestoreKeyW:qword 
RegRestoreKeyW TEXTEQU <__imp_RegRestoreKeyW> 
extern __imp_RegSaveKeyExA:qword 
RegSaveKeyEx TEXTEQU <__imp_RegSaveKeyExA> 
extern __imp_RegSaveKeyExW:qword 
RegSaveKeyExW TEXTEQU <__imp_RegSaveKeyExW> 
extern __imp_RegSetKeySecurity:qword 
RegSetKeySecurity TEXTEQU <__imp_RegSetKeySecurity> 
extern __imp_RegSetValueExA:qword 
RegSetValueEx TEXTEQU <__imp_RegSetValueExA> 
extern __imp_RegSetValueExW:qword 
RegSetValueExW TEXTEQU <__imp_RegSetValueExW> 
extern __imp_RegUnLoadKeyA:qword 
RegUnLoadKey TEXTEQU <__imp_RegUnLoadKeyA> 
extern __imp_RegUnLoadKeyW:qword 
RegUnLoadKeyW TEXTEQU <__imp_RegUnLoadKeyW> 
extern __imp_RegisterApplicationRecoveryCallback:qword 
RegisterApplicationRecoveryCallback TEXTEQU <__imp_RegisterApplicationRecoveryCallback> 
extern __imp_RegisterApplicationRestart:qword 
RegisterApplicationRestart TEXTEQU <__imp_RegisterApplicationRestart> 
extern __imp_RegisterConsoleIME:qword 
RegisterConsoleIME TEXTEQU <__imp_RegisterConsoleIME> 
extern __imp_RegisterConsoleOS2:qword 
RegisterConsoleOS2 TEXTEQU <__imp_RegisterConsoleOS2> 
extern __imp_RegisterConsoleVDM:qword 
RegisterConsoleVDM TEXTEQU <__imp_RegisterConsoleVDM> 
extern __imp_RegisterWaitForInputIdle:qword 
RegisterWaitForInputIdle TEXTEQU <__imp_RegisterWaitForInputIdle> 
extern __imp_RegisterWaitForSingleObject:qword 
RegisterWaitForSingleObject TEXTEQU <__imp_RegisterWaitForSingleObject> 
extern __imp_RegisterWaitForSingleObjectEx:qword 
RegisterWaitForSingleObjectEx TEXTEQU <__imp_RegisterWaitForSingleObjectEx> 
extern __imp_RegisterWowBaseHandlers:qword 
RegisterWowBaseHandlers TEXTEQU <__imp_RegisterWowBaseHandlers> 
extern __imp_RegisterWowExec:qword 
RegisterWowExec TEXTEQU <__imp_RegisterWowExec> 
extern __imp_ReleaseActCtx:qword 
ReleaseActCtx TEXTEQU <__imp_ReleaseActCtx> 
extern __imp_ReleaseMutex:qword 
ReleaseMutex TEXTEQU <__imp_ReleaseMutex> 
extern __imp_ReleaseSemaphore:qword 
ReleaseSemaphore TEXTEQU <__imp_ReleaseSemaphore> 
extern __imp_RemoveDirectoryA:qword 
RemoveDirectory TEXTEQU <__imp_RemoveDirectoryA> 
extern __imp_RemoveDirectoryTransactedA:qword 
RemoveDirectoryTransacted TEXTEQU <__imp_RemoveDirectoryTransactedA> 
extern __imp_RemoveDirectoryTransactedW:qword 
RemoveDirectoryTransactedW TEXTEQU <__imp_RemoveDirectoryTransactedW> 
extern __imp_RemoveDirectoryW:qword 
RemoveDirectoryW TEXTEQU <__imp_RemoveDirectoryW> 
extern __imp_RemoveLocalAlternateComputerNameA:qword 
RemoveLocalAlternateComputerName TEXTEQU <__imp_RemoveLocalAlternateComputerNameA> 
extern __imp_RemoveLocalAlternateComputerNameW:qword 
RemoveLocalAlternateComputerNameW TEXTEQU <__imp_RemoveLocalAlternateComputerNameW> 
extern __imp_RemoveSecureMemoryCacheCallback:qword 
RemoveSecureMemoryCacheCallback TEXTEQU <__imp_RemoveSecureMemoryCacheCallback> 
extern __imp_ReplaceFile:qword 
ReplaceFile TEXTEQU <__imp_ReplaceFile> 
extern __imp_ReplaceFileA:qword 
ReplaceFile TEXTEQU <__imp_ReplaceFileA> 
extern __imp_ReplaceFileW:qword 
ReplaceFileW TEXTEQU <__imp_ReplaceFileW> 
extern __imp_ReplacePartitionUnit:qword 
ReplacePartitionUnit TEXTEQU <__imp_ReplacePartitionUnit> 
extern __imp_RequestDeviceWakeup:qword 
RequestDeviceWakeup TEXTEQU <__imp_RequestDeviceWakeup> 
extern __imp_RequestWakeupLatency:qword 
RequestWakeupLatency TEXTEQU <__imp_RequestWakeupLatency> 
extern __imp_ResetEvent:qword 
ResetEvent TEXTEQU <__imp_ResetEvent> 
extern __imp_ResetWriteWatch:qword 
ResetWriteWatch TEXTEQU <__imp_ResetWriteWatch> 
extern __imp_ResolveLocaleName:qword 
ResolveLocaleName TEXTEQU <__imp_ResolveLocaleName> 
extern __imp_ResumeThread:qword 
ResumeThread TEXTEQU <__imp_ResumeThread> 
extern __imp_RtlAddFunctionTable:qword 
RtlAddFunctionTable TEXTEQU <__imp_RtlAddFunctionTable> 
extern __imp_RtlCaptureContext:qword 
RtlCaptureContext TEXTEQU <__imp_RtlCaptureContext> 
extern __imp_RtlCaptureStackBackTrace:qword 
RtlCaptureStackBackTrace TEXTEQU <__imp_RtlCaptureStackBackTrace> 
extern __imp_RtlCompareMemory:qword 
RtlCompareMemory TEXTEQU <__imp_RtlCompareMemory> 
extern __imp_RtlCopyMemory:qword 
RtlCopyMemory TEXTEQU <__imp_RtlCopyMemory> 
extern __imp_RtlDeleteFunctionTable:qword 
RtlDeleteFunctionTable TEXTEQU <__imp_RtlDeleteFunctionTable> 
extern __imp_RtlFillMemory:qword 
RtlFillMemory TEXTEQU <__imp_RtlFillMemory> 
extern __imp_RtlInstallFunctionTableCallback:qword 
RtlInstallFunctionTableCallback TEXTEQU <__imp_RtlInstallFunctionTableCallback> 
extern __imp_RtlLookupFunctionEntry:qword 
RtlLookupFunctionEntry TEXTEQU <__imp_RtlLookupFunctionEntry> 
extern __imp_RtlMoveMemory:qword 
RtlMoveMemory TEXTEQU <__imp_RtlMoveMemory> 
extern __imp_RtlPcToFileHeader:qword 
RtlPcToFileHeader TEXTEQU <__imp_RtlPcToFileHeader> 
extern __imp_RtlRaiseException:qword 
RtlRaiseException TEXTEQU <__imp_RtlRaiseException> 
extern __imp_RtlRestoreContext:qword 
RtlRestoreContext TEXTEQU <__imp_RtlRestoreContext> 
extern __imp_RtlUnwind:qword 
RtlUnwind TEXTEQU <__imp_RtlUnwind> 
extern __imp_RtlUnwindEx:qword 
RtlUnwindEx TEXTEQU <__imp_RtlUnwindEx> 
extern __imp_RtlVirtualUnwind:qword 
RtlVirtualUnwind TEXTEQU <__imp_RtlVirtualUnwind> 
extern __imp_ScrollConsoleScreenBufferA:qword 
ScrollConsoleScreenBuffer TEXTEQU <__imp_ScrollConsoleScreenBufferA> 
extern __imp_ScrollConsoleScreenBufferW:qword 
ScrollConsoleScreenBufferW TEXTEQU <__imp_ScrollConsoleScreenBufferW> 
extern __imp_SearchPathA:qword 
SearchPath TEXTEQU <__imp_SearchPathA> 
extern __imp_SearchPathW:qword 
SearchPathW TEXTEQU <__imp_SearchPathW> 
extern __imp_SetCalendarInfoA:qword 
SetCalendarInfo TEXTEQU <__imp_SetCalendarInfoA> 
extern __imp_SetCalendarInfoW:qword 
SetCalendarInfoW TEXTEQU <__imp_SetCalendarInfoW> 
extern __imp_SetClientTimeZoneInformation:qword 
SetClientTimeZoneInformation TEXTEQU <__imp_SetClientTimeZoneInformation> 
extern __imp_SetComPlusPackageInstallStatus:qword 
SetComPlusPackageInstallStatus TEXTEQU <__imp_SetComPlusPackageInstallStatus> 
extern __imp_SetCommBreak:qword 
SetCommBreak TEXTEQU <__imp_SetCommBreak> 
extern __imp_SetCommConfig:qword 
SetCommConfig TEXTEQU <__imp_SetCommConfig> 
extern __imp_SetCommMask:qword 
SetCommMask TEXTEQU <__imp_SetCommMask> 
extern __imp_SetCommState:qword 
SetCommState TEXTEQU <__imp_SetCommState> 
extern __imp_SetCommTimeouts:qword 
SetCommTimeouts TEXTEQU <__imp_SetCommTimeouts> 
extern __imp_SetComputerNameA:qword 
SetComputerName TEXTEQU <__imp_SetComputerNameA> 
extern __imp_SetComputerNameExA:qword 
SetComputerNameEx TEXTEQU <__imp_SetComputerNameExA> 
extern __imp_SetComputerNameExW:qword 
SetComputerNameExW TEXTEQU <__imp_SetComputerNameExW> 
extern __imp_SetComputerNameW:qword 
SetComputerNameW TEXTEQU <__imp_SetComputerNameW> 
extern __imp_SetConsoleActiveScreenBuffer:qword 
SetConsoleActiveScreenBuffer TEXTEQU <__imp_SetConsoleActiveScreenBuffer> 
extern __imp_SetConsoleCP:qword 
SetConsoleCP TEXTEQU <__imp_SetConsoleCP> 
extern __imp_SetConsoleCtrlHandler:qword 
SetConsoleCtrlHandler TEXTEQU <__imp_SetConsoleCtrlHandler> 
extern __imp_SetConsoleCursor:qword 
SetConsoleCursor TEXTEQU <__imp_SetConsoleCursor> 
extern __imp_SetConsoleCursorInfo:qword 
SetConsoleCursorInfo TEXTEQU <__imp_SetConsoleCursorInfo> 
extern __imp_SetConsoleCursorMode:qword 
SetConsoleCursorMode TEXTEQU <__imp_SetConsoleCursorMode> 
extern __imp_SetConsoleCursorPosition:qword 
SetConsoleCursorPosition TEXTEQU <__imp_SetConsoleCursorPosition> 
extern __imp_SetConsoleDisplayMode:qword 
SetConsoleDisplayMode TEXTEQU <__imp_SetConsoleDisplayMode> 
extern __imp_SetConsoleFont:qword 
SetConsoleFont TEXTEQU <__imp_SetConsoleFont> 
extern __imp_SetConsoleHardwareState:qword 
SetConsoleHardwareState TEXTEQU <__imp_SetConsoleHardwareState> 
extern __imp_SetConsoleHistoryInfo:qword 
SetConsoleHistoryInfo TEXTEQU <__imp_SetConsoleHistoryInfo> 
extern __imp_SetConsoleIcon:qword 
SetConsoleIcon TEXTEQU <__imp_SetConsoleIcon> 
extern __imp_SetConsoleInputExeNameA:qword 
SetConsoleInputExeName TEXTEQU <__imp_SetConsoleInputExeNameA> 
extern __imp_SetConsoleInputExeNameW:qword 
SetConsoleInputExeNameW TEXTEQU <__imp_SetConsoleInputExeNameW> 
extern __imp_SetConsoleKeyShortcuts:qword 
SetConsoleKeyShortcuts TEXTEQU <__imp_SetConsoleKeyShortcuts> 
extern __imp_SetConsoleLocalEUDC:qword 
SetConsoleLocalEUDC TEXTEQU <__imp_SetConsoleLocalEUDC> 
extern __imp_SetConsoleMaximumWindowSize:qword 
SetConsoleMaximumWindowSize TEXTEQU <__imp_SetConsoleMaximumWindowSize> 
extern __imp_SetConsoleMenuClose:qword 
SetConsoleMenuClose TEXTEQU <__imp_SetConsoleMenuClose> 
extern __imp_SetConsoleMode:qword 
SetConsoleMode TEXTEQU <__imp_SetConsoleMode> 
extern __imp_SetConsoleNlsMode:qword 
SetConsoleNlsMode TEXTEQU <__imp_SetConsoleNlsMode> 
extern __imp_SetConsoleNumberOfCommandsA:qword 
SetConsoleNumberOfCommands TEXTEQU <__imp_SetConsoleNumberOfCommandsA> 
extern __imp_SetConsoleNumberOfCommandsW:qword 
SetConsoleNumberOfCommandsW TEXTEQU <__imp_SetConsoleNumberOfCommandsW> 
extern __imp_SetConsoleOS2OemFormat:qword 
SetConsoleOS2OemFormat TEXTEQU <__imp_SetConsoleOS2OemFormat> 
extern __imp_SetConsoleOutputCP:qword 
SetConsoleOutputCP TEXTEQU <__imp_SetConsoleOutputCP> 
extern __imp_SetConsolePalette:qword 
SetConsolePalette TEXTEQU <__imp_SetConsolePalette> 
extern __imp_SetConsoleScreenBufferInfoEx:qword 
SetConsoleScreenBufferInfoEx TEXTEQU <__imp_SetConsoleScreenBufferInfoEx> 
extern __imp_SetConsoleScreenBufferSize:qword 
SetConsoleScreenBufferSize TEXTEQU <__imp_SetConsoleScreenBufferSize> 
extern __imp_SetConsoleTextAttribute:qword 
SetConsoleTextAttribute TEXTEQU <__imp_SetConsoleTextAttribute> 
extern __imp_SetConsoleTitleA:qword 
SetConsoleTitle TEXTEQU <__imp_SetConsoleTitleA> 
extern __imp_SetConsoleTitleW:qword 
SetConsoleTitleW TEXTEQU <__imp_SetConsoleTitleW> 
extern __imp_SetConsoleWindowInfo:qword 
SetConsoleWindowInfo TEXTEQU <__imp_SetConsoleWindowInfo> 
extern __imp_SetCurrentConsoleFontEx:qword 
SetCurrentConsoleFontEx TEXTEQU <__imp_SetCurrentConsoleFontEx> 
extern __imp_SetCurrentDirectoryA:qword 
SetCurrentDirectory TEXTEQU <__imp_SetCurrentDirectoryA> 
extern __imp_SetCurrentDirectoryW:qword 
SetCurrentDirectoryW TEXTEQU <__imp_SetCurrentDirectoryW> 
extern __imp_SetDefaultCommConfigA:qword 
SetDefaultCommConfig TEXTEQU <__imp_SetDefaultCommConfigA> 
extern __imp_SetDefaultCommConfigW:qword 
SetDefaultCommConfigW TEXTEQU <__imp_SetDefaultCommConfigW> 
extern __imp_SetDllDirectoryA:qword 
SetDllDirectory TEXTEQU <__imp_SetDllDirectoryA> 
extern __imp_SetDllDirectoryW:qword 
SetDllDirectoryW TEXTEQU <__imp_SetDllDirectoryW> 
extern __imp_SetDynamicTimeZoneInformation:qword 
SetDynamicTimeZoneInformation TEXTEQU <__imp_SetDynamicTimeZoneInformation> 
extern __imp_SetEndOfFile:qword 
SetEndOfFile TEXTEQU <__imp_SetEndOfFile> 
extern __imp_SetEnvironmentStringsA:qword 
SetEnvironmentStrings TEXTEQU <__imp_SetEnvironmentStringsA> 
extern __imp_SetEnvironmentStringsW:qword 
SetEnvironmentStringsW TEXTEQU <__imp_SetEnvironmentStringsW> 
extern __imp_SetEnvironmentVariableA:qword 
SetEnvironmentVariable TEXTEQU <__imp_SetEnvironmentVariableA> 
extern __imp_SetEnvironmentVariableW:qword 
SetEnvironmentVariableW TEXTEQU <__imp_SetEnvironmentVariableW> 
extern __imp_SetErrorMode:qword 
SetErrorMode TEXTEQU <__imp_SetErrorMode> 
extern __imp_SetEvent:qword 
SetEvent TEXTEQU <__imp_SetEvent> 
extern __imp_SetFileApisToANSI:qword 
SetFileApisToANSI TEXTEQU <__imp_SetFileApisToANSI> 
extern __imp_SetFileApisToOEM:qword 
SetFileApisToOEM TEXTEQU <__imp_SetFileApisToOEM> 
extern __imp_SetFileAttributesA:qword 
SetFileAttributes TEXTEQU <__imp_SetFileAttributesA> 
extern __imp_SetFileAttributesTransactedA:qword 
SetFileAttributesTransacted TEXTEQU <__imp_SetFileAttributesTransactedA> 
extern __imp_SetFileAttributesTransactedW:qword 
SetFileAttributesTransactedW TEXTEQU <__imp_SetFileAttributesTransactedW> 
extern __imp_SetFileAttributesW:qword 
SetFileAttributesW TEXTEQU <__imp_SetFileAttributesW> 
extern __imp_SetFileBandwidthReservation:qword 
SetFileBandwidthReservation TEXTEQU <__imp_SetFileBandwidthReservation> 
extern __imp_SetFileCompletionNotificationModes:qword 
SetFileCompletionNotificationModes TEXTEQU <__imp_SetFileCompletionNotificationModes> 
extern __imp_SetFileInformationByHandle:qword 
SetFileInformationByHandle TEXTEQU <__imp_SetFileInformationByHandle> 
extern __imp_SetFileIoOverlappedRange:qword 
SetFileIoOverlappedRange TEXTEQU <__imp_SetFileIoOverlappedRange> 
extern __imp_SetFilePointer:qword 
SetFilePointer TEXTEQU <__imp_SetFilePointer> 
extern __imp_SetFilePointerEx:qword 
SetFilePointerEx TEXTEQU <__imp_SetFilePointerEx> 
extern __imp_SetFileShortNameA:qword 
SetFileShortName TEXTEQU <__imp_SetFileShortNameA> 
extern __imp_SetFileShortNameW:qword 
SetFileShortNameW TEXTEQU <__imp_SetFileShortNameW> 
extern __imp_SetFileTime:qword 
SetFileTime TEXTEQU <__imp_SetFileTime> 
extern __imp_SetFileValidData:qword 
SetFileValidDat TEXTEQU <__imp_SetFileValidData> 
extern __imp_SetFirmwareEnvironmentVariableA:qword 
SetFirmwareEnvironmentVariable TEXTEQU <__imp_SetFirmwareEnvironmentVariableA> 
extern __imp_SetFirmwareEnvironmentVariableW:qword 
SetFirmwareEnvironmentVariableW TEXTEQU <__imp_SetFirmwareEnvironmentVariableW> 
extern __imp_SetHandleCount:qword 
SetHandleCount TEXTEQU <__imp_SetHandleCount> 
extern __imp_SetHandleInformation:qword 
SetHandleInformation TEXTEQU <__imp_SetHandleInformation> 
extern __imp_SetInformationJobObject:qword 
SetInformationJobObject TEXTEQU <__imp_SetInformationJobObject> 
extern __imp_SetLastConsoleEventActive:qword 
SetLastConsoleEventActive TEXTEQU <__imp_SetLastConsoleEventActive> 
extern __imp_SetLastError:qword 
SetLastError TEXTEQU <__imp_SetLastError> 
extern __imp_SetLocalPrimaryComputerNameA:qword 
SetLocalPrimaryComputerName TEXTEQU <__imp_SetLocalPrimaryComputerNameA> 
extern __imp_SetLocalPrimaryComputerNameW:qword 
SetLocalPrimaryComputerNameW TEXTEQU <__imp_SetLocalPrimaryComputerNameW> 
extern __imp_SetLocalTime:qword 
SetLocalTime TEXTEQU <__imp_SetLocalTime> 
extern __imp_SetLocaleInfoA:qword 
SetLocaleInfo TEXTEQU <__imp_SetLocaleInfoA> 
extern __imp_SetLocaleInfoW:qword 
SetLocaleInfoW TEXTEQU <__imp_SetLocaleInfoW> 
extern __imp_SetMailslotInfo:qword 
SetMailslotInfo TEXTEQU <__imp_SetMailslotInfo> 
extern __imp_SetMessageWaitingIndicator:qword 
SetMessageWaitingIndicator TEXTEQU <__imp_SetMessageWaitingIndicator> 
extern __imp_SetNamedPipeAttribute:qword 
SetNamedPipeAttribute TEXTEQU <__imp_SetNamedPipeAttribute> 
extern __imp_SetNamedPipeHandleState:qword 
SetNamedPipeHandleState TEXTEQU <__imp_SetNamedPipeHandleState> 
extern __imp_SetPriorityClass:qword 
SetPriorityClass TEXTEQU <__imp_SetPriorityClass> 
extern __imp_SetProcessAffinityMask:qword 
SetProcessAffinityMask TEXTEQU <__imp_SetProcessAffinityMask> 
extern __imp_SetProcessAffinityUpdateMode:qword 
SetProcessAffinityUpdateMode TEXTEQU <__imp_SetProcessAffinityUpdateMode> 
extern __imp_SetProcessDEPPolicy:qword 
SetProcessDEPPolicy TEXTEQU <__imp_SetProcessDEPPolicy> 
extern __imp_SetProcessPreferredUILanguages:qword 
SetProcessPreferredUILanguages TEXTEQU <__imp_SetProcessPreferredUILanguages> 
extern __imp_SetProcessPriorityBoost:qword 
SetProcessPriorityBoost TEXTEQU <__imp_SetProcessPriorityBoost> 
extern __imp_SetProcessShutdownParameters:qword 
SetProcessShutdownParameters TEXTEQU <__imp_SetProcessShutdownParameters> 
extern __imp_SetProcessUserModeExceptionPolicy:qword 
SetProcessUserModeExceptionPolicy TEXTEQU <__imp_SetProcessUserModeExceptionPolicy> 
extern __imp_SetProcessWorkingSetSize:qword 
SetProcessWorkingSetSize TEXTEQU <__imp_SetProcessWorkingSetSize> 
extern __imp_SetProcessWorkingSetSizeEx:qword 
SetProcessWorkingSetSizeEx TEXTEQU <__imp_SetProcessWorkingSetSizeEx> 
extern __imp_SetSearchPathMode:qword 
SetSearchPathMode TEXTEQU <__imp_SetSearchPathMode> 
extern __imp_SetStdHandle:qword 
SetStdHandle TEXTEQU <__imp_SetStdHandle> 
extern __imp_SetStdHandleEx:qword 
SetStdHandleEx TEXTEQU <__imp_SetStdHandleEx> 
extern __imp_SetSystemFileCacheSize:qword 
SetSystemFileCacheSize TEXTEQU <__imp_SetSystemFileCacheSize> 
extern __imp_SetSystemPowerState:qword 
SetSystemPowerState TEXTEQU <__imp_SetSystemPowerState> 
extern __imp_SetSystemTime:qword 
SetSystemTime TEXTEQU <__imp_SetSystemTime> 
extern __imp_SetSystemTimeAdjustment:qword 
SetSystemTimeAdjustment TEXTEQU <__imp_SetSystemTimeAdjustment> 
extern __imp_SetTapeParameters:qword 
SetTapeParameters TEXTEQU <__imp_SetTapeParameters> 
extern __imp_SetTapePosition:qword 
SetTapePosition TEXTEQU <__imp_SetTapePosition> 
extern __imp_SetTermsrvAppInstallMode:qword 
SetTermsrvAppInstallMode TEXTEQU <__imp_SetTermsrvAppInstallMode> 
extern __imp_SetThreadAffinityMask:qword 
SetThreadAffinityMask TEXTEQU <__imp_SetThreadAffinityMask> 
extern __imp_SetThreadContext:qword 
SetThreadContext TEXTEQU <__imp_SetThreadContext> 
extern __imp_SetThreadErrorMode:qword 
SetThreadErrorMode TEXTEQU <__imp_SetThreadErrorMode> 
extern __imp_SetThreadExecutionState:qword 
SetThreadExecutionState TEXTEQU <__imp_SetThreadExecutionState> 
extern __imp_SetThreadGroupAffinity:qword 
SetThreadGroupAffinity TEXTEQU <__imp_SetThreadGroupAffinity> 
extern __imp_SetThreadIdealProcessor:qword 
SetThreadIdealProcessor TEXTEQU <__imp_SetThreadIdealProcessor> 
extern __imp_SetThreadIdealProcessorEx:qword 
SetThreadIdealProcessorEx TEXTEQU <__imp_SetThreadIdealProcessorEx> 
extern __imp_SetThreadLocale:qword 
SetThreadLocale TEXTEQU <__imp_SetThreadLocale> 
extern __imp_SetThreadPreferredUILanguages:qword 
SetThreadPreferredUILanguages TEXTEQU <__imp_SetThreadPreferredUILanguages> 
extern __imp_SetThreadPriority:qword 
SetThreadPriority TEXTEQU <__imp_SetThreadPriority> 
extern __imp_SetThreadPriorityBoost:qword 
SetThreadPriorityBoost TEXTEQU <__imp_SetThreadPriorityBoost> 
extern __imp_SetThreadStackGuarantee:qword 
SetThreadStackGuarantee TEXTEQU <__imp_SetThreadStackGuarantee> 
extern __imp_SetThreadUILanguage:qword 
SetThreadUILanguage TEXTEQU <__imp_SetThreadUILanguage> 
extern __imp_SetThreadpoolStackInformation:qword 
SetThreadpoolStackInformation TEXTEQU <__imp_SetThreadpoolStackInformation> 
extern __imp_SetThreadpoolThreadMinimum:qword 
SetThreadpoolThreadMinimum TEXTEQU <__imp_SetThreadpoolThreadMinimum> 
extern __imp_SetTimeZoneInformation:qword 
SetTimeZoneInformation TEXTEQU <__imp_SetTimeZoneInformation> 
extern __imp_SetTimerQueueTimer:qword 
SetTimerQueueTimer TEXTEQU <__imp_SetTimerQueueTimer> 
extern __imp_SetUmsThreadInformation:qword 
SetUmsThreadInformation TEXTEQU <__imp_SetUmsThreadInformation> 
extern __imp_SetUnhandledExceptionFilter:qword 
SetUnhandledExceptionFilter TEXTEQU <__imp_SetUnhandledExceptionFilter> 
extern __imp_SetUserGeoID:qword 
SetUserGeoID TEXTEQU <__imp_SetUserGeoID> 
extern __imp_SetVDMCurrentDirectories:qword 
SetVDMCurrentDirectories TEXTEQU <__imp_SetVDMCurrentDirectories> 
extern __imp_SetVolumeLabelA:qword 
SetVolumeLabel TEXTEQU <__imp_SetVolumeLabelA> 
extern __imp_SetVolumeLabelW:qword 
SetVolumeLabelW TEXTEQU <__imp_SetVolumeLabelW> 
extern __imp_SetVolumeMountPointA:qword 
SetVolumeMountPoint TEXTEQU <__imp_SetVolumeMountPointA> 
extern __imp_SetVolumeMountPointW:qword 
SetVolumeMountPointW TEXTEQU <__imp_SetVolumeMountPointW> 
extern __imp_SetWaitableTimer:qword 
SetWaitableTimer TEXTEQU <__imp_SetWaitableTimer> 
extern __imp_SetXStateFeaturesMask:qword 
SetXStateFeaturesMask TEXTEQU <__imp_SetXStateFeaturesMask> 
extern __imp_SetupComm:qword 
SetupComm TEXTEQU <__imp_SetupComm> 
extern __imp_ShowConsoleCursor:qword 
ShowConsoleCursor TEXTEQU <__imp_ShowConsoleCursor> 
extern __imp_SignalObjectAndWait:qword 
SignalObjectAndWait TEXTEQU <__imp_SignalObjectAndWait> 
extern __imp_SizeofResource:qword 
SizeofResource TEXTEQU <__imp_SizeofResource> 
extern __imp_Sleep:qword 
Sleep TEXTEQU <__imp_Sleep> 
extern __imp_SleepConditionVariableCS:qword 
SleepConditionVariableCS TEXTEQU <__imp_SleepConditionVariableCS> 
extern __imp_SleepConditionVariableSRW:qword 
SleepConditionVariableSRW TEXTEQU <__imp_SleepConditionVariableSRW> 
extern __imp_SleepEx:qword 
SleepEx TEXTEQU <__imp_SleepEx> 
extern __imp_SortCloseHandle:qword 
SortCloseHandle TEXTEQU <__imp_SortCloseHandle> 
extern __imp_SortGetHandle:qword 
SortGetHandle TEXTEQU <__imp_SortGetHandle> 
extern __imp_SuspendThread:qword 
SuspendThread TEXTEQU <__imp_SuspendThread> 
extern __imp_SwitchToFiber:qword 
SwitchToFiber TEXTEQU <__imp_SwitchToFiber> 
extern __imp_SwitchToThread:qword 
SwitchToThread TEXTEQU <__imp_SwitchToThread> 
extern __imp_SystemTimeToFileTime:qword 
SystemTimeToFileTime TEXTEQU <__imp_SystemTimeToFileTime> 
extern __imp_SystemTimeToTzSpecificLocalTime:qword 
SystemTimeToTzSpecificLocalTime TEXTEQU <__imp_SystemTimeToTzSpecificLocalTime> 
extern __imp_TerminateJobObject:qword 
TerminateJobObject TEXTEQU <__imp_TerminateJobObject> 
extern __imp_TerminateProcess:qword 
TerminateProcess TEXTEQU <__imp_TerminateProcess> 
extern __imp_TerminateThread:qword 
TerminateThread TEXTEQU <__imp_TerminateThread> 
extern __imp_TermsrvAppInstallMode:qword 
TermsrvAppInstallMode TEXTEQU <__imp_TermsrvAppInstallMode> 
extern __imp_Thread32First:qword 
Thread32First TEXTEQU <__imp_Thread32First> 
extern __imp_Thread32Next:qword 
Thread32Next TEXTEQU <__imp_Thread32Next> 
extern __imp_TlsAlloc:qword 
TlsAlloc TEXTEQU <__imp_TlsAlloc> 
extern __imp_TlsFree:qword 
TlsFree TEXTEQU <__imp_TlsFree> 
extern __imp_TlsGetValue:qword 
TlsGetValue TEXTEQU <__imp_TlsGetValue> 
extern __imp_TlsSetValue:qword 
TlsSetValue TEXTEQU <__imp_TlsSetValue> 
extern __imp_Toolhelp32ReadProcessMemory:qword 
Toolhelp32ReadProcessMemory TEXTEQU <__imp_Toolhelp32ReadProcessMemory> 
extern __imp_TransactNamedPipe:qword 
TransactNamedPipe TEXTEQU <__imp_TransactNamedPipe> 
extern __imp_TransmitCommChar:qword 
TransmitCommChar TEXTEQU <__imp_TransmitCommChar> 
extern __imp_TrySubmitThreadpoolCallback:qword 
TrySubmitThreadpoolCallback TEXTEQU <__imp_TrySubmitThreadpoolCallback> 
extern __imp_TzSpecificLocalTimeToSystemTime:qword 
TzSpecificLocalTimeToSystemTime TEXTEQU <__imp_TzSpecificLocalTimeToSystemTime> 
extern __imp_UTRegister:qword 
UTRegister TEXTEQU <__imp_UTRegister> 
extern __imp_UTUnRegister:qword 
UTUnRegister TEXTEQU <__imp_UTUnRegister> 
extern __imp_UmsThreadYield:qword 
UmsThreadYield TEXTEQU <__imp_UmsThreadYield> 
extern __imp_UnhandledExceptionFilter:qword 
UnhandledExceptionFilter TEXTEQU <__imp_UnhandledExceptionFilter> 
extern __imp_UnlockFile:qword 
UnlockFile TEXTEQU <__imp_UnlockFile> 
extern __imp_UnlockFileEx:qword 
UnlockFileEx TEXTEQU <__imp_UnlockFileEx> 
extern __imp_UnmapViewOfFile:qword 
UnmapViewOfFile TEXTEQU <__imp_UnmapViewOfFile> 
extern __imp_UnregisterApplicationRecoveryCallback:qword 
UnregisterApplicationRecoveryCallback TEXTEQU <__imp_UnregisterApplicationRecoveryCallback> 
extern __imp_UnregisterApplicationRestart:qword 
UnregisterApplicationRestart TEXTEQU <__imp_UnregisterApplicationRestart> 
extern __imp_UnregisterConsoleIME:qword 
UnregisterConsoleIME TEXTEQU <__imp_UnregisterConsoleIME> 
extern __imp_UnregisterWait:qword 
UnregisterWait TEXTEQU <__imp_UnregisterWait> 
extern __imp_UnregisterWaitEx:qword 
UnregisterWaitEx TEXTEQU <__imp_UnregisterWaitEx> 
extern __imp_UpdateCalendarDayOfWeek:qword 
UpdateCalendarDayOfWeek TEXTEQU <__imp_UpdateCalendarDayOfWeek> 
extern __imp_UpdateResourceA:qword 
UpdateResource TEXTEQU <__imp_UpdateResourceA> 
extern __imp_UpdateResourceW:qword 
UpdateResourceW TEXTEQU <__imp_UpdateResourceW> 
extern __imp_VDMConsoleOperation:qword 
VDMConsoleOperation TEXTEQU <__imp_VDMConsoleOperation> 
extern __imp_VDMOperationStarted:qword 
VDMOperationStarted TEXTEQU <__imp_VDMOperationStarted> 
extern __imp_VerLanguageNameA:qword 
VerLanguageName TEXTEQU <__imp_VerLanguageNameA> 
extern __imp_VerLanguageNameW:qword 
VerLanguageNameW TEXTEQU <__imp_VerLanguageNameW> 
extern __imp_VerifyConsoleIoHandle:qword 
VerifyConsoleIoHandle TEXTEQU <__imp_VerifyConsoleIoHandle> 
extern __imp_VerifyScripts:qword 
VerifyScripts TEXTEQU <__imp_VerifyScripts> 
extern __imp_VerifyVersionInfoA:qword 
VerifyVersionInfo TEXTEQU <__imp_VerifyVersionInfoA> 
extern __imp_VerifyVersionInfoW:qword 
VerifyVersionInfoW TEXTEQU <__imp_VerifyVersionInfoW> 
extern __imp_VirtualAlloc:qword 
VirtualAlloc TEXTEQU <__imp_VirtualAlloc> 
extern __imp_VirtualAllocEx:qword 
VirtualAllocEx TEXTEQU <__imp_VirtualAllocEx> 
extern __imp_VirtualAllocExNuma:qword 
VirtualAllocExNum TEXTEQU <__imp_VirtualAllocExNuma> 
extern __imp_VirtualFree:qword 
VirtualFree TEXTEQU <__imp_VirtualFree> 
extern __imp_VirtualFreeEx:qword 
VirtualFreeEx TEXTEQU <__imp_VirtualFreeEx> 
extern __imp_VirtualLock:qword 
VirtualLock TEXTEQU <__imp_VirtualLock> 
extern __imp_VirtualProtect:qword 
VirtualProtect TEXTEQU <__imp_VirtualProtect> 
extern __imp_VirtualProtectEx:qword 
VirtualProtectEx TEXTEQU <__imp_VirtualProtectEx> 
extern __imp_VirtualQuery:qword 
VirtualQuery TEXTEQU <__imp_VirtualQuery> 
extern __imp_VirtualQueryEx:qword 
VirtualQueryEx TEXTEQU <__imp_VirtualQueryEx> 
extern __imp_VirtualUnlock:qword 
VirtualUnlock TEXTEQU <__imp_VirtualUnlock> 
extern __imp_WTSGetActiveConsoleSessionId:qword 
WTSGetActiveConsoleSessionId TEXTEQU <__imp_WTSGetActiveConsoleSessionId> 
extern __imp_WaitCommEvent:qword 
WaitCommEvent TEXTEQU <__imp_WaitCommEvent> 
extern __imp_WaitForDebugEvent:qword 
WaitForDebugEvent TEXTEQU <__imp_WaitForDebugEvent> 
extern __imp_WaitForMultipleObjects:qword 
WaitForMultipleObjects TEXTEQU <__imp_WaitForMultipleObjects> 
extern __imp_WaitForMultipleObjectsEx:qword 
WaitForMultipleObjectsEx TEXTEQU <__imp_WaitForMultipleObjectsEx> 
extern __imp_WaitForSingleObject:qword 
WaitForSingleObject TEXTEQU <__imp_WaitForSingleObject> 
extern __imp_WaitForSingleObjectEx:qword 
WaitForSingleObjectEx TEXTEQU <__imp_WaitForSingleObjectEx> 
extern __imp_WaitNamedPipeA:qword 
WaitNamedPipe TEXTEQU <__imp_WaitNamedPipeA> 
extern __imp_WaitNamedPipeW:qword 
WaitNamedPipeW TEXTEQU <__imp_WaitNamedPipeW> 
extern __imp_WerGetFlags:qword 
WerGetFlags TEXTEQU <__imp_WerGetFlags> 
extern __imp_WerRegisterFile:qword 
WerRegisterFile TEXTEQU <__imp_WerRegisterFile> 
extern __imp_WerRegisterMemoryBlock:qword 
WerRegisterMemoryBlock TEXTEQU <__imp_WerRegisterMemoryBlock> 
extern __imp_WerRegisterRuntimeExceptionModule:qword 
WerRegisterRuntimeExceptionModule TEXTEQU <__imp_WerRegisterRuntimeExceptionModule> 
extern __imp_WerSetFlags:qword 
WerSetFlags TEXTEQU <__imp_WerSetFlags> 
extern __imp_WerUnregisterFile:qword 
WerUnregisterFile TEXTEQU <__imp_WerUnregisterFile> 
extern __imp_WerUnregisterMemoryBlock:qword 
WerUnregisterMemoryBlock TEXTEQU <__imp_WerUnregisterMemoryBlock> 
extern __imp_WerUnregisterRuntimeExceptionModule:qword 
WerUnregisterRuntimeExceptionModule TEXTEQU <__imp_WerUnregisterRuntimeExceptionModule> 
extern __imp_WerpCleanupMessageMapping:qword 
WerpCleanupMessageMapping TEXTEQU <__imp_WerpCleanupMessageMapping> 
extern __imp_WerpInitiateRemoteRecovery:qword 
WerpInitiateRemoteRecovery TEXTEQU <__imp_WerpInitiateRemoteRecovery> 
extern __imp_WerpNotifyLoadStringResource:qword 
WerpNotifyLoadStringResource TEXTEQU <__imp_WerpNotifyLoadStringResource> 
extern __imp_WerpNotifyLoadStringResourceEx:qword 
WerpNotifyLoadStringResourceEx TEXTEQU <__imp_WerpNotifyLoadStringResourceEx> 
extern __imp_WerpNotifyUseStringResource:qword 
WerpNotifyUseStringResource TEXTEQU <__imp_WerpNotifyUseStringResource> 
extern __imp_WerpStringLookup:qword 
WerpStringLookup TEXTEQU <__imp_WerpStringLookup> 
extern __imp_WideCharToMultiByte:qword 
WideCharToMultiByte TEXTEQU <__imp_WideCharToMultiByte> 
extern __imp_WinExec:qword 
WinExec TEXTEQU <__imp_WinExec> 
extern __imp_Wow64DisableWow64FsRedirection:qword 
Wow64DisableWow64FsRedirection TEXTEQU <__imp_Wow64DisableWow64FsRedirection> 
extern __imp_Wow64EnableWow64FsRedirection:qword 
Wow64EnableWow64FsRedirection TEXTEQU <__imp_Wow64EnableWow64FsRedirection> 
extern __imp_Wow64GetThreadContext:qword 
Wow64GetThreadContext TEXTEQU <__imp_Wow64GetThreadContext> 
extern __imp_Wow64GetThreadSelectorEntry:qword 
Wow64GetThreadSelectorEntry TEXTEQU <__imp_Wow64GetThreadSelectorEntry> 
extern __imp_Wow64RevertWow64FsRedirection:qword 
Wow64RevertWow64FsRedirection TEXTEQU <__imp_Wow64RevertWow64FsRedirection> 
extern __imp_Wow64SetThreadContext:qword 
Wow64SetThreadContext TEXTEQU <__imp_Wow64SetThreadContext> 
extern __imp_Wow64SuspendThread:qword 
Wow64SuspendThread TEXTEQU <__imp_Wow64SuspendThread> 
extern __imp_WriteConsoleA:qword 
WriteConsole TEXTEQU <__imp_WriteConsoleA> 
extern __imp_WriteConsoleInputA:qword 
WriteConsoleInput TEXTEQU <__imp_WriteConsoleInputA> 
extern __imp_WriteConsoleInputVDMA:qword 
WriteConsoleInputVDM TEXTEQU <__imp_WriteConsoleInputVDMA> 
extern __imp_WriteConsoleInputVDMW:qword 
WriteConsoleInputVDMW TEXTEQU <__imp_WriteConsoleInputVDMW> 
extern __imp_WriteConsoleInputW:qword 
WriteConsoleInputW TEXTEQU <__imp_WriteConsoleInputW> 
extern __imp_WriteConsoleOutputA:qword 
WriteConsoleOutput TEXTEQU <__imp_WriteConsoleOutputA> 
extern __imp_WriteConsoleOutputAttribute:qword 
WriteConsoleOutputAttribute TEXTEQU <__imp_WriteConsoleOutputAttribute> 
extern __imp_WriteConsoleOutputCharacterA:qword 
WriteConsoleOutputCharacter TEXTEQU <__imp_WriteConsoleOutputCharacterA> 
extern __imp_WriteConsoleOutputCharacterW:qword 
WriteConsoleOutputCharacterW TEXTEQU <__imp_WriteConsoleOutputCharacterW> 
extern __imp_WriteConsoleOutputW:qword 
WriteConsoleOutputW TEXTEQU <__imp_WriteConsoleOutputW> 
extern __imp_WriteConsoleW:qword 
WriteConsoleW TEXTEQU <__imp_WriteConsoleW> 
extern __imp_WriteFile:qword 
WriteFile TEXTEQU <__imp_WriteFile> 
extern __imp_WriteFileEx:qword 
WriteFileEx TEXTEQU <__imp_WriteFileEx> 
extern __imp_WriteFileGather:qword 
WriteFileGather TEXTEQU <__imp_WriteFileGather> 
extern __imp_WritePrivateProfileSectionA:qword 
WritePrivateProfileSection TEXTEQU <__imp_WritePrivateProfileSectionA> 
extern __imp_WritePrivateProfileSectionW:qword 
WritePrivateProfileSectionW TEXTEQU <__imp_WritePrivateProfileSectionW> 
extern __imp_WritePrivateProfileStringA:qword 
WritePrivateProfileString TEXTEQU <__imp_WritePrivateProfileStringA> 
extern __imp_WritePrivateProfileStringW:qword 
WritePrivateProfileStringW TEXTEQU <__imp_WritePrivateProfileStringW> 
extern __imp_WritePrivateProfileStructA:qword 
WritePrivateProfileStruct TEXTEQU <__imp_WritePrivateProfileStructA> 
extern __imp_WritePrivateProfileStructW:qword 
WritePrivateProfileStructW TEXTEQU <__imp_WritePrivateProfileStructW> 
extern __imp_WriteProcessMemory:qword 
WriteProcessMemory TEXTEQU <__imp_WriteProcessMemory> 
extern __imp_WriteProfileSectionA:qword 
WriteProfileSection TEXTEQU <__imp_WriteProfileSectionA> 
extern __imp_WriteProfileSectionW:qword 
WriteProfileSectionW TEXTEQU <__imp_WriteProfileSectionW> 
extern __imp_WriteProfileStringA:qword 
WriteProfileString TEXTEQU <__imp_WriteProfileStringA> 
extern __imp_WriteProfileStringW:qword 
WriteProfileStringW TEXTEQU <__imp_WriteProfileStringW> 
extern __imp_WriteTapemark:qword 
WriteTapemark TEXTEQU <__imp_WriteTapemark> 
extern __imp_ZombifyActCtx:qword 
ZombifyActCtx TEXTEQU <__imp_ZombifyActCtx> 
extern __imp__hread:qword 
_hread TEXTEQU <__imp__hread> 
extern __imp__hwrite:qword 
_hwrite TEXTEQU <__imp__hwrite> 
extern __imp__lclose:qword 
_lclose TEXTEQU <__imp__lclose> 
extern __imp__lcreat:qword 
_lcreat TEXTEQU <__imp__lcreat> 
extern __imp__llseek:qword 
_llseek TEXTEQU <__imp__llseek> 
extern __imp__lopen:qword 
_lopen TEXTEQU <__imp__lopen> 
extern __imp__lread:qword 
_lread TEXTEQU <__imp__lread> 
extern __imp__lwrite:qword 
_lwrite TEXTEQU <__imp__lwrite> 
extern __imp_lstrcat:qword 
lstrcat TEXTEQU <__imp_lstrcat> 
extern __imp_lstrcatA:qword 
lstrcat TEXTEQU <__imp_lstrcatA> 
extern __imp_lstrcatW:qword 
lstrcatW TEXTEQU <__imp_lstrcatW> 
extern __imp_lstrcmp:qword 
lstrcmp TEXTEQU <__imp_lstrcmp> 
extern __imp_lstrcmpA:qword 
lstrcmp TEXTEQU <__imp_lstrcmpA> 
extern __imp_lstrcmpW:qword 
lstrcmpW TEXTEQU <__imp_lstrcmpW> 
extern __imp_lstrcmpi:qword 
lstrcmpi TEXTEQU <__imp_lstrcmpi> 
extern __imp_lstrcmpiA:qword 
lstrcmpi TEXTEQU <__imp_lstrcmpiA> 
extern __imp_lstrcmpiW:qword 
lstrcmpiW TEXTEQU <__imp_lstrcmpiW> 
extern __imp_lstrcpy:qword 
lstrcpy TEXTEQU <__imp_lstrcpy> 
extern __imp_lstrcpyA:qword 
lstrcpy TEXTEQU <__imp_lstrcpyA> 
extern __imp_lstrcpyW:qword 
lstrcpyW TEXTEQU <__imp_lstrcpyW> 
extern __imp_lstrcpyn:qword 
lstrcpyn TEXTEQU <__imp_lstrcpyn> 
extern __imp_lstrcpynA:qword 
lstrcpyn TEXTEQU <__imp_lstrcpynA> 
extern __imp_lstrcpynW:qword 
lstrcpynW TEXTEQU <__imp_lstrcpynW> 
extern __imp_lstrlen:qword 
lstrlen TEXTEQU <__imp_lstrlen> 
extern __imp_lstrlenA:qword 
lstrlen TEXTEQU <__imp_lstrlenA> 
extern __imp_lstrlenW:qword 
lstrlenW TEXTEQU <__imp_lstrlenW> 
extern __imp_uaw_lstrcmpW:qword 
uaw_lstrcmpW TEXTEQU <__imp_uaw_lstrcmpW> 
extern __imp_uaw_lstrcmpiW:qword 
uaw_lstrcmpiW TEXTEQU <__imp_uaw_lstrcmpiW> 
extern __imp_uaw_lstrlenW:qword 
uaw_lstrlenW TEXTEQU <__imp_uaw_lstrlenW> 
extern __imp_uaw_wcschr:qword 
uaw_wcschr TEXTEQU <__imp_uaw_wcschr> 
extern __imp_uaw_wcscpy:qword 
uaw_wcscpy TEXTEQU <__imp_uaw_wcscpy> 
extern __imp_uaw_wcsicmp:qword 
uaw_wcsicmp TEXTEQU <__imp_uaw_wcsicmp> 
extern __imp_uaw_wcslen:qword 
uaw_wcslen TEXTEQU <__imp_uaw_wcslen> 
extern __imp_uaw_wcsrchr:qword 
uaw_wcsrchr TEXTEQU <__imp_uaw_wcsrchr> 
