extern __imp_DrawDibBegin:qword 
DrawDibBegin TEXTEQU <__imp_DrawDibBegin> 
extern __imp_DrawDibChangePalette:qword 
DrawDibChangePalette TEXTEQU <__imp_DrawDibChangePalette> 
extern __imp_DrawDibClose:qword 
DrawDibClose TEXTEQU <__imp_DrawDibClose> 
extern __imp_DrawDibDraw:qword 
DrawDibDraw TEXTEQU <__imp_DrawDibDraw> 
extern __imp_DrawDibEnd:qword 
DrawDibEnd TEXTEQU <__imp_DrawDibEnd> 
extern __imp_DrawDibGetBuffer:qword 
DrawDibGetBuffer TEXTEQU <__imp_DrawDibGetBuffer> 
extern __imp_DrawDibGetPalette:qword 
DrawDibGetPalette TEXTEQU <__imp_DrawDibGetPalette> 
extern __imp_DrawDibOpen:qword 
DrawDibOpen TEXTEQU <__imp_DrawDibOpen> 
extern __imp_DrawDibProfileDisplay:qword 
DrawDibProfileDisplay TEXTEQU <__imp_DrawDibProfileDisplay> 
extern __imp_DrawDibRealize:qword 
DrawDibRealize TEXTEQU <__imp_DrawDibRealize> 
extern __imp_DrawDibSetPalette:qword 
DrawDibSetPalette TEXTEQU <__imp_DrawDibSetPalette> 
extern __imp_DrawDibStart:qword 
DrawDibStart TEXTEQU <__imp_DrawDibStart> 
extern __imp_DrawDibStop:qword 
DrawDibStop TEXTEQU <__imp_DrawDibStop> 
extern __imp_DrawDibTime:qword 
DrawDibTime TEXTEQU <__imp_DrawDibTime> 
extern __imp_GetOpenFileNamePreview:qword 
GetOpenFileNamePreview TEXTEQU <__imp_GetOpenFileNamePreview> 
extern __imp_GetOpenFileNamePreviewA:qword 
GetOpenFileNamePreview TEXTEQU <__imp_GetOpenFileNamePreviewA> 
extern __imp_GetOpenFileNamePreviewW:qword 
GetOpenFileNamePreviewW TEXTEQU <__imp_GetOpenFileNamePreviewW> 
extern __imp_GetSaveFileNamePreviewA:qword 
GetSaveFileNamePreview TEXTEQU <__imp_GetSaveFileNamePreviewA> 
extern __imp_GetSaveFileNamePreviewW:qword 
GetSaveFileNamePreviewW TEXTEQU <__imp_GetSaveFileNamePreviewW> 
extern __imp_ICClose:qword 
ICClose TEXTEQU <__imp_ICClose> 
extern __imp_ICCompress:qword 
ICCompress TEXTEQU <__imp_ICCompress> 
extern __imp_ICCompressorChoose:qword 
ICCompressorChoose TEXTEQU <__imp_ICCompressorChoose> 
extern __imp_ICCompressorFree:qword 
ICCompressorFree TEXTEQU <__imp_ICCompressorFree> 
extern __imp_ICDecompress:qword 
ICDecompress TEXTEQU <__imp_ICDecompress> 
extern __imp_ICDraw:qword 
ICDraw TEXTEQU <__imp_ICDraw> 
extern __imp_ICDrawBegin:qword 
ICDrawBegin TEXTEQU <__imp_ICDrawBegin> 
extern __imp_ICGetDisplayFormat:qword 
ICGetDisplayFormat TEXTEQU <__imp_ICGetDisplayFormat> 
extern __imp_ICGetInfo:qword 
ICGetInfo TEXTEQU <__imp_ICGetInfo> 
extern __imp_ICImageCompress:qword 
ICImageCompress TEXTEQU <__imp_ICImageCompress> 
extern __imp_ICImageDecompress:qword 
ICImageDecompress TEXTEQU <__imp_ICImageDecompress> 
extern __imp_ICInfo:qword 
ICInfo TEXTEQU <__imp_ICInfo> 
extern __imp_ICInstall:qword 
ICInstall TEXTEQU <__imp_ICInstall> 
extern __imp_ICLocate:qword 
ICLocate TEXTEQU <__imp_ICLocate> 
extern __imp_ICMThunk32:qword 
ICMThunk32 TEXTEQU <__imp_ICMThunk32> 
extern __imp_ICOpen:qword 
ICOpen TEXTEQU <__imp_ICOpen> 
extern __imp_ICOpenFunction:qword 
ICOpenFunction TEXTEQU <__imp_ICOpenFunction> 
extern __imp_ICRemove:qword 
ICRemove TEXTEQU <__imp_ICRemove> 
extern __imp_ICSendMessage:qword 
ICSendMessage TEXTEQU <__imp_ICSendMessage> 
extern __imp_ICSeqCompressFrame:qword 
ICSeqCompressFrame TEXTEQU <__imp_ICSeqCompressFrame> 
extern __imp_ICSeqCompressFrameEnd:qword 
ICSeqCompressFrameEnd TEXTEQU <__imp_ICSeqCompressFrameEnd> 
extern __imp_ICSeqCompressFrameStart:qword 
ICSeqCompressFrameStart TEXTEQU <__imp_ICSeqCompressFrameStart> 
extern __imp_MCIWndCreate:qword 
MCIWndCreate TEXTEQU <__imp_MCIWndCreate> 
extern __imp_MCIWndCreateA:qword 
MCIWndCreate TEXTEQU <__imp_MCIWndCreateA> 
extern __imp_MCIWndCreateW:qword 
MCIWndCreateW TEXTEQU <__imp_MCIWndCreateW> 
extern __imp_MCIWndRegisterClass:qword 
MCIWndRegisterClass TEXTEQU <__imp_MCIWndRegisterClass> 
extern __imp_StretchDIB:qword 
StretchDIB TEXTEQU <__imp_StretchDIB> 
extern __imp_VideoForWindowsVersion:qword 
VideoForWindowsVersion TEXTEQU <__imp_VideoForWindowsVersion> 
