extern __imp_BindMoniker:qword 
BindMoniker TEXTEQU <__imp_BindMoniker> 
extern __imp_CLIPFORMAT_UserFree:qword 
CLIPFORMAT_UserFree TEXTEQU <__imp_CLIPFORMAT_UserFree> 
extern __imp_CLIPFORMAT_UserFree64:qword 
CLIPFORMAT_UserFree64 TEXTEQU <__imp_CLIPFORMAT_UserFree64> 
extern __imp_CLIPFORMAT_UserMarshal:qword 
CLIPFORMAT_UserMarshal TEXTEQU <__imp_CLIPFORMAT_UserMarshal> 
extern __imp_CLIPFORMAT_UserMarshal64:qword 
CLIPFORMAT_UserMarshal64 TEXTEQU <__imp_CLIPFORMAT_UserMarshal64> 
extern __imp_CLIPFORMAT_UserSize:qword 
CLIPFORMAT_UserSize TEXTEQU <__imp_CLIPFORMAT_UserSize> 
extern __imp_CLIPFORMAT_UserSize64:qword 
CLIPFORMAT_UserSize64 TEXTEQU <__imp_CLIPFORMAT_UserSize64> 
extern __imp_CLIPFORMAT_UserUnmarshal:qword 
CLIPFORMAT_UserUnmarshal TEXTEQU <__imp_CLIPFORMAT_UserUnmarshal> 
extern __imp_CLIPFORMAT_UserUnmarshal64:qword 
CLIPFORMAT_UserUnmarshal64 TEXTEQU <__imp_CLIPFORMAT_UserUnmarshal64> 
extern __imp_CLSIDFromOle1Class:qword 
CLSIDFromOle1Class TEXTEQU <__imp_CLSIDFromOle1Class> 
extern __imp_CLSIDFromProgID:qword 
CLSIDFromProgID TEXTEQU <__imp_CLSIDFromProgID> 
extern __imp_CLSIDFromProgIDEx:qword 
CLSIDFromProgIDEx TEXTEQU <__imp_CLSIDFromProgIDEx> 
extern __imp_CLSIDFromString:qword 
CLSIDFromString TEXTEQU <__imp_CLSIDFromString> 
extern __imp_CoAddRefServerProcess:qword 
CoAddRefServerProcess TEXTEQU <__imp_CoAddRefServerProcess> 
extern __imp_CoAllowSetForegroundWindow:qword 
CoAllowSetForegroundWindow TEXTEQU <__imp_CoAllowSetForegroundWindow> 
extern __imp_CoBuildVersion:qword 
CoBuildVersion TEXTEQU <__imp_CoBuildVersion> 
extern __imp_CoCancelCall:qword 
CoCancelCall TEXTEQU <__imp_CoCancelCall> 
extern __imp_CoCopyProxy:qword 
CoCopyProxy TEXTEQU <__imp_CoCopyProxy> 
extern __imp_CoCreateFreeThreadedMarshaler:qword 
CoCreateFreeThreadedMarshaler TEXTEQU <__imp_CoCreateFreeThreadedMarshaler> 
extern __imp_CoCreateGuid:qword 
CoCreateGuid TEXTEQU <__imp_CoCreateGuid> 
extern __imp_CoCreateInstance:qword 
CoCreateInstance TEXTEQU <__imp_CoCreateInstance> 
extern __imp_CoCreateInstanceEx:qword 
CoCreateInstanceEx TEXTEQU <__imp_CoCreateInstanceEx> 
extern __imp_CoCreateObjectInContext:qword 
CoCreateObjectInContext TEXTEQU <__imp_CoCreateObjectInContext> 
extern __imp_CoDeactivateObject:qword 
CoDeactivateObject TEXTEQU <__imp_CoDeactivateObject> 
extern __imp_CoDisableCallCancellation:qword 
CoDisableCallCancellation TEXTEQU <__imp_CoDisableCallCancellation> 
extern __imp_CoDisconnectContext:qword 
CoDisconnectContext TEXTEQU <__imp_CoDisconnectContext> 
extern __imp_CoDisconnectObject:qword 
CoDisconnectObject TEXTEQU <__imp_CoDisconnectObject> 
extern __imp_CoDosDateTimeToFileTime:qword 
CoDosDateTimeToFileTime TEXTEQU <__imp_CoDosDateTimeToFileTime> 
extern __imp_CoEnableCallCancellation:qword 
CoEnableCallCancellation TEXTEQU <__imp_CoEnableCallCancellation> 
extern __imp_CoFileTimeNow:qword 
CoFileTimeNow TEXTEQU <__imp_CoFileTimeNow> 
extern __imp_CoFileTimeToDosDateTime:qword 
CoFileTimeToDosDateTime TEXTEQU <__imp_CoFileTimeToDosDateTime> 
extern __imp_CoFreeAllLibraries:qword 
CoFreeAllLibraries TEXTEQU <__imp_CoFreeAllLibraries> 
extern __imp_CoFreeLibrary:qword 
CoFreeLibrary TEXTEQU <__imp_CoFreeLibrary> 
extern __imp_CoFreeUnusedLibraries:qword 
CoFreeUnusedLibraries TEXTEQU <__imp_CoFreeUnusedLibraries> 
extern __imp_CoFreeUnusedLibrariesEx:qword 
CoFreeUnusedLibrariesEx TEXTEQU <__imp_CoFreeUnusedLibrariesEx> 
extern __imp_CoGetActivationState:qword 
CoGetActivationState TEXTEQU <__imp_CoGetActivationState> 
extern __imp_CoGetApartmentID:qword 
CoGetApartmentID TEXTEQU <__imp_CoGetApartmentID> 
extern __imp_CoGetApartmentType:qword 
CoGetApartmentType TEXTEQU <__imp_CoGetApartmentType> 
extern __imp_CoGetCallContext:qword 
CoGetCallContext TEXTEQU <__imp_CoGetCallContext> 
extern __imp_CoGetCallState:qword 
CoGetCallState TEXTEQU <__imp_CoGetCallState> 
extern __imp_CoGetCallerTID:qword 
CoGetCallerTID TEXTEQU <__imp_CoGetCallerTID> 
extern __imp_CoGetCancelObject:qword 
CoGetCancelObject TEXTEQU <__imp_CoGetCancelObject> 
extern __imp_CoGetClassObject:qword 
CoGetClassObject TEXTEQU <__imp_CoGetClassObject> 
extern __imp_CoGetClassVersion:qword 
CoGetClassVersion TEXTEQU <__imp_CoGetClassVersion> 
extern __imp_CoGetComCatalog:qword 
CoGetComCatalog TEXTEQU <__imp_CoGetComCatalog> 
extern __imp_CoGetContextToken:qword 
CoGetContextToken TEXTEQU <__imp_CoGetContextToken> 
extern __imp_CoGetCurrentLogicalThreadId:qword 
CoGetCurrentLogicalThreadId TEXTEQU <__imp_CoGetCurrentLogicalThreadId> 
extern __imp_CoGetCurrentProcess:qword 
CoGetCurrentProcess TEXTEQU <__imp_CoGetCurrentProcess> 
extern __imp_CoGetDefaultContext:qword 
CoGetDefaultContext TEXTEQU <__imp_CoGetDefaultContext> 
extern __imp_CoGetInstanceFromFile:qword 
CoGetInstanceFromFile TEXTEQU <__imp_CoGetInstanceFromFile> 
extern __imp_CoGetInstanceFromIStorage:qword 
CoGetInstanceFromIStorage TEXTEQU <__imp_CoGetInstanceFromIStorage> 
extern __imp_CoGetInterceptor:qword 
CoGetInterceptor TEXTEQU <__imp_CoGetInterceptor> 
extern __imp_CoGetInterceptorFromTypeInfo:qword 
CoGetInterceptorFromTypeInfo TEXTEQU <__imp_CoGetInterceptorFromTypeInfo> 
extern __imp_CoGetInterfaceAndReleaseStream:qword 
CoGetInterfaceAndReleaseStream TEXTEQU <__imp_CoGetInterfaceAndReleaseStream> 
extern __imp_CoGetMalloc:qword 
CoGetMalloc TEXTEQU <__imp_CoGetMalloc> 
extern __imp_CoGetMarshalSizeMax:qword 
CoGetMarshalSizeMax TEXTEQU <__imp_CoGetMarshalSizeMax> 
extern __imp_CoGetModuleType:qword 
CoGetModuleType TEXTEQU <__imp_CoGetModuleType> 
extern __imp_CoGetObject:qword 
CoGetObject TEXTEQU <__imp_CoGetObject> 
extern __imp_CoGetObjectContext:qword 
CoGetObjectContext TEXTEQU <__imp_CoGetObjectContext> 
extern __imp_CoGetPSClsid:qword 
CoGetPSClsid TEXTEQU <__imp_CoGetPSClsid> 
extern __imp_CoGetProcessIdentifier:qword 
CoGetProcessIdentifier TEXTEQU <__imp_CoGetProcessIdentifier> 
extern __imp_CoGetStandardMarshal:qword 
CoGetStandardMarshal TEXTEQU <__imp_CoGetStandardMarshal> 
extern __imp_CoGetStdMarshalEx:qword 
CoGetStdMarshalEx TEXTEQU <__imp_CoGetStdMarshalEx> 
extern __imp_CoGetSystemSecurityPermissions:qword 
CoGetSystemSecurityPermissions TEXTEQU <__imp_CoGetSystemSecurityPermissions> 
extern __imp_CoGetTreatAsClass:qword 
CoGetTreatAsClass TEXTEQU <__imp_CoGetTreatAsClass> 
extern __imp_CoImpersonateClient:qword 
CoImpersonateClient TEXTEQU <__imp_CoImpersonateClient> 
extern __imp_CoInitialize:qword 
CoInitialize TEXTEQU <__imp_CoInitialize> 
extern __imp_CoInitializeEx:qword 
CoInitializeEx TEXTEQU <__imp_CoInitializeEx> 
extern __imp_CoInitializeSecurity:qword 
CoInitializeSecurity TEXTEQU <__imp_CoInitializeSecurity> 
extern __imp_CoInitializeWOW:qword 
CoInitializeWOW TEXTEQU <__imp_CoInitializeWOW> 
extern __imp_CoInstall:qword 
CoInstall TEXTEQU <__imp_CoInstall> 
extern __imp_CoInvalidateRemoteMachineBindings:qword 
CoInvalidateRemoteMachineBindings TEXTEQU <__imp_CoInvalidateRemoteMachineBindings> 
extern __imp_CoIsHandlerConnected:qword 
CoIsHandlerConnected TEXTEQU <__imp_CoIsHandlerConnected> 
extern __imp_CoIsOle1Class:qword 
CoIsOle1Class TEXTEQU <__imp_CoIsOle1Class> 
extern __imp_CoLoadLibrary:qword 
CoLoadLibrary TEXTEQU <__imp_CoLoadLibrary> 
extern __imp_CoLockObjectExternal:qword 
CoLockObjectExternal TEXTEQU <__imp_CoLockObjectExternal> 
extern __imp_CoMarshalHresult:qword 
CoMarshalHresult TEXTEQU <__imp_CoMarshalHresult> 
extern __imp_CoMarshalInterThreadInterfaceInStream:qword 
CoMarshalInterThreadInterfaceInStream TEXTEQU <__imp_CoMarshalInterThreadInterfaceInStream> 
extern __imp_CoMarshalInterface:qword 
CoMarshalInterface TEXTEQU <__imp_CoMarshalInterface> 
extern __imp_CoPopServiceDomain:qword 
CoPopServiceDomain TEXTEQU <__imp_CoPopServiceDomain> 
extern __imp_CoPushServiceDomain:qword 
CoPushServiceDomain TEXTEQU <__imp_CoPushServiceDomain> 
extern __imp_CoQueryAuthenticationServices:qword 
CoQueryAuthenticationServices TEXTEQU <__imp_CoQueryAuthenticationServices> 
extern __imp_CoQueryClientBlanket:qword 
CoQueryClientBlanket TEXTEQU <__imp_CoQueryClientBlanket> 
extern __imp_CoQueryProxyBlanket:qword 
CoQueryProxyBlanket TEXTEQU <__imp_CoQueryProxyBlanket> 
extern __imp_CoQueryReleaseObject:qword 
CoQueryReleaseObject TEXTEQU <__imp_CoQueryReleaseObject> 
extern __imp_CoReactivateObject:qword 
CoReactivateObject TEXTEQU <__imp_CoReactivateObject> 
extern __imp_CoRegisterChannelHook:qword 
CoRegisterChannelHook TEXTEQU <__imp_CoRegisterChannelHook> 
extern __imp_CoRegisterClassObject:qword 
CoRegisterClassObject TEXTEQU <__imp_CoRegisterClassObject> 
extern __imp_CoRegisterInitializeSpy:qword 
CoRegisterInitializeSpy TEXTEQU <__imp_CoRegisterInitializeSpy> 
extern __imp_CoRegisterMallocSpy:qword 
CoRegisterMallocSpy TEXTEQU <__imp_CoRegisterMallocSpy> 
extern __imp_CoRegisterMessageFilter:qword 
CoRegisterMessageFilter TEXTEQU <__imp_CoRegisterMessageFilter> 
extern __imp_CoRegisterPSClsid:qword 
CoRegisterPSClsid TEXTEQU <__imp_CoRegisterPSClsid> 
extern __imp_CoRegisterSurrogate:qword 
CoRegisterSurrogate TEXTEQU <__imp_CoRegisterSurrogate> 
extern __imp_CoRegisterSurrogateEx:qword 
CoRegisterSurrogateEx TEXTEQU <__imp_CoRegisterSurrogateEx> 
extern __imp_CoReleaseMarshalData:qword 
CoReleaseMarshalData TEXTEQU <__imp_CoReleaseMarshalData> 
extern __imp_CoReleaseServerProcess:qword 
CoReleaseServerProcess TEXTEQU <__imp_CoReleaseServerProcess> 
extern __imp_CoResumeClassObjects:qword 
CoResumeClassObjects TEXTEQU <__imp_CoResumeClassObjects> 
extern __imp_CoRetireServer:qword 
CoRetireServer TEXTEQU <__imp_CoRetireServer> 
extern __imp_CoRevertToSelf:qword 
CoRevertToSelf TEXTEQU <__imp_CoRevertToSelf> 
extern __imp_CoRevokeClassObject:qword 
CoRevokeClassObject TEXTEQU <__imp_CoRevokeClassObject> 
extern __imp_CoRevokeInitializeSpy:qword 
CoRevokeInitializeSpy TEXTEQU <__imp_CoRevokeInitializeSpy> 
extern __imp_CoRevokeMallocSpy:qword 
CoRevokeMallocSpy TEXTEQU <__imp_CoRevokeMallocSpy> 
extern __imp_CoSetCancelObject:qword 
CoSetCancelObject TEXTEQU <__imp_CoSetCancelObject> 
extern __imp_CoSetProxyBlanket:qword 
CoSetProxyBlanket TEXTEQU <__imp_CoSetProxyBlanket> 
extern __imp_CoSetState:qword 
CoSetState TEXTEQU <__imp_CoSetState> 
extern __imp_CoSuspendClassObjects:qword 
CoSuspendClassObjects TEXTEQU <__imp_CoSuspendClassObjects> 
extern __imp_CoSwitchCallContext:qword 
CoSwitchCallContext TEXTEQU <__imp_CoSwitchCallContext> 
extern __imp_CoTaskMemAlloc:qword 
CoTaskMemAlloc TEXTEQU <__imp_CoTaskMemAlloc> 
extern __imp_CoTaskMemFree:qword 
CoTaskMemFree TEXTEQU <__imp_CoTaskMemFree> 
extern __imp_CoTaskMemRealloc:qword 
CoTaskMemRealloc TEXTEQU <__imp_CoTaskMemRealloc> 
extern __imp_CoTestCancel:qword 
CoTestCancel TEXTEQU <__imp_CoTestCancel> 
extern __imp_CoTreatAsClass:qword 
CoTreatAsClass TEXTEQU <__imp_CoTreatAsClass> 
extern __imp_CoUninitialize:qword 
CoUninitialize TEXTEQU <__imp_CoUninitialize> 
extern __imp_CoUnloadingWOW:qword 
CoUnloadingWOW TEXTEQU <__imp_CoUnloadingWOW> 
extern __imp_CoUnmarshalHresult:qword 
CoUnmarshalHresult TEXTEQU <__imp_CoUnmarshalHresult> 
extern __imp_CoUnmarshalInterface:qword 
CoUnmarshalInterface TEXTEQU <__imp_CoUnmarshalInterface> 
extern __imp_CoVrfCheckThreadState:qword 
CoVrfCheckThreadState TEXTEQU <__imp_CoVrfCheckThreadState> 
extern __imp_CoVrfGetThreadState:qword 
CoVrfGetThreadState TEXTEQU <__imp_CoVrfGetThreadState> 
extern __imp_CoVrfReleaseThreadState:qword 
CoVrfReleaseThreadState TEXTEQU <__imp_CoVrfReleaseThreadState> 
extern __imp_CoWaitForMultipleHandles:qword 
CoWaitForMultipleHandles TEXTEQU <__imp_CoWaitForMultipleHandles> 
extern __imp_ComPs_NdrDllCanUnloadNow:qword 
ComPs_NdrDllCanUnloadNow TEXTEQU <__imp_ComPs_NdrDllCanUnloadNow> 
extern __imp_ComPs_NdrDllGetClassObject:qword 
ComPs_NdrDllGetClassObject TEXTEQU <__imp_ComPs_NdrDllGetClassObject> 
extern __imp_ComPs_NdrDllRegisterProxy:qword 
ComPs_NdrDllRegisterProxy TEXTEQU <__imp_ComPs_NdrDllRegisterProxy> 
extern __imp_ComPs_NdrDllUnregisterProxy:qword 
ComPs_NdrDllUnregisterProxy TEXTEQU <__imp_ComPs_NdrDllUnregisterProxy> 
extern __imp_CreateAntiMoniker:qword 
CreateAntiMoniker TEXTEQU <__imp_CreateAntiMoniker> 
extern __imp_CreateBindCtx:qword 
CreateBindCtx TEXTEQU <__imp_CreateBindCtx> 
extern __imp_CreateClassMoniker:qword 
CreateClassMoniker TEXTEQU <__imp_CreateClassMoniker> 
extern __imp_CreateDataAdviseHolder:qword 
CreateDataAdviseHolder TEXTEQU <__imp_CreateDataAdviseHolder> 
extern __imp_CreateDataCache:qword 
CreateDataCache TEXTEQU <__imp_CreateDataCache> 
extern __imp_CreateErrorInfo:qword 
CreateErrorInfo TEXTEQU <__imp_CreateErrorInfo> 
extern __imp_CreateFileMoniker:qword 
CreateFileMoniker TEXTEQU <__imp_CreateFileMoniker> 
extern __imp_CreateGenericComposite:qword 
CreateGenericComposite TEXTEQU <__imp_CreateGenericComposite> 
extern __imp_CreateILockBytesOnHGlobal:qword 
CreateILockBytesOnHGlobal TEXTEQU <__imp_CreateILockBytesOnHGlobal> 
extern __imp_CreateItemMoniker:qword 
CreateItemMoniker TEXTEQU <__imp_CreateItemMoniker> 
extern __imp_CreateObjrefMoniker:qword 
CreateObjrefMoniker TEXTEQU <__imp_CreateObjrefMoniker> 
extern __imp_CreateOleAdviseHolder:qword 
CreateOleAdviseHolder TEXTEQU <__imp_CreateOleAdviseHolder> 
extern __imp_CreatePointerMoniker:qword 
CreatePointerMoniker TEXTEQU <__imp_CreatePointerMoniker> 
extern __imp_CreateStdProgressIndicator:qword 
CreateStdProgressIndicator TEXTEQU <__imp_CreateStdProgressIndicator> 
extern __imp_CreateStreamOnHGlobal:qword 
CreateStreamOnHGlobal TEXTEQU <__imp_CreateStreamOnHGlobal> 
extern __imp_DcomChannelSetHResult:qword 
DcomChannelSetHResult TEXTEQU <__imp_DcomChannelSetHResult> 
extern __imp_DllDebugObjectRPCHook:qword 
DllDebugObjectRPCHook TEXTEQU <__imp_DllDebugObjectRPCHook> 
extern __imp_DllGetClassObject:qword 
DllGetClassObject TEXTEQU <__imp_DllGetClassObject> 
extern __imp_DllGetClassObjectWOW:qword 
DllGetClassObjectWOW TEXTEQU <__imp_DllGetClassObjectWOW> 
extern __imp_DllRegisterServer:qword 
DllRegisterServer TEXTEQU <__imp_DllRegisterServer> 
extern __imp_DoDragDrop:qword 
DoDragDrop TEXTEQU <__imp_DoDragDrop> 
extern __imp_EnableHookObject:qword 
EnableHookObject TEXTEQU <__imp_EnableHookObject> 
extern __imp_FmtIdToPropStgName:qword 
FmtIdToPropStgName TEXTEQU <__imp_FmtIdToPropStgName> 
extern __imp_FreePropVariantArray:qword 
FreePropVariantArray TEXTEQU <__imp_FreePropVariantArray> 
extern __imp_GetClassFile:qword 
GetClassFile TEXTEQU <__imp_GetClassFile> 
extern __imp_GetConvertStg:qword 
GetConvertStg TEXTEQU <__imp_GetConvertStg> 
extern __imp_GetDocumentBitStg:qword 
GetDocumentBitStg TEXTEQU <__imp_GetDocumentBitStg> 
extern __imp_GetErrorInfo:qword 
GetErrorInfo TEXTEQU <__imp_GetErrorInfo> 
extern __imp_GetHGlobalFromILockBytes:qword 
GetHGlobalFromILockBytes TEXTEQU <__imp_GetHGlobalFromILockBytes> 
extern __imp_GetHGlobalFromStream:qword 
GetHGlobalFromStream TEXTEQU <__imp_GetHGlobalFromStream> 
extern __imp_GetHookInterface:qword 
GetHookInterface TEXTEQU <__imp_GetHookInterface> 
extern __imp_GetRunningObjectTable:qword 
GetRunningObjectTable TEXTEQU <__imp_GetRunningObjectTable> 
extern __imp_HACCEL_UserFree:qword 
HACCEL_UserFree TEXTEQU <__imp_HACCEL_UserFree> 
extern __imp_HACCEL_UserFree64:qword 
HACCEL_UserFree64 TEXTEQU <__imp_HACCEL_UserFree64> 
extern __imp_HACCEL_UserMarshal:qword 
HACCEL_UserMarshal TEXTEQU <__imp_HACCEL_UserMarshal> 
extern __imp_HACCEL_UserMarshal64:qword 
HACCEL_UserMarshal64 TEXTEQU <__imp_HACCEL_UserMarshal64> 
extern __imp_HACCEL_UserSize:qword 
HACCEL_UserSize TEXTEQU <__imp_HACCEL_UserSize> 
extern __imp_HACCEL_UserSize64:qword 
HACCEL_UserSize64 TEXTEQU <__imp_HACCEL_UserSize64> 
extern __imp_HACCEL_UserUnmarshal:qword 
HACCEL_UserUnmarshal TEXTEQU <__imp_HACCEL_UserUnmarshal> 
extern __imp_HACCEL_UserUnmarshal64:qword 
HACCEL_UserUnmarshal64 TEXTEQU <__imp_HACCEL_UserUnmarshal64> 
extern __imp_HBITMAP_UserFree:qword 
HBITMAP_UserFree TEXTEQU <__imp_HBITMAP_UserFree> 
extern __imp_HBITMAP_UserFree64:qword 
HBITMAP_UserFree64 TEXTEQU <__imp_HBITMAP_UserFree64> 
extern __imp_HBITMAP_UserMarshal:qword 
HBITMAP_UserMarshal TEXTEQU <__imp_HBITMAP_UserMarshal> 
extern __imp_HBITMAP_UserMarshal64:qword 
HBITMAP_UserMarshal64 TEXTEQU <__imp_HBITMAP_UserMarshal64> 
extern __imp_HBITMAP_UserSize:qword 
HBITMAP_UserSize TEXTEQU <__imp_HBITMAP_UserSize> 
extern __imp_HBITMAP_UserSize64:qword 
HBITMAP_UserSize64 TEXTEQU <__imp_HBITMAP_UserSize64> 
extern __imp_HBITMAP_UserUnmarshal:qword 
HBITMAP_UserUnmarshal TEXTEQU <__imp_HBITMAP_UserUnmarshal> 
extern __imp_HBITMAP_UserUnmarshal64:qword 
HBITMAP_UserUnmarshal64 TEXTEQU <__imp_HBITMAP_UserUnmarshal64> 
extern __imp_HBRUSH_UserFree:qword 
HBRUSH_UserFree TEXTEQU <__imp_HBRUSH_UserFree> 
extern __imp_HBRUSH_UserFree64:qword 
HBRUSH_UserFree64 TEXTEQU <__imp_HBRUSH_UserFree64> 
extern __imp_HBRUSH_UserMarshal:qword 
HBRUSH_UserMarshal TEXTEQU <__imp_HBRUSH_UserMarshal> 
extern __imp_HBRUSH_UserMarshal64:qword 
HBRUSH_UserMarshal64 TEXTEQU <__imp_HBRUSH_UserMarshal64> 
extern __imp_HBRUSH_UserSize:qword 
HBRUSH_UserSize TEXTEQU <__imp_HBRUSH_UserSize> 
extern __imp_HBRUSH_UserSize64:qword 
HBRUSH_UserSize64 TEXTEQU <__imp_HBRUSH_UserSize64> 
extern __imp_HBRUSH_UserUnmarshal:qword 
HBRUSH_UserUnmarshal TEXTEQU <__imp_HBRUSH_UserUnmarshal> 
extern __imp_HBRUSH_UserUnmarshal64:qword 
HBRUSH_UserUnmarshal64 TEXTEQU <__imp_HBRUSH_UserUnmarshal64> 
extern __imp_HDC_UserFree:qword 
HDC_UserFree TEXTEQU <__imp_HDC_UserFree> 
extern __imp_HDC_UserFree64:qword 
HDC_UserFree64 TEXTEQU <__imp_HDC_UserFree64> 
extern __imp_HDC_UserMarshal:qword 
HDC_UserMarshal TEXTEQU <__imp_HDC_UserMarshal> 
extern __imp_HDC_UserMarshal64:qword 
HDC_UserMarshal64 TEXTEQU <__imp_HDC_UserMarshal64> 
extern __imp_HDC_UserSize:qword 
HDC_UserSize TEXTEQU <__imp_HDC_UserSize> 
extern __imp_HDC_UserSize64:qword 
HDC_UserSize64 TEXTEQU <__imp_HDC_UserSize64> 
extern __imp_HDC_UserUnmarshal:qword 
HDC_UserUnmarshal TEXTEQU <__imp_HDC_UserUnmarshal> 
extern __imp_HDC_UserUnmarshal64:qword 
HDC_UserUnmarshal64 TEXTEQU <__imp_HDC_UserUnmarshal64> 
extern __imp_HENHMETAFILE_UserFree:qword 
HENHMETAFILE_UserFree TEXTEQU <__imp_HENHMETAFILE_UserFree> 
extern __imp_HENHMETAFILE_UserFree64:qword 
HENHMETAFILE_UserFree64 TEXTEQU <__imp_HENHMETAFILE_UserFree64> 
extern __imp_HENHMETAFILE_UserMarshal:qword 
HENHMETAFILE_UserMarshal TEXTEQU <__imp_HENHMETAFILE_UserMarshal> 
extern __imp_HENHMETAFILE_UserMarshal64:qword 
HENHMETAFILE_UserMarshal64 TEXTEQU <__imp_HENHMETAFILE_UserMarshal64> 
extern __imp_HENHMETAFILE_UserSize:qword 
HENHMETAFILE_UserSize TEXTEQU <__imp_HENHMETAFILE_UserSize> 
extern __imp_HENHMETAFILE_UserSize64:qword 
HENHMETAFILE_UserSize64 TEXTEQU <__imp_HENHMETAFILE_UserSize64> 
extern __imp_HENHMETAFILE_UserUnmarshal:qword 
HENHMETAFILE_UserUnmarshal TEXTEQU <__imp_HENHMETAFILE_UserUnmarshal> 
extern __imp_HENHMETAFILE_UserUnmarshal64:qword 
HENHMETAFILE_UserUnmarshal64 TEXTEQU <__imp_HENHMETAFILE_UserUnmarshal64> 
extern __imp_HGLOBAL_UserFree:qword 
HGLOBAL_UserFree TEXTEQU <__imp_HGLOBAL_UserFree> 
extern __imp_HGLOBAL_UserFree64:qword 
HGLOBAL_UserFree64 TEXTEQU <__imp_HGLOBAL_UserFree64> 
extern __imp_HGLOBAL_UserMarshal:qword 
HGLOBAL_UserMarshal TEXTEQU <__imp_HGLOBAL_UserMarshal> 
extern __imp_HGLOBAL_UserMarshal64:qword 
HGLOBAL_UserMarshal64 TEXTEQU <__imp_HGLOBAL_UserMarshal64> 
extern __imp_HGLOBAL_UserSize:qword 
HGLOBAL_UserSize TEXTEQU <__imp_HGLOBAL_UserSize> 
extern __imp_HGLOBAL_UserSize64:qword 
HGLOBAL_UserSize64 TEXTEQU <__imp_HGLOBAL_UserSize64> 
extern __imp_HGLOBAL_UserUnmarshal:qword 
HGLOBAL_UserUnmarshal TEXTEQU <__imp_HGLOBAL_UserUnmarshal> 
extern __imp_HGLOBAL_UserUnmarshal64:qword 
HGLOBAL_UserUnmarshal64 TEXTEQU <__imp_HGLOBAL_UserUnmarshal64> 
extern __imp_HICON_UserFree:qword 
HICON_UserFree TEXTEQU <__imp_HICON_UserFree> 
extern __imp_HICON_UserFree64:qword 
HICON_UserFree64 TEXTEQU <__imp_HICON_UserFree64> 
extern __imp_HICON_UserMarshal:qword 
HICON_UserMarshal TEXTEQU <__imp_HICON_UserMarshal> 
extern __imp_HICON_UserMarshal64:qword 
HICON_UserMarshal64 TEXTEQU <__imp_HICON_UserMarshal64> 
extern __imp_HICON_UserSize:qword 
HICON_UserSize TEXTEQU <__imp_HICON_UserSize> 
extern __imp_HICON_UserSize64:qword 
HICON_UserSize64 TEXTEQU <__imp_HICON_UserSize64> 
extern __imp_HICON_UserUnmarshal:qword 
HICON_UserUnmarshal TEXTEQU <__imp_HICON_UserUnmarshal> 
extern __imp_HICON_UserUnmarshal64:qword 
HICON_UserUnmarshal64 TEXTEQU <__imp_HICON_UserUnmarshal64> 
extern __imp_HMENU_UserFree:qword 
HMENU_UserFree TEXTEQU <__imp_HMENU_UserFree> 
extern __imp_HMENU_UserFree64:qword 
HMENU_UserFree64 TEXTEQU <__imp_HMENU_UserFree64> 
extern __imp_HMENU_UserMarshal:qword 
HMENU_UserMarshal TEXTEQU <__imp_HMENU_UserMarshal> 
extern __imp_HMENU_UserMarshal64:qword 
HMENU_UserMarshal64 TEXTEQU <__imp_HMENU_UserMarshal64> 
extern __imp_HMENU_UserSize:qword 
HMENU_UserSize TEXTEQU <__imp_HMENU_UserSize> 
extern __imp_HMENU_UserSize64:qword 
HMENU_UserSize64 TEXTEQU <__imp_HMENU_UserSize64> 
extern __imp_HMENU_UserUnmarshal:qword 
HMENU_UserUnmarshal TEXTEQU <__imp_HMENU_UserUnmarshal> 
extern __imp_HMENU_UserUnmarshal64:qword 
HMENU_UserUnmarshal64 TEXTEQU <__imp_HMENU_UserUnmarshal64> 
extern __imp_HMETAFILEPICT_UserFree:qword 
HMETAFILEPICT_UserFree TEXTEQU <__imp_HMETAFILEPICT_UserFree> 
extern __imp_HMETAFILEPICT_UserFree64:qword 
HMETAFILEPICT_UserFree64 TEXTEQU <__imp_HMETAFILEPICT_UserFree64> 
extern __imp_HMETAFILEPICT_UserMarshal:qword 
HMETAFILEPICT_UserMarshal TEXTEQU <__imp_HMETAFILEPICT_UserMarshal> 
extern __imp_HMETAFILEPICT_UserMarshal64:qword 
HMETAFILEPICT_UserMarshal64 TEXTEQU <__imp_HMETAFILEPICT_UserMarshal64> 
extern __imp_HMETAFILEPICT_UserSize:qword 
HMETAFILEPICT_UserSize TEXTEQU <__imp_HMETAFILEPICT_UserSize> 
extern __imp_HMETAFILEPICT_UserSize64:qword 
HMETAFILEPICT_UserSize64 TEXTEQU <__imp_HMETAFILEPICT_UserSize64> 
extern __imp_HMETAFILEPICT_UserUnmarshal:qword 
HMETAFILEPICT_UserUnmarshal TEXTEQU <__imp_HMETAFILEPICT_UserUnmarshal> 
extern __imp_HMETAFILEPICT_UserUnmarshal64:qword 
HMETAFILEPICT_UserUnmarshal64 TEXTEQU <__imp_HMETAFILEPICT_UserUnmarshal64> 
extern __imp_HMETAFILE_UserFree:qword 
HMETAFILE_UserFree TEXTEQU <__imp_HMETAFILE_UserFree> 
extern __imp_HMETAFILE_UserFree64:qword 
HMETAFILE_UserFree64 TEXTEQU <__imp_HMETAFILE_UserFree64> 
extern __imp_HMETAFILE_UserMarshal:qword 
HMETAFILE_UserMarshal TEXTEQU <__imp_HMETAFILE_UserMarshal> 
extern __imp_HMETAFILE_UserMarshal64:qword 
HMETAFILE_UserMarshal64 TEXTEQU <__imp_HMETAFILE_UserMarshal64> 
extern __imp_HMETAFILE_UserSize:qword 
HMETAFILE_UserSize TEXTEQU <__imp_HMETAFILE_UserSize> 
extern __imp_HMETAFILE_UserSize64:qword 
HMETAFILE_UserSize64 TEXTEQU <__imp_HMETAFILE_UserSize64> 
extern __imp_HMETAFILE_UserUnmarshal:qword 
HMETAFILE_UserUnmarshal TEXTEQU <__imp_HMETAFILE_UserUnmarshal> 
extern __imp_HMETAFILE_UserUnmarshal64:qword 
HMETAFILE_UserUnmarshal64 TEXTEQU <__imp_HMETAFILE_UserUnmarshal64> 
extern __imp_HPALETTE_UserFree:qword 
HPALETTE_UserFree TEXTEQU <__imp_HPALETTE_UserFree> 
extern __imp_HPALETTE_UserFree64:qword 
HPALETTE_UserFree64 TEXTEQU <__imp_HPALETTE_UserFree64> 
extern __imp_HPALETTE_UserMarshal:qword 
HPALETTE_UserMarshal TEXTEQU <__imp_HPALETTE_UserMarshal> 
extern __imp_HPALETTE_UserMarshal64:qword 
HPALETTE_UserMarshal64 TEXTEQU <__imp_HPALETTE_UserMarshal64> 
extern __imp_HPALETTE_UserSize:qword 
HPALETTE_UserSize TEXTEQU <__imp_HPALETTE_UserSize> 
extern __imp_HPALETTE_UserSize64:qword 
HPALETTE_UserSize64 TEXTEQU <__imp_HPALETTE_UserSize64> 
extern __imp_HPALETTE_UserUnmarshal:qword 
HPALETTE_UserUnmarshal TEXTEQU <__imp_HPALETTE_UserUnmarshal> 
extern __imp_HPALETTE_UserUnmarshal64:qword 
HPALETTE_UserUnmarshal64 TEXTEQU <__imp_HPALETTE_UserUnmarshal64> 
extern __imp_HRGN_UserFree:qword 
HRGN_UserFree TEXTEQU <__imp_HRGN_UserFree> 
extern __imp_HRGN_UserMarshal:qword 
HRGN_UserMarshal TEXTEQU <__imp_HRGN_UserMarshal> 
extern __imp_HRGN_UserSize:qword 
HRGN_UserSize TEXTEQU <__imp_HRGN_UserSize> 
extern __imp_HRGN_UserUnmarshal:qword 
HRGN_UserUnmarshal TEXTEQU <__imp_HRGN_UserUnmarshal> 
extern __imp_HWND_UserFree:qword 
HWND_UserFree TEXTEQU <__imp_HWND_UserFree> 
extern __imp_HWND_UserFree64:qword 
HWND_UserFree64 TEXTEQU <__imp_HWND_UserFree64> 
extern __imp_HWND_UserMarshal:qword 
HWND_UserMarshal TEXTEQU <__imp_HWND_UserMarshal> 
extern __imp_HWND_UserMarshal64:qword 
HWND_UserMarshal64 TEXTEQU <__imp_HWND_UserMarshal64> 
extern __imp_HWND_UserSize:qword 
HWND_UserSize TEXTEQU <__imp_HWND_UserSize> 
extern __imp_HWND_UserSize64:qword 
HWND_UserSize64 TEXTEQU <__imp_HWND_UserSize64> 
extern __imp_HWND_UserUnmarshal:qword 
HWND_UserUnmarshal TEXTEQU <__imp_HWND_UserUnmarshal> 
extern __imp_HWND_UserUnmarshal64:qword 
HWND_UserUnmarshal64 TEXTEQU <__imp_HWND_UserUnmarshal64> 
extern __imp_HkOleRegisterObject:qword 
HkOleRegisterObject TEXTEQU <__imp_HkOleRegisterObject> 
extern __imp_IIDFromString:qword 
IIDFromString TEXTEQU <__imp_IIDFromString> 
extern __imp_IsAccelerator:qword 
IsAccelerator TEXTEQU <__imp_IsAccelerator> 
extern __imp_IsEqualGUID:qword 
IsEqualGUID TEXTEQU <__imp_IsEqualGUID> 
extern __imp_IsValidIid:qword 
IsValidIid TEXTEQU <__imp_IsValidIid> 
extern __imp_IsValidInterface:qword 
IsValidInterface TEXTEQU <__imp_IsValidInterface> 
extern __imp_IsValidPtrIn:qword 
IsValidPtrIn TEXTEQU <__imp_IsValidPtrIn> 
extern __imp_IsValidPtrOut:qword 
IsValidPtrOut TEXTEQU <__imp_IsValidPtrOut> 
extern __imp_MkParseDisplayName:qword 
MkParseDisplayName TEXTEQU <__imp_MkParseDisplayName> 
extern __imp_MonikerCommonPrefixWith:qword 
MonikerCommonPrefixWith TEXTEQU <__imp_MonikerCommonPrefixWith> 
extern __imp_MonikerRelativePathTo:qword 
MonikerRelativePathTo TEXTEQU <__imp_MonikerRelativePathTo> 
extern __imp_NdrOleInitializeExtension:qword 
NdrOleInitializeExtension TEXTEQU <__imp_NdrOleInitializeExtension> 
extern __imp_NdrProxyForwardingFunction10:qword 
NdrProxyForwardingFunction10 TEXTEQU <__imp_NdrProxyForwardingFunction10> 
extern __imp_NdrProxyForwardingFunction11:qword 
NdrProxyForwardingFunction11 TEXTEQU <__imp_NdrProxyForwardingFunction11> 
extern __imp_NdrProxyForwardingFunction12:qword 
NdrProxyForwardingFunction12 TEXTEQU <__imp_NdrProxyForwardingFunction12> 
extern __imp_NdrProxyForwardingFunction13:qword 
NdrProxyForwardingFunction13 TEXTEQU <__imp_NdrProxyForwardingFunction13> 
extern __imp_NdrProxyForwardingFunction14:qword 
NdrProxyForwardingFunction14 TEXTEQU <__imp_NdrProxyForwardingFunction14> 
extern __imp_NdrProxyForwardingFunction15:qword 
NdrProxyForwardingFunction15 TEXTEQU <__imp_NdrProxyForwardingFunction15> 
extern __imp_NdrProxyForwardingFunction16:qword 
NdrProxyForwardingFunction16 TEXTEQU <__imp_NdrProxyForwardingFunction16> 
extern __imp_NdrProxyForwardingFunction17:qword 
NdrProxyForwardingFunction17 TEXTEQU <__imp_NdrProxyForwardingFunction17> 
extern __imp_NdrProxyForwardingFunction18:qword 
NdrProxyForwardingFunction18 TEXTEQU <__imp_NdrProxyForwardingFunction18> 
extern __imp_NdrProxyForwardingFunction19:qword 
NdrProxyForwardingFunction19 TEXTEQU <__imp_NdrProxyForwardingFunction19> 
extern __imp_NdrProxyForwardingFunction20:qword 
NdrProxyForwardingFunction20 TEXTEQU <__imp_NdrProxyForwardingFunction20> 
extern __imp_NdrProxyForwardingFunction21:qword 
NdrProxyForwardingFunction21 TEXTEQU <__imp_NdrProxyForwardingFunction21> 
extern __imp_NdrProxyForwardingFunction22:qword 
NdrProxyForwardingFunction22 TEXTEQU <__imp_NdrProxyForwardingFunction22> 
extern __imp_NdrProxyForwardingFunction23:qword 
NdrProxyForwardingFunction23 TEXTEQU <__imp_NdrProxyForwardingFunction23> 
extern __imp_NdrProxyForwardingFunction24:qword 
NdrProxyForwardingFunction24 TEXTEQU <__imp_NdrProxyForwardingFunction24> 
extern __imp_NdrProxyForwardingFunction25:qword 
NdrProxyForwardingFunction25 TEXTEQU <__imp_NdrProxyForwardingFunction25> 
extern __imp_NdrProxyForwardingFunction26:qword 
NdrProxyForwardingFunction26 TEXTEQU <__imp_NdrProxyForwardingFunction26> 
extern __imp_NdrProxyForwardingFunction27:qword 
NdrProxyForwardingFunction27 TEXTEQU <__imp_NdrProxyForwardingFunction27> 
extern __imp_NdrProxyForwardingFunction28:qword 
NdrProxyForwardingFunction28 TEXTEQU <__imp_NdrProxyForwardingFunction28> 
extern __imp_NdrProxyForwardingFunction29:qword 
NdrProxyForwardingFunction29 TEXTEQU <__imp_NdrProxyForwardingFunction29> 
extern __imp_NdrProxyForwardingFunction3:qword 
NdrProxyForwardingFunction3 TEXTEQU <__imp_NdrProxyForwardingFunction3> 
extern __imp_NdrProxyForwardingFunction30:qword 
NdrProxyForwardingFunction30 TEXTEQU <__imp_NdrProxyForwardingFunction30> 
extern __imp_NdrProxyForwardingFunction31:qword 
NdrProxyForwardingFunction31 TEXTEQU <__imp_NdrProxyForwardingFunction31> 
extern __imp_NdrProxyForwardingFunction32:qword 
NdrProxyForwardingFunction32 TEXTEQU <__imp_NdrProxyForwardingFunction32> 
extern __imp_NdrProxyForwardingFunction4:qword 
NdrProxyForwardingFunction4 TEXTEQU <__imp_NdrProxyForwardingFunction4> 
extern __imp_NdrProxyForwardingFunction5:qword 
NdrProxyForwardingFunction5 TEXTEQU <__imp_NdrProxyForwardingFunction5> 
extern __imp_NdrProxyForwardingFunction6:qword 
NdrProxyForwardingFunction6 TEXTEQU <__imp_NdrProxyForwardingFunction6> 
extern __imp_NdrProxyForwardingFunction7:qword 
NdrProxyForwardingFunction7 TEXTEQU <__imp_NdrProxyForwardingFunction7> 
extern __imp_NdrProxyForwardingFunction8:qword 
NdrProxyForwardingFunction8 TEXTEQU <__imp_NdrProxyForwardingFunction8> 
extern __imp_NdrProxyForwardingFunction9:qword 
NdrProxyForwardingFunction9 TEXTEQU <__imp_NdrProxyForwardingFunction9> 
extern __imp_ObjectStublessClient10:qword 
ObjectStublessClient10 TEXTEQU <__imp_ObjectStublessClient10> 
extern __imp_ObjectStublessClient11:qword 
ObjectStublessClient11 TEXTEQU <__imp_ObjectStublessClient11> 
extern __imp_ObjectStublessClient12:qword 
ObjectStublessClient12 TEXTEQU <__imp_ObjectStublessClient12> 
extern __imp_ObjectStublessClient13:qword 
ObjectStublessClient13 TEXTEQU <__imp_ObjectStublessClient13> 
extern __imp_ObjectStublessClient14:qword 
ObjectStublessClient14 TEXTEQU <__imp_ObjectStublessClient14> 
extern __imp_ObjectStublessClient15:qword 
ObjectStublessClient15 TEXTEQU <__imp_ObjectStublessClient15> 
extern __imp_ObjectStublessClient16:qword 
ObjectStublessClient16 TEXTEQU <__imp_ObjectStublessClient16> 
extern __imp_ObjectStublessClient17:qword 
ObjectStublessClient17 TEXTEQU <__imp_ObjectStublessClient17> 
extern __imp_ObjectStublessClient18:qword 
ObjectStublessClient18 TEXTEQU <__imp_ObjectStublessClient18> 
extern __imp_ObjectStublessClient19:qword 
ObjectStublessClient19 TEXTEQU <__imp_ObjectStublessClient19> 
extern __imp_ObjectStublessClient20:qword 
ObjectStublessClient20 TEXTEQU <__imp_ObjectStublessClient20> 
extern __imp_ObjectStublessClient21:qword 
ObjectStublessClient21 TEXTEQU <__imp_ObjectStublessClient21> 
extern __imp_ObjectStublessClient22:qword 
ObjectStublessClient22 TEXTEQU <__imp_ObjectStublessClient22> 
extern __imp_ObjectStublessClient23:qword 
ObjectStublessClient23 TEXTEQU <__imp_ObjectStublessClient23> 
extern __imp_ObjectStublessClient24:qword 
ObjectStublessClient24 TEXTEQU <__imp_ObjectStublessClient24> 
extern __imp_ObjectStublessClient25:qword 
ObjectStublessClient25 TEXTEQU <__imp_ObjectStublessClient25> 
extern __imp_ObjectStublessClient26:qword 
ObjectStublessClient26 TEXTEQU <__imp_ObjectStublessClient26> 
extern __imp_ObjectStublessClient27:qword 
ObjectStublessClient27 TEXTEQU <__imp_ObjectStublessClient27> 
extern __imp_ObjectStublessClient28:qword 
ObjectStublessClient28 TEXTEQU <__imp_ObjectStublessClient28> 
extern __imp_ObjectStublessClient29:qword 
ObjectStublessClient29 TEXTEQU <__imp_ObjectStublessClient29> 
extern __imp_ObjectStublessClient3:qword 
ObjectStublessClient3 TEXTEQU <__imp_ObjectStublessClient3> 
extern __imp_ObjectStublessClient30:qword 
ObjectStublessClient30 TEXTEQU <__imp_ObjectStublessClient30> 
extern __imp_ObjectStublessClient31:qword 
ObjectStublessClient31 TEXTEQU <__imp_ObjectStublessClient31> 
extern __imp_ObjectStublessClient32:qword 
ObjectStublessClient32 TEXTEQU <__imp_ObjectStublessClient32> 
extern __imp_ObjectStublessClient4:qword 
ObjectStublessClient4 TEXTEQU <__imp_ObjectStublessClient4> 
extern __imp_ObjectStublessClient5:qword 
ObjectStublessClient5 TEXTEQU <__imp_ObjectStublessClient5> 
extern __imp_ObjectStublessClient6:qword 
ObjectStublessClient6 TEXTEQU <__imp_ObjectStublessClient6> 
extern __imp_ObjectStublessClient7:qword 
ObjectStublessClient7 TEXTEQU <__imp_ObjectStublessClient7> 
extern __imp_ObjectStublessClient8:qword 
ObjectStublessClient8 TEXTEQU <__imp_ObjectStublessClient8> 
extern __imp_ObjectStublessClient9:qword 
ObjectStublessClient9 TEXTEQU <__imp_ObjectStublessClient9> 
extern __imp_OleBuildVersion:qword 
OleBuildVersion TEXTEQU <__imp_OleBuildVersion> 
extern __imp_OleConvertIStorageToOLESTREAM:qword 
OleConvertIStorageToOLESTREAM TEXTEQU <__imp_OleConvertIStorageToOLESTREAM> 
extern __imp_OleConvertIStorageToOLESTREAMEx:qword 
OleConvertIStorageToOLESTREAMEx TEXTEQU <__imp_OleConvertIStorageToOLESTREAMEx> 
extern __imp_OleConvertOLESTREAMToIStorage:qword 
OleConvertOLESTREAMToIStorage TEXTEQU <__imp_OleConvertOLESTREAMToIStorage> 
extern __imp_OleConvertOLESTREAMToIStorageEx:qword 
OleConvertOLESTREAMToIStorageEx TEXTEQU <__imp_OleConvertOLESTREAMToIStorageEx> 
extern __imp_OleCreate:qword 
OleCreate TEXTEQU <__imp_OleCreate> 
extern __imp_OleCreateDefaultHandler:qword 
OleCreateDefaultHandler TEXTEQU <__imp_OleCreateDefaultHandler> 
extern __imp_OleCreateEmbeddingHelper:qword 
OleCreateEmbeddingHelper TEXTEQU <__imp_OleCreateEmbeddingHelper> 
extern __imp_OleCreateEx:qword 
OleCreateEx TEXTEQU <__imp_OleCreateEx> 
extern __imp_OleCreateFromData:qword 
OleCreateFromData TEXTEQU <__imp_OleCreateFromData> 
extern __imp_OleCreateFromDataEx:qword 
OleCreateFromDataEx TEXTEQU <__imp_OleCreateFromDataEx> 
extern __imp_OleCreateFromFile:qword 
OleCreateFromFile TEXTEQU <__imp_OleCreateFromFile> 
extern __imp_OleCreateFromFileEx:qword 
OleCreateFromFileEx TEXTEQU <__imp_OleCreateFromFileEx> 
extern __imp_OleCreateLink:qword 
OleCreateLink TEXTEQU <__imp_OleCreateLink> 
extern __imp_OleCreateLinkEx:qword 
OleCreateLinkEx TEXTEQU <__imp_OleCreateLinkEx> 
extern __imp_OleCreateLinkFromData:qword 
OleCreateLinkFromData TEXTEQU <__imp_OleCreateLinkFromData> 
extern __imp_OleCreateLinkFromDataEx:qword 
OleCreateLinkFromDataEx TEXTEQU <__imp_OleCreateLinkFromDataEx> 
extern __imp_OleCreateLinkToFile:qword 
OleCreateLinkToFile TEXTEQU <__imp_OleCreateLinkToFile> 
extern __imp_OleCreateLinkToFileEx:qword 
OleCreateLinkToFileEx TEXTEQU <__imp_OleCreateLinkToFileEx> 
extern __imp_OleCreateMenuDescriptor:qword 
OleCreateMenuDescriptor TEXTEQU <__imp_OleCreateMenuDescriptor> 
extern __imp_OleCreateStaticFromData:qword 
OleCreateStaticFromData TEXTEQU <__imp_OleCreateStaticFromData> 
extern __imp_OleDestroyMenuDescriptor:qword 
OleDestroyMenuDescriptor TEXTEQU <__imp_OleDestroyMenuDescriptor> 
extern __imp_OleDoAutoConvert:qword 
OleDoAutoConvert TEXTEQU <__imp_OleDoAutoConvert> 
extern __imp_OleDraw:qword 
OleDraw TEXTEQU <__imp_OleDraw> 
extern __imp_OleDuplicateData:qword 
OleDuplicateData TEXTEQU <__imp_OleDuplicateData> 
extern __imp_OleFlushClipboard:qword 
OleFlushClipboard TEXTEQU <__imp_OleFlushClipboard> 
extern __imp_OleGetAutoConvert:qword 
OleGetAutoConvert TEXTEQU <__imp_OleGetAutoConvert> 
extern __imp_OleGetClipboard:qword 
OleGetClipboard TEXTEQU <__imp_OleGetClipboard> 
extern __imp_OleGetIconOfClass:qword 
OleGetIconOfClass TEXTEQU <__imp_OleGetIconOfClass> 
extern __imp_OleGetIconOfFile:qword 
OleGetIconOfFile TEXTEQU <__imp_OleGetIconOfFile> 
extern __imp_OleInitialize:qword 
OleInitialize TEXTEQU <__imp_OleInitialize> 
extern __imp_OleInitializeWOW:qword 
OleInitializeWOW TEXTEQU <__imp_OleInitializeWOW> 
extern __imp_OleIsCurrentClipboard:qword 
OleIsCurrentClipboard TEXTEQU <__imp_OleIsCurrentClipboard> 
extern __imp_OleIsRunning:qword 
OleIsRunning TEXTEQU <__imp_OleIsRunning> 
extern __imp_OleLoad:qword 
OleLoad TEXTEQU <__imp_OleLoad> 
extern __imp_OleLoadFromStream:qword 
OleLoadFromStream TEXTEQU <__imp_OleLoadFromStream> 
extern __imp_OleLockRunning:qword 
OleLockRunning TEXTEQU <__imp_OleLockRunning> 
extern __imp_OleMetafilePictFromIconAndLabel:qword 
OleMetafilePictFromIconAndLabel TEXTEQU <__imp_OleMetafilePictFromIconAndLabel> 
extern __imp_OleNoteObjectVisible:qword 
OleNoteObjectVisible TEXTEQU <__imp_OleNoteObjectVisible> 
extern __imp_OleQueryCreateFromData:qword 
OleQueryCreateFromData TEXTEQU <__imp_OleQueryCreateFromData> 
extern __imp_OleQueryLinkFromData:qword 
OleQueryLinkFromData TEXTEQU <__imp_OleQueryLinkFromData> 
extern __imp_OleRegEnumFormatEtc:qword 
OleRegEnumFormatEtc TEXTEQU <__imp_OleRegEnumFormatEtc> 
extern __imp_OleRegEnumVerbs:qword 
OleRegEnumVerbs TEXTEQU <__imp_OleRegEnumVerbs> 
extern __imp_OleRegGetMiscStatus:qword 
OleRegGetMiscStatus TEXTEQU <__imp_OleRegGetMiscStatus> 
extern __imp_OleRegGetUserType:qword 
OleRegGetUserType TEXTEQU <__imp_OleRegGetUserType> 
extern __imp_OleRun:qword 
OleRun TEXTEQU <__imp_OleRun> 
extern __imp_OleSave:qword 
OleSave TEXTEQU <__imp_OleSave> 
extern __imp_OleSaveToStream:qword 
OleSaveToStream TEXTEQU <__imp_OleSaveToStream> 
extern __imp_OleSetAutoConvert:qword 
OleSetAutoConvert TEXTEQU <__imp_OleSetAutoConvert> 
extern __imp_OleSetClipboard:qword 
OleSetClipboard TEXTEQU <__imp_OleSetClipboard> 
extern __imp_OleSetContainedObject:qword 
OleSetContainedObject TEXTEQU <__imp_OleSetContainedObject> 
extern __imp_OleSetMenuDescriptor:qword 
OleSetMenuDescriptor TEXTEQU <__imp_OleSetMenuDescriptor> 
extern __imp_OleTranslateAccelerator:qword 
OleTranslateAccelerator TEXTEQU <__imp_OleTranslateAccelerator> 
extern __imp_OleUninitialize:qword 
OleUninitialize TEXTEQU <__imp_OleUninitialize> 
extern __imp_OpenOrCreateStream:qword 
OpenOrCreateStream TEXTEQU <__imp_OpenOrCreateStream> 
extern __imp_ProgIDFromCLSID:qword 
ProgIDFromCLSID TEXTEQU <__imp_ProgIDFromCLSID> 
extern __imp_PropStgNameToFmtId:qword 
PropStgNameToFmtId TEXTEQU <__imp_PropStgNameToFmtId> 
extern __imp_PropSysAllocString:qword 
PropSysAllocString TEXTEQU <__imp_PropSysAllocString> 
extern __imp_PropSysFreeString:qword 
PropSysFreeString TEXTEQU <__imp_PropSysFreeString> 
extern __imp_PropVariantChangeType:qword 
PropVariantChangeType TEXTEQU <__imp_PropVariantChangeType> 
extern __imp_PropVariantClear:qword 
PropVariantClear TEXTEQU <__imp_PropVariantClear> 
extern __imp_PropVariantCopy:qword 
PropVariantCopy TEXTEQU <__imp_PropVariantCopy> 
extern __imp_ReadClassStg:qword 
ReadClassStg TEXTEQU <__imp_ReadClassStg> 
extern __imp_ReadClassStm:qword 
ReadClassStm TEXTEQU <__imp_ReadClassStm> 
extern __imp_ReadFmtUserTypeStg:qword 
ReadFmtUserTypeStg TEXTEQU <__imp_ReadFmtUserTypeStg> 
extern __imp_ReadOleStg:qword 
ReadOleStg TEXTEQU <__imp_ReadOleStg> 
extern __imp_ReadStringStream:qword 
ReadStringStream TEXTEQU <__imp_ReadStringStream> 
extern __imp_RegisterDragDrop:qword 
RegisterDragDrop TEXTEQU <__imp_RegisterDragDrop> 
extern __imp_ReleaseStgMedium:qword 
ReleaseStgMedium TEXTEQU <__imp_ReleaseStgMedium> 
extern __imp_RevokeDragDrop:qword 
RevokeDragDrop TEXTEQU <__imp_RevokeDragDrop> 
extern __imp_SNB_UserFree:qword 
SNB_UserFree TEXTEQU <__imp_SNB_UserFree> 
extern __imp_SNB_UserFree64:qword 
SNB_UserFree64 TEXTEQU <__imp_SNB_UserFree64> 
extern __imp_SNB_UserMarshal:qword 
SNB_UserMarshal TEXTEQU <__imp_SNB_UserMarshal> 
extern __imp_SNB_UserMarshal64:qword 
SNB_UserMarshal64 TEXTEQU <__imp_SNB_UserMarshal64> 
extern __imp_SNB_UserSize:qword 
SNB_UserSize TEXTEQU <__imp_SNB_UserSize> 
extern __imp_SNB_UserSize64:qword 
SNB_UserSize64 TEXTEQU <__imp_SNB_UserSize64> 
extern __imp_SNB_UserUnmarshal:qword 
SNB_UserUnmarshal TEXTEQU <__imp_SNB_UserUnmarshal> 
extern __imp_SNB_UserUnmarshal64:qword 
SNB_UserUnmarshal64 TEXTEQU <__imp_SNB_UserUnmarshal64> 
extern __imp_STGMEDIUM_UserFree:qword 
STGMEDIUM_UserFree TEXTEQU <__imp_STGMEDIUM_UserFree> 
extern __imp_STGMEDIUM_UserFree64:qword 
STGMEDIUM_UserFree64 TEXTEQU <__imp_STGMEDIUM_UserFree64> 
extern __imp_STGMEDIUM_UserMarshal:qword 
STGMEDIUM_UserMarshal TEXTEQU <__imp_STGMEDIUM_UserMarshal> 
extern __imp_STGMEDIUM_UserMarshal64:qword 
STGMEDIUM_UserMarshal64 TEXTEQU <__imp_STGMEDIUM_UserMarshal64> 
extern __imp_STGMEDIUM_UserSize:qword 
STGMEDIUM_UserSize TEXTEQU <__imp_STGMEDIUM_UserSize> 
extern __imp_STGMEDIUM_UserSize64:qword 
STGMEDIUM_UserSize64 TEXTEQU <__imp_STGMEDIUM_UserSize64> 
extern __imp_STGMEDIUM_UserUnmarshal:qword 
STGMEDIUM_UserUnmarshal TEXTEQU <__imp_STGMEDIUM_UserUnmarshal> 
extern __imp_STGMEDIUM_UserUnmarshal64:qword 
STGMEDIUM_UserUnmarshal64 TEXTEQU <__imp_STGMEDIUM_UserUnmarshal64> 
extern __imp_SetConvertStg:qword 
SetConvertStg TEXTEQU <__imp_SetConvertStg> 
extern __imp_SetDocumentBitStg:qword 
SetDocumentBitStg TEXTEQU <__imp_SetDocumentBitStg> 
extern __imp_SetErrorInfo:qword 
SetErrorInfo TEXTEQU <__imp_SetErrorInfo> 
extern __imp_StgConvertPropertyToVariant:qword 
StgConvertPropertyToVariant TEXTEQU <__imp_StgConvertPropertyToVariant> 
extern __imp_StgConvertVariantToProperty:qword 
StgConvertVariantToProperty TEXTEQU <__imp_StgConvertVariantToProperty> 
extern __imp_StgCreateDocfile:qword 
StgCreateDocfile TEXTEQU <__imp_StgCreateDocfile> 
extern __imp_StgCreateDocfileOnILockBytes:qword 
StgCreateDocfileOnILockBytes TEXTEQU <__imp_StgCreateDocfileOnILockBytes> 
extern __imp_StgCreatePropSetStg:qword 
StgCreatePropSetStg TEXTEQU <__imp_StgCreatePropSetStg> 
extern __imp_StgCreatePropStg:qword 
StgCreatePropStg TEXTEQU <__imp_StgCreatePropStg> 
extern __imp_StgCreateStorageEx:qword 
StgCreateStorageEx TEXTEQU <__imp_StgCreateStorageEx> 
extern __imp_StgGetIFillLockBytesOnFile:qword 
StgGetIFillLockBytesOnFile TEXTEQU <__imp_StgGetIFillLockBytesOnFile> 
extern __imp_StgGetIFillLockBytesOnILockBytes:qword 
StgGetIFillLockBytesOnILockBytes TEXTEQU <__imp_StgGetIFillLockBytesOnILockBytes> 
extern __imp_StgIsStorageFile:qword 
StgIsStorageFile TEXTEQU <__imp_StgIsStorageFile> 
extern __imp_StgIsStorageILockBytes:qword 
StgIsStorageILockBytes TEXTEQU <__imp_StgIsStorageILockBytes> 
extern __imp_StgOpenAsyncDocfileOnIFillLockBytes:qword 
StgOpenAsyncDocfileOnIFillLockBytes TEXTEQU <__imp_StgOpenAsyncDocfileOnIFillLockBytes> 
extern __imp_StgOpenPropStg:qword 
StgOpenPropStg TEXTEQU <__imp_StgOpenPropStg> 
extern __imp_StgOpenStorage:qword 
StgOpenStorage TEXTEQU <__imp_StgOpenStorage> 
extern __imp_StgOpenStorageEx:qword 
StgOpenStorageEx TEXTEQU <__imp_StgOpenStorageEx> 
extern __imp_StgOpenStorageOnHandle:qword 
StgOpenStorageOnHandle TEXTEQU <__imp_StgOpenStorageOnHandle> 
extern __imp_StgOpenStorageOnILockBytes:qword 
StgOpenStorageOnILockBytes TEXTEQU <__imp_StgOpenStorageOnILockBytes> 
extern __imp_StgPropertyLengthAsVariant:qword 
StgPropertyLengthAsVariant TEXTEQU <__imp_StgPropertyLengthAsVariant> 
extern __imp_StgSetTimes:qword 
StgSetTimes TEXTEQU <__imp_StgSetTimes> 
extern __imp_StringFromCLSID:qword 
StringFromCLSID TEXTEQU <__imp_StringFromCLSID> 
extern __imp_StringFromGUID2:qword 
StringFromGUID2 TEXTEQU <__imp_StringFromGUID2> 
extern __imp_StringFromIID:qword 
StringFromIID TEXTEQU <__imp_StringFromIID> 
extern __imp_UpdateDCOMSettings:qword 
UpdateDCOMSettings TEXTEQU <__imp_UpdateDCOMSettings> 
extern __imp_UpdateProcessTracing:qword 
UpdateProcessTracing TEXTEQU <__imp_UpdateProcessTracing> 
extern __imp_UtConvertDvtd16toDvtd32:qword 
UtConvertDvtd16toDvtd32 TEXTEQU <__imp_UtConvertDvtd16toDvtd32> 
extern __imp_UtConvertDvtd32toDvtd16:qword 
UtConvertDvtd32toDvtd16 TEXTEQU <__imp_UtConvertDvtd32toDvtd16> 
extern __imp_UtGetDvtd16Info:qword 
UtGetDvtd16Info TEXTEQU <__imp_UtGetDvtd16Info> 
extern __imp_UtGetDvtd32Info:qword 
UtGetDvtd32Info TEXTEQU <__imp_UtGetDvtd32Info> 
extern __imp_WdtpInterfacePointer_UserFree:qword 
WdtpInterfacePointer_UserFree TEXTEQU <__imp_WdtpInterfacePointer_UserFree> 
extern __imp_WdtpInterfacePointer_UserFree64:qword 
WdtpInterfacePointer_UserFree64 TEXTEQU <__imp_WdtpInterfacePointer_UserFree64> 
extern __imp_WdtpInterfacePointer_UserMarshal:qword 
WdtpInterfacePointer_UserMarshal TEXTEQU <__imp_WdtpInterfacePointer_UserMarshal> 
extern __imp_WdtpInterfacePointer_UserMarshal64:qword 
WdtpInterfacePointer_UserMarshal64 TEXTEQU <__imp_WdtpInterfacePointer_UserMarshal64> 
extern __imp_WdtpInterfacePointer_UserSize:qword 
WdtpInterfacePointer_UserSize TEXTEQU <__imp_WdtpInterfacePointer_UserSize> 
extern __imp_WdtpInterfacePointer_UserSize64:qword 
WdtpInterfacePointer_UserSize64 TEXTEQU <__imp_WdtpInterfacePointer_UserSize64> 
extern __imp_WdtpInterfacePointer_UserUnmarshal:qword 
WdtpInterfacePointer_UserUnmarshal TEXTEQU <__imp_WdtpInterfacePointer_UserUnmarshal> 
extern __imp_WdtpInterfacePointer_UserUnmarshal64:qword 
WdtpInterfacePointer_UserUnmarshal64 TEXTEQU <__imp_WdtpInterfacePointer_UserUnmarshal64> 
extern __imp_WriteClassStg:qword 
WriteClassStg TEXTEQU <__imp_WriteClassStg> 
extern __imp_WriteClassStm:qword 
WriteClassStm TEXTEQU <__imp_WriteClassStm> 
extern __imp_WriteFmtUserTypeStg:qword 
WriteFmtUserTypeStg TEXTEQU <__imp_WriteFmtUserTypeStg> 
extern __imp_WriteOleStg:qword 
WriteOleStg TEXTEQU <__imp_WriteOleStg> 
extern __imp_WriteStringStream:qword 
WriteStringStream TEXTEQU <__imp_WriteStringStream> 
