extern __imp_AppCompat_RunDLLW:qword 
AppCompat_RunDLLW TEXTEQU <__imp_AppCompat_RunDLLW> 
extern __imp_AssocCreateForClasses:qword 
AssocCreateForClasses TEXTEQU <__imp_AssocCreateForClasses> 
extern __imp_AssocGetDetailsOfPropKey:qword 
AssocGetDetailsOfPropKey TEXTEQU <__imp_AssocGetDetailsOfPropKey> 
extern __imp_CDefFolderMenu_Create2:qword 
CDefFolderMenu_Create2 TEXTEQU <__imp_CDefFolderMenu_Create2> 
extern __imp_CIDLData_CreateFromIDArray:qword 
CIDLData_CreateFromIDArray TEXTEQU <__imp_CIDLData_CreateFromIDArray> 
extern __imp_CheckEscapesW:qword 
CheckEscapesW TEXTEQU <__imp_CheckEscapesW> 
extern __imp_CommandLineToArgvW:qword 
CommandLineToArgvW TEXTEQU <__imp_CommandLineToArgvW> 
extern __imp_Control_RunDLL:qword 
Control_RunDLL TEXTEQU <__imp_Control_RunDLL> 
extern __imp_Control_RunDLLA:qword 
Control_RunDLL TEXTEQU <__imp_Control_RunDLLA> 
extern __imp_Control_RunDLLAsUserW:qword 
Control_RunDLLAsUserW TEXTEQU <__imp_Control_RunDLLAsUserW> 
extern __imp_Control_RunDLLW:qword 
Control_RunDLLW TEXTEQU <__imp_Control_RunDLLW> 
extern __imp_DAD_AutoScroll:qword 
DAD_AutoScroll TEXTEQU <__imp_DAD_AutoScroll> 
extern __imp_DAD_DragEnterEx:qword 
DAD_DragEnterEx TEXTEQU <__imp_DAD_DragEnterEx> 
extern __imp_DAD_DragEnterEx2:qword 
DAD_DragEnterEx2 TEXTEQU <__imp_DAD_DragEnterEx2> 
extern __imp_DAD_DragLeave:qword 
DAD_DragLeave TEXTEQU <__imp_DAD_DragLeave> 
extern __imp_DAD_DragMove:qword 
DAD_DragMove TEXTEQU <__imp_DAD_DragMove> 
extern __imp_DAD_SetDragImage:qword 
DAD_SetDragImage TEXTEQU <__imp_DAD_SetDragImage> 
extern __imp_DAD_ShowDragImage:qword 
DAD_ShowDragImage TEXTEQU <__imp_DAD_ShowDragImage> 
extern __imp_DllCanUnloadNow:qword 
DllCanUnloadNow TEXTEQU <__imp_DllCanUnloadNow> 
extern __imp_DllGetClassObject:qword 
DllGetClassObject TEXTEQU <__imp_DllGetClassObject> 
extern __imp_DllGetVersion:qword 
DllGetVersion TEXTEQU <__imp_DllGetVersion> 
extern __imp_DllInstall:qword 
DllInstall TEXTEQU <__imp_DllInstall> 
extern __imp_DllRegisterServer:qword 
DllRegisterServer TEXTEQU <__imp_DllRegisterServer> 
extern __imp_DllUnregisterServer:qword 
DllUnregisterServer TEXTEQU <__imp_DllUnregisterServer> 
extern __imp_DoEnvironmentSubstA:qword 
DoEnvironmentSubst TEXTEQU <__imp_DoEnvironmentSubstA> 
extern __imp_DoEnvironmentSubstW:qword 
DoEnvironmentSubstW TEXTEQU <__imp_DoEnvironmentSubstW> 
extern __imp_DragAcceptFiles:qword 
DragAcceptFiles TEXTEQU <__imp_DragAcceptFiles> 
extern __imp_DragFinish:qword 
DragFinish TEXTEQU <__imp_DragFinish> 
extern __imp_DragQueryFile:qword 
DragQueryFile TEXTEQU <__imp_DragQueryFile> 
extern __imp_DragQueryFileA:qword 
DragQueryFile TEXTEQU <__imp_DragQueryFileA> 
extern __imp_DragQueryFileAorW:qword 
DragQueryFileAorW TEXTEQU <__imp_DragQueryFileAorW> 
extern __imp_DragQueryFileW:qword 
DragQueryFileW TEXTEQU <__imp_DragQueryFileW> 
extern __imp_DragQueryPoint:qword 
DragQueryPoint TEXTEQU <__imp_DragQueryPoint> 
extern __imp_DriveType:qword 
DriveType TEXTEQU <__imp_DriveType> 
extern __imp_DuplicateIcon:qword 
DuplicateIcon TEXTEQU <__imp_DuplicateIcon> 
extern __imp_ExtractAssociatedIconA:qword 
ExtractAssociatedIcon TEXTEQU <__imp_ExtractAssociatedIconA> 
extern __imp_ExtractAssociatedIconExA:qword 
ExtractAssociatedIconEx TEXTEQU <__imp_ExtractAssociatedIconExA> 
extern __imp_ExtractAssociatedIconExW:qword 
ExtractAssociatedIconExW TEXTEQU <__imp_ExtractAssociatedIconExW> 
extern __imp_ExtractAssociatedIconW:qword 
ExtractAssociatedIconW TEXTEQU <__imp_ExtractAssociatedIconW> 
extern __imp_ExtractIconA:qword 
ExtractIcon TEXTEQU <__imp_ExtractIconA> 
extern __imp_ExtractIconEx:qword 
ExtractIconEx TEXTEQU <__imp_ExtractIconEx> 
extern __imp_ExtractIconExA:qword 
ExtractIconEx TEXTEQU <__imp_ExtractIconExA> 
extern __imp_ExtractIconExW:qword 
ExtractIconExW TEXTEQU <__imp_ExtractIconExW> 
extern __imp_ExtractIconW:qword 
ExtractIconW TEXTEQU <__imp_ExtractIconW> 
extern __imp_FindExecutableA:qword 
FindExecutable TEXTEQU <__imp_FindExecutableA> 
extern __imp_FindExecutableW:qword 
FindExecutableW TEXTEQU <__imp_FindExecutableW> 
extern __imp_FreeIconList:qword 
FreeIconList TEXTEQU <__imp_FreeIconList> 
extern __imp_GetCurrentProcessExplicitAppUserModelID:qword 
GetCurrentProcessExplicitAppUserModelID TEXTEQU <__imp_GetCurrentProcessExplicitAppUserModelID> 
extern __imp_GetFileNameFromBrowse:qword 
GetFileNameFromBrowse TEXTEQU <__imp_GetFileNameFromBrowse> 
extern __imp_ILAppendID:qword 
ILAppendID TEXTEQU <__imp_ILAppendID> 
extern __imp_ILClone:qword 
ILClone TEXTEQU <__imp_ILClone> 
extern __imp_ILCloneFirst:qword 
ILCloneFirst TEXTEQU <__imp_ILCloneFirst> 
extern __imp_ILCombine:qword 
ILCombine TEXTEQU <__imp_ILCombine> 
extern __imp_ILCreateFromPath:qword 
ILCreateFromPath TEXTEQU <__imp_ILCreateFromPath> 
extern __imp_ILCreateFromPathA:qword 
ILCreateFromPath TEXTEQU <__imp_ILCreateFromPathA> 
extern __imp_ILCreateFromPathW:qword 
ILCreateFromPathW TEXTEQU <__imp_ILCreateFromPathW> 
extern __imp_ILFindChild:qword 
ILFindChild TEXTEQU <__imp_ILFindChild> 
extern __imp_ILFindLastID:qword 
ILFindLastID TEXTEQU <__imp_ILFindLastID> 
extern __imp_ILFree:qword 
ILFree TEXTEQU <__imp_ILFree> 
extern __imp_ILGetNext:qword 
ILGetNext TEXTEQU <__imp_ILGetNext> 
extern __imp_ILGetSize:qword 
ILGetSize TEXTEQU <__imp_ILGetSize> 
extern __imp_ILIsEqual:qword 
ILIsEqual TEXTEQU <__imp_ILIsEqual> 
extern __imp_ILIsParent:qword 
ILIsParent TEXTEQU <__imp_ILIsParent> 
extern __imp_ILLoadFromStreamEx:qword 
ILLoadFromStreamEx TEXTEQU <__imp_ILLoadFromStreamEx> 
extern __imp_ILRemoveLastID:qword 
ILRemoveLastID TEXTEQU <__imp_ILRemoveLastID> 
extern __imp_ILSaveToStream:qword 
ILSaveToStream TEXTEQU <__imp_ILSaveToStream> 
extern __imp_InitNetworkAddressControl:qword 
InitNetworkAddressControl TEXTEQU <__imp_InitNetworkAddressControl> 
extern __imp_InternalExtractIconListA:qword 
InternalExtractIconList TEXTEQU <__imp_InternalExtractIconListA> 
extern __imp_InternalExtractIconListW:qword 
InternalExtractIconListW TEXTEQU <__imp_InternalExtractIconListW> 
extern __imp_IsLFNDrive:qword 
IsLFNDrive TEXTEQU <__imp_IsLFNDrive> 
extern __imp_IsLFNDriveA:qword 
IsLFNDrive TEXTEQU <__imp_IsLFNDriveA> 
extern __imp_IsLFNDriveW:qword 
IsLFNDriveW TEXTEQU <__imp_IsLFNDriveW> 
extern __imp_IsNetDrive:qword 
IsNetDrive TEXTEQU <__imp_IsNetDrive> 
extern __imp_IsUserAnAdmin:qword 
IsUserAnAdmin TEXTEQU <__imp_IsUserAnAdmin> 
extern __imp_LaunchMSHelp_RunDLLW:qword 
LaunchMSHelp_RunDLLW TEXTEQU <__imp_LaunchMSHelp_RunDLLW> 
extern __imp_OpenAs_RunDLL:qword 
OpenAs_RunDLL TEXTEQU <__imp_OpenAs_RunDLL> 
extern __imp_OpenAs_RunDLLA:qword 
OpenAs_RunDLL TEXTEQU <__imp_OpenAs_RunDLLA> 
extern __imp_OpenAs_RunDLLW:qword 
OpenAs_RunDLLW TEXTEQU <__imp_OpenAs_RunDLLW> 
extern __imp_OpenRegStream:qword 
OpenRegStream TEXTEQU <__imp_OpenRegStream> 
extern __imp_Options_RunDLL:qword 
Options_RunDLL TEXTEQU <__imp_Options_RunDLL> 
extern __imp_Options_RunDLLA:qword 
Options_RunDLL TEXTEQU <__imp_Options_RunDLLA> 
extern __imp_Options_RunDLLW:qword 
Options_RunDLLW TEXTEQU <__imp_Options_RunDLLW> 
extern __imp_PathCleanupSpec:qword 
PathCleanupSpec TEXTEQU <__imp_PathCleanupSpec> 
extern __imp_PathGetShortPath:qword 
PathGetShortPath TEXTEQU <__imp_PathGetShortPath> 
extern __imp_PathIsExe:qword 
PathIsExe TEXTEQU <__imp_PathIsExe> 
extern __imp_PathIsSlowA:qword 
PathIsSlow TEXTEQU <__imp_PathIsSlowA> 
extern __imp_PathIsSlowW:qword 
PathIsSlowW TEXTEQU <__imp_PathIsSlowW> 
extern __imp_PathMakeUniqueName:qword 
PathMakeUniqueName TEXTEQU <__imp_PathMakeUniqueName> 
extern __imp_PathQualify:qword 
PathQualify TEXTEQU <__imp_PathQualify> 
extern __imp_PathResolve:qword 
PathResolve TEXTEQU <__imp_PathResolve> 
extern __imp_PathYetAnotherMakeUniqueName:qword 
PathYetAnotherMakeUniqueName TEXTEQU <__imp_PathYetAnotherMakeUniqueName> 
extern __imp_PickIconDlg:qword 
PickIconDlg TEXTEQU <__imp_PickIconDlg> 
extern __imp_PifMgr_CloseProperties:qword 
PifMgr_CloseProperties TEXTEQU <__imp_PifMgr_CloseProperties> 
extern __imp_PifMgr_GetProperties:qword 
PifMgr_GetProperties TEXTEQU <__imp_PifMgr_GetProperties> 
extern __imp_PifMgr_OpenProperties:qword 
PifMgr_OpenProperties TEXTEQU <__imp_PifMgr_OpenProperties> 
extern __imp_PifMgr_SetProperties:qword 
PifMgr_SetProperties TEXTEQU <__imp_PifMgr_SetProperties> 
extern __imp_PrepareDiscForBurnRunDllW:qword 
PrepareDiscForBurnRunDllW TEXTEQU <__imp_PrepareDiscForBurnRunDllW> 
extern __imp_PrintersGetCommand_RunDLL:qword 
PrintersGetCommand_RunDLL TEXTEQU <__imp_PrintersGetCommand_RunDLL> 
extern __imp_PrintersGetCommand_RunDLLA:qword 
PrintersGetCommand_RunDLL TEXTEQU <__imp_PrintersGetCommand_RunDLLA> 
extern __imp_PrintersGetCommand_RunDLLW:qword 
PrintersGetCommand_RunDLLW TEXTEQU <__imp_PrintersGetCommand_RunDLLW> 
extern __imp_ReadCabinetState:qword 
ReadCabinetState TEXTEQU <__imp_ReadCabinetState> 
extern __imp_RealDriveType:qword 
RealDriveType TEXTEQU <__imp_RealDriveType> 
extern __imp_RealShellExecuteA:qword 
RealShellExecute TEXTEQU <__imp_RealShellExecuteA> 
extern __imp_RealShellExecuteExA:qword 
RealShellExecuteEx TEXTEQU <__imp_RealShellExecuteExA> 
extern __imp_RealShellExecuteExW:qword 
RealShellExecuteExW TEXTEQU <__imp_RealShellExecuteExW> 
extern __imp_RealShellExecuteW:qword 
RealShellExecuteW TEXTEQU <__imp_RealShellExecuteW> 
extern __imp_RegenerateUserEnvironment:qword 
RegenerateUserEnvironment TEXTEQU <__imp_RegenerateUserEnvironment> 
extern __imp_RestartDialog:qword 
RestartDialog TEXTEQU <__imp_RestartDialog> 
extern __imp_RestartDialogEx:qword 
RestartDialogEx TEXTEQU <__imp_RestartDialogEx> 
extern __imp_RunAsNewUser_RunDLLW:qword 
RunAsNewUser_RunDLLW TEXTEQU <__imp_RunAsNewUser_RunDLLW> 
extern __imp_SHAddDefaultPropertiesByExt:qword 
SHAddDefaultPropertiesByExt TEXTEQU <__imp_SHAddDefaultPropertiesByExt> 
extern __imp_SHAddFromPropSheetExtArray:qword 
SHAddFromPropSheetExtArray TEXTEQU <__imp_SHAddFromPropSheetExtArray> 
extern __imp_SHAddToRecentDocs:qword 
SHAddToRecentDocs TEXTEQU <__imp_SHAddToRecentDocs> 
extern __imp_SHAlloc:qword 
SHAlloc TEXTEQU <__imp_SHAlloc> 
extern __imp_SHAppBarMessage:qword 
SHAppBarMessage TEXTEQU <__imp_SHAppBarMessage> 
extern __imp_SHAssocEnumHandlers:qword 
SHAssocEnumHandlers TEXTEQU <__imp_SHAssocEnumHandlers> 
extern __imp_SHAssocEnumHandlersForProtocolByApplication:qword 
SHAssocEnumHandlersForProtocolByApplication TEXTEQU <__imp_SHAssocEnumHandlersForProtocolByApplication> 
extern __imp_SHBindToFolderIDListParent:qword 
SHBindToFolderIDListParent TEXTEQU <__imp_SHBindToFolderIDListParent> 
extern __imp_SHBindToFolderIDListParentEx:qword 
SHBindToFolderIDListParentEx TEXTEQU <__imp_SHBindToFolderIDListParentEx> 
extern __imp_SHBindToObject:qword 
SHBindToObject TEXTEQU <__imp_SHBindToObject> 
extern __imp_SHBindToParent:qword 
SHBindToParent TEXTEQU <__imp_SHBindToParent> 
extern __imp_SHBrowseForFolder:qword 
SHBrowseForFolder TEXTEQU <__imp_SHBrowseForFolder> 
extern __imp_SHBrowseForFolderA:qword 
SHBrowseForFolder TEXTEQU <__imp_SHBrowseForFolderA> 
extern __imp_SHBrowseForFolderW:qword 
SHBrowseForFolderW TEXTEQU <__imp_SHBrowseForFolderW> 
extern __imp_SHCLSIDFromString:qword 
SHCLSIDFromString TEXTEQU <__imp_SHCLSIDFromString> 
extern __imp_SHChangeNotification_Lock:qword 
SHChangeNotification_Lock TEXTEQU <__imp_SHChangeNotification_Lock> 
extern __imp_SHChangeNotification_Unlock:qword 
SHChangeNotification_Unlock TEXTEQU <__imp_SHChangeNotification_Unlock> 
extern __imp_SHChangeNotify:qword 
SHChangeNotify TEXTEQU <__imp_SHChangeNotify> 
extern __imp_SHChangeNotifyDeregister:qword 
SHChangeNotifyDeregister TEXTEQU <__imp_SHChangeNotifyDeregister> 
extern __imp_SHChangeNotifyRegister:qword 
SHChangeNotifyRegister TEXTEQU <__imp_SHChangeNotifyRegister> 
extern __imp_SHChangeNotifyRegisterThread:qword 
SHChangeNotifyRegisterThread TEXTEQU <__imp_SHChangeNotifyRegisterThread> 
extern __imp_SHChangeNotifySuspendResume:qword 
SHChangeNotifySuspendResume TEXTEQU <__imp_SHChangeNotifySuspendResume> 
extern __imp_SHCloneSpecialIDList:qword 
SHCloneSpecialIDList TEXTEQU <__imp_SHCloneSpecialIDList> 
extern __imp_SHCoCreateInstance:qword 
SHCoCreateInstance TEXTEQU <__imp_SHCoCreateInstance> 
extern __imp_SHCreateAssociationRegistration:qword 
SHCreateAssociationRegistration TEXTEQU <__imp_SHCreateAssociationRegistration> 
extern __imp_SHCreateDataObject:qword 
SHCreateDataObject TEXTEQU <__imp_SHCreateDataObject> 
extern __imp_SHCreateDefaultContextMenu:qword 
SHCreateDefaultContextMenu TEXTEQU <__imp_SHCreateDefaultContextMenu> 
extern __imp_SHCreateDefaultExtractIcon:qword 
SHCreateDefaultExtractIcon TEXTEQU <__imp_SHCreateDefaultExtractIcon> 
extern __imp_SHCreateDefaultPropertiesOp:qword 
SHCreateDefaultPropertiesOp TEXTEQU <__imp_SHCreateDefaultPropertiesOp> 
extern __imp_SHCreateDirectory:qword 
SHCreateDirectory TEXTEQU <__imp_SHCreateDirectory> 
extern __imp_SHCreateDirectoryExA:qword 
SHCreateDirectoryEx TEXTEQU <__imp_SHCreateDirectoryExA> 
extern __imp_SHCreateDirectoryExW:qword 
SHCreateDirectoryExW TEXTEQU <__imp_SHCreateDirectoryExW> 
extern __imp_SHCreateFileExtractIconW:qword 
SHCreateFileExtractIconW TEXTEQU <__imp_SHCreateFileExtractIconW> 
extern __imp_SHCreateItemFromIDList:qword 
SHCreateItemFromIDList TEXTEQU <__imp_SHCreateItemFromIDList> 
extern __imp_SHCreateItemFromParsingName:qword 
SHCreateItemFromParsingName TEXTEQU <__imp_SHCreateItemFromParsingName> 
extern __imp_SHCreateItemFromRelativeName:qword 
SHCreateItemFromRelativeName TEXTEQU <__imp_SHCreateItemFromRelativeName> 
extern __imp_SHCreateItemInKnownFolder:qword 
SHCreateItemInKnownFolder TEXTEQU <__imp_SHCreateItemInKnownFolder> 
extern __imp_SHCreateItemWithParent:qword 
SHCreateItemWithParent TEXTEQU <__imp_SHCreateItemWithParent> 
extern __imp_SHCreateLocalServerRunDll:qword 
SHCreateLocalServerRunDll TEXTEQU <__imp_SHCreateLocalServerRunDll> 
extern __imp_SHCreateProcessAsUserW:qword 
SHCreateProcessAsUserW TEXTEQU <__imp_SHCreateProcessAsUserW> 
extern __imp_SHCreatePropSheetExtArray:qword 
SHCreatePropSheetExtArray TEXTEQU <__imp_SHCreatePropSheetExtArray> 
extern __imp_SHCreateQueryCancelAutoPlayMoniker:qword 
SHCreateQueryCancelAutoPlayMoniker TEXTEQU <__imp_SHCreateQueryCancelAutoPlayMoniker> 
extern __imp_SHCreateShellFolderView:qword 
SHCreateShellFolderView TEXTEQU <__imp_SHCreateShellFolderView> 
extern __imp_SHCreateShellFolderViewEx:qword 
SHCreateShellFolderViewEx TEXTEQU <__imp_SHCreateShellFolderViewEx> 
extern __imp_SHCreateShellItem:qword 
SHCreateShellItem TEXTEQU <__imp_SHCreateShellItem> 
extern __imp_SHCreateShellItemArray:qword 
SHCreateShellItemArray TEXTEQU <__imp_SHCreateShellItemArray> 
extern __imp_SHCreateShellItemArrayFromDataObject:qword 
SHCreateShellItemArrayFromDataObject TEXTEQU <__imp_SHCreateShellItemArrayFromDataObject> 
extern __imp_SHCreateShellItemArrayFromIDLists:qword 
SHCreateShellItemArrayFromIDLists TEXTEQU <__imp_SHCreateShellItemArrayFromIDLists> 
extern __imp_SHCreateShellItemArrayFromShellItem:qword 
SHCreateShellItemArrayFromShellItem TEXTEQU <__imp_SHCreateShellItemArrayFromShellItem> 
extern __imp_SHCreateStdEnumFmtEtc:qword 
SHCreateStdEnumFmtEtc TEXTEQU <__imp_SHCreateStdEnumFmtEtc> 
extern __imp_SHDefExtractIconA:qword 
SHDefExtractIcon TEXTEQU <__imp_SHDefExtractIconA> 
extern __imp_SHDefExtractIconW:qword 
SHDefExtractIconW TEXTEQU <__imp_SHDefExtractIconW> 
extern __imp_SHDestroyPropSheetExtArray:qword 
SHDestroyPropSheetExtArray TEXTEQU <__imp_SHDestroyPropSheetExtArray> 
extern __imp_SHDoDragDrop:qword 
SHDoDragDrop TEXTEQU <__imp_SHDoDragDrop> 
extern __imp_SHEmptyRecycleBinA:qword 
SHEmptyRecycleBin TEXTEQU <__imp_SHEmptyRecycleBinA> 
extern __imp_SHEmptyRecycleBinW:qword 
SHEmptyRecycleBinW TEXTEQU <__imp_SHEmptyRecycleBinW> 
extern __imp_SHEnableServiceObject:qword 
SHEnableServiceObject TEXTEQU <__imp_SHEnableServiceObject> 
extern __imp_SHEnumerateUnreadMailAccountsW:qword 
SHEnumerateUnreadMailAccountsW TEXTEQU <__imp_SHEnumerateUnreadMailAccountsW> 
extern __imp_SHEvaluateSystemCommandTemplate:qword 
SHEvaluateSystemCommandTemplate TEXTEQU <__imp_SHEvaluateSystemCommandTemplate> 
extern __imp_SHExtractIconsW:qword 
SHExtractIconsW TEXTEQU <__imp_SHExtractIconsW> 
extern __imp_SHFileOperation:qword 
SHFileOperation TEXTEQU <__imp_SHFileOperation> 
extern __imp_SHFileOperationA:qword 
SHFileOperation TEXTEQU <__imp_SHFileOperationA> 
extern __imp_SHFileOperationW:qword 
SHFileOperationW TEXTEQU <__imp_SHFileOperationW> 
extern __imp_SHFindFiles:qword 
SHFindFiles TEXTEQU <__imp_SHFindFiles> 
extern __imp_SHFind_InitMenuPopup:qword 
SHFind_InitMenuPopup TEXTEQU <__imp_SHFind_InitMenuPopup> 
extern __imp_SHFlushSFCache:qword 
SHFlushSFCache TEXTEQU <__imp_SHFlushSFCache> 
extern __imp_SHFormatDrive:qword 
SHFormatDrive TEXTEQU <__imp_SHFormatDrive> 
extern __imp_SHFree:qword 
SHFree TEXTEQU <__imp_SHFree> 
extern __imp_SHFreeNameMappings:qword 
SHFreeNameMappings TEXTEQU <__imp_SHFreeNameMappings> 
extern __imp_SHGetAttributesFromDataObject:qword 
SHGetAttributesFromDataObject TEXTEQU <__imp_SHGetAttributesFromDataObject> 
extern __imp_SHGetDataFromIDListA:qword 
SHGetDataFromIDList TEXTEQU <__imp_SHGetDataFromIDListA> 
extern __imp_SHGetDataFromIDListW:qword 
SHGetDataFromIDListW TEXTEQU <__imp_SHGetDataFromIDListW> 
extern __imp_SHGetDesktopFolder:qword 
SHGetDesktopFolder TEXTEQU <__imp_SHGetDesktopFolder> 
extern __imp_SHGetDiskFreeSpaceA:qword 
SHGetDiskFreeSpace TEXTEQU <__imp_SHGetDiskFreeSpaceA> 
extern __imp_SHGetDiskFreeSpaceExA:qword 
SHGetDiskFreeSpaceEx TEXTEQU <__imp_SHGetDiskFreeSpaceExA> 
extern __imp_SHGetDiskFreeSpaceExW:qword 
SHGetDiskFreeSpaceExW TEXTEQU <__imp_SHGetDiskFreeSpaceExW> 
extern __imp_SHGetDriveMedia:qword 
SHGetDriveMedia TEXTEQU <__imp_SHGetDriveMedia> 
extern __imp_SHGetFileInfo:qword 
SHGetFileInfo TEXTEQU <__imp_SHGetFileInfo> 
extern __imp_SHGetFileInfoA:qword 
SHGetFileInfo TEXTEQU <__imp_SHGetFileInfoA> 
extern __imp_SHGetFileInfoW:qword 
SHGetFileInfoW TEXTEQU <__imp_SHGetFileInfoW> 
extern __imp_SHGetFolderLocation:qword 
SHGetFolderLocation TEXTEQU <__imp_SHGetFolderLocation> 
extern __imp_SHGetFolderPathA:qword 
SHGetFolderPath TEXTEQU <__imp_SHGetFolderPathA> 
extern __imp_SHGetFolderPathAndSubDirA:qword 
SHGetFolderPathAndSubDir TEXTEQU <__imp_SHGetFolderPathAndSubDirA> 
extern __imp_SHGetFolderPathAndSubDirW:qword 
SHGetFolderPathAndSubDirW TEXTEQU <__imp_SHGetFolderPathAndSubDirW> 
extern __imp_SHGetFolderPathEx:qword 
SHGetFolderPathEx TEXTEQU <__imp_SHGetFolderPathEx> 
extern __imp_SHGetFolderPathW:qword 
SHGetFolderPathW TEXTEQU <__imp_SHGetFolderPathW> 
extern __imp_SHGetIDListFromObject:qword 
SHGetIDListFromObject TEXTEQU <__imp_SHGetIDListFromObject> 
extern __imp_SHGetIconOverlayIndexA:qword 
SHGetIconOverlayIndex TEXTEQU <__imp_SHGetIconOverlayIndexA> 
extern __imp_SHGetIconOverlayIndexW:qword 
SHGetIconOverlayIndexW TEXTEQU <__imp_SHGetIconOverlayIndexW> 
extern __imp_SHGetImageList:qword 
SHGetImageList TEXTEQU <__imp_SHGetImageList> 
extern __imp_SHGetInstanceExplorer:qword 
SHGetInstanceExplorer TEXTEQU <__imp_SHGetInstanceExplorer> 
extern __imp_SHGetItemFromDataObject:qword 
SHGetItemFromDataObject TEXTEQU <__imp_SHGetItemFromDataObject> 
extern __imp_SHGetItemFromObject:qword 
SHGetItemFromObject TEXTEQU <__imp_SHGetItemFromObject> 
extern __imp_SHGetKnownFolderIDList:qword 
SHGetKnownFolderIDList TEXTEQU <__imp_SHGetKnownFolderIDList> 
extern __imp_SHGetKnownFolderItem:qword 
SHGetKnownFolderItem TEXTEQU <__imp_SHGetKnownFolderItem> 
extern __imp_SHGetKnownFolderPath:qword 
SHGetKnownFolderPath TEXTEQU <__imp_SHGetKnownFolderPath> 
extern __imp_SHGetLocalizedName:qword 
SHGetLocalizedName TEXTEQU <__imp_SHGetLocalizedName> 
extern __imp_SHGetMalloc:qword 
SHGetMalloc TEXTEQU <__imp_SHGetMalloc> 
extern __imp_SHGetNameFromIDList:qword 
SHGetNameFromIDList TEXTEQU <__imp_SHGetNameFromIDList> 
extern __imp_SHGetNewLinkInfo:qword 
SHGetNewLinkInfo TEXTEQU <__imp_SHGetNewLinkInfo> 
extern __imp_SHGetNewLinkInfoA:qword 
SHGetNewLinkInfo TEXTEQU <__imp_SHGetNewLinkInfoA> 
extern __imp_SHGetNewLinkInfoW:qword 
SHGetNewLinkInfoW TEXTEQU <__imp_SHGetNewLinkInfoW> 
extern __imp_SHGetPathFromIDList:qword 
SHGetPathFromIDList TEXTEQU <__imp_SHGetPathFromIDList> 
extern __imp_SHGetPathFromIDListA:qword 
SHGetPathFromIDList TEXTEQU <__imp_SHGetPathFromIDListA> 
extern __imp_SHGetPathFromIDListEx:qword 
SHGetPathFromIDListEx TEXTEQU <__imp_SHGetPathFromIDListEx> 
extern __imp_SHGetPathFromIDListW:qword 
SHGetPathFromIDListW TEXTEQU <__imp_SHGetPathFromIDListW> 
extern __imp_SHGetPropertyStoreForWindow:qword 
SHGetPropertyStoreForWindow TEXTEQU <__imp_SHGetPropertyStoreForWindow> 
extern __imp_SHGetPropertyStoreFromIDList:qword 
SHGetPropertyStoreFromIDList TEXTEQU <__imp_SHGetPropertyStoreFromIDList> 
extern __imp_SHGetPropertyStoreFromParsingName:qword 
SHGetPropertyStoreFromParsingName TEXTEQU <__imp_SHGetPropertyStoreFromParsingName> 
extern __imp_SHGetRealIDL:qword 
SHGetRealIDL TEXTEQU <__imp_SHGetRealIDL> 
extern __imp_SHGetSetFolderCustomSettings:qword 
SHGetSetFolderCustomSettings TEXTEQU <__imp_SHGetSetFolderCustomSettings> 
extern __imp_SHGetSetSettings:qword 
SHGetSetSettings TEXTEQU <__imp_SHGetSetSettings> 
extern __imp_SHGetSettings:qword 
SHGetSettings TEXTEQU <__imp_SHGetSettings> 
extern __imp_SHGetSpecialFolderLocation:qword 
SHGetSpecialFolderLocation TEXTEQU <__imp_SHGetSpecialFolderLocation> 
extern __imp_SHGetSpecialFolderPathA:qword 
SHGetSpecialFolderPath TEXTEQU <__imp_SHGetSpecialFolderPathA> 
extern __imp_SHGetSpecialFolderPathW:qword 
SHGetSpecialFolderPathW TEXTEQU <__imp_SHGetSpecialFolderPathW> 
extern __imp_SHGetStockIconInfo:qword 
SHGetStockIconInfo TEXTEQU <__imp_SHGetStockIconInfo> 
extern __imp_SHGetTemporaryPropertyForItem:qword 
SHGetTemporaryPropertyForItem TEXTEQU <__imp_SHGetTemporaryPropertyForItem> 
extern __imp_SHGetUnreadMailCountW:qword 
SHGetUnreadMailCountW TEXTEQU <__imp_SHGetUnreadMailCountW> 
extern __imp_SHHandleUpdateImage:qword 
SHHandleUpdateImage TEXTEQU <__imp_SHHandleUpdateImage> 
extern __imp_SHHelpShortcuts_RunDLL:qword 
SHHelpShortcuts_RunDLL TEXTEQU <__imp_SHHelpShortcuts_RunDLL> 
extern __imp_SHHelpShortcuts_RunDLLA:qword 
SHHelpShortcuts_RunDLL TEXTEQU <__imp_SHHelpShortcuts_RunDLLA> 
extern __imp_SHHelpShortcuts_RunDLLW:qword 
SHHelpShortcuts_RunDLLW TEXTEQU <__imp_SHHelpShortcuts_RunDLLW> 
extern __imp_SHILCreateFromPath:qword 
SHILCreateFromPath TEXTEQU <__imp_SHILCreateFromPath> 
extern __imp_SHInvokePrinterCommandA:qword 
SHInvokePrinterCommand TEXTEQU <__imp_SHInvokePrinterCommandA> 
extern __imp_SHInvokePrinterCommandW:qword 
SHInvokePrinterCommandW TEXTEQU <__imp_SHInvokePrinterCommandW> 
extern __imp_SHIsFileAvailableOffline:qword 
SHIsFileAvailableOffline TEXTEQU <__imp_SHIsFileAvailableOffline> 
extern __imp_SHLimitInputEdit:qword 
SHLimitInputEdit TEXTEQU <__imp_SHLimitInputEdit> 
extern __imp_SHLoadInProc:qword 
SHLoadInProc TEXTEQU <__imp_SHLoadInProc> 
extern __imp_SHLoadNonloadedIconOverlayIdentifiers:qword 
SHLoadNonloadedIconOverlayIdentifiers TEXTEQU <__imp_SHLoadNonloadedIconOverlayIdentifiers> 
extern __imp_SHMapPIDLToSystemImageListIndex:qword 
SHMapPIDLToSystemImageListIndex TEXTEQU <__imp_SHMapPIDLToSystemImageListIndex> 
extern __imp_SHMultiFileProperties:qword 
SHMultiFileProperties TEXTEQU <__imp_SHMultiFileProperties> 
extern __imp_SHObjectProperties:qword 
SHObjectProperties TEXTEQU <__imp_SHObjectProperties> 
extern __imp_SHOpenFolderAndSelectItems:qword 
SHOpenFolderAndSelectItems TEXTEQU <__imp_SHOpenFolderAndSelectItems> 
extern __imp_SHOpenPropSheetW:qword 
SHOpenPropSheetW TEXTEQU <__imp_SHOpenPropSheetW> 
extern __imp_SHOpenWithDialog:qword 
SHOpenWithDialog TEXTEQU <__imp_SHOpenWithDialog> 
extern __imp_SHParseDisplayName:qword 
SHParseDisplayName TEXTEQU <__imp_SHParseDisplayName> 
extern __imp_SHPathPrepareForWriteA:qword 
SHPathPrepareForWrite TEXTEQU <__imp_SHPathPrepareForWriteA> 
extern __imp_SHPathPrepareForWriteW:qword 
SHPathPrepareForWriteW TEXTEQU <__imp_SHPathPrepareForWriteW> 
extern __imp_SHPropStgCreate:qword 
SHPropStgCreate TEXTEQU <__imp_SHPropStgCreate> 
extern __imp_SHPropStgReadMultiple:qword 
SHPropStgReadMultiple TEXTEQU <__imp_SHPropStgReadMultiple> 
extern __imp_SHPropStgWriteMultiple:qword 
SHPropStgWriteMultiple TEXTEQU <__imp_SHPropStgWriteMultiple> 
extern __imp_SHQueryRecycleBinA:qword 
SHQueryRecycleBin TEXTEQU <__imp_SHQueryRecycleBinA> 
extern __imp_SHQueryRecycleBinW:qword 
SHQueryRecycleBinW TEXTEQU <__imp_SHQueryRecycleBinW> 
extern __imp_SHQueryUserNotificationState:qword 
SHQueryUserNotificationState TEXTEQU <__imp_SHQueryUserNotificationState> 
extern __imp_SHRemoveLocalizedName:qword 
SHRemoveLocalizedName TEXTEQU <__imp_SHRemoveLocalizedName> 
extern __imp_SHReplaceFromPropSheetExtArray:qword 
SHReplaceFromPropSheetExtArray TEXTEQU <__imp_SHReplaceFromPropSheetExtArray> 
extern __imp_SHResolveLibrary:qword 
SHResolveLibrary TEXTEQU <__imp_SHResolveLibrary> 
extern __imp_SHRestricted:qword 
SHRestricted TEXTEQU <__imp_SHRestricted> 
extern __imp_SHSetDefaultProperties:qword 
SHSetDefaultProperties TEXTEQU <__imp_SHSetDefaultProperties> 
extern __imp_SHSetFolderPathA:qword 
SHSetFolderPath TEXTEQU <__imp_SHSetFolderPathA> 
extern __imp_SHSetFolderPathW:qword 
SHSetFolderPathW TEXTEQU <__imp_SHSetFolderPathW> 
extern __imp_SHSetInstanceExplorer:qword 
SHSetInstanceExplorer TEXTEQU <__imp_SHSetInstanceExplorer> 
extern __imp_SHSetKnownFolderPath:qword 
SHSetKnownFolderPath TEXTEQU <__imp_SHSetKnownFolderPath> 
extern __imp_SHSetLocalizedName:qword 
SHSetLocalizedName TEXTEQU <__imp_SHSetLocalizedName> 
extern __imp_SHSetTemporaryPropertyForItem:qword 
SHSetTemporaryPropertyForItem TEXTEQU <__imp_SHSetTemporaryPropertyForItem> 
extern __imp_SHSetUnreadMailCountW:qword 
SHSetUnreadMailCountW TEXTEQU <__imp_SHSetUnreadMailCountW> 
extern __imp_SHShellFolderView_Message:qword 
SHShellFolderView_Message TEXTEQU <__imp_SHShellFolderView_Message> 
extern __imp_SHShowManageLibraryUI:qword 
SHShowManageLibraryUI TEXTEQU <__imp_SHShowManageLibraryUI> 
extern __imp_SHSimpleIDListFromPath:qword 
SHSimpleIDListFromPath TEXTEQU <__imp_SHSimpleIDListFromPath> 
extern __imp_SHStartNetConnectionDialogW:qword 
SHStartNetConnectionDialogW TEXTEQU <__imp_SHStartNetConnectionDialogW> 
extern __imp_SHTestTokenMembership:qword 
SHTestTokenMembership TEXTEQU <__imp_SHTestTokenMembership> 
extern __imp_SHUpdateImageA:qword 
SHUpdateImage TEXTEQU <__imp_SHUpdateImageA> 
extern __imp_SHUpdateImageW:qword 
SHUpdateImageW TEXTEQU <__imp_SHUpdateImageW> 
extern __imp_SHUpdateRecycleBinIcon:qword 
SHUpdateRecycleBinIcon TEXTEQU <__imp_SHUpdateRecycleBinIcon> 
extern __imp_SHValidateUNC:qword 
SHValidateUNC TEXTEQU <__imp_SHValidateUNC> 
extern __imp_SetCurrentProcessExplicitAppUserModelID:qword 
SetCurrentProcessExplicitAppUserModelID TEXTEQU <__imp_SetCurrentProcessExplicitAppUserModelID> 
extern __imp_SheChangeDirA:qword 
SheChangeDir TEXTEQU <__imp_SheChangeDirA> 
extern __imp_SheChangeDirExW:qword 
SheChangeDirExW TEXTEQU <__imp_SheChangeDirExW> 
extern __imp_SheGetDirA:qword 
SheGetDir TEXTEQU <__imp_SheGetDirA> 
extern __imp_SheSetCurDrive:qword 
SheSetCurDrive TEXTEQU <__imp_SheSetCurDrive> 
extern __imp_ShellAboutA:qword 
ShellAbout TEXTEQU <__imp_ShellAboutA> 
extern __imp_ShellAboutW:qword 
ShellAboutW TEXTEQU <__imp_ShellAboutW> 
extern __imp_ShellExec_RunDLL:qword 
ShellExec_RunDLL TEXTEQU <__imp_ShellExec_RunDLL> 
extern __imp_ShellExec_RunDLLA:qword 
ShellExec_RunDLL TEXTEQU <__imp_ShellExec_RunDLLA> 
extern __imp_ShellExec_RunDLLW:qword 
ShellExec_RunDLLW TEXTEQU <__imp_ShellExec_RunDLLW> 
extern __imp_ShellExecuteA:qword 
ShellExecute TEXTEQU <__imp_ShellExecuteA> 
extern __imp_ShellExecuteEx:qword 
ShellExecuteEx TEXTEQU <__imp_ShellExecuteEx> 
extern __imp_ShellExecuteExA:qword 
ShellExecuteEx TEXTEQU <__imp_ShellExecuteExA> 
extern __imp_ShellExecuteExW:qword 
ShellExecuteExW TEXTEQU <__imp_ShellExecuteExW> 
extern __imp_ShellExecuteW:qword 
ShellExecuteW TEXTEQU <__imp_ShellExecuteW> 
extern __imp_ShellHookProc:qword 
ShellHookProc TEXTEQU <__imp_ShellHookProc> 
extern __imp_Shell_GetCachedImageIndex:qword 
Shell_GetCachedImageIndex TEXTEQU <__imp_Shell_GetCachedImageIndex> 
extern __imp_Shell_GetCachedImageIndexA:qword 
Shell_GetCachedImageIndex TEXTEQU <__imp_Shell_GetCachedImageIndexA> 
extern __imp_Shell_GetCachedImageIndexW:qword 
Shell_GetCachedImageIndexW TEXTEQU <__imp_Shell_GetCachedImageIndexW> 
extern __imp_Shell_GetImageLists:qword 
Shell_GetImageLists TEXTEQU <__imp_Shell_GetImageLists> 
extern __imp_Shell_MergeMenus:qword 
Shell_MergeMenus TEXTEQU <__imp_Shell_MergeMenus> 
extern __imp_Shell_NotifyIcon:qword 
Shell_NotifyIcon TEXTEQU <__imp_Shell_NotifyIcon> 
extern __imp_Shell_NotifyIconA:qword 
Shell_NotifyIcon TEXTEQU <__imp_Shell_NotifyIconA> 
extern __imp_Shell_NotifyIconGetRect:qword 
Shell_NotifyIconGetRect TEXTEQU <__imp_Shell_NotifyIconGetRect> 
extern __imp_Shell_NotifyIconW:qword 
Shell_NotifyIconW TEXTEQU <__imp_Shell_NotifyIconW> 
extern __imp_SignalFileOpen:qword 
SignalFileOpen TEXTEQU <__imp_SignalFileOpen> 
extern __imp_StgMakeUniqueName:qword 
StgMakeUniqueName TEXTEQU <__imp_StgMakeUniqueName> 
extern __imp_StrChrA:qword 
StrChr TEXTEQU <__imp_StrChrA> 
extern __imp_StrChrIA:qword 
StrChrI TEXTEQU <__imp_StrChrIA> 
extern __imp_StrChrIW:qword 
StrChrIW TEXTEQU <__imp_StrChrIW> 
extern __imp_StrChrW:qword 
StrChrW TEXTEQU <__imp_StrChrW> 
extern __imp_StrCmpNA:qword 
StrCmpN TEXTEQU <__imp_StrCmpNA> 
extern __imp_StrCmpNIA:qword 
StrCmpNI TEXTEQU <__imp_StrCmpNIA> 
extern __imp_StrCmpNIW:qword 
StrCmpNIW TEXTEQU <__imp_StrCmpNIW> 
extern __imp_StrCmpNW:qword 
StrCmpNW TEXTEQU <__imp_StrCmpNW> 
extern __imp_StrNCmpA:qword 
StrNCmp TEXTEQU <__imp_StrNCmpA> 
extern __imp_StrNCmpIA:qword 
StrNCmpI TEXTEQU <__imp_StrNCmpIA> 
extern __imp_StrNCmpIW:qword 
StrNCmpIW TEXTEQU <__imp_StrNCmpIW> 
extern __imp_StrNCmpW:qword 
StrNCmpW TEXTEQU <__imp_StrNCmpW> 
extern __imp_StrRChrA:qword 
StrRChr TEXTEQU <__imp_StrRChrA> 
extern __imp_StrRChrIA:qword 
StrRChrI TEXTEQU <__imp_StrRChrIA> 
extern __imp_StrRChrIW:qword 
StrRChrIW TEXTEQU <__imp_StrRChrIW> 
extern __imp_StrRChrW:qword 
StrRChrW TEXTEQU <__imp_StrRChrW> 
extern __imp_StrRStrA:qword 
StrRStr TEXTEQU <__imp_StrRStrA> 
extern __imp_StrRStrIA:qword 
StrRStrI TEXTEQU <__imp_StrRStrIA> 
extern __imp_StrRStrIW:qword 
StrRStrIW TEXTEQU <__imp_StrRStrIW> 
extern __imp_StrRStrW:qword 
StrRStrW TEXTEQU <__imp_StrRStrW> 
extern __imp_StrStrA:qword 
StrStr TEXTEQU <__imp_StrStrA> 
extern __imp_StrStrIA:qword 
StrStrI TEXTEQU <__imp_StrStrIA> 
extern __imp_StrStrIW:qword 
StrStrIW TEXTEQU <__imp_StrStrIW> 
extern __imp_StrStrW:qword 
StrStrW TEXTEQU <__imp_StrStrW> 
extern __imp_WOWShellExecute:qword 
WOWShellExecute TEXTEQU <__imp_WOWShellExecute> 
extern __imp_WaitForExplorerRestartW:qword 
WaitForExplorerRestartW TEXTEQU <__imp_WaitForExplorerRestartW> 
extern __imp_Win32DeleteFile:qword 
Win32DeleteFile TEXTEQU <__imp_Win32DeleteFile> 
extern __imp_WriteCabinetState:qword 
WriteCabinetState TEXTEQU <__imp_WriteCabinetState> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal12:qword 
shell32_ordinal12 TEXTEQU <__imp_shell32_ordinal12> 
extern __imp_shell32_ordinal15:qword 
shell32_ordinal15 TEXTEQU <__imp_shell32_ordinal15> 
extern __imp_shell32_ordinal20:qword 
shell32_ordinal20 TEXTEQU <__imp_shell32_ordinal20> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal29:qword 
shell32_ordinal29 TEXTEQU <__imp_shell32_ordinal29> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal35:qword 
shell32_ordinal35 TEXTEQU <__imp_shell32_ordinal35> 
extern __imp_shell32_ordinal36:qword 
shell32_ordinal36 TEXTEQU <__imp_shell32_ordinal36> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal44:qword 
shell32_ordinal44 TEXTEQU <__imp_shell32_ordinal44> 
extern __imp_shell32_ordinal45:qword 
shell32_ordinal45 TEXTEQU <__imp_shell32_ordinal45> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal54:qword 
shell32_ordinal54 TEXTEQU <__imp_shell32_ordinal54> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal58:qword 
shell32_ordinal58 TEXTEQU <__imp_shell32_ordinal58> 
extern __imp_shell32_ordinal60:qword 
shell32_ordinal60 TEXTEQU <__imp_shell32_ordinal60> 
extern __imp_shell32_ordinal61:qword 
shell32_ordinal61 TEXTEQU <__imp_shell32_ordinal61> 
extern __imp_shell32_ordinal65:qword 
shell32_ordinal65 TEXTEQU <__imp_shell32_ordinal65> 
extern __imp_shell32_ordinal69:qword 
shell32_ordinal69 TEXTEQU <__imp_shell32_ordinal69> 
extern __imp_shell32_ordinal70:qword 
shell32_ordinal70 TEXTEQU <__imp_shell32_ordinal70> 
extern __imp_shell32_ordinal76:qword 
shell32_ordinal76 TEXTEQU <__imp_shell32_ordinal76> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal91:qword 
shell32_ordinal91 TEXTEQU <__imp_shell32_ordinal91> 
extern __imp_shell32_ordinal93:qword 
shell32_ordinal93 TEXTEQU <__imp_shell32_ordinal93> 
extern __imp_shell32_ordinal94:qword 
shell32_ordinal94 TEXTEQU <__imp_shell32_ordinal94> 
extern __imp_shell32_ordinal95:qword 
shell32_ordinal95 TEXTEQU <__imp_shell32_ordinal95> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal97:qword 
shell32_ordinal97 TEXTEQU <__imp_shell32_ordinal97> 
extern __imp_shell32_ordinal99:qword 
shell32_ordinal99 TEXTEQU <__imp_shell32_ordinal99> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal128:qword 
shell32_ordinal128 TEXTEQU <__imp_shell32_ordinal128> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal156:qword 
shell32_ordinal156 TEXTEQU <__imp_shell32_ordinal156> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal160:qword 
shell32_ordinal160 TEXTEQU <__imp_shell32_ordinal160> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal172:qword 
shell32_ordinal172 TEXTEQU <__imp_shell32_ordinal172> 
extern __imp_shell32_ordinal175:qword 
shell32_ordinal175 TEXTEQU <__imp_shell32_ordinal175> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal181:qword 
shell32_ordinal181 TEXTEQU <__imp_shell32_ordinal181> 
extern __imp_shell32_ordinal184:qword 
shell32_ordinal184 TEXTEQU <__imp_shell32_ordinal184> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal186:qword 
shell32_ordinal186 TEXTEQU <__imp_shell32_ordinal186> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal188:qword 
shell32_ordinal188 TEXTEQU <__imp_shell32_ordinal188> 
extern __imp_shell32_ordinal194:qword 
shell32_ordinal194 TEXTEQU <__imp_shell32_ordinal194> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal200:qword 
shell32_ordinal200 TEXTEQU <__imp_shell32_ordinal200> 
extern __imp_shell32_ordinal201:qword 
shell32_ordinal201 TEXTEQU <__imp_shell32_ordinal201> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal203:qword 
shell32_ordinal203 TEXTEQU <__imp_shell32_ordinal203> 
extern __imp_shell32_ordinal204:qword 
shell32_ordinal204 TEXTEQU <__imp_shell32_ordinal204> 
extern __imp_shell32_ordinal205:qword 
shell32_ordinal205 TEXTEQU <__imp_shell32_ordinal205> 
extern __imp_shell32_ordinal209:qword 
shell32_ordinal209 TEXTEQU <__imp_shell32_ordinal209> 
extern __imp_shell32_ordinal210:qword 
shell32_ordinal210 TEXTEQU <__imp_shell32_ordinal210> 
extern __imp_shell32_ordinal211:qword 
shell32_ordinal211 TEXTEQU <__imp_shell32_ordinal211> 
extern __imp_shell32_ordinal212:qword 
shell32_ordinal212 TEXTEQU <__imp_shell32_ordinal212> 
extern __imp_shell32_ordinal213:qword 
shell32_ordinal213 TEXTEQU <__imp_shell32_ordinal213> 
extern __imp_shell32_ordinal214:qword 
shell32_ordinal214 TEXTEQU <__imp_shell32_ordinal214> 
extern __imp_shell32_ordinal215:qword 
shell32_ordinal215 TEXTEQU <__imp_shell32_ordinal215> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal236:qword 
shell32_ordinal236 TEXTEQU <__imp_shell32_ordinal236> 
extern __imp_shell32_ordinal237:qword 
shell32_ordinal237 TEXTEQU <__imp_shell32_ordinal237> 
extern __imp_shell32_ordinal241:qword 
shell32_ordinal241 TEXTEQU <__imp_shell32_ordinal241> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal244:qword 
shell32_ordinal244 TEXTEQU <__imp_shell32_ordinal244> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal254:qword 
shell32_ordinal254 TEXTEQU <__imp_shell32_ordinal254> 
extern __imp_shell32_ordinal257:qword 
shell32_ordinal257 TEXTEQU <__imp_shell32_ordinal257> 
extern __imp_shell32_ordinal258:qword 
shell32_ordinal258 TEXTEQU <__imp_shell32_ordinal258> 
extern __imp_shell32_ordinal259:qword 
shell32_ordinal259 TEXTEQU <__imp_shell32_ordinal259> 
extern __imp_shell32_ordinal260:qword 
shell32_ordinal260 TEXTEQU <__imp_shell32_ordinal260> 
extern __imp_shell32_ordinal261:qword 
shell32_ordinal261 TEXTEQU <__imp_shell32_ordinal261> 
extern __imp_shell32_ordinal262:qword 
shell32_ordinal262 TEXTEQU <__imp_shell32_ordinal262> 
extern __imp_shell32_ordinal264:qword 
shell32_ordinal264 TEXTEQU <__imp_shell32_ordinal264> 
extern __imp_shell32_ordinal265:qword 
shell32_ordinal265 TEXTEQU <__imp_shell32_ordinal265> 
extern __imp_shell32_ordinal266:qword 
shell32_ordinal266 TEXTEQU <__imp_shell32_ordinal266> 
extern __imp_shell32_ordinal270:qword 
shell32_ordinal270 TEXTEQU <__imp_shell32_ordinal270> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal651:qword 
shell32_ordinal651 TEXTEQU <__imp_shell32_ordinal651> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal660:qword 
shell32_ordinal660 TEXTEQU <__imp_shell32_ordinal660> 
extern __imp_shell32_ordinal681:qword 
shell32_ordinal681 TEXTEQU <__imp_shell32_ordinal681> 
extern __imp_shell32_ordinal683:qword 
shell32_ordinal683 TEXTEQU <__imp_shell32_ordinal683> 
extern __imp_shell32_ordinal684:qword 
shell32_ordinal684 TEXTEQU <__imp_shell32_ordinal684> 
extern __imp_shell32_ordinal690:qword 
shell32_ordinal690 TEXTEQU <__imp_shell32_ordinal690> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal702:qword 
shell32_ordinal702 TEXTEQU <__imp_shell32_ordinal702> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal711:qword 
shell32_ordinal711 TEXTEQU <__imp_shell32_ordinal711> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal713:qword 
shell32_ordinal713 TEXTEQU <__imp_shell32_ordinal713> 
extern __imp_shell32_ordinal714:qword 
shell32_ordinal714 TEXTEQU <__imp_shell32_ordinal714> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal719:qword 
shell32_ordinal719 TEXTEQU <__imp_shell32_ordinal719> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal723:qword 
shell32_ordinal723 TEXTEQU <__imp_shell32_ordinal723> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal731:qword 
shell32_ordinal731 TEXTEQU <__imp_shell32_ordinal731> 
extern __imp_shell32_ordinal732:qword 
shell32_ordinal732 TEXTEQU <__imp_shell32_ordinal732> 
extern __imp_shell32_ordinal733:qword 
shell32_ordinal733 TEXTEQU <__imp_shell32_ordinal733> 
extern __imp_shell32_ordinal740:qword 
shell32_ordinal740 TEXTEQU <__imp_shell32_ordinal740> 
extern __imp_shell32_ordinal744:qword 
shell32_ordinal744 TEXTEQU <__imp_shell32_ordinal744> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal748:qword 
shell32_ordinal748 TEXTEQU <__imp_shell32_ordinal748> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal751:qword 
shell32_ordinal751 TEXTEQU <__imp_shell32_ordinal751> 
extern __imp_shell32_ordinal752:qword 
shell32_ordinal752 TEXTEQU <__imp_shell32_ordinal752> 
extern __imp_shell32_ordinal753:qword 
shell32_ordinal753 TEXTEQU <__imp_shell32_ordinal753> 
extern __imp_shell32_ordinal754:qword 
shell32_ordinal754 TEXTEQU <__imp_shell32_ordinal754> 
extern __imp_shell32_ordinal755:qword 
shell32_ordinal755 TEXTEQU <__imp_shell32_ordinal755> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal757:qword 
shell32_ordinal757 TEXTEQU <__imp_shell32_ordinal757> 
extern __imp_shell32_ordinal758:qword 
shell32_ordinal758 TEXTEQU <__imp_shell32_ordinal758> 
extern __imp_shell32_ordinal759:qword 
shell32_ordinal759 TEXTEQU <__imp_shell32_ordinal759> 
extern __imp_shell32_ordinal760:qword 
shell32_ordinal760 TEXTEQU <__imp_shell32_ordinal760> 
extern __imp_shell32_ordinal761:qword 
shell32_ordinal761 TEXTEQU <__imp_shell32_ordinal761> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal763:qword 
shell32_ordinal763 TEXTEQU <__imp_shell32_ordinal763> 
extern __imp_shell32_ordinal764:qword 
shell32_ordinal764 TEXTEQU <__imp_shell32_ordinal764> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal767:qword 
shell32_ordinal767 TEXTEQU <__imp_shell32_ordinal767> 
extern __imp_shell32_ordinal777:qword 
shell32_ordinal777 TEXTEQU <__imp_shell32_ordinal777> 
extern __imp_shell32_ordinal778:qword 
shell32_ordinal778 TEXTEQU <__imp_shell32_ordinal778> 
extern __imp_shell32_ordinal781:qword 
shell32_ordinal781 TEXTEQU <__imp_shell32_ordinal781> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal787:qword 
shell32_ordinal787 TEXTEQU <__imp_shell32_ordinal787> 
extern __imp_shell32_ordinal788:qword 
shell32_ordinal788 TEXTEQU <__imp_shell32_ordinal788> 
extern __imp_shell32_ordinal789:qword 
shell32_ordinal789 TEXTEQU <__imp_shell32_ordinal789> 
extern __imp_shell32_ordinal790:qword 
shell32_ordinal790 TEXTEQU <__imp_shell32_ordinal790> 
extern __imp_shell32_ordinal791:qword 
shell32_ordinal791 TEXTEQU <__imp_shell32_ordinal791> 
extern __imp_shell32_ordinal810:qword 
shell32_ordinal810 TEXTEQU <__imp_shell32_ordinal810> 
extern __imp_shell32_ordinal811:qword 
shell32_ordinal811 TEXTEQU <__imp_shell32_ordinal811> 
extern __imp_shell32_ordinal812:qword 
shell32_ordinal812 TEXTEQU <__imp_shell32_ordinal812> 
extern __imp_shell32_ordinal813:qword 
shell32_ordinal813 TEXTEQU <__imp_shell32_ordinal813> 
extern __imp_shell32_ordinal814:qword 
shell32_ordinal814 TEXTEQU <__imp_shell32_ordinal814> 
extern __imp_shell32_ordinal815:qword 
shell32_ordinal815 TEXTEQU <__imp_shell32_ordinal815> 
extern __imp_shell32_ordinal816:qword 
shell32_ordinal816 TEXTEQU <__imp_shell32_ordinal816> 
extern __imp_shell32_ordinal817:qword 
shell32_ordinal817 TEXTEQU <__imp_shell32_ordinal817> 
extern __imp_shell32_ordinal818:qword 
shell32_ordinal818 TEXTEQU <__imp_shell32_ordinal818> 
extern __imp_shell32_ordinal819:qword 
shell32_ordinal819 TEXTEQU <__imp_shell32_ordinal819> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal823:qword 
shell32_ordinal823 TEXTEQU <__imp_shell32_ordinal823> 
extern __imp_shell32_ordinal824:qword 
shell32_ordinal824 TEXTEQU <__imp_shell32_ordinal824> 
extern __imp_shell32_ordinal825:qword 
shell32_ordinal825 TEXTEQU <__imp_shell32_ordinal825> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal828:qword 
shell32_ordinal828 TEXTEQU <__imp_shell32_ordinal828> 
extern __imp_shell32_ordinal829:qword 
shell32_ordinal829 TEXTEQU <__imp_shell32_ordinal829> 
extern __imp_shell32_ordinal830:qword 
shell32_ordinal830 TEXTEQU <__imp_shell32_ordinal830> 
extern __imp_shell32_ordinal831:qword 
shell32_ordinal831 TEXTEQU <__imp_shell32_ordinal831> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal833:qword 
shell32_ordinal833 TEXTEQU <__imp_shell32_ordinal833> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal840:qword 
shell32_ordinal840 TEXTEQU <__imp_shell32_ordinal840> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal844:qword 
shell32_ordinal844 TEXTEQU <__imp_shell32_ordinal844> 
extern __imp_shell32_ordinal845:qword 
shell32_ordinal845 TEXTEQU <__imp_shell32_ordinal845> 
extern __imp_shell32_ordinal847:qword 
shell32_ordinal847 TEXTEQU <__imp_shell32_ordinal847> 
extern __imp_shell32_ordinal848:qword 
shell32_ordinal848 TEXTEQU <__imp_shell32_ordinal848> 
extern __imp_shell32_ordinal849:qword 
shell32_ordinal849 TEXTEQU <__imp_shell32_ordinal849> 
extern __imp_shell32_ordinal850:qword 
shell32_ordinal850 TEXTEQU <__imp_shell32_ordinal850> 
extern __imp_shell32_ordinal851:qword 
shell32_ordinal851 TEXTEQU <__imp_shell32_ordinal851> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal859:qword 
shell32_ordinal859 TEXTEQU <__imp_shell32_ordinal859> 
extern __imp_shell32_ordinal860:qword 
shell32_ordinal860 TEXTEQU <__imp_shell32_ordinal860> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal862:qword 
shell32_ordinal862 TEXTEQU <__imp_shell32_ordinal862> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal864:qword 
shell32_ordinal864 TEXTEQU <__imp_shell32_ordinal864> 
extern __imp_shell32_ordinal865:qword 
shell32_ordinal865 TEXTEQU <__imp_shell32_ordinal865> 
extern __imp_shell32_ordinal866:qword 
shell32_ordinal866 TEXTEQU <__imp_shell32_ordinal866> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal870:qword 
shell32_ordinal870 TEXTEQU <__imp_shell32_ordinal870> 
extern __imp_shell32_ordinal871:qword 
shell32_ordinal871 TEXTEQU <__imp_shell32_ordinal871> 
extern __imp_to:qword 
to TEXTEQU <__imp_to> 
extern __imp_shell32_ordinal873:qword 
shell32_ordinal873 TEXTEQU <__imp_shell32_ordinal873> 
extern __imp_shell32_ordinal874:qword 
shell32_ordinal874 TEXTEQU <__imp_shell32_ordinal874> 
extern __imp_shell32_ordinal875:qword 
shell32_ordinal875 TEXTEQU <__imp_shell32_ordinal875> 
extern __imp_shell32_ordinal876:qword 
shell32_ordinal876 TEXTEQU <__imp_shell32_ordinal876> 
extern __imp_shell32_ordinal877:qword 
shell32_ordinal877 TEXTEQU <__imp_shell32_ordinal877> 
extern __imp_shell32_ordinal878:qword 
shell32_ordinal878 TEXTEQU <__imp_shell32_ordinal878> 
extern __imp_shell32_ordinal880:qword 
shell32_ordinal880 TEXTEQU <__imp_shell32_ordinal880> 
extern __imp_shell32_ordinal881:qword 
shell32_ordinal881 TEXTEQU <__imp_shell32_ordinal881> 
extern __imp_shell32_ordinal882:qword 
shell32_ordinal882 TEXTEQU <__imp_shell32_ordinal882> 
extern __imp_shell32_ordinal883:qword 
shell32_ordinal883 TEXTEQU <__imp_shell32_ordinal883> 
extern __imp_shell32_ordinal884:qword 
shell32_ordinal884 TEXTEQU <__imp_shell32_ordinal884> 
extern __imp_shell32_ordinal885:qword 
shell32_ordinal885 TEXTEQU <__imp_shell32_ordinal885> 
extern __imp_shell32_ordinal886:qword 
shell32_ordinal886 TEXTEQU <__imp_shell32_ordinal886> 
extern __imp_shell32_ordinal887:qword 
shell32_ordinal887 TEXTEQU <__imp_shell32_ordinal887> 
extern __imp_shell32_ordinal888:qword 
shell32_ordinal888 TEXTEQU <__imp_shell32_ordinal888> 
extern __imp_shell32_ordinal889:qword 
shell32_ordinal889 TEXTEQU <__imp_shell32_ordinal889> 
extern __imp_shell32_ordinal890:qword 
shell32_ordinal890 TEXTEQU <__imp_shell32_ordinal890> 
extern __imp_shell32_ordinal891:qword 
shell32_ordinal891 TEXTEQU <__imp_shell32_ordinal891> 
extern __imp_shell32_ordinal892:qword 
shell32_ordinal892 TEXTEQU <__imp_shell32_ordinal892> 
extern __imp_shell32_ordinal893:qword 
shell32_ordinal893 TEXTEQU <__imp_shell32_ordinal893> 
extern __imp_shell32_ordinal894:qword 
shell32_ordinal894 TEXTEQU <__imp_shell32_ordinal894> 
extern __imp_shell32_ordinal895:qword 
shell32_ordinal895 TEXTEQU <__imp_shell32_ordinal895> 
extern __imp_shell32_ordinal896:qword 
shell32_ordinal896 TEXTEQU <__imp_shell32_ordinal896> 
extern __imp_shell32_ordinal897:qword 
shell32_ordinal897 TEXTEQU <__imp_shell32_ordinal897> 
extern __imp_shell32_ordinal898:qword 
shell32_ordinal898 TEXTEQU <__imp_shell32_ordinal898> 
extern __imp_shell32_ordinal899:qword 
shell32_ordinal899 TEXTEQU <__imp_shell32_ordinal899> 
extern __imp_shell32_ordinal900:qword 
shell32_ordinal900 TEXTEQU <__imp_shell32_ordinal900> 
extern __imp_shell32_ordinal901:qword 
shell32_ordinal901 TEXTEQU <__imp_shell32_ordinal901> 
extern __imp_shell32_ordinal902:qword 
shell32_ordinal902 TEXTEQU <__imp_shell32_ordinal902> 
extern __imp_shell32_ordinal903:qword 
shell32_ordinal903 TEXTEQU <__imp_shell32_ordinal903> 
;--------------------------
BROWSEINFO STRUCT
  hwndOwner	 QWORD ?
  pidlRoot	 QWORD ?
  pszDisplayName QWORD ?
  lpszTitle	 QWORD ?
  ulFlags	 DWORD ?,?
  lpfn		 QWORD ?
  lParam	 QWORD ?
  iImage	 QWORD ?
BROWSEINFO ENDS
NOTIFYICONDATA STRUCT
  cbSize	   DWORD ?,?
  hWnd		   QWORD ?
  uID		   DWORD ?
  uFlags	   DWORD ?
  uCallbackMessage DWORD ?,?
  hIcon 	   QWORD ?
  szTip 	   BYTE 64 dup (?)
NOTIFYICONDATA ENDS