extern __imp_ActivateKeyboardLayout:qword 
ActivateKeyboardLayout TEXTEQU <__imp_ActivateKeyboardLayout> 
extern __imp_AddClipboardFormatListener:qword 
AddClipboardFormatListener TEXTEQU <__imp_AddClipboardFormatListener> 
extern __imp_AdjustWindowRect:qword 
AdjustWindowRect TEXTEQU <__imp_AdjustWindowRect> 
extern __imp_AdjustWindowRectEx:qword 
AdjustWindowRectEx TEXTEQU <__imp_AdjustWindowRectEx> 
extern __imp_AlignRects:qword 
AlignRects TEXTEQU <__imp_AlignRects> 
extern __imp_AllowForegroundActivation:qword 
AllowForegroundActivation TEXTEQU <__imp_AllowForegroundActivation> 
extern __imp_AllowSetForegroundWindow:qword 
AllowSetForegroundWindow TEXTEQU <__imp_AllowSetForegroundWindow> 
extern __imp_AnimateWindow:qword 
AnimateWindow TEXTEQU <__imp_AnimateWindow> 
extern __imp_AnyPopup:qword 
AnyPopup TEXTEQU <__imp_AnyPopup> 
extern __imp_AppendMenuA:qword 
AppendMenu TEXTEQU <__imp_AppendMenuA> 
extern __imp_AppendMenuW:qword 
AppendMenuW TEXTEQU <__imp_AppendMenuW> 
extern __imp_ArrangeIconicWindows:qword 
ArrangeIconicWindows TEXTEQU <__imp_ArrangeIconicWindows> 
extern __imp_AttachThreadInput:qword 
AttachThreadInput TEXTEQU <__imp_AttachThreadInput> 
extern __imp_BeginDeferWindowPos:qword 
BeginDeferWindowPos TEXTEQU <__imp_BeginDeferWindowPos> 
extern __imp_BeginPaint:qword 
BeginPaint TEXTEQU <__imp_BeginPaint> 
extern __imp_BlockInput:qword 
BlockInput TEXTEQU <__imp_BlockInput> 
extern __imp_BringWindowToTop:qword 
BringWindowToTop TEXTEQU <__imp_BringWindowToTop> 
extern __imp_BroadcastSystemMessage:qword 
BroadcastSystemMessage TEXTEQU <__imp_BroadcastSystemMessage> 
extern __imp_BroadcastSystemMessageA:qword 
BroadcastSystemMessage TEXTEQU <__imp_BroadcastSystemMessageA> 
extern __imp_BroadcastSystemMessageExA:qword 
BroadcastSystemMessageEx TEXTEQU <__imp_BroadcastSystemMessageExA> 
extern __imp_BroadcastSystemMessageExW:qword 
BroadcastSystemMessageExW TEXTEQU <__imp_BroadcastSystemMessageExW> 
extern __imp_BroadcastSystemMessageW:qword 
BroadcastSystemMessageW TEXTEQU <__imp_BroadcastSystemMessageW> 
extern __imp_BuildReasonArray:qword 
BuildReasonArray TEXTEQU <__imp_BuildReasonArray> 
extern __imp_CalcMenuBar:qword 
CalcMenuBar TEXTEQU <__imp_CalcMenuBar> 
extern __imp_CalculatePopupWindowPosition:qword 
CalculatePopupWindowPosition TEXTEQU <__imp_CalculatePopupWindowPosition> 
extern __imp_CallMsgFilter:qword 
CallMsgFilter TEXTEQU <__imp_CallMsgFilter> 
extern __imp_CallMsgFilterA:qword 
CallMsgFilter TEXTEQU <__imp_CallMsgFilterA> 
extern __imp_CallMsgFilterW:qword 
CallMsgFilterW TEXTEQU <__imp_CallMsgFilterW> 
extern __imp_CallNextHookEx:qword 
CallNextHookEx TEXTEQU <__imp_CallNextHookEx> 
extern __imp_CallWindowProcA:qword 
CallWindowProc TEXTEQU <__imp_CallWindowProcA> 
extern __imp_CallWindowProcW:qword 
CallWindowProcW TEXTEQU <__imp_CallWindowProcW> 
extern __imp_CancelShutdown:qword 
CancelShutdown TEXTEQU <__imp_CancelShutdown> 
extern __imp_CascadeChildWindows:qword 
CascadeChildWindows TEXTEQU <__imp_CascadeChildWindows> 
extern __imp_CascadeWindows:qword 
CascadeWindows TEXTEQU <__imp_CascadeWindows> 
extern __imp_ChangeClipboardChain:qword 
ChangeClipboardChain TEXTEQU <__imp_ChangeClipboardChain> 
extern __imp_ChangeDisplaySettingsA:qword 
ChangeDisplaySettings TEXTEQU <__imp_ChangeDisplaySettingsA> 
extern __imp_ChangeDisplaySettingsExA:qword 
ChangeDisplaySettingsEx TEXTEQU <__imp_ChangeDisplaySettingsExA> 
extern __imp_ChangeDisplaySettingsExW:qword 
ChangeDisplaySettingsExW TEXTEQU <__imp_ChangeDisplaySettingsExW> 
extern __imp_ChangeDisplaySettingsW:qword 
ChangeDisplaySettingsW TEXTEQU <__imp_ChangeDisplaySettingsW> 
extern __imp_ChangeMenuA:qword 
ChangeMenu TEXTEQU <__imp_ChangeMenuA> 
extern __imp_ChangeMenuW:qword 
ChangeMenuW TEXTEQU <__imp_ChangeMenuW> 
extern __imp_ChangeWindowMessageFilter:qword 
ChangeWindowMessageFilter TEXTEQU <__imp_ChangeWindowMessageFilter> 
extern __imp_ChangeWindowMessageFilterEx:qword 
ChangeWindowMessageFilterEx TEXTEQU <__imp_ChangeWindowMessageFilterEx> 
extern __imp_CharLowerA:qword 
CharLower TEXTEQU <__imp_CharLowerA> 
extern __imp_CharLowerBuffA:qword 
CharLowerBuff TEXTEQU <__imp_CharLowerBuffA> 
extern __imp_CharLowerBuffW:qword 
CharLowerBuffW TEXTEQU <__imp_CharLowerBuffW> 
extern __imp_CharLowerW:qword 
CharLowerW TEXTEQU <__imp_CharLowerW> 
extern __imp_CharNextA:qword 
CharNext TEXTEQU <__imp_CharNextA> 
extern __imp_CharNextExA:qword 
CharNextEx TEXTEQU <__imp_CharNextExA> 
extern __imp_CharNextW:qword 
CharNextW TEXTEQU <__imp_CharNextW> 
extern __imp_CharPrevA:qword 
CharPrev TEXTEQU <__imp_CharPrevA> 
extern __imp_CharPrevExA:qword 
CharPrevEx TEXTEQU <__imp_CharPrevExA> 
extern __imp_CharPrevW:qword 
CharPrevW TEXTEQU <__imp_CharPrevW> 
extern __imp_CharToOemA:qword 
CharToOem TEXTEQU <__imp_CharToOemA> 
extern __imp_CharToOemBuffA:qword 
CharToOemBuff TEXTEQU <__imp_CharToOemBuffA> 
extern __imp_CharToOemBuffW:qword 
CharToOemBuffW TEXTEQU <__imp_CharToOemBuffW> 
extern __imp_CharToOemW:qword 
CharToOemW TEXTEQU <__imp_CharToOemW> 
extern __imp_CharUpperA:qword 
CharUpper TEXTEQU <__imp_CharUpperA> 
extern __imp_CharUpperBuffA:qword 
CharUpperBuff TEXTEQU <__imp_CharUpperBuffA> 
extern __imp_CharUpperBuffW:qword 
CharUpperBuffW TEXTEQU <__imp_CharUpperBuffW> 
extern __imp_CharUpperW:qword 
CharUpperW TEXTEQU <__imp_CharUpperW> 
extern __imp_CheckDesktopByThreadId:qword 
CheckDesktopByThreadId TEXTEQU <__imp_CheckDesktopByThreadId> 
extern __imp_CheckDlgButton:qword 
CheckDlgButton TEXTEQU <__imp_CheckDlgButton> 
extern __imp_CheckMenuItem:qword 
CheckMenuItem TEXTEQU <__imp_CheckMenuItem> 
extern __imp_CheckMenuRadioItem:qword 
CheckMenuRadioItem TEXTEQU <__imp_CheckMenuRadioItem> 
extern __imp_CheckRadioButton:qword 
CheckRadioButton TEXTEQU <__imp_CheckRadioButton> 
extern __imp_CheckWindowThreadDesktop:qword 
CheckWindowThreadDesktop TEXTEQU <__imp_CheckWindowThreadDesktop> 
extern __imp_ChildWindowFromPoint:qword 
ChildWindowFromPoint TEXTEQU <__imp_ChildWindowFromPoint> 
extern __imp_ChildWindowFromPointEx:qword 
ChildWindowFromPointEx TEXTEQU <__imp_ChildWindowFromPointEx> 
extern __imp_CliImmSetHotKey:qword 
CliImmSetHotKey TEXTEQU <__imp_CliImmSetHotKey> 
extern __imp_ClientThreadSetup:qword 
ClientThreadSetup TEXTEQU <__imp_ClientThreadSetup> 
extern __imp_ClientToScreen:qword 
ClientToScreen TEXTEQU <__imp_ClientToScreen> 
extern __imp_ClipCursor:qword 
ClipCursor TEXTEQU <__imp_ClipCursor> 
extern __imp_CloseClipboard:qword 
CloseClipboard TEXTEQU <__imp_CloseClipboard> 
extern __imp_CloseDesktop:qword 
CloseDesktop TEXTEQU <__imp_CloseDesktop> 
extern __imp_CloseGestureInfoHandle:qword 
CloseGestureInfoHandle TEXTEQU <__imp_CloseGestureInfoHandle> 
extern __imp_CloseTouchInputHandle:qword 
CloseTouchInputHandle TEXTEQU <__imp_CloseTouchInputHandle> 
extern __imp_CloseWindow:qword 
CloseWindow TEXTEQU <__imp_CloseWindow> 
extern __imp_CloseWindowStation:qword 
CloseWindowStation TEXTEQU <__imp_CloseWindowStation> 
extern __imp_ConsoleControl:qword 
ConsoleControl TEXTEQU <__imp_ConsoleControl> 
extern __imp_ControlMagnification:qword 
ControlMagnification TEXTEQU <__imp_ControlMagnification> 
extern __imp_CopyAcceleratorTableA:qword 
CopyAcceleratorTable TEXTEQU <__imp_CopyAcceleratorTableA> 
extern __imp_CopyAcceleratorTableW:qword 
CopyAcceleratorTableW TEXTEQU <__imp_CopyAcceleratorTableW> 
extern __imp_CopyIcon:qword 
CopyIcon TEXTEQU <__imp_CopyIcon> 
extern __imp_CopyImage:qword 
CopyImage TEXTEQU <__imp_CopyImage> 
extern __imp_CopyRect:qword 
CopyRect TEXTEQU <__imp_CopyRect> 
extern __imp_CountClipboardFormats:qword 
CountClipboardFormats TEXTEQU <__imp_CountClipboardFormats> 
extern __imp_CreateAcceleratorTableA:qword 
CreateAcceleratorTable TEXTEQU <__imp_CreateAcceleratorTableA> 
extern __imp_CreateAcceleratorTableW:qword 
CreateAcceleratorTableW TEXTEQU <__imp_CreateAcceleratorTableW> 
extern __imp_CreateCaret:qword 
CreateCaret TEXTEQU <__imp_CreateCaret> 
extern __imp_CreateCursor:qword 
CreateCursor TEXTEQU <__imp_CreateCursor> 
extern __imp_CreateDesktopA:qword 
CreateDesktop TEXTEQU <__imp_CreateDesktopA> 
extern __imp_CreateDesktopExA:qword 
CreateDesktopEx TEXTEQU <__imp_CreateDesktopExA> 
extern __imp_CreateDesktopExW:qword 
CreateDesktopExW TEXTEQU <__imp_CreateDesktopExW> 
extern __imp_CreateDesktopW:qword 
CreateDesktopW TEXTEQU <__imp_CreateDesktopW> 
extern __imp_CreateDialogIndirectParamA:qword 
CreateDialogIndirectParam TEXTEQU <__imp_CreateDialogIndirectParamA> 
extern __imp_CreateDialogIndirectParamAorW:qword 
CreateDialogIndirectParamAorW TEXTEQU <__imp_CreateDialogIndirectParamAorW> 
extern __imp_CreateDialogIndirectParamW:qword 
CreateDialogIndirectParamW TEXTEQU <__imp_CreateDialogIndirectParamW> 
extern __imp_CreateDialogParamA:qword 
CreateDialogParam TEXTEQU <__imp_CreateDialogParamA> 
extern __imp_CreateDialogParamW:qword 
CreateDialogParamW TEXTEQU <__imp_CreateDialogParamW> 
extern __imp_CreateIcon:qword 
CreateIcon TEXTEQU <__imp_CreateIcon> 
extern __imp_CreateIconFromResource:qword 
CreateIconFromResource TEXTEQU <__imp_CreateIconFromResource> 
extern __imp_CreateIconFromResourceEx:qword 
CreateIconFromResourceEx TEXTEQU <__imp_CreateIconFromResourceEx> 
extern __imp_CreateIconIndirect:qword 
CreateIconIndirect TEXTEQU <__imp_CreateIconIndirect> 
extern __imp_CreateMDIWindowA:qword 
CreateMDIWindow TEXTEQU <__imp_CreateMDIWindowA> 
extern __imp_CreateMDIWindowW:qword 
CreateMDIWindowW TEXTEQU <__imp_CreateMDIWindowW> 
extern __imp_CreateMenu:qword 
CreateMenu TEXTEQU <__imp_CreateMenu> 
extern __imp_CreatePopupMenu:qword 
CreatePopupMenu TEXTEQU <__imp_CreatePopupMenu> 
extern __imp_CreateSystemThreads:qword 
CreateSystemThreads TEXTEQU <__imp_CreateSystemThreads> 
extern __imp_CreateWindowExA:qword 
CreateWindowEx TEXTEQU <__imp_CreateWindowExA> 
extern __imp_CreateWindowExW:qword 
CreateWindowExW TEXTEQU <__imp_CreateWindowExW> 
extern __imp_CreateWindowStationA:qword 
CreateWindowStation TEXTEQU <__imp_CreateWindowStationA> 
extern __imp_CreateWindowStationW:qword 
CreateWindowStationW TEXTEQU <__imp_CreateWindowStationW> 
extern __imp_CsrBroadcastSystemMessageExW:qword 
CsrBroadcastSystemMessageExW TEXTEQU <__imp_CsrBroadcastSystemMessageExW> 
extern __imp_CtxInitUser32:qword 
CtxInitUser32 TEXTEQU <__imp_CtxInitUser32> 
extern __imp_DdeAbandonTransaction:qword 
DdeAbandonTransaction TEXTEQU <__imp_DdeAbandonTransaction> 
extern __imp_DdeAccessData:qword 
DdeAccessDat TEXTEQU <__imp_DdeAccessData> 
extern __imp_DdeAddData:qword 
DdeAddDat TEXTEQU <__imp_DdeAddData> 
extern __imp_DdeClientTransaction:qword 
DdeClientTransaction TEXTEQU <__imp_DdeClientTransaction> 
extern __imp_DdeCmpStringHandles:qword 
DdeCmpStringHandles TEXTEQU <__imp_DdeCmpStringHandles> 
extern __imp_DdeConnect:qword 
DdeConnect TEXTEQU <__imp_DdeConnect> 
extern __imp_DdeConnectList:qword 
DdeConnectList TEXTEQU <__imp_DdeConnectList> 
extern __imp_DdeCreateDataHandle:qword 
DdeCreateDataHandle TEXTEQU <__imp_DdeCreateDataHandle> 
extern __imp_DdeCreateStringHandleA:qword 
DdeCreateStringHandle TEXTEQU <__imp_DdeCreateStringHandleA> 
extern __imp_DdeCreateStringHandleW:qword 
DdeCreateStringHandleW TEXTEQU <__imp_DdeCreateStringHandleW> 
extern __imp_DdeDisconnect:qword 
DdeDisconnect TEXTEQU <__imp_DdeDisconnect> 
extern __imp_DdeDisconnectList:qword 
DdeDisconnectList TEXTEQU <__imp_DdeDisconnectList> 
extern __imp_DdeEnableCallback:qword 
DdeEnableCallback TEXTEQU <__imp_DdeEnableCallback> 
extern __imp_DdeFreeDataHandle:qword 
DdeFreeDataHandle TEXTEQU <__imp_DdeFreeDataHandle> 
extern __imp_DdeFreeStringHandle:qword 
DdeFreeStringHandle TEXTEQU <__imp_DdeFreeStringHandle> 
extern __imp_DdeGetData:qword 
DdeGetDat TEXTEQU <__imp_DdeGetData> 
extern __imp_DdeGetLastError:qword 
DdeGetLastError TEXTEQU <__imp_DdeGetLastError> 
extern __imp_DdeGetQualityOfService:qword 
DdeGetQualityOfService TEXTEQU <__imp_DdeGetQualityOfService> 
extern __imp_DdeImpersonateClient:qword 
DdeImpersonateClient TEXTEQU <__imp_DdeImpersonateClient> 
extern __imp_DdeInitializeA:qword 
DdeInitialize TEXTEQU <__imp_DdeInitializeA> 
extern __imp_DdeInitializeW:qword 
DdeInitializeW TEXTEQU <__imp_DdeInitializeW> 
extern __imp_DdeKeepStringHandle:qword 
DdeKeepStringHandle TEXTEQU <__imp_DdeKeepStringHandle> 
extern __imp_DdeNameService:qword 
DdeNameService TEXTEQU <__imp_DdeNameService> 
extern __imp_DdePostAdvise:qword 
DdePostAdvise TEXTEQU <__imp_DdePostAdvise> 
extern __imp_DdeQueryConvInfo:qword 
DdeQueryConvInfo TEXTEQU <__imp_DdeQueryConvInfo> 
extern __imp_DdeQueryNextServer:qword 
DdeQueryNextServer TEXTEQU <__imp_DdeQueryNextServer> 
extern __imp_DdeQueryStringA:qword 
DdeQueryString TEXTEQU <__imp_DdeQueryStringA> 
extern __imp_DdeQueryStringW:qword 
DdeQueryStringW TEXTEQU <__imp_DdeQueryStringW> 
extern __imp_DdeReconnect:qword 
DdeReconnect TEXTEQU <__imp_DdeReconnect> 
extern __imp_DdeSetQualityOfService:qword 
DdeSetQualityOfService TEXTEQU <__imp_DdeSetQualityOfService> 
extern __imp_DdeSetUserHandle:qword 
DdeSetUserHandle TEXTEQU <__imp_DdeSetUserHandle> 
extern __imp_DdeUnaccessData:qword 
DdeUnaccessDat TEXTEQU <__imp_DdeUnaccessData> 
extern __imp_DdeUninitialize:qword 
DdeUninitialize TEXTEQU <__imp_DdeUninitialize> 
extern __imp_DefFrameProcA:qword 
DefFrameProc TEXTEQU <__imp_DefFrameProcA> 
extern __imp_DefFrameProcW:qword 
DefFrameProcW TEXTEQU <__imp_DefFrameProcW> 
extern __imp_DefMDIChildProcA:qword 
DefMDIChildProc TEXTEQU <__imp_DefMDIChildProcA> 
extern __imp_DefMDIChildProcW:qword 
DefMDIChildProcW TEXTEQU <__imp_DefMDIChildProcW> 
extern __imp_DefRawInputProc:qword 
DefRawInputProc TEXTEQU <__imp_DefRawInputProc> 
extern __imp_DeferWindowPos:qword 
DeferWindowPos TEXTEQU <__imp_DeferWindowPos> 
extern __imp_DeleteMenu:qword 
DeleteMenu TEXTEQU <__imp_DeleteMenu> 
extern __imp_DeregisterShellHookWindow:qword 
DeregisterShellHookWindow TEXTEQU <__imp_DeregisterShellHookWindow> 
extern __imp_DestroyAcceleratorTable:qword 
DestroyAcceleratorTable TEXTEQU <__imp_DestroyAcceleratorTable> 
extern __imp_DestroyCaret:qword 
DestroyCaret TEXTEQU <__imp_DestroyCaret> 
extern __imp_DestroyCursor:qword 
DestroyCursor TEXTEQU <__imp_DestroyCursor> 
extern __imp_DestroyIcon:qword 
DestroyIcon TEXTEQU <__imp_DestroyIcon> 
extern __imp_DestroyMenu:qword 
DestroyMenu TEXTEQU <__imp_DestroyMenu> 
extern __imp_DestroyReasons:qword 
DestroyReasons TEXTEQU <__imp_DestroyReasons> 
extern __imp_DestroyWindow:qword 
DestroyWindow TEXTEQU <__imp_DestroyWindow> 
extern __imp_DeviceEventWorker:qword 
DeviceEventWorker TEXTEQU <__imp_DeviceEventWorker> 
extern __imp_DialogBoxIndirectParamA:qword 
DialogBoxIndirectParam TEXTEQU <__imp_DialogBoxIndirectParamA> 
extern __imp_DialogBoxIndirectParamAorW:qword 
DialogBoxIndirectParamAorW TEXTEQU <__imp_DialogBoxIndirectParamAorW> 
extern __imp_DialogBoxIndirectParamW:qword 
DialogBoxIndirectParamW TEXTEQU <__imp_DialogBoxIndirectParamW> 
extern __imp_DialogBoxParamA:qword 
DialogBoxParam TEXTEQU <__imp_DialogBoxParamA> 
extern __imp_DialogBoxParamW:qword 
DialogBoxParamW TEXTEQU <__imp_DialogBoxParamW> 
extern __imp_DisableProcessWindowsGhosting:qword 
DisableProcessWindowsGhosting TEXTEQU <__imp_DisableProcessWindowsGhosting> 
extern __imp_DispatchMessageA:qword 
DispatchMessage TEXTEQU <__imp_DispatchMessageA> 
extern __imp_DispatchMessageW:qword 
DispatchMessageW TEXTEQU <__imp_DispatchMessageW> 
extern __imp_DisplayConfigGetDeviceInfo:qword 
DisplayConfigGetDeviceInfo TEXTEQU <__imp_DisplayConfigGetDeviceInfo> 
extern __imp_DisplayConfigSetDeviceInfo:qword 
DisplayConfigSetDeviceInfo TEXTEQU <__imp_DisplayConfigSetDeviceInfo> 
extern __imp_DisplayExitWindowsWarnings:qword 
DisplayExitWindowsWarnings TEXTEQU <__imp_DisplayExitWindowsWarnings> 
extern __imp_DlgDirListA:qword 
DlgDirList TEXTEQU <__imp_DlgDirListA> 
extern __imp_DlgDirListComboBoxA:qword 
DlgDirListComboBox TEXTEQU <__imp_DlgDirListComboBoxA> 
extern __imp_DlgDirListComboBoxW:qword 
DlgDirListComboBoxW TEXTEQU <__imp_DlgDirListComboBoxW> 
extern __imp_DlgDirListW:qword 
DlgDirListW TEXTEQU <__imp_DlgDirListW> 
extern __imp_DlgDirSelectComboBoxExA:qword 
DlgDirSelectComboBoxEx TEXTEQU <__imp_DlgDirSelectComboBoxExA> 
extern __imp_DlgDirSelectComboBoxExW:qword 
DlgDirSelectComboBoxExW TEXTEQU <__imp_DlgDirSelectComboBoxExW> 
extern __imp_DlgDirSelectExA:qword 
DlgDirSelectEx TEXTEQU <__imp_DlgDirSelectExA> 
extern __imp_DlgDirSelectExW:qword 
DlgDirSelectExW TEXTEQU <__imp_DlgDirSelectExW> 
extern __imp_DoSoundConnect:qword 
DoSoundConnect TEXTEQU <__imp_DoSoundConnect> 
extern __imp_DoSoundDisconnect:qword 
DoSoundDisconnect TEXTEQU <__imp_DoSoundDisconnect> 
extern __imp_DragDetect:qword 
DragDetect TEXTEQU <__imp_DragDetect> 
extern __imp_DragObject:qword 
DragObject TEXTEQU <__imp_DragObject> 
extern __imp_DrawAnimatedRects:qword 
DrawAnimatedRects TEXTEQU <__imp_DrawAnimatedRects> 
extern __imp_DrawCaption:qword 
DrawCaption TEXTEQU <__imp_DrawCaption> 
extern __imp_DrawCaptionTempA:qword 
DrawCaptionTemp TEXTEQU <__imp_DrawCaptionTempA> 
extern __imp_DrawCaptionTempW:qword 
DrawCaptionTempW TEXTEQU <__imp_DrawCaptionTempW> 
extern __imp_DrawEdge:qword 
DrawEdge TEXTEQU <__imp_DrawEdge> 
extern __imp_DrawFocusRect:qword 
DrawFocusRect TEXTEQU <__imp_DrawFocusRect> 
extern __imp_DrawFrame:qword 
DrawFrame TEXTEQU <__imp_DrawFrame> 
extern __imp_DrawFrameControl:qword 
DrawFrameControl TEXTEQU <__imp_DrawFrameControl> 
extern __imp_DrawIcon:qword 
DrawIcon TEXTEQU <__imp_DrawIcon> 
extern __imp_DrawIconEx:qword 
DrawIconEx TEXTEQU <__imp_DrawIconEx> 
extern __imp_DrawMenuBar:qword 
DrawMenuBar TEXTEQU <__imp_DrawMenuBar> 
extern __imp_DrawMenuBarTemp:qword 
DrawMenuBarTemp TEXTEQU <__imp_DrawMenuBarTemp> 
extern __imp_DrawStateA:qword 
DrawState TEXTEQU <__imp_DrawStateA> 
extern __imp_DrawStateW:qword 
DrawStateW TEXTEQU <__imp_DrawStateW> 
extern __imp_DrawTextA:qword 
DrawText TEXTEQU <__imp_DrawTextA> 
extern __imp_DrawTextExA:qword 
DrawTextEx TEXTEQU <__imp_DrawTextExA> 
extern __imp_DrawTextExW:qword 
DrawTextExW TEXTEQU <__imp_DrawTextExW> 
extern __imp_DrawTextW:qword 
DrawTextW TEXTEQU <__imp_DrawTextW> 
extern __imp_DwmGetDxSharedSurface:qword 
DwmGetDxSharedSurface TEXTEQU <__imp_DwmGetDxSharedSurface> 
extern __imp_DwmStartRedirection:qword 
DwmStartRedirection TEXTEQU <__imp_DwmStartRedirection> 
extern __imp_DwmStopRedirection:qword 
DwmStopRedirection TEXTEQU <__imp_DwmStopRedirection> 
extern __imp_EditWndProc:qword 
EditWndProc TEXTEQU <__imp_EditWndProc> 
extern __imp_EmptyClipboard:qword 
EmptyClipboard TEXTEQU <__imp_EmptyClipboard> 
extern __imp_EnableMenuItem:qword 
EnableMenuItem TEXTEQU <__imp_EnableMenuItem> 
extern __imp_EnableScrollBar:qword 
EnableScrollBar TEXTEQU <__imp_EnableScrollBar> 
extern __imp_EnableWindow:qword 
EnableWindow TEXTEQU <__imp_EnableWindow> 
extern __imp_EndDeferWindowPos:qword 
EndDeferWindowPos TEXTEQU <__imp_EndDeferWindowPos> 
extern __imp_EndDialog:qword 
EndDialog TEXTEQU <__imp_EndDialog> 
extern __imp_EndMenu:qword 
EndMenu TEXTEQU <__imp_EndMenu> 
extern __imp_EndPaint:qword 
EndPaint TEXTEQU <__imp_EndPaint> 
extern __imp_EndTask:qword 
EndTask TEXTEQU <__imp_EndTask> 
extern __imp_EnterReaderModeHelper:qword 
EnterReaderModeHelper TEXTEQU <__imp_EnterReaderModeHelper> 
extern __imp_EnumChildWindows:qword 
EnumChildWindows TEXTEQU <__imp_EnumChildWindows> 
extern __imp_EnumClipboardFormats:qword 
EnumClipboardFormats TEXTEQU <__imp_EnumClipboardFormats> 
extern __imp_EnumDesktopWindows:qword 
EnumDesktopWindows TEXTEQU <__imp_EnumDesktopWindows> 
extern __imp_EnumDesktopsA:qword 
EnumDesktops TEXTEQU <__imp_EnumDesktopsA> 
extern __imp_EnumDesktopsW:qword 
EnumDesktopsW TEXTEQU <__imp_EnumDesktopsW> 
extern __imp_EnumDisplayDevicesA:qword 
EnumDisplayDevices TEXTEQU <__imp_EnumDisplayDevicesA> 
extern __imp_EnumDisplayDevicesW:qword 
EnumDisplayDevicesW TEXTEQU <__imp_EnumDisplayDevicesW> 
extern __imp_EnumDisplayMonitors:qword 
EnumDisplayMonitors TEXTEQU <__imp_EnumDisplayMonitors> 
extern __imp_EnumDisplaySettingsA:qword 
EnumDisplaySettings TEXTEQU <__imp_EnumDisplaySettingsA> 
extern __imp_EnumDisplaySettingsExA:qword 
EnumDisplaySettingsEx TEXTEQU <__imp_EnumDisplaySettingsExA> 
extern __imp_EnumDisplaySettingsExW:qword 
EnumDisplaySettingsExW TEXTEQU <__imp_EnumDisplaySettingsExW> 
extern __imp_EnumDisplaySettingsW:qword 
EnumDisplaySettingsW TEXTEQU <__imp_EnumDisplaySettingsW> 
extern __imp_EnumPropsA:qword 
EnumProps TEXTEQU <__imp_EnumPropsA> 
extern __imp_EnumPropsExA:qword 
EnumPropsEx TEXTEQU <__imp_EnumPropsExA> 
extern __imp_EnumPropsExW:qword 
EnumPropsExW TEXTEQU <__imp_EnumPropsExW> 
extern __imp_EnumPropsW:qword 
EnumPropsW TEXTEQU <__imp_EnumPropsW> 
extern __imp_EnumThreadWindows:qword 
EnumThreadWindows TEXTEQU <__imp_EnumThreadWindows> 
extern __imp_EnumWindowStationsA:qword 
EnumWindowStations TEXTEQU <__imp_EnumWindowStationsA> 
extern __imp_EnumWindowStationsW:qword 
EnumWindowStationsW TEXTEQU <__imp_EnumWindowStationsW> 
extern __imp_EnumWindows:qword 
EnumWindows TEXTEQU <__imp_EnumWindows> 
extern __imp_EqualRect:qword 
EqualRect TEXTEQU <__imp_EqualRect> 
extern __imp_ExcludeUpdateRgn:qword 
ExcludeUpdateRgn TEXTEQU <__imp_ExcludeUpdateRgn> 
extern __imp_ExitWindowsEx:qword 
ExitWindowsEx TEXTEQU <__imp_ExitWindowsEx> 
extern __imp_FillRect:qword 
FillRect TEXTEQU <__imp_FillRect> 
extern __imp_FindWindowA:qword 
FindWindow TEXTEQU <__imp_FindWindowA> 
extern __imp_FindWindowExA:qword 
FindWindowEx TEXTEQU <__imp_FindWindowExA> 
extern __imp_FindWindowExW:qword 
FindWindowExW TEXTEQU <__imp_FindWindowExW> 
extern __imp_FindWindowW:qword 
FindWindowW TEXTEQU <__imp_FindWindowW> 
extern __imp_FlashWindow:qword 
FlashWindow TEXTEQU <__imp_FlashWindow> 
extern __imp_FlashWindowEx:qword 
FlashWindowEx TEXTEQU <__imp_FlashWindowEx> 
extern __imp_FrameRect:qword 
FrameRect TEXTEQU <__imp_FrameRect> 
extern __imp_FreeDDElParam:qword 
FreeDDElParam TEXTEQU <__imp_FreeDDElParam> 
extern __imp_FrostCrashedWindow:qword 
FrostCrashedWindow TEXTEQU <__imp_FrostCrashedWindow> 
extern __imp_GetActiveWindow:qword 
GetActiveWindow TEXTEQU <__imp_GetActiveWindow> 
extern __imp_GetAltTabInfo:qword 
GetAltTabInfo TEXTEQU <__imp_GetAltTabInfo> 
extern __imp_GetAltTabInfoA:qword 
GetAltTabInfo TEXTEQU <__imp_GetAltTabInfoA> 
extern __imp_GetAltTabInfoW:qword 
GetAltTabInfoW TEXTEQU <__imp_GetAltTabInfoW> 
extern __imp_GetAncestor:qword 
GetAncestor TEXTEQU <__imp_GetAncestor> 
extern __imp_GetAppCompatFlags:qword 
GetAppCompatFlags TEXTEQU <__imp_GetAppCompatFlags> 
extern __imp_GetAppCompatFlags2:qword 
GetAppCompatFlags2 TEXTEQU <__imp_GetAppCompatFlags2> 
extern __imp_GetAsyncKeyState:qword 
GetAsyncKeyState TEXTEQU <__imp_GetAsyncKeyState> 
extern __imp_GetCapture:qword 
GetCapture TEXTEQU <__imp_GetCapture> 
extern __imp_GetCaretBlinkTime:qword 
GetCaretBlinkTime TEXTEQU <__imp_GetCaretBlinkTime> 
extern __imp_GetCaretPos:qword 
GetCaretPos TEXTEQU <__imp_GetCaretPos> 
extern __imp_GetClassInfoA:qword 
GetClassInfo TEXTEQU <__imp_GetClassInfoA> 
extern __imp_GetClassInfoExA:qword 
GetClassInfoEx TEXTEQU <__imp_GetClassInfoExA> 
extern __imp_GetClassInfoExW:qword 
GetClassInfoExW TEXTEQU <__imp_GetClassInfoExW> 
extern __imp_GetClassInfoW:qword 
GetClassInfoW TEXTEQU <__imp_GetClassInfoW> 
extern __imp_GetClassLongA:qword 
GetClassLong TEXTEQU <__imp_GetClassLongA> 
extern __imp_GetClassLongPtrA:qword 
GetClassLongPtr TEXTEQU <__imp_GetClassLongPtrA> 
extern __imp_GetClassLongPtrW:qword 
GetClassLongPtrW TEXTEQU <__imp_GetClassLongPtrW> 
extern __imp_GetClassLongW:qword 
GetClassLongW TEXTEQU <__imp_GetClassLongW> 
extern __imp_GetClassNameA:qword 
GetClassName TEXTEQU <__imp_GetClassNameA> 
extern __imp_GetClassNameW:qword 
GetClassNameW TEXTEQU <__imp_GetClassNameW> 
extern __imp_GetClassWord:qword 
GetClassWord TEXTEQU <__imp_GetClassWord> 
extern __imp_GetClientRect:qword 
GetClientRect TEXTEQU <__imp_GetClientRect> 
extern __imp_GetClipCursor:qword 
GetClipCursor TEXTEQU <__imp_GetClipCursor> 
extern __imp_GetClipboardData:qword 
GetClipboardDat TEXTEQU <__imp_GetClipboardData> 
extern __imp_GetClipboardFormatNameA:qword 
GetClipboardFormatName TEXTEQU <__imp_GetClipboardFormatNameA> 
extern __imp_GetClipboardFormatNameW:qword 
GetClipboardFormatNameW TEXTEQU <__imp_GetClipboardFormatNameW> 
extern __imp_GetClipboardOwner:qword 
GetClipboardOwner TEXTEQU <__imp_GetClipboardOwner> 
extern __imp_GetClipboardSequenceNumber:qword 
GetClipboardSequenceNumber TEXTEQU <__imp_GetClipboardSequenceNumber> 
extern __imp_GetClipboardViewer:qword 
GetClipboardViewer TEXTEQU <__imp_GetClipboardViewer> 
extern __imp_GetComboBoxInfo:qword 
GetComboBoxInfo TEXTEQU <__imp_GetComboBoxInfo> 
extern __imp_GetCursor:qword 
GetCursor TEXTEQU <__imp_GetCursor> 
extern __imp_GetCursorFrameInfo:qword 
GetCursorFrameInfo TEXTEQU <__imp_GetCursorFrameInfo> 
extern __imp_GetCursorInfo:qword 
GetCursorInfo TEXTEQU <__imp_GetCursorInfo> 
extern __imp_GetCursorPos:qword 
GetCursorPos TEXTEQU <__imp_GetCursorPos> 
extern __imp_GetDC:qword 
GetDC TEXTEQU <__imp_GetDC> 
extern __imp_GetDCEx:qword 
GetDCEx TEXTEQU <__imp_GetDCEx> 
extern __imp_GetDesktopWindow:qword 
GetDesktopWindow TEXTEQU <__imp_GetDesktopWindow> 
extern __imp_GetDialogBaseUnits:qword 
GetDialogBaseUnits TEXTEQU <__imp_GetDialogBaseUnits> 
extern __imp_GetDisplayConfigBufferSizes:qword 
GetDisplayConfigBufferSizes TEXTEQU <__imp_GetDisplayConfigBufferSizes> 
extern __imp_GetDlgCtrlID:qword 
GetDlgCtrlID TEXTEQU <__imp_GetDlgCtrlID> 
extern __imp_GetDlgItem:qword 
GetDlgItem TEXTEQU <__imp_GetDlgItem> 
extern __imp_GetDlgItemInt:qword 
GetDlgItemInt TEXTEQU <__imp_GetDlgItemInt> 
extern __imp_GetDlgItemTextA:qword 
GetDlgItemText TEXTEQU <__imp_GetDlgItemTextA> 
extern __imp_GetDlgItemTextW:qword 
GetDlgItemTextW TEXTEQU <__imp_GetDlgItemTextW> 
extern __imp_GetDoubleClickTime:qword 
GetDoubleClickTime TEXTEQU <__imp_GetDoubleClickTime> 
extern __imp_GetFocus:qword 
GetFocus TEXTEQU <__imp_GetFocus> 
extern __imp_GetForegroundWindow:qword 
GetForegroundWindow TEXTEQU <__imp_GetForegroundWindow> 
extern __imp_GetGUIThreadInfo:qword 
GetGUIThreadInfo TEXTEQU <__imp_GetGUIThreadInfo> 
extern __imp_GetGestureConfig:qword 
GetGestureConfig TEXTEQU <__imp_GetGestureConfig> 
extern __imp_GetGestureExtraArgs:qword 
GetGestureExtraArgs TEXTEQU <__imp_GetGestureExtraArgs> 
extern __imp_GetGestureInfo:qword 
GetGestureInfo TEXTEQU <__imp_GetGestureInfo> 
extern __imp_GetGuiResources:qword 
GetGuiResources TEXTEQU <__imp_GetGuiResources> 
extern __imp_GetIconInfo:qword 
GetIconInfo TEXTEQU <__imp_GetIconInfo> 
extern __imp_GetIconInfoExA:qword 
GetIconInfoEx TEXTEQU <__imp_GetIconInfoExA> 
extern __imp_GetIconInfoExW:qword 
GetIconInfoExW TEXTEQU <__imp_GetIconInfoExW> 
extern __imp_GetInputDesktop:qword 
GetInputDesktop TEXTEQU <__imp_GetInputDesktop> 
extern __imp_GetInputLocaleInfo:qword 
GetInputLocaleInfo TEXTEQU <__imp_GetInputLocaleInfo> 
extern __imp_GetInputState:qword 
GetInputState TEXTEQU <__imp_GetInputState> 
extern __imp_GetInternalWindowPos:qword 
GetInternalWindowPos TEXTEQU <__imp_GetInternalWindowPos> 
extern __imp_GetKBCodePage:qword 
GetKBCodePage TEXTEQU <__imp_GetKBCodePage> 
extern __imp_GetKeyNameTextA:qword 
GetKeyNameText TEXTEQU <__imp_GetKeyNameTextA> 
extern __imp_GetKeyNameTextW:qword 
GetKeyNameTextW TEXTEQU <__imp_GetKeyNameTextW> 
extern __imp_GetKeyState:qword 
GetKeyState TEXTEQU <__imp_GetKeyState> 
extern __imp_GetKeyboardLayout:qword 
GetKeyboardLayout TEXTEQU <__imp_GetKeyboardLayout> 
extern __imp_GetKeyboardLayoutList:qword 
GetKeyboardLayoutList TEXTEQU <__imp_GetKeyboardLayoutList> 
extern __imp_GetKeyboardLayoutNameA:qword 
GetKeyboardLayoutName TEXTEQU <__imp_GetKeyboardLayoutNameA> 
extern __imp_GetKeyboardLayoutNameW:qword 
GetKeyboardLayoutNameW TEXTEQU <__imp_GetKeyboardLayoutNameW> 
extern __imp_GetKeyboardState:qword 
GetKeyboardState TEXTEQU <__imp_GetKeyboardState> 
extern __imp_GetKeyboardType:qword 
GetKeyboardType TEXTEQU <__imp_GetKeyboardType> 
extern __imp_GetLastActivePopup:qword 
GetLastActivePopup TEXTEQU <__imp_GetLastActivePopup> 
extern __imp_GetLastInputInfo:qword 
GetLastInputInfo TEXTEQU <__imp_GetLastInputInfo> 
extern __imp_GetLayeredWindowAttributes:qword 
GetLayeredWindowAttributes TEXTEQU <__imp_GetLayeredWindowAttributes> 
extern __imp_GetListBoxInfo:qword 
GetListBoxInfo TEXTEQU <__imp_GetListBoxInfo> 
extern __imp_GetMagnificationDesktopColorEffect:qword 
GetMagnificationDesktopColorEffect TEXTEQU <__imp_GetMagnificationDesktopColorEffect> 
extern __imp_GetMagnificationDesktopMagnification:qword 
GetMagnificationDesktopMagnification TEXTEQU <__imp_GetMagnificationDesktopMagnification> 
extern __imp_GetMagnificationLensCtxInformation:qword 
GetMagnificationLensCtxInformation TEXTEQU <__imp_GetMagnificationLensCtxInformation> 
extern __imp_GetMenu:qword 
GetMenu TEXTEQU <__imp_GetMenu> 
extern __imp_GetMenuBarInfo:qword 
GetMenuBarInfo TEXTEQU <__imp_GetMenuBarInfo> 
extern __imp_GetMenuCheckMarkDimensions:qword 
GetMenuCheckMarkDimensions TEXTEQU <__imp_GetMenuCheckMarkDimensions> 
extern __imp_GetMenuContextHelpId:qword 
GetMenuContextHelpId TEXTEQU <__imp_GetMenuContextHelpId> 
extern __imp_GetMenuDefaultItem:qword 
GetMenuDefaultItem TEXTEQU <__imp_GetMenuDefaultItem> 
extern __imp_GetMenuInfo:qword 
GetMenuInfo TEXTEQU <__imp_GetMenuInfo> 
extern __imp_GetMenuItemCount:qword 
GetMenuItemCount TEXTEQU <__imp_GetMenuItemCount> 
extern __imp_GetMenuItemID:qword 
GetMenuItemID TEXTEQU <__imp_GetMenuItemID> 
extern __imp_GetMenuItemInfoA:qword 
GetMenuItemInfo TEXTEQU <__imp_GetMenuItemInfoA> 
extern __imp_GetMenuItemInfoW:qword 
GetMenuItemInfoW TEXTEQU <__imp_GetMenuItemInfoW> 
extern __imp_GetMenuItemRect:qword 
GetMenuItemRect TEXTEQU <__imp_GetMenuItemRect> 
extern __imp_GetMenuState:qword 
GetMenuState TEXTEQU <__imp_GetMenuState> 
extern __imp_GetMenuStringA:qword 
GetMenuString TEXTEQU <__imp_GetMenuStringA> 
extern __imp_GetMenuStringW:qword 
GetMenuStringW TEXTEQU <__imp_GetMenuStringW> 
extern __imp_GetMessageA:qword 
GetMessage TEXTEQU <__imp_GetMessageA> 
extern __imp_GetMessageExtraInfo:qword 
GetMessageExtraInfo TEXTEQU <__imp_GetMessageExtraInfo> 
extern __imp_GetMessagePos:qword 
GetMessagePos TEXTEQU <__imp_GetMessagePos> 
extern __imp_GetMessageTime:qword 
GetMessageTime TEXTEQU <__imp_GetMessageTime> 
extern __imp_GetMessageW:qword 
GetMessageW TEXTEQU <__imp_GetMessageW> 
extern __imp_GetMonitorInfoA:qword 
GetMonitorInfo TEXTEQU <__imp_GetMonitorInfoA> 
extern __imp_GetMonitorInfoW:qword 
GetMonitorInfoW TEXTEQU <__imp_GetMonitorInfoW> 
extern __imp_GetMouseMovePointsEx:qword 
GetMouseMovePointsEx TEXTEQU <__imp_GetMouseMovePointsEx> 
extern __imp_GetNextDlgGroupItem:qword 
GetNextDlgGroupItem TEXTEQU <__imp_GetNextDlgGroupItem> 
extern __imp_GetNextDlgTabItem:qword 
GetNextDlgTabItem TEXTEQU <__imp_GetNextDlgTabItem> 
extern __imp_GetOpenClipboardWindow:qword 
GetOpenClipboardWindow TEXTEQU <__imp_GetOpenClipboardWindow> 
extern __imp_GetParent:qword 
GetParent TEXTEQU <__imp_GetParent> 
extern __imp_GetPhysicalCursorPos:qword 
GetPhysicalCursorPos TEXTEQU <__imp_GetPhysicalCursorPos> 
extern __imp_GetPriorityClipboardFormat:qword 
GetPriorityClipboardFormat TEXTEQU <__imp_GetPriorityClipboardFormat> 
extern __imp_GetProcessDefaultLayout:qword 
GetProcessDefaultLayout TEXTEQU <__imp_GetProcessDefaultLayout> 
extern __imp_GetProcessWindowStation:qword 
GetProcessWindowStation TEXTEQU <__imp_GetProcessWindowStation> 
extern __imp_GetProgmanWindow:qword 
GetProgmanWindow TEXTEQU <__imp_GetProgmanWindow> 
extern __imp_GetPropA:qword 
GetProp TEXTEQU <__imp_GetPropA> 
extern __imp_GetPropW:qword 
GetPropW TEXTEQU <__imp_GetPropW> 
extern __imp_GetQueueStatus:qword 
GetQueueStatus TEXTEQU <__imp_GetQueueStatus> 
extern __imp_GetRawInputBuffer:qword 
GetRawInputBuffer TEXTEQU <__imp_GetRawInputBuffer> 
extern __imp_GetRawInputData:qword 
GetRawInputDat TEXTEQU <__imp_GetRawInputData> 
extern __imp_GetRawInputDeviceInfoA:qword 
GetRawInputDeviceInfo TEXTEQU <__imp_GetRawInputDeviceInfoA> 
extern __imp_GetRawInputDeviceInfoW:qword 
GetRawInputDeviceInfoW TEXTEQU <__imp_GetRawInputDeviceInfoW> 
extern __imp_GetRawInputDeviceList:qword 
GetRawInputDeviceList TEXTEQU <__imp_GetRawInputDeviceList> 
extern __imp_GetReasonTitleFromReasonCode:qword 
GetReasonTitleFromReasonCode TEXTEQU <__imp_GetReasonTitleFromReasonCode> 
extern __imp_GetRegisteredRawInputDevices:qword 
GetRegisteredRawInputDevices TEXTEQU <__imp_GetRegisteredRawInputDevices> 
extern __imp_GetScrollBarInfo:qword 
GetScrollBarInfo TEXTEQU <__imp_GetScrollBarInfo> 
extern __imp_GetScrollInfo:qword 
GetScrollInfo TEXTEQU <__imp_GetScrollInfo> 
extern __imp_GetScrollPos:qword 
GetScrollPos TEXTEQU <__imp_GetScrollPos> 
extern __imp_GetScrollRange:qword 
GetScrollRange TEXTEQU <__imp_GetScrollRange> 
extern __imp_GetSendMessageReceiver:qword 
GetSendMessageReceiver TEXTEQU <__imp_GetSendMessageReceiver> 
extern __imp_GetShellWindow:qword 
GetShellWindow TEXTEQU <__imp_GetShellWindow> 
extern __imp_GetSubMenu:qword 
GetSubMenu TEXTEQU <__imp_GetSubMenu> 
extern __imp_GetSysColor:qword 
GetSysColor TEXTEQU <__imp_GetSysColor> 
extern __imp_GetSysColorBrush:qword 
GetSysColorBrush TEXTEQU <__imp_GetSysColorBrush> 
extern __imp_GetSystemMenu:qword 
GetSystemMenu TEXTEQU <__imp_GetSystemMenu> 
extern __imp_GetSystemMetrics:qword 
GetSystemMetrics TEXTEQU <__imp_GetSystemMetrics> 
extern __imp_GetTabbedTextExtentA:qword 
GetTabbedTextExtent TEXTEQU <__imp_GetTabbedTextExtentA> 
extern __imp_GetTabbedTextExtentW:qword 
GetTabbedTextExtentW TEXTEQU <__imp_GetTabbedTextExtentW> 
extern __imp_GetTaskmanWindow:qword 
GetTaskmanWindow TEXTEQU <__imp_GetTaskmanWindow> 
extern __imp_GetThreadDesktop:qword 
GetThreadDesktop TEXTEQU <__imp_GetThreadDesktop> 
extern __imp_GetTitleBarInfo:qword 
GetTitleBarInfo TEXTEQU <__imp_GetTitleBarInfo> 
extern __imp_GetTopLevelWindow:qword 
GetTopLevelWindow TEXTEQU <__imp_GetTopLevelWindow> 
extern __imp_GetTopWindow:qword 
GetTopWindow TEXTEQU <__imp_GetTopWindow> 
extern __imp_GetTouchInputInfo:qword 
GetTouchInputInfo TEXTEQU <__imp_GetTouchInputInfo> 
extern __imp_GetUpdateRect:qword 
GetUpdateRect TEXTEQU <__imp_GetUpdateRect> 
extern __imp_GetUpdateRgn:qword 
GetUpdateRgn TEXTEQU <__imp_GetUpdateRgn> 
extern __imp_GetUpdatedClipboardFormats:qword 
GetUpdatedClipboardFormats TEXTEQU <__imp_GetUpdatedClipboardFormats> 
extern __imp_GetUserObjectInformationA:qword 
GetUserObjectInformation TEXTEQU <__imp_GetUserObjectInformationA> 
extern __imp_GetUserObjectInformationW:qword 
GetUserObjectInformationW TEXTEQU <__imp_GetUserObjectInformationW> 
extern __imp_GetUserObjectSecurity:qword 
GetUserObjectSecurity TEXTEQU <__imp_GetUserObjectSecurity> 
extern __imp_GetWinStationInfo:qword 
GetWinStationInfo TEXTEQU <__imp_GetWinStationInfo> 
extern __imp_GetWindow:qword 
GetWindow TEXTEQU <__imp_GetWindow> 
extern __imp_GetWindowCompositionAttribute:qword 
GetWindowCompositionAttribute TEXTEQU <__imp_GetWindowCompositionAttribute> 
extern __imp_GetWindowCompositionInfo:qword 
GetWindowCompositionInfo TEXTEQU <__imp_GetWindowCompositionInfo> 
extern __imp_GetWindowContextHelpId:qword 
GetWindowContextHelpId TEXTEQU <__imp_GetWindowContextHelpId> 
extern __imp_GetWindowDC:qword 
GetWindowDC TEXTEQU <__imp_GetWindowDC> 
extern __imp_GetWindowDisplayAffinity:qword 
GetWindowDisplayAffinity TEXTEQU <__imp_GetWindowDisplayAffinity> 
extern __imp_GetWindowInfo:qword 
GetWindowInfo TEXTEQU <__imp_GetWindowInfo> 
extern __imp_GetWindowLongA:qword 
GetWindowLong TEXTEQU <__imp_GetWindowLongA> 
extern __imp_GetWindowLongPtrA:qword 
GetWindowLongPtr TEXTEQU <__imp_GetWindowLongPtrA> 
extern __imp_GetWindowLongPtrW:qword 
GetWindowLongPtrW TEXTEQU <__imp_GetWindowLongPtrW> 
extern __imp_GetWindowLongW:qword 
GetWindowLongW TEXTEQU <__imp_GetWindowLongW> 
extern __imp_GetWindowMinimizeRect:qword 
GetWindowMinimizeRect TEXTEQU <__imp_GetWindowMinimizeRect> 
extern __imp_GetWindowModuleFileName:qword 
GetWindowModuleFileName TEXTEQU <__imp_GetWindowModuleFileName> 
extern __imp_GetWindowModuleFileNameA:qword 
GetWindowModuleFileName TEXTEQU <__imp_GetWindowModuleFileNameA> 
extern __imp_GetWindowModuleFileNameW:qword 
GetWindowModuleFileNameW TEXTEQU <__imp_GetWindowModuleFileNameW> 
extern __imp_GetWindowPlacement:qword 
GetWindowPlacement TEXTEQU <__imp_GetWindowPlacement> 
extern __imp_GetWindowRect:qword 
GetWindowRect TEXTEQU <__imp_GetWindowRect> 
extern __imp_GetWindowRgn:qword 
GetWindowRgn TEXTEQU <__imp_GetWindowRgn> 
extern __imp_GetWindowRgnBox:qword 
GetWindowRgnBox TEXTEQU <__imp_GetWindowRgnBox> 
extern __imp_GetWindowRgnEx:qword 
GetWindowRgnEx TEXTEQU <__imp_GetWindowRgnEx> 
extern __imp_GetWindowTextA:qword 
GetWindowText TEXTEQU <__imp_GetWindowTextA> 
extern __imp_GetWindowTextLengthA:qword 
GetWindowTextLength TEXTEQU <__imp_GetWindowTextLengthA> 
extern __imp_GetWindowTextLengthW:qword 
GetWindowTextLengthW TEXTEQU <__imp_GetWindowTextLengthW> 
extern __imp_GetWindowTextW:qword 
GetWindowTextW TEXTEQU <__imp_GetWindowTextW> 
extern __imp_GetWindowThreadProcessId:qword 
GetWindowThreadProcessId TEXTEQU <__imp_GetWindowThreadProcessId> 
extern __imp_GetWindowWord:qword 
GetWindowWord TEXTEQU <__imp_GetWindowWord> 
extern __imp_GhostWindowFromHungWindow:qword 
GhostWindowFromHungWindow TEXTEQU <__imp_GhostWindowFromHungWindow> 
extern __imp_GrayStringA:qword 
GrayString TEXTEQU <__imp_GrayStringA> 
extern __imp_GrayStringW:qword 
GrayStringW TEXTEQU <__imp_GrayStringW> 
extern __imp_HideCaret:qword 
HideCaret TEXTEQU <__imp_HideCaret> 
extern __imp_HiliteMenuItem:qword 
HiliteMenuItem TEXTEQU <__imp_HiliteMenuItem> 
extern __imp_HungWindowFromGhostWindow:qword 
HungWindowFromGhostWindow TEXTEQU <__imp_HungWindowFromGhostWindow> 
extern __imp_IMPGetIMEA:qword 
IMPGetIME TEXTEQU <__imp_IMPGetIMEA> 
extern __imp_IMPGetIMEW:qword 
IMPGetIMEW TEXTEQU <__imp_IMPGetIMEW> 
extern __imp_IMPQueryIMEA:qword 
IMPQueryIME TEXTEQU <__imp_IMPQueryIMEA> 
extern __imp_IMPQueryIMEW:qword 
IMPQueryIMEW TEXTEQU <__imp_IMPQueryIMEW> 
extern __imp_IMPSetIMEA:qword 
IMPSetIME TEXTEQU <__imp_IMPSetIMEA> 
extern __imp_IMPSetIMEW:qword 
IMPSetIMEW TEXTEQU <__imp_IMPSetIMEW> 
extern __imp_ImpersonateDdeClientWindow:qword 
ImpersonateDdeClientWindow TEXTEQU <__imp_ImpersonateDdeClientWindow> 
extern __imp_InSendMessage:qword 
InSendMessage TEXTEQU <__imp_InSendMessage> 
extern __imp_InSendMessageEx:qword 
InSendMessageEx TEXTEQU <__imp_InSendMessageEx> 
extern __imp_InflateRect:qword 
InflateRect TEXTEQU <__imp_InflateRect> 
extern __imp_InitializeLpkHooks:qword 
InitializeLpkHooks TEXTEQU <__imp_InitializeLpkHooks> 
extern __imp_InsertMenuA:qword 
InsertMenu TEXTEQU <__imp_InsertMenuA> 
extern __imp_InsertMenuItemA:qword 
InsertMenuItem TEXTEQU <__imp_InsertMenuItemA> 
extern __imp_InsertMenuItemW:qword 
InsertMenuItemW TEXTEQU <__imp_InsertMenuItemW> 
extern __imp_InsertMenuW:qword 
InsertMenuW TEXTEQU <__imp_InsertMenuW> 
extern __imp_InternalGetWindowIcon:qword 
InternalGetWindowIcon TEXTEQU <__imp_InternalGetWindowIcon> 
extern __imp_InternalGetWindowText:qword 
InternalGetWindowText TEXTEQU <__imp_InternalGetWindowText> 
extern __imp_IntersectRect:qword 
IntersectRect TEXTEQU <__imp_IntersectRect> 
extern __imp_InvalidateRect:qword 
InvalidateRect TEXTEQU <__imp_InvalidateRect> 
extern __imp_InvalidateRgn:qword 
InvalidateRgn TEXTEQU <__imp_InvalidateRgn> 
extern __imp_InvertRect:qword 
InvertRect TEXTEQU <__imp_InvertRect> 
extern __imp_IsCharAlphaA:qword 
IsCharAlpha TEXTEQU <__imp_IsCharAlphaA> 
extern __imp_IsCharAlphaNumericA:qword 
IsCharAlphaNumeric TEXTEQU <__imp_IsCharAlphaNumericA> 
extern __imp_IsCharAlphaNumericW:qword 
IsCharAlphaNumericW TEXTEQU <__imp_IsCharAlphaNumericW> 
extern __imp_IsCharAlphaW:qword 
IsCharAlphaW TEXTEQU <__imp_IsCharAlphaW> 
extern __imp_IsCharLowerA:qword 
IsCharLower TEXTEQU <__imp_IsCharLowerA> 
extern __imp_IsCharLowerW:qword 
IsCharLowerW TEXTEQU <__imp_IsCharLowerW> 
extern __imp_IsCharUpperA:qword 
IsCharUpper TEXTEQU <__imp_IsCharUpperA> 
extern __imp_IsCharUpperW:qword 
IsCharUpperW TEXTEQU <__imp_IsCharUpperW> 
extern __imp_IsChild:qword 
IsChild TEXTEQU <__imp_IsChild> 
extern __imp_IsClipboardFormatAvailable:qword 
IsClipboardFormatAvailable TEXTEQU <__imp_IsClipboardFormatAvailable> 
extern __imp_IsDialogMessage:qword 
IsDialogMessage TEXTEQU <__imp_IsDialogMessage> 
extern __imp_IsDialogMessageA:qword 
IsDialogMessage TEXTEQU <__imp_IsDialogMessageA> 
extern __imp_IsDialogMessageW:qword 
IsDialogMessageW TEXTEQU <__imp_IsDialogMessageW> 
extern __imp_IsDlgButtonChecked:qword 
IsDlgButtonChecked TEXTEQU <__imp_IsDlgButtonChecked> 
extern __imp_IsGUIThread:qword 
IsGUIThread TEXTEQU <__imp_IsGUIThread> 
extern __imp_IsHungAppWindow:qword 
IsHungAppWindow TEXTEQU <__imp_IsHungAppWindow> 
extern __imp_IsIconic:qword 
IsIconic TEXTEQU <__imp_IsIconic> 
extern __imp_IsMenu:qword 
IsMenu TEXTEQU <__imp_IsMenu> 
extern __imp_IsProcessDPIAware:qword 
IsProcessDPIAware TEXTEQU <__imp_IsProcessDPIAware> 
extern __imp_IsRectEmpty:qword 
IsRectEmpty TEXTEQU <__imp_IsRectEmpty> 
extern __imp_IsSETEnabled:qword 
IsSETEnabled TEXTEQU <__imp_IsSETEnabled> 
extern __imp_IsServerSideWindow:qword 
IsServerSideWindow TEXTEQU <__imp_IsServerSideWindow> 
extern __imp_IsThreadDesktopComposited:qword 
IsThreadDesktopComposited TEXTEQU <__imp_IsThreadDesktopComposited> 
extern __imp_IsTopLevelWindow:qword 
IsTopLevelWindow TEXTEQU <__imp_IsTopLevelWindow> 
extern __imp_IsTouchWindow:qword 
IsTouchWindow TEXTEQU <__imp_IsTouchWindow> 
extern __imp_IsWinEventHookInstalled:qword 
IsWinEventHookInstalled TEXTEQU <__imp_IsWinEventHookInstalled> 
extern __imp_IsWindow:qword 
IsWindow TEXTEQU <__imp_IsWindow> 
extern __imp_IsWindowEnabled:qword 
IsWindowEnabled TEXTEQU <__imp_IsWindowEnabled> 
extern __imp_IsWindowInDestroy:qword 
IsWindowInDestroy TEXTEQU <__imp_IsWindowInDestroy> 
extern __imp_IsWindowRedirectedForPrint:qword 
IsWindowRedirectedForPrint TEXTEQU <__imp_IsWindowRedirectedForPrint> 
extern __imp_IsWindowUnicode:qword 
IsWindowUnicode TEXTEQU <__imp_IsWindowUnicode> 
extern __imp_IsWindowVisible:qword 
IsWindowVisible TEXTEQU <__imp_IsWindowVisible> 
extern __imp_IsWow64Message:qword 
IsWow64Message TEXTEQU <__imp_IsWow64Message> 
extern __imp_IsZoomed:qword 
IsZoomed TEXTEQU <__imp_IsZoomed> 
extern __imp_KillTimer:qword 
KillTimer TEXTEQU <__imp_KillTimer> 
extern __imp_LoadAcceleratorsA:qword 
LoadAccelerators TEXTEQU <__imp_LoadAcceleratorsA> 
extern __imp_LoadAcceleratorsW:qword 
LoadAcceleratorsW TEXTEQU <__imp_LoadAcceleratorsW> 
extern __imp_LoadBitmapA:qword 
LoadBitmap TEXTEQU <__imp_LoadBitmapA> 
extern __imp_LoadBitmapW:qword 
LoadBitmapW TEXTEQU <__imp_LoadBitmapW> 
extern __imp_LoadCursorA:qword 
LoadCursor TEXTEQU <__imp_LoadCursorA> 
extern __imp_LoadCursorFromFileA:qword 
LoadCursorFromFile TEXTEQU <__imp_LoadCursorFromFileA> 
extern __imp_LoadCursorFromFileW:qword 
LoadCursorFromFileW TEXTEQU <__imp_LoadCursorFromFileW> 
extern __imp_LoadCursorW:qword 
LoadCursorW TEXTEQU <__imp_LoadCursorW> 
extern __imp_LoadIconA:qword 
LoadIcon TEXTEQU <__imp_LoadIconA> 
extern __imp_LoadIconW:qword 
LoadIconW TEXTEQU <__imp_LoadIconW> 
extern __imp_LoadImageA:qword 
LoadImage TEXTEQU <__imp_LoadImageA> 
extern __imp_LoadImageW:qword 
LoadImageW TEXTEQU <__imp_LoadImageW> 
extern __imp_LoadKeyboardLayoutA:qword 
LoadKeyboardLayout TEXTEQU <__imp_LoadKeyboardLayoutA> 
extern __imp_LoadKeyboardLayoutEx:qword 
LoadKeyboardLayoutEx TEXTEQU <__imp_LoadKeyboardLayoutEx> 
extern __imp_LoadKeyboardLayoutW:qword 
LoadKeyboardLayoutW TEXTEQU <__imp_LoadKeyboardLayoutW> 
extern __imp_LoadLocalFonts:qword 
LoadLocalFonts TEXTEQU <__imp_LoadLocalFonts> 
extern __imp_LoadMenuA:qword 
LoadMenu TEXTEQU <__imp_LoadMenuA> 
extern __imp_LoadMenuIndirectA:qword 
LoadMenuIndirect TEXTEQU <__imp_LoadMenuIndirectA> 
extern __imp_LoadMenuIndirectW:qword 
LoadMenuIndirectW TEXTEQU <__imp_LoadMenuIndirectW> 
extern __imp_LoadMenuW:qword 
LoadMenuW TEXTEQU <__imp_LoadMenuW> 
extern __imp_LoadRemoteFonts:qword 
LoadRemoteFonts TEXTEQU <__imp_LoadRemoteFonts> 
extern __imp_LoadStringA:qword 
LoadString TEXTEQU <__imp_LoadStringA> 
extern __imp_LoadStringW:qword 
LoadStringW TEXTEQU <__imp_LoadStringW> 
extern __imp_LockSetForegroundWindow:qword 
LockSetForegroundWindow TEXTEQU <__imp_LockSetForegroundWindow> 
extern __imp_LockWindowStation:qword 
LockWindowStation TEXTEQU <__imp_LockWindowStation> 
extern __imp_LockWindowUpdate:qword 
LockWindowUpdate TEXTEQU <__imp_LockWindowUpdate> 
extern __imp_LockWorkStation:qword 
LockWorkStation TEXTEQU <__imp_LockWorkStation> 
extern __imp_LogicalToPhysicalPoint:qword 
LogicalToPhysicalPoint TEXTEQU <__imp_LogicalToPhysicalPoint> 
extern __imp_LookupIconIdFromDirectory:qword 
LookupIconIdFromDirectory TEXTEQU <__imp_LookupIconIdFromDirectory> 
extern __imp_LookupIconIdFromDirectoryEx:qword 
LookupIconIdFromDirectoryEx TEXTEQU <__imp_LookupIconIdFromDirectoryEx> 
extern __imp_MBToWCSEx:qword 
MBToWCSEx TEXTEQU <__imp_MBToWCSEx> 
extern __imp_MB_GetString:qword 
MB_GetString TEXTEQU <__imp_MB_GetString> 
extern __imp_MapDialogRect:qword 
MapDialogRect TEXTEQU <__imp_MapDialogRect> 
extern __imp_MapVirtualKeyA:qword 
MapVirtualKey TEXTEQU <__imp_MapVirtualKeyA> 
extern __imp_MapVirtualKeyExA:qword 
MapVirtualKeyEx TEXTEQU <__imp_MapVirtualKeyExA> 
extern __imp_MapVirtualKeyExW:qword 
MapVirtualKeyExW TEXTEQU <__imp_MapVirtualKeyExW> 
extern __imp_MapVirtualKeyW:qword 
MapVirtualKeyW TEXTEQU <__imp_MapVirtualKeyW> 
extern __imp_MapWindowPoints:qword 
MapWindowPoints TEXTEQU <__imp_MapWindowPoints> 
extern __imp_MenuItemFromPoint:qword 
MenuItemFromPoint TEXTEQU <__imp_MenuItemFromPoint> 
extern __imp_MenuWindowProcA:qword 
MenuWindowProc TEXTEQU <__imp_MenuWindowProcA> 
extern __imp_MenuWindowProcW:qword 
MenuWindowProcW TEXTEQU <__imp_MenuWindowProcW> 
extern __imp_MessageBeep:qword 
MessageBeep TEXTEQU <__imp_MessageBeep> 
extern __imp_MessageBoxA:qword 
MessageBox TEXTEQU <__imp_MessageBoxA> 
extern __imp_MessageBoxExA:qword 
MessageBoxEx TEXTEQU <__imp_MessageBoxExA> 
extern __imp_MessageBoxExW:qword 
MessageBoxExW TEXTEQU <__imp_MessageBoxExW> 
extern __imp_MessageBoxIndirectA:qword 
MessageBoxIndirect TEXTEQU <__imp_MessageBoxIndirectA> 
extern __imp_MessageBoxIndirectW:qword 
MessageBoxIndirectW TEXTEQU <__imp_MessageBoxIndirectW> 
extern __imp_MessageBoxTimeoutA:qword 
MessageBoxTimeout TEXTEQU <__imp_MessageBoxTimeoutA> 
extern __imp_MessageBoxTimeoutW:qword 
MessageBoxTimeoutW TEXTEQU <__imp_MessageBoxTimeoutW> 
extern __imp_MessageBoxW:qword 
MessageBoxW TEXTEQU <__imp_MessageBoxW> 
extern __imp_ModifyMenuA:qword 
ModifyMenu TEXTEQU <__imp_ModifyMenuA> 
extern __imp_ModifyMenuW:qword 
ModifyMenuW TEXTEQU <__imp_ModifyMenuW> 
extern __imp_MonitorFromPoint:qword 
MonitorFromPoint TEXTEQU <__imp_MonitorFromPoint> 
extern __imp_MonitorFromRect:qword 
MonitorFromRect TEXTEQU <__imp_MonitorFromRect> 
extern __imp_MonitorFromWindow:qword 
MonitorFromWindow TEXTEQU <__imp_MonitorFromWindow> 
extern __imp_MoveWindow:qword 
MoveWindow TEXTEQU <__imp_MoveWindow> 
extern __imp_MsgWaitForMultipleObjects:qword 
MsgWaitForMultipleObjects TEXTEQU <__imp_MsgWaitForMultipleObjects> 
extern __imp_MsgWaitForMultipleObjectsEx:qword 
MsgWaitForMultipleObjectsEx TEXTEQU <__imp_MsgWaitForMultipleObjectsEx> 
extern __imp_NotifyOverlayWindow:qword 
NotifyOverlayWindow TEXTEQU <__imp_NotifyOverlayWindow> 
extern __imp_NotifyWinEvent:qword 
NotifyWinEvent TEXTEQU <__imp_NotifyWinEvent> 
extern __imp_OemKeyScan:qword 
OemKeyScan TEXTEQU <__imp_OemKeyScan> 
extern __imp_OemToCharA:qword 
OemToChar TEXTEQU <__imp_OemToCharA> 
extern __imp_OemToCharBuffA:qword 
OemToCharBuff TEXTEQU <__imp_OemToCharBuffA> 
extern __imp_OemToCharBuffW:qword 
OemToCharBuffW TEXTEQU <__imp_OemToCharBuffW> 
extern __imp_OemToCharW:qword 
OemToCharW TEXTEQU <__imp_OemToCharW> 
extern __imp_OffsetRect:qword 
OffsetRect TEXTEQU <__imp_OffsetRect> 
extern __imp_OpenClipboard:qword 
OpenClipboard TEXTEQU <__imp_OpenClipboard> 
extern __imp_OpenDesktopA:qword 
OpenDesktop TEXTEQU <__imp_OpenDesktopA> 
extern __imp_OpenDesktopW:qword 
OpenDesktopW TEXTEQU <__imp_OpenDesktopW> 
extern __imp_OpenIcon:qword 
OpenIcon TEXTEQU <__imp_OpenIcon> 
extern __imp_OpenInputDesktop:qword 
OpenInputDesktop TEXTEQU <__imp_OpenInputDesktop> 
extern __imp_OpenThreadDesktop:qword 
OpenThreadDesktop TEXTEQU <__imp_OpenThreadDesktop> 
extern __imp_OpenWindowStationA:qword 
OpenWindowStation TEXTEQU <__imp_OpenWindowStationA> 
extern __imp_OpenWindowStationW:qword 
OpenWindowStationW TEXTEQU <__imp_OpenWindowStationW> 
extern __imp_PackDDElParam:qword 
PackDDElParam TEXTEQU <__imp_PackDDElParam> 
extern __imp_PaintDesktop:qword 
PaintDesktop TEXTEQU <__imp_PaintDesktop> 
extern __imp_PaintMenuBar:qword 
PaintMenuBar TEXTEQU <__imp_PaintMenuBar> 
extern __imp_PaintMonitor:qword 
PaintMonitor TEXTEQU <__imp_PaintMonitor> 
extern __imp_PeekMessageA:qword 
PeekMessage TEXTEQU <__imp_PeekMessageA> 
extern __imp_PeekMessageW:qword 
PeekMessageW TEXTEQU <__imp_PeekMessageW> 
extern __imp_PhysicalToLogicalPoint:qword 
PhysicalToLogicalPoint TEXTEQU <__imp_PhysicalToLogicalPoint> 
extern __imp_PostMessageA:qword 
PostMessage TEXTEQU <__imp_PostMessageA> 
extern __imp_PostMessageW:qword 
PostMessageW TEXTEQU <__imp_PostMessageW> 
extern __imp_PostQuitMessage:qword 
PostQuitMessage TEXTEQU <__imp_PostQuitMessage> 
extern __imp_PostThreadMessageA:qword 
PostThreadMessage TEXTEQU <__imp_PostThreadMessageA> 
extern __imp_PostThreadMessageW:qword 
PostThreadMessageW TEXTEQU <__imp_PostThreadMessageW> 
extern __imp_PrintWindow:qword 
PrintWindow TEXTEQU <__imp_PrintWindow> 
extern __imp_PrivateExtractIconExA:qword 
PrivateExtractIconEx TEXTEQU <__imp_PrivateExtractIconExA> 
extern __imp_PrivateExtractIconExW:qword 
PrivateExtractIconExW TEXTEQU <__imp_PrivateExtractIconExW> 
extern __imp_PrivateExtractIconsA:qword 
PrivateExtractIcons TEXTEQU <__imp_PrivateExtractIconsA> 
extern __imp_PrivateExtractIconsW:qword 
PrivateExtractIconsW TEXTEQU <__imp_PrivateExtractIconsW> 
extern __imp_PrivateRegisterICSProc:qword 
PrivateRegisterICSProc TEXTEQU <__imp_PrivateRegisterICSProc> 
extern __imp_PtInRect:qword 
PtInRect TEXTEQU <__imp_PtInRect> 
extern __imp_QueryDisplayConfig:qword 
QueryDisplayConfig TEXTEQU <__imp_QueryDisplayConfig> 
extern __imp_QuerySendMessage:qword 
QuerySendMessage TEXTEQU <__imp_QuerySendMessage> 
extern __imp_RealChildWindowFromPoint:qword 
RealChildWindowFromPoint TEXTEQU <__imp_RealChildWindowFromPoint> 
extern __imp_RealGetWindowClass:qword 
RealGetWindowClass TEXTEQU <__imp_RealGetWindowClass> 
extern __imp_RealGetWindowClassA:qword 
RealGetWindowClass TEXTEQU <__imp_RealGetWindowClassA> 
extern __imp_RealGetWindowClassW:qword 
RealGetWindowClassW TEXTEQU <__imp_RealGetWindowClassW> 
extern __imp_ReasonCodeNeedsBugID:qword 
ReasonCodeNeedsBugID TEXTEQU <__imp_ReasonCodeNeedsBugID> 
extern __imp_ReasonCodeNeedsComment:qword 
ReasonCodeNeedsComment TEXTEQU <__imp_ReasonCodeNeedsComment> 
extern __imp_RecordShutdownReason:qword 
RecordShutdownReason TEXTEQU <__imp_RecordShutdownReason> 
extern __imp_RedrawWindow:qword 
RedrawWindow TEXTEQU <__imp_RedrawWindow> 
extern __imp_RegisterClassA:qword 
RegisterClass TEXTEQU <__imp_RegisterClassA> 
extern __imp_RegisterClassExA:qword 
RegisterClassEx TEXTEQU <__imp_RegisterClassExA> 
extern __imp_RegisterClassExW:qword 
RegisterClassExW TEXTEQU <__imp_RegisterClassExW> 
extern __imp_RegisterClassW:qword 
RegisterClassW TEXTEQU <__imp_RegisterClassW> 
extern __imp_RegisterClipboardFormatA:qword 
RegisterClipboardFormat TEXTEQU <__imp_RegisterClipboardFormatA> 
extern __imp_RegisterClipboardFormatW:qword 
RegisterClipboardFormatW TEXTEQU <__imp_RegisterClipboardFormatW> 
extern __imp_RegisterDeviceNotificationA:qword 
RegisterDeviceNotification TEXTEQU <__imp_RegisterDeviceNotificationA> 
extern __imp_RegisterDeviceNotificationW:qword 
RegisterDeviceNotificationW TEXTEQU <__imp_RegisterDeviceNotificationW> 
extern __imp_RegisterErrorReportingDialog:qword 
RegisterErrorReportingDialog TEXTEQU <__imp_RegisterErrorReportingDialog> 
extern __imp_RegisterFrostWindow:qword 
RegisterFrostWindow TEXTEQU <__imp_RegisterFrostWindow> 
extern __imp_RegisterGhostWindow:qword 
RegisterGhostWindow TEXTEQU <__imp_RegisterGhostWindow> 
extern __imp_RegisterHotKey:qword 
RegisterHotKey TEXTEQU <__imp_RegisterHotKey> 
extern __imp_RegisterLogonProcess:qword 
RegisterLogonProcess TEXTEQU <__imp_RegisterLogonProcess> 
extern __imp_RegisterMessagePumpHook:qword 
RegisterMessagePumpHook TEXTEQU <__imp_RegisterMessagePumpHook> 
extern __imp_RegisterPowerSettingNotification:qword 
RegisterPowerSettingNotification TEXTEQU <__imp_RegisterPowerSettingNotification> 
extern __imp_RegisterRawInputDevices:qword 
RegisterRawInputDevices TEXTEQU <__imp_RegisterRawInputDevices> 
extern __imp_RegisterServicesProcess:qword 
RegisterServicesProcess TEXTEQU <__imp_RegisterServicesProcess> 
extern __imp_RegisterSessionPort:qword 
RegisterSessionPort TEXTEQU <__imp_RegisterSessionPort> 
extern __imp_RegisterShellHookWindow:qword 
RegisterShellHookWindow TEXTEQU <__imp_RegisterShellHookWindow> 
extern __imp_RegisterSystemThread:qword 
RegisterSystemThread TEXTEQU <__imp_RegisterSystemThread> 
extern __imp_RegisterTasklist:qword 
RegisterTasklist TEXTEQU <__imp_RegisterTasklist> 
extern __imp_RegisterTouchWindow:qword 
RegisterTouchWindow TEXTEQU <__imp_RegisterTouchWindow> 
extern __imp_RegisterUserApiHook:qword 
RegisterUserApiHook TEXTEQU <__imp_RegisterUserApiHook> 
extern __imp_RegisterWindowMessageA:qword 
RegisterWindowMessage TEXTEQU <__imp_RegisterWindowMessageA> 
extern __imp_RegisterWindowMessageW:qword 
RegisterWindowMessageW TEXTEQU <__imp_RegisterWindowMessageW> 
extern __imp_ReleaseCapture:qword 
ReleaseCapture TEXTEQU <__imp_ReleaseCapture> 
extern __imp_ReleaseDC:qword 
ReleaseDC TEXTEQU <__imp_ReleaseDC> 
extern __imp_RemoveClipboardFormatListener:qword 
RemoveClipboardFormatListener TEXTEQU <__imp_RemoveClipboardFormatListener> 
extern __imp_RemoveMenu:qword 
RemoveMenu TEXTEQU <__imp_RemoveMenu> 
extern __imp_RemovePropA:qword 
RemoveProp TEXTEQU <__imp_RemovePropA> 
extern __imp_RemovePropW:qword 
RemovePropW TEXTEQU <__imp_RemovePropW> 
extern __imp_ReplyMessage:qword 
ReplyMessage TEXTEQU <__imp_ReplyMessage> 
extern __imp_ResolveDesktopForWOW:qword 
ResolveDesktopForWOW TEXTEQU <__imp_ResolveDesktopForWOW> 
extern __imp_ReuseDDElParam:qword 
ReuseDDElParam TEXTEQU <__imp_ReuseDDElParam> 
extern __imp_ScreenToClient:qword 
ScreenToClient TEXTEQU <__imp_ScreenToClient> 
extern __imp_ScrollChildren:qword 
ScrollChildren TEXTEQU <__imp_ScrollChildren> 
extern __imp_ScrollDC:qword 
ScrollDC TEXTEQU <__imp_ScrollDC> 
extern __imp_ScrollWindow:qword 
ScrollWindow TEXTEQU <__imp_ScrollWindow> 
extern __imp_ScrollWindowEx:qword 
ScrollWindowEx TEXTEQU <__imp_ScrollWindowEx> 
extern __imp_SendDlgItemMessageA:qword 
SendDlgItemMessage TEXTEQU <__imp_SendDlgItemMessageA> 
extern __imp_SendDlgItemMessageW:qword 
SendDlgItemMessageW TEXTEQU <__imp_SendDlgItemMessageW> 
extern __imp_SendIMEMessageExA:qword 
SendIMEMessageEx TEXTEQU <__imp_SendIMEMessageExA> 
extern __imp_SendIMEMessageExW:qword 
SendIMEMessageExW TEXTEQU <__imp_SendIMEMessageExW> 
extern __imp_SendInput:qword 
SendInput TEXTEQU <__imp_SendInput> 
extern __imp_SendMessageA:qword 
SendMessage TEXTEQU <__imp_SendMessageA> 
extern __imp_SendMessageCallbackA:qword 
SendMessageCallback TEXTEQU <__imp_SendMessageCallbackA> 
extern __imp_SendMessageCallbackW:qword 
SendMessageCallbackW TEXTEQU <__imp_SendMessageCallbackW> 
extern __imp_SendMessageTimeoutA:qword 
SendMessageTimeout TEXTEQU <__imp_SendMessageTimeoutA> 
extern __imp_SendMessageTimeoutW:qword 
SendMessageTimeoutW TEXTEQU <__imp_SendMessageTimeoutW> 
extern __imp_SendMessageW:qword 
SendMessageW TEXTEQU <__imp_SendMessageW> 
extern __imp_SendNotifyMessageA:qword 
SendNotifyMessage TEXTEQU <__imp_SendNotifyMessageA> 
extern __imp_SendNotifyMessageW:qword 
SendNotifyMessageW TEXTEQU <__imp_SendNotifyMessageW> 
extern __imp_SetActiveWindow:qword 
SetActiveWindow TEXTEQU <__imp_SetActiveWindow> 
extern __imp_SetCapture:qword 
SetCapture TEXTEQU <__imp_SetCapture> 
extern __imp_SetCaretBlinkTime:qword 
SetCaretBlinkTime TEXTEQU <__imp_SetCaretBlinkTime> 
extern __imp_SetCaretPos:qword 
SetCaretPos TEXTEQU <__imp_SetCaretPos> 
extern __imp_SetClassLongA:qword 
SetClassLong TEXTEQU <__imp_SetClassLongA> 
extern __imp_SetClassLongPtrA:qword 
SetClassLongPtr TEXTEQU <__imp_SetClassLongPtrA> 
extern __imp_SetClassLongPtrW:qword 
SetClassLongPtrW TEXTEQU <__imp_SetClassLongPtrW> 
extern __imp_SetClassLongW:qword 
SetClassLongW TEXTEQU <__imp_SetClassLongW> 
extern __imp_SetClassWord:qword 
SetClassWord TEXTEQU <__imp_SetClassWord> 
extern __imp_SetClipboardData:qword 
SetClipboardDat TEXTEQU <__imp_SetClipboardData> 
extern __imp_SetClipboardViewer:qword 
SetClipboardViewer TEXTEQU <__imp_SetClipboardViewer> 
extern __imp_SetCursor:qword 
SetCursor TEXTEQU <__imp_SetCursor> 
extern __imp_SetCursorContents:qword 
SetCursorContents TEXTEQU <__imp_SetCursorContents> 
extern __imp_SetCursorPos:qword 
SetCursorPos TEXTEQU <__imp_SetCursorPos> 
extern __imp_SetDebugErrorLevel:qword 
SetDebugErrorLevel TEXTEQU <__imp_SetDebugErrorLevel> 
extern __imp_SetDeskWallpaper:qword 
SetDeskWallpaper TEXTEQU <__imp_SetDeskWallpaper> 
extern __imp_SetDisplayConfig:qword 
SetDisplayConfig TEXTEQU <__imp_SetDisplayConfig> 
extern __imp_SetDlgItemInt:qword 
SetDlgItemInt TEXTEQU <__imp_SetDlgItemInt> 
extern __imp_SetDlgItemTextA:qword 
SetDlgItemText TEXTEQU <__imp_SetDlgItemTextA> 
extern __imp_SetDlgItemTextW:qword 
SetDlgItemTextW TEXTEQU <__imp_SetDlgItemTextW> 
extern __imp_SetDoubleClickTime:qword 
SetDoubleClickTime TEXTEQU <__imp_SetDoubleClickTime> 
extern __imp_SetFocus:qword 
SetFocus TEXTEQU <__imp_SetFocus> 
extern __imp_SetForegroundWindow:qword 
SetForegroundWindow TEXTEQU <__imp_SetForegroundWindow> 
extern __imp_SetGestureConfig:qword 
SetGestureConfig TEXTEQU <__imp_SetGestureConfig> 
extern __imp_SetInternalWindowPos:qword 
SetInternalWindowPos TEXTEQU <__imp_SetInternalWindowPos> 
extern __imp_SetKeyboardState:qword 
SetKeyboardState TEXTEQU <__imp_SetKeyboardState> 
extern __imp_SetLastErrorEx:qword 
SetLastErrorEx TEXTEQU <__imp_SetLastErrorEx> 
extern __imp_SetLayeredWindowAttributes:qword 
SetLayeredWindowAttributes TEXTEQU <__imp_SetLayeredWindowAttributes> 
extern __imp_SetMagnificationDesktopColorEffect:qword 
SetMagnificationDesktopColorEffect TEXTEQU <__imp_SetMagnificationDesktopColorEffect> 
extern __imp_SetMagnificationDesktopMagnification:qword 
SetMagnificationDesktopMagnification TEXTEQU <__imp_SetMagnificationDesktopMagnification> 
extern __imp_SetMagnificationLensCtxInformation:qword 
SetMagnificationLensCtxInformation TEXTEQU <__imp_SetMagnificationLensCtxInformation> 
extern __imp_SetMenu:qword 
SetMenu TEXTEQU <__imp_SetMenu> 
extern __imp_SetMenuContextHelpId:qword 
SetMenuContextHelpId TEXTEQU <__imp_SetMenuContextHelpId> 
extern __imp_SetMenuDefaultItem:qword 
SetMenuDefaultItem TEXTEQU <__imp_SetMenuDefaultItem> 
extern __imp_SetMenuInfo:qword 
SetMenuInfo TEXTEQU <__imp_SetMenuInfo> 
extern __imp_SetMenuItemBitmaps:qword 
SetMenuItemBitmaps TEXTEQU <__imp_SetMenuItemBitmaps> 
extern __imp_SetMenuItemInfoA:qword 
SetMenuItemInfo TEXTEQU <__imp_SetMenuItemInfoA> 
extern __imp_SetMenuItemInfoW:qword 
SetMenuItemInfoW TEXTEQU <__imp_SetMenuItemInfoW> 
extern __imp_SetMessageExtraInfo:qword 
SetMessageExtraInfo TEXTEQU <__imp_SetMessageExtraInfo> 
extern __imp_SetMessageQueue:qword 
SetMessageQueue TEXTEQU <__imp_SetMessageQueue> 
extern __imp_SetMirrorRendering:qword 
SetMirrorRendering TEXTEQU <__imp_SetMirrorRendering> 
extern __imp_SetParent:qword 
SetParent TEXTEQU <__imp_SetParent> 
extern __imp_SetPhysicalCursorPos:qword 
SetPhysicalCursorPos TEXTEQU <__imp_SetPhysicalCursorPos> 
extern __imp_SetProcessDPIAware:qword 
SetProcessDPIAware TEXTEQU <__imp_SetProcessDPIAware> 
extern __imp_SetProcessDefaultLayout:qword 
SetProcessDefaultLayout TEXTEQU <__imp_SetProcessDefaultLayout> 
extern __imp_SetProcessWindowStation:qword 
SetProcessWindowStation TEXTEQU <__imp_SetProcessWindowStation> 
extern __imp_SetProgmanWindow:qword 
SetProgmanWindow TEXTEQU <__imp_SetProgmanWindow> 
extern __imp_SetPropA:qword 
SetProp TEXTEQU <__imp_SetPropA> 
extern __imp_SetPropW:qword 
SetPropW TEXTEQU <__imp_SetPropW> 
extern __imp_SetRect:qword 
SetRect TEXTEQU <__imp_SetRect> 
extern __imp_SetRectEmpty:qword 
SetRectEmpty TEXTEQU <__imp_SetRectEmpty> 
extern __imp_SetScrollInfo:qword 
SetScrollInfo TEXTEQU <__imp_SetScrollInfo> 
extern __imp_SetScrollPos:qword 
SetScrollPos TEXTEQU <__imp_SetScrollPos> 
extern __imp_SetScrollRange:qword 
SetScrollRange TEXTEQU <__imp_SetScrollRange> 
extern __imp_SetShellWindow:qword 
SetShellWindow TEXTEQU <__imp_SetShellWindow> 
extern __imp_SetShellWindowEx:qword 
SetShellWindowEx TEXTEQU <__imp_SetShellWindowEx> 
extern __imp_SetSysColors:qword 
SetSysColors TEXTEQU <__imp_SetSysColors> 
extern __imp_SetSysColorsTemp:qword 
SetSysColorsTemp TEXTEQU <__imp_SetSysColorsTemp> 
extern __imp_SetSystemCursor:qword 
SetSystemCursor TEXTEQU <__imp_SetSystemCursor> 
extern __imp_SetSystemMenu:qword 
SetSystemMenu TEXTEQU <__imp_SetSystemMenu> 
extern __imp_SetTaskmanWindow:qword 
SetTaskmanWindow TEXTEQU <__imp_SetTaskmanWindow> 
extern __imp_SetThreadDesktop:qword 
SetThreadDesktop TEXTEQU <__imp_SetThreadDesktop> 
extern __imp_SetTimer:qword 
SetTimer TEXTEQU <__imp_SetTimer> 
extern __imp_SetUserObjectInformationA:qword 
SetUserObjectInformation TEXTEQU <__imp_SetUserObjectInformationA> 
extern __imp_SetUserObjectInformationW:qword 
SetUserObjectInformationW TEXTEQU <__imp_SetUserObjectInformationW> 
extern __imp_SetUserObjectSecurity:qword 
SetUserObjectSecurity TEXTEQU <__imp_SetUserObjectSecurity> 
extern __imp_SetWinEventHook:qword 
SetWinEventHook TEXTEQU <__imp_SetWinEventHook> 
extern __imp_SetWindowCompositionAttribute:qword 
SetWindowCompositionAttribute TEXTEQU <__imp_SetWindowCompositionAttribute> 
extern __imp_SetWindowContextHelpId:qword 
SetWindowContextHelpId TEXTEQU <__imp_SetWindowContextHelpId> 
extern __imp_SetWindowDisplayAffinity:qword 
SetWindowDisplayAffinity TEXTEQU <__imp_SetWindowDisplayAffinity> 
extern __imp_SetWindowLongA:qword 
SetWindowLong TEXTEQU <__imp_SetWindowLongA> 
extern __imp_SetWindowLongPtrA:qword 
SetWindowLongPtr TEXTEQU <__imp_SetWindowLongPtrA> 
extern __imp_SetWindowLongPtrW:qword 
SetWindowLongPtrW TEXTEQU <__imp_SetWindowLongPtrW> 
extern __imp_SetWindowLongW:qword 
SetWindowLongW TEXTEQU <__imp_SetWindowLongW> 
extern __imp_SetWindowPlacement:qword 
SetWindowPlacement TEXTEQU <__imp_SetWindowPlacement> 
extern __imp_SetWindowPos:qword 
SetWindowPos TEXTEQU <__imp_SetWindowPos> 
extern __imp_SetWindowRgn:qword 
SetWindowRgn TEXTEQU <__imp_SetWindowRgn> 
extern __imp_SetWindowRgnEx:qword 
SetWindowRgnEx TEXTEQU <__imp_SetWindowRgnEx> 
extern __imp_SetWindowStationUser:qword 
SetWindowStationUser TEXTEQU <__imp_SetWindowStationUser> 
extern __imp_SetWindowTextA:qword 
SetWindowText TEXTEQU <__imp_SetWindowTextA> 
extern __imp_SetWindowTextW:qword 
SetWindowTextW TEXTEQU <__imp_SetWindowTextW> 
extern __imp_SetWindowWord:qword 
SetWindowWord TEXTEQU <__imp_SetWindowWord> 
extern __imp_SetWindowsHookA:qword 
SetWindowsHook TEXTEQU <__imp_SetWindowsHookA> 
extern __imp_SetWindowsHookExA:qword 
SetWindowsHookEx TEXTEQU <__imp_SetWindowsHookExA> 
extern __imp_SetWindowsHookExW:qword 
SetWindowsHookExW TEXTEQU <__imp_SetWindowsHookExW> 
extern __imp_SetWindowsHookW:qword 
SetWindowsHookW TEXTEQU <__imp_SetWindowsHookW> 
extern __imp_SfmDxBindSwapChain:qword 
SfmDxBindSwapChain TEXTEQU <__imp_SfmDxBindSwapChain> 
extern __imp_SfmDxGetSwapChainStats:qword 
SfmDxGetSwapChainStats TEXTEQU <__imp_SfmDxGetSwapChainStats> 
extern __imp_SfmDxOpenSwapChain:qword 
SfmDxOpenSwapChain TEXTEQU <__imp_SfmDxOpenSwapChain> 
extern __imp_SfmDxQuerySwapChainBindingStatus:qword 
SfmDxQuerySwapChainBindingStatus TEXTEQU <__imp_SfmDxQuerySwapChainBindingStatus> 
extern __imp_SfmDxReleaseSwapChain:qword 
SfmDxReleaseSwapChain TEXTEQU <__imp_SfmDxReleaseSwapChain> 
extern __imp_SfmDxReportPendingBindingsToDwm:qword 
SfmDxReportPendingBindingsToDwm TEXTEQU <__imp_SfmDxReportPendingBindingsToDwm> 
extern __imp_SfmDxSetSwapChainBindingStatus:qword 
SfmDxSetSwapChainBindingStatus TEXTEQU <__imp_SfmDxSetSwapChainBindingStatus> 
extern __imp_SfmDxSetSwapChainStats:qword 
SfmDxSetSwapChainStats TEXTEQU <__imp_SfmDxSetSwapChainStats> 
extern __imp_ShowCaret:qword 
ShowCaret TEXTEQU <__imp_ShowCaret> 
extern __imp_ShowCursor:qword 
ShowCursor TEXTEQU <__imp_ShowCursor> 
extern __imp_ShowOwnedPopups:qword 
ShowOwnedPopups TEXTEQU <__imp_ShowOwnedPopups> 
extern __imp_ShowScrollBar:qword 
ShowScrollBar TEXTEQU <__imp_ShowScrollBar> 
extern __imp_ShowStartGlass:qword 
ShowStartGlass TEXTEQU <__imp_ShowStartGlass> 
extern __imp_ShowSystemCursor:qword 
ShowSystemCursor TEXTEQU <__imp_ShowSystemCursor> 
extern __imp_ShowWindow:qword 
ShowWindow TEXTEQU <__imp_ShowWindow> 
extern __imp_ShowWindowAsync:qword 
ShowWindowAsync TEXTEQU <__imp_ShowWindowAsync> 
extern __imp_ShutdownBlockReasonCreate:qword 
ShutdownBlockReasonCreate TEXTEQU <__imp_ShutdownBlockReasonCreate> 
extern __imp_ShutdownBlockReasonDestroy:qword 
ShutdownBlockReasonDestroy TEXTEQU <__imp_ShutdownBlockReasonDestroy> 
extern __imp_ShutdownBlockReasonQuery:qword 
ShutdownBlockReasonQuery TEXTEQU <__imp_ShutdownBlockReasonQuery> 
extern __imp_SoftModalMessageBox:qword 
SoftModalMessageBox TEXTEQU <__imp_SoftModalMessageBox> 
extern __imp_SoundSentry:qword 
SoundSentry TEXTEQU <__imp_SoundSentry> 
extern __imp_SubtractRect:qword 
SubtractRect TEXTEQU <__imp_SubtractRect> 
extern __imp_SwapMouseButton:qword 
SwapMouseButton TEXTEQU <__imp_SwapMouseButton> 
extern __imp_SwitchDesktop:qword 
SwitchDesktop TEXTEQU <__imp_SwitchDesktop> 
extern __imp_SwitchDesktopWithFade:qword 
SwitchDesktopWithFade TEXTEQU <__imp_SwitchDesktopWithFade> 
extern __imp_SwitchToThisWindow:qword 
SwitchToThisWindow TEXTEQU <__imp_SwitchToThisWindow> 
extern __imp_SystemParametersInfoA:qword 
SystemParametersInfo TEXTEQU <__imp_SystemParametersInfoA> 
extern __imp_SystemParametersInfoW:qword 
SystemParametersInfoW TEXTEQU <__imp_SystemParametersInfoW> 
extern __imp_TabbedTextOutA:qword 
TabbedTextOut TEXTEQU <__imp_TabbedTextOutA> 
extern __imp_TabbedTextOutW:qword 
TabbedTextOutW TEXTEQU <__imp_TabbedTextOutW> 
extern __imp_TileChildWindows:qword 
TileChildWindows TEXTEQU <__imp_TileChildWindows> 
extern __imp_TileWindows:qword 
TileWindows TEXTEQU <__imp_TileWindows> 
extern __imp_ToAscii:qword 
ToAscii TEXTEQU <__imp_ToAscii> 
extern __imp_ToAsciiEx:qword 
ToAsciiEx TEXTEQU <__imp_ToAsciiEx> 
extern __imp_ToUnicode:qword 
ToUnicode TEXTEQU <__imp_ToUnicode> 
extern __imp_ToUnicodeEx:qword 
ToUnicodeEx TEXTEQU <__imp_ToUnicodeEx> 
extern __imp_TrackMouseEvent:qword 
TrackMouseEvent TEXTEQU <__imp_TrackMouseEvent> 
extern __imp_TrackPopupMenu:qword 
TrackPopupMenu TEXTEQU <__imp_TrackPopupMenu> 
extern __imp_TrackPopupMenuEx:qword 
TrackPopupMenuEx TEXTEQU <__imp_TrackPopupMenuEx> 
extern __imp_TranslateAccelerator:qword 
TranslateAccelerator TEXTEQU <__imp_TranslateAccelerator> 
extern __imp_TranslateAcceleratorA:qword 
TranslateAccelerator TEXTEQU <__imp_TranslateAcceleratorA> 
extern __imp_TranslateAcceleratorW:qword 
TranslateAcceleratorW TEXTEQU <__imp_TranslateAcceleratorW> 
extern __imp_TranslateMDISysAccel:qword 
TranslateMDISysAccel TEXTEQU <__imp_TranslateMDISysAccel> 
extern __imp_TranslateMessage:qword 
TranslateMessage TEXTEQU <__imp_TranslateMessage> 
extern __imp_TranslateMessageEx:qword 
TranslateMessageEx TEXTEQU <__imp_TranslateMessageEx> 
extern __imp_UnhookWinEvent:qword 
UnhookWinEvent TEXTEQU <__imp_UnhookWinEvent> 
extern __imp_UnhookWindowsHook:qword 
UnhookWindowsHook TEXTEQU <__imp_UnhookWindowsHook> 
extern __imp_UnhookWindowsHookEx:qword 
UnhookWindowsHookEx TEXTEQU <__imp_UnhookWindowsHookEx> 
extern __imp_UnionRect:qword 
UnionRect TEXTEQU <__imp_UnionRect> 
extern __imp_UnloadKeyboardLayout:qword 
UnloadKeyboardLayout TEXTEQU <__imp_UnloadKeyboardLayout> 
extern __imp_UnlockWindowStation:qword 
UnlockWindowStation TEXTEQU <__imp_UnlockWindowStation> 
extern __imp_UnpackDDElParam:qword 
UnpackDDElParam TEXTEQU <__imp_UnpackDDElParam> 
extern __imp_UnregisterClassA:qword 
UnregisterClass TEXTEQU <__imp_UnregisterClassA> 
extern __imp_UnregisterClassW:qword 
UnregisterClassW TEXTEQU <__imp_UnregisterClassW> 
extern __imp_UnregisterDeviceNotification:qword 
UnregisterDeviceNotification TEXTEQU <__imp_UnregisterDeviceNotification> 
extern __imp_UnregisterHotKey:qword 
UnregisterHotKey TEXTEQU <__imp_UnregisterHotKey> 
extern __imp_UnregisterMessagePumpHook:qword 
UnregisterMessagePumpHook TEXTEQU <__imp_UnregisterMessagePumpHook> 
extern __imp_UnregisterPowerSettingNotification:qword 
UnregisterPowerSettingNotification TEXTEQU <__imp_UnregisterPowerSettingNotification> 
extern __imp_UnregisterSessionPort:qword 
UnregisterSessionPort TEXTEQU <__imp_UnregisterSessionPort> 
extern __imp_UnregisterTouchWindow:qword 
UnregisterTouchWindow TEXTEQU <__imp_UnregisterTouchWindow> 
extern __imp_UnregisterUserApiHook:qword 
UnregisterUserApiHook TEXTEQU <__imp_UnregisterUserApiHook> 
extern __imp_UpdateLayeredWindow:qword 
UpdateLayeredWindow TEXTEQU <__imp_UpdateLayeredWindow> 
extern __imp_UpdateLayeredWindowIndirect:qword 
UpdateLayeredWindowIndirect TEXTEQU <__imp_UpdateLayeredWindowIndirect> 
extern __imp_UpdatePerUserSystemParameters:qword 
UpdatePerUserSystemParameters TEXTEQU <__imp_UpdatePerUserSystemParameters> 
extern __imp_UpdateWindow:qword 
UpdateWindow TEXTEQU <__imp_UpdateWindow> 
extern __imp_UpdateWindowTransform:qword 
UpdateWindowTransform TEXTEQU <__imp_UpdateWindowTransform> 
extern __imp_User32InitializeImmEntryTable:qword 
User32InitializeImmEntryTable TEXTEQU <__imp_User32InitializeImmEntryTable> 
extern __imp_UserClientDllInitialize:qword 
UserClientDllInitialize TEXTEQU <__imp_UserClientDllInitialize> 
extern __imp_UserHandleGrantAccess:qword 
UserHandleGrantAccess TEXTEQU <__imp_UserHandleGrantAccess> 
extern __imp_UserLpkPSMTextOut:qword 
UserLpkPSMTextOut TEXTEQU <__imp_UserLpkPSMTextOut> 
extern __imp_UserLpkTabbedTextOut:qword 
UserLpkTabbedTextOut TEXTEQU <__imp_UserLpkTabbedTextOut> 
extern __imp_UserRealizePalette:qword 
UserRealizePalette TEXTEQU <__imp_UserRealizePalette> 
extern __imp_UserRegisterWowHandlers:qword 
UserRegisterWowHandlers TEXTEQU <__imp_UserRegisterWowHandlers> 
extern __imp_VRipOutput:qword 
VRipOutput TEXTEQU <__imp_VRipOutput> 
extern __imp_VTagOutput:qword 
VTagOutput TEXTEQU <__imp_VTagOutput> 
extern __imp_ValidateRect:qword 
ValidateRect TEXTEQU <__imp_ValidateRect> 
extern __imp_ValidateRgn:qword 
ValidateRgn TEXTEQU <__imp_ValidateRgn> 
extern __imp_VkKeyScanA:qword 
VkKeyScan TEXTEQU <__imp_VkKeyScanA> 
extern __imp_VkKeyScanExA:qword 
VkKeyScanEx TEXTEQU <__imp_VkKeyScanExA> 
extern __imp_VkKeyScanExW:qword 
VkKeyScanExW TEXTEQU <__imp_VkKeyScanExW> 
extern __imp_VkKeyScanW:qword 
VkKeyScanW TEXTEQU <__imp_VkKeyScanW> 
extern __imp_WCSToMBEx:qword 
WCSToMBEx TEXTEQU <__imp_WCSToMBEx> 
extern __imp_WINNLSEnableIME:qword 
WINNLSEnableIME TEXTEQU <__imp_WINNLSEnableIME> 
extern __imp_WINNLSGetEnableStatus:qword 
WINNLSGetEnableStatus TEXTEQU <__imp_WINNLSGetEnableStatus> 
extern __imp_WINNLSGetIMEHotkey:qword 
WINNLSGetIMEHotkey TEXTEQU <__imp_WINNLSGetIMEHotkey> 
extern __imp_WaitForInputIdle:qword 
WaitForInputIdle TEXTEQU <__imp_WaitForInputIdle> 
extern __imp_WaitMessage:qword 
WaitMessage TEXTEQU <__imp_WaitMessage> 
extern __imp_WinHelpA:qword 
WinHelp TEXTEQU <__imp_WinHelpA> 
extern __imp_WinHelpW:qword 
WinHelpW TEXTEQU <__imp_WinHelpW> 
extern __imp_WindowFromDC:qword 
WindowFromDC TEXTEQU <__imp_WindowFromDC> 
extern __imp_WindowFromPhysicalPoint:qword 
WindowFromPhysicalPoint TEXTEQU <__imp_WindowFromPhysicalPoint> 
extern __imp_WindowFromPoint:qword 
WindowFromPoint TEXTEQU <__imp_WindowFromPoint> 
extern __imp__UserTestTokenForInteractive:qword 
_UserTestTokenForInteractive TEXTEQU <__imp__UserTestTokenForInteractive> 
extern __imp_gSharedInfo:qword 
gSharedInfo TEXTEQU <__imp_gSharedInfo> 
extern __imp_gapfnScSendMessage:qword 
gapfnScSendMessage TEXTEQU <__imp_gapfnScSendMessage> 
extern __imp_keybd_event:qword 
keybd_event TEXTEQU <__imp_keybd_event> 
extern __imp_mouse_event:qword 
mouse_event TEXTEQU <__imp_mouse_event> 
extern __imp_wsprintfA:qword 
wsprintf TEXTEQU <__imp_wsprintfA> 
extern __imp_wsprintfW:qword 
wsprintfW TEXTEQU <__imp_wsprintfW> 
extern __imp_wvsprintfA:qword 
wvsprintf TEXTEQU <__imp_wvsprintfA> 
extern __imp_wvsprintfW:qword 
wvsprintfW TEXTEQU <__imp_wvsprintfW> 
extern __imp_user32_ordinal1500:qword 
user32_ordinal1500 TEXTEQU <__imp_user32_ordinal1500> 
extern __imp_user32_ordinal1501:qword 
user32_ordinal1501 TEXTEQU <__imp_user32_ordinal1501> 
extern __imp_user32_ordinal1550:qword 
user32_ordinal1550 TEXTEQU <__imp_user32_ordinal1550> 
extern __imp_user32_ordinal1551:qword 
user32_ordinal1551 TEXTEQU <__imp_user32_ordinal1551> 
extern __imp_user32_ordinal1552:qword 
user32_ordinal1552 TEXTEQU <__imp_user32_ordinal1552> 
extern __imp_user32_ordinal1553:qword 
user32_ordinal1553 TEXTEQU <__imp_user32_ordinal1553> 
extern __imp_user32_ordinal1554:qword 
user32_ordinal1554 TEXTEQU <__imp_user32_ordinal1554> 
extern __imp_user32_ordinal1555:qword 
user32_ordinal1555 TEXTEQU <__imp_user32_ordinal1555> 
extern __imp_user32_ordinal1556:qword 
user32_ordinal1556 TEXTEQU <__imp_user32_ordinal1556> 
extern __imp_user32_ordinal2000:qword 
user32_ordinal2000 TEXTEQU <__imp_user32_ordinal2000> 
extern __imp_user32_ordinal2001:qword 
user32_ordinal2001 TEXTEQU <__imp_user32_ordinal2001> 
extern __imp_user32_ordinal2002:qword 
user32_ordinal2002 TEXTEQU <__imp_user32_ordinal2002> 
extern __imp_user32_ordinal2005:qword 
user32_ordinal2005 TEXTEQU <__imp_user32_ordinal2005> 
extern __imp_user32_ordinal2500:qword 
user32_ordinal2500 TEXTEQU <__imp_user32_ordinal2500> 
extern __imp_user32_ordinal2501:qword 
user32_ordinal2501 TEXTEQU <__imp_user32_ordinal2501> 
extern __imp_user32_ordinal2502:qword 
user32_ordinal2502 TEXTEQU <__imp_user32_ordinal2502> 
;---------------------------------
; Menu flags

MF_INSERT	   = 0000h
MF_CHANGE	   = 0080h
MF_APPEND	   = 0100h
MF_DELETE	   = 0200h
MF_REMOVE	   = 1000h
MF_BYCOMMAND	   = 0000h
MF_BYPOSITION	   = 0400h
MF_SEPARATOR	   = 0800h
MF_UNCHECKED	   = 0000h
MF_ENABLED	   = 0000h
MF_GRAYED	   = 0001h
MF_DISABLED	   = 0002h
MF_CHECKED	   = 0008h
MF_USECHECKBITMAPS = 0200h
MF_STRING	   = 0000h
MF_BITMAP	   = 0004h
MF_OWNERDRAW	   = 0100h
MF_POPUP	   = 0010h
MF_MENUBARBREAK    = 0020h
MF_MENUBREAK	   = 0040h
MF_UNHILITE	   = 0000h
MF_HILITE	   = 0080h
MF_DEFAULT	   = 1000h
MF_SYSMENU	   = 2000h
MF_HELP 	   = 4000h
MF_RIGHTJUSTIFY    = 4000h
MF_MOUSESELECT	   = 8000h
MF_END		   = 0080h
MFT_STRING	   = MF_STRING
MFT_BITMAP	   = MF_BITMAP
MFT_MENUBARBREAK   = MF_MENUBARBREAK
MFT_MENUBREAK	   = MF_MENUBREAK
MFT_OWNERDRAW	   = MF_OWNERDRAW
MFT_RADIOCHECK	   = 0200h
MFT_SEPARATOR	   = MF_SEPARATOR
MFT_RIGHTORDER	   = 2000h
MFT_RIGHTJUSTIFY   = MF_RIGHTJUSTIFY
MFS_GRAYED	   = 0003h
MFS_DISABLED	   = MFS_GRAYED
MFS_CHECKED	   = MF_CHECKED
MFS_HILITE	   = MF_HILITE
MFS_ENABLED	   = MF_ENABLED
MFS_UNCHECKED	   = MF_UNCHECKED
MFS_UNHILITE	   = MF_UNHILITE
MFS_DEFAULT	   = MF_DEFAULT
MFR_POPUP	   = 0001h
MFR_END 	   = MF_END

; Toolbar button states

TBSTATE_CHECKED       = 01h
TBSTATE_PRESSED       = 02h
TBSTATE_ENABLED       = 04h
TBSTATE_HIDDEN	      = 08h
TBSTATE_INDETERMINATE = 10h
TBSTATE_WRAP	      = 20h
TBSTATE_ELLIPSES      = 40h

; Toolbar button styles

TBSTYLE_BUTTON	    = 0000h
TBSTYLE_SEP	    = 0001h
TBSTYLE_CHECK	    = 0002h
TBSTYLE_GROUP	    = 0004h
TBSTYLE_CHECKGROUP  = TBSTYLE_GROUP or TBSTYLE_CHECK
TBSTYLE_DROPDOWN    = 0008h
TBSTYLE_TOOLTIPS    = 0100h
TBSTYLE_WRAPABLE    = 0200h
TBSTYLE_ALTDRAG     = 0400h
TBSTYLE_FLAT	    = 0800h
TBSTYLE_LIST	    = 1000h
TBSTYLE_CUSTOMERASE = 2000h
TBSTYLE_TRANSPARENT = 8000h

; Toolbar button extended styles

TBSTYLE_EX_DRAWDDARROWS = 0001h

TTN_FIRST  = -520
; Tooltip notifications

TTN_NEEDTEXTA = TTN_FIRST - 0
TTN_SHOW      = TTN_FIRST - 1
TTN_POP       = TTN_FIRST - 2
TTN_NEEDTEXTW = TTN_FIRST - 10
TTN_NEEDTEXT  = TTN_NEEDTEXTA

; Status bar styles

SBARS_SIZEGRIP = 100h

; Status bar messages

SB_SETTEXTA	  = WM_USER + 1
SB_GETTEXTA	  = WM_USER + 2
SB_GETTEXTLENGTHA = WM_USER + 3
SB_SETPARTS	  = WM_USER + 4
SB_GETPARTS	  = WM_USER + 6
SB_GETBORDERS	  = WM_USER + 7
SB_SETMINHEIGHT   = WM_USER + 8
SB_SIMPLE	  = WM_USER + 9
SB_GETRECT	  = WM_USER + 10
SB_SETTEXTW	  = WM_USER + 11
SB_GETTEXTW	  = WM_USER + 13
SB_GETTEXTLENGTHW = WM_USER + 12
SB_SETTEXT	  = SB_SETTEXTA
SB_GETTEXT	  = SB_GETTEXTA
SB_GETTEXTLENGTH  = SB_GETTEXTLENGTHA

; Tooltip styles

TTS_ALWAYSTIP = 1
TTS_NOPREFIX  = 2

; Tooltip flags

TTF_IDISHWND   = 01h
TTF_CENTERTIP  = 02h
TTF_RTLREADING = 04h
TTF_SUBCLASS   = 10h

; Tooltip durations

TTDT_AUTOMATIC = 0
TTDT_RESHOW    = 1
TTDT_AUTOPOP   = 2
TTDT_INITIAL   = 3

; Tooltip messages

TTM_ACTIVATE	    = WM_USER + 1
TTM_SETDELAYTIME    = WM_USER + 3
TTM_ADDTOOLA	    = WM_USER + 4
TTM_DELTOOLA	    = WM_USER + 5
TTM_NEWTOOLRECTA    = WM_USER + 6
TTM_RELAYEVENT	    = WM_USER + 7
TTM_GETTOOLINFOA    = WM_USER + 8
TTM_SETTOOLINFOA    = WM_USER + 9
TTM_HITTESTA	    = WM_USER + 10
TTM_GETTEXTA	    = WM_USER + 11
TTM_UPDATETIPTEXTA  = WM_USER + 12
TTM_GETTOOLCOUNT    = WM_USER + 13
TTM_ENUMTOOLSA	    = WM_USER + 14
TTM_GETCURRENTTOOLA = WM_USER + 15
TTM_WINDOWFROMPOINT = WM_USER + 16
TTM_ADDTOOLW	    = WM_USER + 50
TTM_DELTOOLW	    = WM_USER + 51
TTM_NEWTOOLRECTW    = WM_USER + 52
TTM_GETTOOLINFOW    = WM_USER + 53
TTM_SETTOOLINFOW    = WM_USER + 54
TTM_HITTESTW	    = WM_USER + 55
TTM_GETTEXTW	    = WM_USER + 56
TTM_UPDATETIPTEXTW  = WM_USER + 57
TTM_ENUMTOOLSW	    = WM_USER + 58
TTM_GETCURRENTTOOLW = WM_USER + 59
TTM_ADDTOOL	    = TTM_ADDTOOLA
TTM_DELTOOL	    = TTM_DELTOOLA
TTM_NEWTOOLRECT     = TTM_NEWTOOLRECTA
TTM_GETTOOLINFO     = TTM_GETTOOLINFOA
TTM_SETTOOLINFO     = TTM_SETTOOLINFOA
TTM_HITTEST	    = TTM_HITTESTA
TTM_GETTEXT	    = TTM_GETTEXTA
TTM_UPDATETIPTEXT   = TTM_UPDATETIPTEXTA
TTM_ENUMTOOLS	    = TTM_ENUMTOOLSA
TTM_GETCURRENTTOOL  = TTM_GETCURRENTTOOLA

MSGBOXPARAMS struc
  cbSize	     dd ?,?;UINT
  hwndOwner	     dq ?  ;HWND
  hInstance	     dq ?  ;HINSTANCE
  lpszText	     dq ?  ;LPCTSTR
  lpszCaption	     dq ?  ;LPCTSTR
  dwStyle	     dd ?,?;DWORD
  lpszIcon	     dq ?  ;LPCTSTR
  dwContextHelpId    dd ?,?;DWORD_PTR
  lpfnMsgBoxCallback dq ?  ;MSGBOXCALLBACK
  dwLanguageId	     dd ?,?;DWORD
MSGBOXPARAMS ends