extern __imp_CloseDriver:qword 
CloseDriver TEXTEQU <__imp_CloseDriver> 
extern __imp_DefDriverProc:qword 
DefDriverProc TEXTEQU <__imp_DefDriverProc> 
extern __imp_DriverCallback:qword 
DriverCallback TEXTEQU <__imp_DriverCallback> 
extern __imp_DrvGetModuleHandle:qword 
DrvGetModuleHandle TEXTEQU <__imp_DrvGetModuleHandle> 
extern __imp_GetDriverModuleHandle:qword 
GetDriverModuleHandle TEXTEQU <__imp_GetDriverModuleHandle> 
extern __imp_OpenDriver:qword 
OpenDriver TEXTEQU <__imp_OpenDriver> 
extern __imp_PlaySound:qword 
PlaySound TEXTEQU <__imp_PlaySound> 
extern __imp_PlaySoundA:qword 
PlaySound TEXTEQU <__imp_PlaySoundA> 
extern __imp_PlaySoundW:qword 
PlaySoundW TEXTEQU <__imp_PlaySoundW> 
extern __imp_SendDriverMessage:qword 
SendDriverMessage TEXTEQU <__imp_SendDriverMessage> 
extern __imp_WOWAppExit:qword 
WOWAppExit TEXTEQU <__imp_WOWAppExit> 
extern __imp_auxGetDevCapsA:qword 
auxGetDevCaps TEXTEQU <__imp_auxGetDevCapsA> 
extern __imp_auxGetDevCapsW:qword 
auxGetDevCapsW TEXTEQU <__imp_auxGetDevCapsW> 
extern __imp_auxGetNumDevs:qword 
auxGetNumDevs TEXTEQU <__imp_auxGetNumDevs> 
extern __imp_auxGetVolume:qword 
auxGetVolume TEXTEQU <__imp_auxGetVolume> 
extern __imp_auxOutMessage:qword 
auxOutMessage TEXTEQU <__imp_auxOutMessage> 
extern __imp_auxSetVolume:qword 
auxSetVolume TEXTEQU <__imp_auxSetVolume> 
extern __imp_joyConfigChanged:qword 
joyConfigChanged TEXTEQU <__imp_joyConfigChanged> 
extern __imp_joyGetDevCapsA:qword 
joyGetDevCaps TEXTEQU <__imp_joyGetDevCapsA> 
extern __imp_joyGetDevCapsW:qword 
joyGetDevCapsW TEXTEQU <__imp_joyGetDevCapsW> 
extern __imp_joyGetNumDevs:qword 
joyGetNumDevs TEXTEQU <__imp_joyGetNumDevs> 
extern __imp_joyGetPos:qword 
joyGetPos TEXTEQU <__imp_joyGetPos> 
extern __imp_joyGetPosEx:qword 
joyGetPosEx TEXTEQU <__imp_joyGetPosEx> 
extern __imp_joyGetThreshold:qword 
joyGetThreshold TEXTEQU <__imp_joyGetThreshold> 
extern __imp_joyReleaseCapture:qword 
joyReleaseCapture TEXTEQU <__imp_joyReleaseCapture> 
extern __imp_joySetCapture:qword 
joySetCapture TEXTEQU <__imp_joySetCapture> 
extern __imp_joySetThreshold:qword 
joySetThreshold TEXTEQU <__imp_joySetThreshold> 
extern __imp_mciDriverNotify:qword 
mciDriverNotify TEXTEQU <__imp_mciDriverNotify> 
extern __imp_mciDriverYield:qword 
mciDriverYield TEXTEQU <__imp_mciDriverYield> 
extern __imp_mciExecute:qword 
mciExecute TEXTEQU <__imp_mciExecute> 
extern __imp_mciFreeCommandResource:qword 
mciFreeCommandResource TEXTEQU <__imp_mciFreeCommandResource> 
extern __imp_mciGetCreatorTask:qword 
mciGetCreatorTask TEXTEQU <__imp_mciGetCreatorTask> 
extern __imp_mciGetDeviceIDA:qword 
mciGetDeviceID TEXTEQU <__imp_mciGetDeviceIDA> 
extern __imp_mciGetDeviceIDFromElementIDA:qword 
mciGetDeviceIDFromElementID TEXTEQU <__imp_mciGetDeviceIDFromElementIDA> 
extern __imp_mciGetDeviceIDFromElementIDW:qword 
mciGetDeviceIDFromElementIDW TEXTEQU <__imp_mciGetDeviceIDFromElementIDW> 
extern __imp_mciGetDeviceIDW:qword 
mciGetDeviceIDW TEXTEQU <__imp_mciGetDeviceIDW> 
extern __imp_mciGetDriverData:qword 
mciGetDriverData TEXTEQU <__imp_mciGetDriverData> 
extern __imp_mciGetErrorStringA:qword 
mciGetErrorString TEXTEQU <__imp_mciGetErrorStringA> 
extern __imp_mciGetErrorStringW:qword 
mciGetErrorStringW TEXTEQU <__imp_mciGetErrorStringW> 
extern __imp_mciGetYieldProc:qword 
mciGetYieldProc TEXTEQU <__imp_mciGetYieldProc> 
extern __imp_mciLoadCommandResource:qword 
mciLoadCommandResource TEXTEQU <__imp_mciLoadCommandResource> 
extern __imp_mciSendCommandA:qword 
mciSendCommand TEXTEQU <__imp_mciSendCommandA> 
extern __imp_mciSendCommandW:qword 
mciSendCommandW TEXTEQU <__imp_mciSendCommandW> 
extern __imp_mciSendStringA:qword 
mciSendString TEXTEQU <__imp_mciSendStringA> 
extern __imp_mciSendStringW:qword 
mciSendStringW TEXTEQU <__imp_mciSendStringW> 
extern __imp_mciSetDriverData:qword 
mciSetDriverData TEXTEQU <__imp_mciSetDriverData> 
extern __imp_mciSetYieldProc:qword 
mciSetYieldProc TEXTEQU <__imp_mciSetYieldProc> 
extern __imp_midiConnect:qword 
midiConnect TEXTEQU <__imp_midiConnect> 
extern __imp_midiDisconnect:qword 
midiDisconnect TEXTEQU <__imp_midiDisconnect> 
extern __imp_midiInAddBuffer:qword 
midiInAddBuffer TEXTEQU <__imp_midiInAddBuffer> 
extern __imp_midiInClose:qword 
midiInClose TEXTEQU <__imp_midiInClose> 
extern __imp_midiInGetDevCapsA:qword 
midiInGetDevCaps TEXTEQU <__imp_midiInGetDevCapsA> 
extern __imp_midiInGetDevCapsW:qword 
midiInGetDevCapsW TEXTEQU <__imp_midiInGetDevCapsW> 
extern __imp_midiInGetErrorTextA:qword 
midiInGetErrorText TEXTEQU <__imp_midiInGetErrorTextA> 
extern __imp_midiInGetErrorTextW:qword 
midiInGetErrorTextW TEXTEQU <__imp_midiInGetErrorTextW> 
extern __imp_midiInGetID:qword 
midiInGetID TEXTEQU <__imp_midiInGetID> 
extern __imp_midiInGetNumDevs:qword 
midiInGetNumDevs TEXTEQU <__imp_midiInGetNumDevs> 
extern __imp_midiInMessage:qword 
midiInMessage TEXTEQU <__imp_midiInMessage> 
extern __imp_midiInOpen:qword 
midiInOpen TEXTEQU <__imp_midiInOpen> 
extern __imp_midiInPrepareHeader:qword 
midiInPrepareHeader TEXTEQU <__imp_midiInPrepareHeader> 
extern __imp_midiInReset:qword 
midiInReset TEXTEQU <__imp_midiInReset> 
extern __imp_midiInStart:qword 
midiInStart TEXTEQU <__imp_midiInStart> 
extern __imp_midiInStop:qword 
midiInStop TEXTEQU <__imp_midiInStop> 
extern __imp_midiInUnprepareHeader:qword 
midiInUnprepareHeader TEXTEQU <__imp_midiInUnprepareHeader> 
extern __imp_midiOutCacheDrumPatches:qword 
midiOutCacheDrumPatches TEXTEQU <__imp_midiOutCacheDrumPatches> 
extern __imp_midiOutCachePatches:qword 
midiOutCachePatches TEXTEQU <__imp_midiOutCachePatches> 
extern __imp_midiOutClose:qword 
midiOutClose TEXTEQU <__imp_midiOutClose> 
extern __imp_midiOutGetDevCapsA:qword 
midiOutGetDevCaps TEXTEQU <__imp_midiOutGetDevCapsA> 
extern __imp_midiOutGetDevCapsW:qword 
midiOutGetDevCapsW TEXTEQU <__imp_midiOutGetDevCapsW> 
extern __imp_midiOutGetErrorTextA:qword 
midiOutGetErrorText TEXTEQU <__imp_midiOutGetErrorTextA> 
extern __imp_midiOutGetErrorTextW:qword 
midiOutGetErrorTextW TEXTEQU <__imp_midiOutGetErrorTextW> 
extern __imp_midiOutGetID:qword 
midiOutGetID TEXTEQU <__imp_midiOutGetID> 
extern __imp_midiOutGetNumDevs:qword 
midiOutGetNumDevs TEXTEQU <__imp_midiOutGetNumDevs> 
extern __imp_midiOutGetVolume:qword 
midiOutGetVolume TEXTEQU <__imp_midiOutGetVolume> 
extern __imp_midiOutLongMsg:qword 
midiOutLongMsg TEXTEQU <__imp_midiOutLongMsg> 
extern __imp_midiOutMessage:qword 
midiOutMessage TEXTEQU <__imp_midiOutMessage> 
extern __imp_midiOutOpen:qword 
midiOutOpen TEXTEQU <__imp_midiOutOpen> 
extern __imp_midiOutPrepareHeader:qword 
midiOutPrepareHeader TEXTEQU <__imp_midiOutPrepareHeader> 
extern __imp_midiOutReset:qword 
midiOutReset TEXTEQU <__imp_midiOutReset> 
extern __imp_midiOutSetVolume:qword 
midiOutSetVolume TEXTEQU <__imp_midiOutSetVolume> 
extern __imp_midiOutShortMsg:qword 
midiOutShortMsg TEXTEQU <__imp_midiOutShortMsg> 
extern __imp_midiOutUnprepareHeader:qword 
midiOutUnprepareHeader TEXTEQU <__imp_midiOutUnprepareHeader> 
extern __imp_midiStreamClose:qword 
midiStreamClose TEXTEQU <__imp_midiStreamClose> 
extern __imp_midiStreamOpen:qword 
midiStreamOpen TEXTEQU <__imp_midiStreamOpen> 
extern __imp_midiStreamOut:qword 
midiStreamOut TEXTEQU <__imp_midiStreamOut> 
extern __imp_midiStreamPause:qword 
midiStreamPause TEXTEQU <__imp_midiStreamPause> 
extern __imp_midiStreamPosition:qword 
midiStreamPosition TEXTEQU <__imp_midiStreamPosition> 
extern __imp_midiStreamProperty:qword 
midiStreamProperty TEXTEQU <__imp_midiStreamProperty> 
extern __imp_midiStreamRestart:qword 
midiStreamRestart TEXTEQU <__imp_midiStreamRestart> 
extern __imp_midiStreamStop:qword 
midiStreamStop TEXTEQU <__imp_midiStreamStop> 
extern __imp_mixerClose:qword 
mixerClose TEXTEQU <__imp_mixerClose> 
extern __imp_mixerGetControlDetailsA:qword 
mixerGetControlDetails TEXTEQU <__imp_mixerGetControlDetailsA> 
extern __imp_mixerGetControlDetailsW:qword 
mixerGetControlDetailsW TEXTEQU <__imp_mixerGetControlDetailsW> 
extern __imp_mixerGetDevCapsA:qword 
mixerGetDevCaps TEXTEQU <__imp_mixerGetDevCapsA> 
extern __imp_mixerGetDevCapsW:qword 
mixerGetDevCapsW TEXTEQU <__imp_mixerGetDevCapsW> 
extern __imp_mixerGetID:qword 
mixerGetID TEXTEQU <__imp_mixerGetID> 
extern __imp_mixerGetLineControlsA:qword 
mixerGetLineControls TEXTEQU <__imp_mixerGetLineControlsA> 
extern __imp_mixerGetLineControlsW:qword 
mixerGetLineControlsW TEXTEQU <__imp_mixerGetLineControlsW> 
extern __imp_mixerGetLineInfoA:qword 
mixerGetLineInfo TEXTEQU <__imp_mixerGetLineInfoA> 
extern __imp_mixerGetLineInfoW:qword 
mixerGetLineInfoW TEXTEQU <__imp_mixerGetLineInfoW> 
extern __imp_mixerGetNumDevs:qword 
mixerGetNumDevs TEXTEQU <__imp_mixerGetNumDevs> 
extern __imp_mixerMessage:qword 
mixerMessage TEXTEQU <__imp_mixerMessage> 
extern __imp_mixerOpen:qword 
mixerOpen TEXTEQU <__imp_mixerOpen> 
extern __imp_mixerSetControlDetails:qword 
mixerSetControlDetails TEXTEQU <__imp_mixerSetControlDetails> 
extern __imp_mmDrvInstall:qword 
mmDrvInstall TEXTEQU <__imp_mmDrvInstall> 
extern __imp_mmGetCurrentTask:qword 
mmGetCurrentTask TEXTEQU <__imp_mmGetCurrentTask> 
extern __imp_mmTaskBlock:qword 
mmTaskBlock TEXTEQU <__imp_mmTaskBlock> 
extern __imp_mmTaskCreate:qword 
mmTaskCreate TEXTEQU <__imp_mmTaskCreate> 
extern __imp_mmTaskSignal:qword 
mmTaskSignal TEXTEQU <__imp_mmTaskSignal> 
extern __imp_mmTaskYield:qword 
mmTaskYield TEXTEQU <__imp_mmTaskYield> 
extern __imp_mmioAdvance:qword 
mmioAdvance TEXTEQU <__imp_mmioAdvance> 
extern __imp_mmioAscend:qword 
mmioAscend TEXTEQU <__imp_mmioAscend> 
extern __imp_mmioClose:qword 
mmioClose TEXTEQU <__imp_mmioClose> 
extern __imp_mmioCreateChunk:qword 
mmioCreateChunk TEXTEQU <__imp_mmioCreateChunk> 
extern __imp_mmioDescend:qword 
mmioDescend TEXTEQU <__imp_mmioDescend> 
extern __imp_mmioFlush:qword 
mmioFlush TEXTEQU <__imp_mmioFlush> 
extern __imp_mmioGetInfo:qword 
mmioGetInfo TEXTEQU <__imp_mmioGetInfo> 
extern __imp_mmioInstallIOProcA:qword 
mmioInstallIOProc TEXTEQU <__imp_mmioInstallIOProcA> 
extern __imp_mmioInstallIOProcW:qword 
mmioInstallIOProcW TEXTEQU <__imp_mmioInstallIOProcW> 
extern __imp_mmioOpenA:qword 
mmioOpen TEXTEQU <__imp_mmioOpenA> 
extern __imp_mmioOpenW:qword 
mmioOpenW TEXTEQU <__imp_mmioOpenW> 
extern __imp_mmioRead:qword 
mmioRead TEXTEQU <__imp_mmioRead> 
extern __imp_mmioRenameA:qword 
mmioRename TEXTEQU <__imp_mmioRenameA> 
extern __imp_mmioRenameW:qword 
mmioRenameW TEXTEQU <__imp_mmioRenameW> 
extern __imp_mmioSeek:qword 
mmioSeek TEXTEQU <__imp_mmioSeek> 
extern __imp_mmioSendMessage:qword 
mmioSendMessage TEXTEQU <__imp_mmioSendMessage> 
extern __imp_mmioSetBuffer:qword 
mmioSetBuffer TEXTEQU <__imp_mmioSetBuffer> 
extern __imp_mmioSetInfo:qword 
mmioSetInfo TEXTEQU <__imp_mmioSetInfo> 
extern __imp_mmioStringToFOURCCA:qword 
mmioStringToFOURCC TEXTEQU <__imp_mmioStringToFOURCCA> 
extern __imp_mmioStringToFOURCCW:qword 
mmioStringToFOURCCW TEXTEQU <__imp_mmioStringToFOURCCW> 
extern __imp_mmioWrite:qword 
mmioWrite TEXTEQU <__imp_mmioWrite> 
extern __imp_mmsystemGetVersion:qword 
mmsystemGetVersion TEXTEQU <__imp_mmsystemGetVersion> 
extern __imp_sndPlaySoundA:qword 
sndPlaySound TEXTEQU <__imp_sndPlaySoundA> 
extern __imp_sndPlaySoundW:qword 
sndPlaySoundW TEXTEQU <__imp_sndPlaySoundW> 
extern __imp_timeBeginPeriod:qword 
timeBeginPeriod TEXTEQU <__imp_timeBeginPeriod> 
extern __imp_timeEndPeriod:qword 
timeEndPeriod TEXTEQU <__imp_timeEndPeriod> 
extern __imp_timeGetDevCaps:qword 
timeGetDevCaps TEXTEQU <__imp_timeGetDevCaps> 
extern __imp_timeGetSystemTime:qword 
timeGetSystemTime TEXTEQU <__imp_timeGetSystemTime> 
extern __imp_timeGetTime:qword 
timeGetTime TEXTEQU <__imp_timeGetTime> 
extern __imp_timeKillEvent:qword 
timeKillEvent TEXTEQU <__imp_timeKillEvent> 
extern __imp_timeSetEvent:qword 
timeSetEvent TEXTEQU <__imp_timeSetEvent> 
extern __imp_waveInAddBuffer:qword 
waveInAddBuffer TEXTEQU <__imp_waveInAddBuffer> 
extern __imp_waveInClose:qword 
waveInClose TEXTEQU <__imp_waveInClose> 
extern __imp_waveInGetDevCapsA:qword 
waveInGetDevCaps TEXTEQU <__imp_waveInGetDevCapsA> 
extern __imp_waveInGetDevCapsW:qword 
waveInGetDevCapsW TEXTEQU <__imp_waveInGetDevCapsW> 
extern __imp_waveInGetErrorTextA:qword 
waveInGetErrorText TEXTEQU <__imp_waveInGetErrorTextA> 
extern __imp_waveInGetErrorTextW:qword 
waveInGetErrorTextW TEXTEQU <__imp_waveInGetErrorTextW> 
extern __imp_waveInGetID:qword 
waveInGetID TEXTEQU <__imp_waveInGetID> 
extern __imp_waveInGetNumDevs:qword 
waveInGetNumDevs TEXTEQU <__imp_waveInGetNumDevs> 
extern __imp_waveInGetPosition:qword 
waveInGetPosition TEXTEQU <__imp_waveInGetPosition> 
extern __imp_waveInMessage:qword 
waveInMessage TEXTEQU <__imp_waveInMessage> 
extern __imp_waveInOpen:qword 
waveInOpen TEXTEQU <__imp_waveInOpen> 
extern __imp_waveInPrepareHeader:qword 
waveInPrepareHeader TEXTEQU <__imp_waveInPrepareHeader> 
extern __imp_waveInReset:qword 
waveInReset TEXTEQU <__imp_waveInReset> 
extern __imp_waveInStart:qword 
waveInStart TEXTEQU <__imp_waveInStart> 
extern __imp_waveInStop:qword 
waveInStop TEXTEQU <__imp_waveInStop> 
extern __imp_waveInUnprepareHeader:qword 
waveInUnprepareHeader TEXTEQU <__imp_waveInUnprepareHeader> 
extern __imp_waveOutBreakLoop:qword 
waveOutBreakLoop TEXTEQU <__imp_waveOutBreakLoop> 
extern __imp_waveOutClose:qword 
waveOutClose TEXTEQU <__imp_waveOutClose> 
extern __imp_waveOutGetDevCapsA:qword 
waveOutGetDevCaps TEXTEQU <__imp_waveOutGetDevCapsA> 
extern __imp_waveOutGetDevCapsW:qword 
waveOutGetDevCapsW TEXTEQU <__imp_waveOutGetDevCapsW> 
extern __imp_waveOutGetErrorTextA:qword 
waveOutGetErrorText TEXTEQU <__imp_waveOutGetErrorTextA> 
extern __imp_waveOutGetErrorTextW:qword 
waveOutGetErrorTextW TEXTEQU <__imp_waveOutGetErrorTextW> 
extern __imp_waveOutGetID:qword 
waveOutGetID TEXTEQU <__imp_waveOutGetID> 
extern __imp_waveOutGetNumDevs:qword 
waveOutGetNumDevs TEXTEQU <__imp_waveOutGetNumDevs> 
extern __imp_waveOutGetPitch:qword 
waveOutGetPitch TEXTEQU <__imp_waveOutGetPitch> 
extern __imp_waveOutGetPlaybackRate:qword 
waveOutGetPlaybackRate TEXTEQU <__imp_waveOutGetPlaybackRate> 
extern __imp_waveOutGetPosition:qword 
waveOutGetPosition TEXTEQU <__imp_waveOutGetPosition> 
extern __imp_waveOutGetVolume:qword 
waveOutGetVolume TEXTEQU <__imp_waveOutGetVolume> 
extern __imp_waveOutMessage:qword 
waveOutMessage TEXTEQU <__imp_waveOutMessage> 
extern __imp_waveOutOpen:qword 
waveOutOpen TEXTEQU <__imp_waveOutOpen> 
extern __imp_waveOutPause:qword 
waveOutPause TEXTEQU <__imp_waveOutPause> 
extern __imp_waveOutPrepareHeader:qword 
waveOutPrepareHeader TEXTEQU <__imp_waveOutPrepareHeader> 
extern __imp_waveOutReset:qword 
waveOutReset TEXTEQU <__imp_waveOutReset> 
extern __imp_waveOutRestart:qword 
waveOutRestart TEXTEQU <__imp_waveOutRestart> 
extern __imp_waveOutSetPitch:qword 
waveOutSetPitch TEXTEQU <__imp_waveOutSetPitch> 
extern __imp_waveOutSetPlaybackRate:qword 
waveOutSetPlaybackRate TEXTEQU <__imp_waveOutSetPlaybackRate> 
extern __imp_waveOutSetVolume:qword 
waveOutSetVolume TEXTEQU <__imp_waveOutSetVolume> 
extern __imp_waveOutUnprepareHeader:qword 
waveOutUnprepareHeader TEXTEQU <__imp_waveOutUnprepareHeader> 
extern __imp_waveOutWrite:qword 
waveOutWrite TEXTEQU <__imp_waveOutWrite> 
extern __imp_winmm_ordinal2:qword 
winmm_ordinal2 TEXTEQU <__imp_winmm_ordinal2> 
;---------------------------------
MCI_ANIM_OPEN_PARMS STRUCT
  dwCallback        QWORD      ?
  wDeviceID         DWORD      ?
  lpstrDeviceType   QWORD      ?
  lpstrElementName  QWORD      ?
  lpstrAlias        QWORD      ?
  dwStyle           DWORD      ?
  hWndParent        QWORD      ?
MCI_ANIM_OPEN_PARMS ENDS

MCI_ANIM_PLAY_PARMS STRUCT
  dwCallback    QWORD      ?
  dwFrom        DWORD      ?
  dwTo          DWORD      ?
  dwSpeed       DWORD      ?
MCI_ANIM_PLAY_PARMS ENDS

MCI_GENERIC_PARMS STRUCT
  dwCallback  QWORD      ?
MCI_GENERIC_PARMS ENDS